### ISSUE TITLE
Change cursor color in input bar

### ISSUE THREAD

**Issue by juanmeleiro** [luakit/luakit#1002]
I've looked through previous issues, grepped the code, looked at the documentation, and searched the web, but there seems to be no recorded way of changing cursor color in the input bar. In my case, because of my system's theme, it is too close to the background color.

Despite there not being a way within luakit to customize the cursor shape (as per #859), I'd suppose there is one to customize color, as all other colors around it (text foreground and background, titles of menus, etc) are customizable.

Is there a way to do it?

**Comment by taobert** [comment]
Doesn't look like it (based on a very quick peek).
I think `widgets/entry.c` is where you want to look/play.
In my hands, this minimal patch:
```
diff --git a/widgets/entry.c b/widgets/entry.c
index 38773df7..6ce38dd3 100644
--- a/widgets/entry.c
+++ b/widgets/entry.c
@@ -102,6 +102,7 @@ luaH_entry_newindex(lua_State *L, widget_t *w, luakit_token_t token)
         if (token == L_TK_FG) {
 #if GTK_CHECK_VERSION(3,16,0)
             widget_set_css_properties(w, "color", tmp, NULL);
+            widget_set_css_properties(w, "caret-color", tmp, NULL);
 #else
             gtk_widget_override_color(GTK_WIDGET(w->widget), GTK_STATE_FLAG_NORMAL, &c);
 #endif
```
sets the cursor to the user-specified foreground colour.
From what you've said, it sounds like your primary issue is with legibility,
and i assume your foreground colour is different enough to the background that this will work for you.
It wouldn't be a bad idea to have the cursor themeable on its own, but that's a somewhat larger job.

**Comment by juanmeleiro** [comment]
Yeah, that does work. Should I make a pull request? Seems like the kind of thing that should be in upstream.

**Comment by taobert** [comment]
I certainly feel that _something_ should go into upstream.
I'd planned to have a poke around (and a think) and decide whether something more expansive was worthwhile.
However, i have a habit of getting distracted, so i'll PR this one line rather than risk _nothing_ being done.
