### ISSUE TITLE
(Maybe) regex problem with latest glib

### ISSUE THREAD

**Issue by taobert** [luakit/luakit#1005]
**Presis:**

I'm seeing failure-to-start of luakit `develop` with the default configuration.
It looks like glib has upgraded to libpcre2, and that may have broken the regex used to by `strip_ansi_escapes()` when generatiing stack traces.

**Current Behavior:**

During compilation, i get a warning:
```
cc -c common/util.c -o common/util.o
common/util.c: In function ‘strip_ansi_escapes’:
common/util.c:66:9: warning: ‘G_REGEX_JAVASCRIPT_COMPAT’ is deprecated [-Wdeprecated-declarations]
   66 |         reg = g_regex_new(expr, G_REGEX_JAVASCRIPT_COMPAT | G_REGEX_DOTALL | G_REGEX_EXTENDED | G_REGEX_RAW | G_REGEX_OPTIMIZE, 0, &err);
      |         ^~~
In file included from /usr/include/glib-2.0/glib.h:77,
                 from ./common/util.h:26,
                 from common/util.c:23:
/usr/include/glib-2.0/glib/gregex.h:324:3: note: declared here
  324 |   G_REGEX_JAVASCRIPT_COMPAT GLIB_DEPRECATED_ENUMERATOR_IN_2_74 = 1 << 25
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~
```
and then on luakit start, compilation of the RE fails, causing luakit to crash with:
```
ERROR:common/util.c:67:strip_ansi_escapes: assertion failed (err == NULL): Error while compiling regular expression ‘[\u001b\u009b][[()#;?]*(?:[0-9]{1,4}(?:;[0-9]{0,4})*)?[0-9A-ORZcf-nqry=><]’ at char 3: unrecognized character following \ (g-regex-error-quark, 103)
Bail out! ERROR:common/util.c:67:strip_ansi_escapes: assertion failed (err == NULL): Error while compiling regular expression ‘[\u001b\u009b][[()#;?]*(?:[0-9]{1,4}(?:;[0-9]{0,4})*)?[0-9A-ORZcf-nqry=><]’ at char 3: unrecognized character following \ (g-regex-error-quark, 103)
```
So it appears that `\u` is no longer valid.

**Discussion:**

[glib's news file](https://gitlab.gnome.org/GNOME/glib/-/blob/main/NEWS) states:
```
Overview of changes in GLib 2.73.2, 12-07-2022
==============================================

* Replace PCRE1 with PCRE2: This is a major change to drop the libpcre1
  dependency and use libpcre2 instead, while preserving the behaviour and API of
  GRegex. G_REGEX_OPTIMIZE and G_REGEX_JAVASCRIPT_COMPAT are now deprecated
  and became a no-op, while other flags are adapted accordingly to the new API
  (work by Aleksei Rybalkin, Philipp Withnall) (!2529, #1085)
```
however, it also states:
```
Overview of changes in GLib 2.73.3, 05-08-2022
==============================================

* Revitalize G_REGEX_OPTIMIZE flag and use it to enable PCRE JIT compiler (work
  by Aleksei Rybalkin) (!2817)

* Fix some regressions due to the PCRE2 port (work
  by Aleksei Rybalkin, Mamoru TASAKA and Marco Trevisan) (!2814, !2827, #2694,
  #2699, #2700)
```
so it appears that glib are aware that at least some stuff has broken, and this issue may get fixed upstream (I've not reported it),
and `G_REGEX_OPTIMIZE` may not actually be deprecated.
Indeed Debian Sid now ships `libglib2.0-0` `2.73.3-3` and i don't get a deprecation warning for G_REGEX_OPTIMIZE.
However `G_REGEX_JAVASCRIPT_COMPAT` appears deprecated and glib's docs don't give me any hints about alternatives.

**Alternatives:**

`man pcrecompat` says:
```
5. ...if the PCRE_JAVASCRIPT_COMPAT option is set, \U and \u are interpreted as JavaScript interprets them.
```
`man pcre2compat` says:
```
 5. ...if either of the PCRE2_ALT_BSUX or PCRE2_EXTRA_ALT_BSUX options is set,
     \U and \u are interpreted as ECMAScript interprets them.
```
However, working by analogy and replacing the `G_REGEX_JAVASCRIPT_COMPAT` with `G_REGEX_ALT_BSUX`, `G_REGEX_EXTRA_ALT_BSUX` or `G_REGEX_ECMASCRIPT_COMPAT` don't yield a clean compilation.

According to [the pcre2 docs](https://www.pcre.org/current/doc/html/pcre2syntax.html) `\x{hhhh}` looks to be equivalent to `\uhhhh`.
The following patch implements this change, and seems to prevent the crash:
```
diff --git a/common/util.c b/common/util.c
index 4b44d851..61364f6b 100644
--- a/common/util.c
+++ b/common/util.c
@@ -61,9 +61,9 @@ strip_ansi_escapes(const gchar *in)
     static GRegex *reg;
 
     if (!reg) {
-        const gchar *expr = "[\\u001b\\u009b][[()#;?]*(?:[0-9]{1,4}(?:;[0-9]{0,4})*)?[0-9A-ORZcf-nqry=><]";
+        const gchar *expr = "[\\x{001b}\\x{009b}][[()#;?]*(?:[0-9]{1,4}(?:;[0-9]{0,4})*)?[0-9A-ORZcf-nqry=><]";
         GError *err = NULL;
-        reg = g_regex_new(expr, G_REGEX_JAVASCRIPT_COMPAT | G_REGEX_DOTALL | G_REGEX_EXTENDED | G_REGEX_RAW | G_REGEX_OPTIMIZE, 0, &err);
+        reg = g_regex_new(expr, G_REGEX_DOTALL | G_REGEX_EXTENDED | G_REGEX_RAW | G_REGEX_OPTIMIZE, 0, &err);
         g_assert_no_error(err);
     }
 
```
however, i don't really grasp the regexp, and won't put this in as a PR until i've convinced myself that it's correct.
Given that there are leading zeros on the hex values `...\\x1b\\x9b...` might work as well,
and it may be that `...\\N{U+001b}\\N{U+009b}...` works as well, or instead.

As an aside, using StackTracePlus prevents the crash, but this is not default and (i assume) most people aren't using it.

**Comment by msdemlei** [comment]
So... this thing has hit Debian, too, https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1020404.  As I say over there, what's right here depends on the sort of strings that come in.  If it's UTF-8 (which experimentally seems to be the case), then just writing \x1b does trick.

While investigating, I noticed what I'd consider a potential problem in that if you run luakit from a terminal emulator and have javascript enabled, that javascript can send escape sequences to your terminal.  How bad is that given what else javascript can do?  Probably not a desaster.  But it feels wrong, and perhaps we should consider using this sanitiser for console.log, too?

**Comment by taobert** [comment]
Well, `grep -ri utf` produces _many_ occurrences of UTF-8, in both cases,  and with and without the hyphen.
By contrast, `grep -ri ucs` finds only one variable in one function (`luaH_keystr_push`),
where (by my reading) it's set to be a utf8 character (`ulen = g_unichar_to_utf8(ukval, ucs);`).
So although i don't know enough about encoding schemes to form an opinion on my own,
the code seems to be consistent with your experimental results.
If you're confident that \x1b is equivalent to \u001b, i'll make the PR (unless you'd like to).

I don't know what the implications are of JS writing unchecked to the terminal.
I agree that it doesn't feel sensible, but if (other) people are now noticing that luakit can't be used with Debian,
then patching in the \x now, and fretting about the terminal output later would seem like a reasonable approach.

**Comment by msdemlei** [comment]
On Wed, Sep 21, 2022 at 08:41:22PM -0700, taobert wrote:
> If you're confident that \x1b is equivalent to \u001b, i'll make
> the PR (unless you'd like to).

So, the old \\uXXXX (note the double backslash) was interpreted by
glib.  I've briefly looked at
https://docs.gtk.org/glib/struct.Regex.html, and that says

  Note that, unless you set the G_REGEX_RAW flag, all the strings
  passed to these functions must be encoded in UTF-8.

Regrettably, we *are* using G_REGEX_RAW, but that's even less of a
concern then:

 If you set G_REGEX_RAW the strings can be non-valid UTF-8 strings
 and a byte is treated as a character, so “\xc3\xa0” is two bytes and
 two characters long.

As to what glib did with \u, it says:

  ...use the ‘\u’ escape sequence with 4 hex digits to specify a
  unicode codepoint.

At least for ESC, \x1b, I'm hence sure the effect is the same of just
letting C itself putting in a literal ESC (which is what the Debian
patch does -- not it's using a single backslash).  For ESC with the
8th bit set (\x9b), this would make a difference; but frankly, I'm
not even sure who uses such escapes, and I suspect *if* luakit
creates these, it won't utf-8-ise them.

> I don't know what the implications are of JS writing unchecked to
> the terminal.

Well, there's a history of interesting attacks working by inserting
escapes into log messages, but I don't have a link to one at hand.
But biven that probably not terribly many people start luakit from a
terminal, I don't think that's a reasonable attack surface.  *If* we
address it, I'd say we should rather suppress console.log to the
terminal by default and offer an option --js-log-to-console with the
appropriate warning rather than make an attempt to filter things.

> then patching in the \x now, and fretting about the terminal output
> later would seem like a reasonable approach.

Absolutely.  And since I'm lazy, I'm grateful if you do the PR.
