### ISSUE TITLE
Hints with letters instead of numbers

### ISSUE THREAD

**Issue by robcsi** [luakit/luakit#1008]
**Current Behavior:**
Currently hints are only shown as combinations of digits. At least, I didn't find any way to change them.

**Desired Behavior:**
Provide option to switch to letter-based hints, as in Qutebrowser. It would be easier to use because letters are closer to home row than numbers. But of course to each their own. Still, an option would be nice to switch between the two.

**How can we reproduce it (step by step):**
Press 'f' and see hints being shown as numbers. Letters would be more useful for some.

**Environment:**

Linux Distribution & Version:
Arch linux.
Output of `luakit --version`:
luakit 2.3.1
  built with webkit 2.36.7 (installed version: 2.36.7)

**Comment by taobert** [comment]
I use:
```lua
-- Use home row (and a bit) characters for generating labels
local select = require "select"
select.label_maker = function (s)
    return s.sort(s.reverse(s.charset("fjdksla;ghutnvir")))
end
-- Match only hint label text
local follow = require "follow"
follow.pattern_maker = follow.pattern_styles.match_label
```

**Comment by robcsi** [comment]
Workis fine, thanks.
