### ISSUE TITLE
Problems with new webkitgtk? (2.38.0-2 on arch)

### ISSUE THREAD

**Issue by henkmet** [luakit/luakit#1010]
**Current Behavior:**
crashes on opening with rc.lua not found.

exact error in attached file
[test.txt](https://github.com/luakit/luakit/files/9630609/test.txt)

**Desired Behavior:**
no crash; read rc.lua correctly

**How can we reproduce it (step by step):**
start luakit

**Environment:**
Linux Distribution & Version: archlinux, up-to-date (latest update has webkit2gtk 2.38.0-2)
Output of `luakit --version`:
luakit 2.3.1-4-ga8b1cd5c
  built with webkit 2.38.0 (installed version: 2.38.0)

**Note about webkit issues:**

If you're reporting a rendering issue, please test it with the gnome
browser ephiphany as well. If the issue occurs there too, we're very
likely not able to help. These issues should be reported to webkit:
https://bugs.webkit.org

**Comment by henkmet** [comment]
Sorry, probably should have added the rc.lua as well. 
[rc.lua.txt](https://github.com/luakit/luakit/files/9630648/rc.lua.txt)

Edit to add: Actually, looking at the warnings just above the error I wonder if it may be related to the glib/unicode error that's discussed in another issue?

**Comment by taobert** [comment]
Yes, it's another impact of the same upstream change.
You'll need to patch not just `common/util.c` as i suggest in #1005, but also `common/clib/regex.c`:
```
diff --git a/common/clib/regex.c b/common/clib/regex.c
index c4f42317..e87156cf 100644
--- a/common/clib/regex.c
+++ b/common/clib/regex.c
@@ -59,7 +59,7 @@ luaH_regenerate_regex(lua_State *L, lregex_t *regex)

     GError *error = NULL;
     regex->reg = g_regex_new(regex->pattern,
-            G_REGEX_DOTALL|G_REGEX_OPTIMIZE|G_REGEX_JAVASCRIPT_COMPAT, 0, &error);
+            G_REGEX_DOTALL|G_REGEX_OPTIMIZE, 0, &error);
     if (error) {
         lua_pushstring(L, error->message);
         g_error_free(error);
diff --git a/common/util.c b/common/util.c
index 4b44d851..738e1e5c 100644
--- a/common/util.c
+++ b/common/util.c
@@ -61,9 +61,9 @@ strip_ansi_escapes(const gchar *in)
     static GRegex *reg;

     if (!reg) {
-        const gchar *expr = "[\\u001b\\u009b][[()#;?]*(?:[0-9]{1,4}(?:;[0-9]{0,4})*)?[0-9A-ORZcf-nqry=><]";
+        const gchar *expr = "[\x1b\x9b][[()#;?]*(?:[0-9]{1,4}(?:;[0-9]{0,4})*)?[0-9A-ORZcf-nqry=><]";
         GError *err = NULL;
-        reg = g_regex_new(expr, G_REGEX_JAVASCRIPT_COMPAT | G_REGEX_DOTALL | G_REGEX_EXTENDED | G_REGEX_RAW | G_REGEX_OPTIMIZE, 0, &err);
+        reg = g_regex_new(expr, G_REGEX_DOTALL | G_REGEX_EXTENDED | G_REGEX_RAW | G_REGEX_OPTIMIZE, 0, &err);
         g_assert_no_error(err);
     }

```

I'm not sure how to mark this as a duplicate, but I've submitted the PR with both numbers, so it shouldn't matter much for long.

**Comment by aidanholm** [comment]
Closing due to https://github.com/luakit/luakit/commit/e9c7693f387835bdf2d1ada85c2ba0b813686ebb (wasn't auto-closed)
