### ISSUE TITLE
no option to enable vertical tabs?

### ISSUE THREAD

**Issue by hephaestic** [luakit/luakit#1012]
**Current Behavior:**
no vertical tabs option in settings page. No obvious documentation on how to enable it

**Desired Behavior:**
Show setting for vertical tabs on settings page. Or have documentation on how to enable it via userconf.lua

**How can we reproduce it (step by step):**
open luakit settings page

**Environment:**

Linux Distribution & Version:
kubuntu 22.04

Output of `luakit --version`:luakit 2.3
  built with webkit 2.34.2 (installed version: 2.36.7)

**Note about webkit issues:**

If you're reporting a rendering issue, please test it with the gnome
browser ephiphany as well. If the issue occurs there too, we're very
likely not able to help. These issues should be reported to webkit:
https://bugs.webkit.org

New to Luakit/Lua.
I see there is a module for vertical tabs and I know people have been using it, but no setting to enable it. How can I switch to it?

**Comment by taobert** [comment]
Add `require('vertical_tabs')` to your `userconf.lua` file.
Once you've done that, you'll also have `vertical_tabs.sidebar_width` and `vertical_tabs.side` on the settings page.
Edit: If you had searched for "vertical_tabs" in the issues here, you would have found how to enable it (see #585).

**Comment by hephaestic** [comment]
Somehow overlooked that one. I knew I must have missed something. Thanks.

**Comment by xxxserxxx** [comment]
> Add `require('vertical_tabs')` to your `userconf.lua` file.

That's not sufficient. Or, at least, not for me. I don't get a module error on the require, but the tabs stay obstinately on the top. And #585 says that you only need to require the module, it doesn't say anything about setting `sidebar_width` or `side`. The `settings` page has no options for either of those, and it's not clear what units of measure they are, or what values are legal.

Is there any documentation for this feature?

**Update**

It can't be required in `rc.lua`, like all of the other modules; it has to be required in `userconf.lua`. Then it works.
