### ISSUE TITLE
zoom_level quirky behavior

### ISSUE THREAD

**Issue by myf** [luakit/luakit#1013]
**Current Behavior:**

zoom_level is set to a number above 100% due to HiDPI screen. 
I found it has erratic behaviors: sometimes the zoom would not work, everything is really tiny. and some times either j/k scrolling would not work or touchpad scrolling would not work.
today i seem to have found a reproducable behavior:

- zoom would work in a new tab
- zoom would not work in a current tab
- 
**Desired Behavior:**

- zoom would work in a new tab
- zoom would work in a current tab after refreshing or a new page
 
**How can we reproduce it (step by step):**

- set zoom to say 180
- restart luakit and it will load correctly
- :tabopen a page will load correctly
- however refreshing or :open another url in the current tab will not load correctly

**Environment:**

Linux Distribution & Version:
Output of `luakit --version`:

luakit 2.3-35-g4c69751d
(i had to get it working with taobert's patch https://github.com/luakit/luakit/pull/1011)

**Note about webkit issues:**

If you're reporting a rendering issue, please test it with the gnome
browser ephiphany as well. If the issue occurs there too, we're very
likely not able to help. These issues should be reported to webkit:
https://bugs.webkit.org

**Comment by taobert** [comment]
I can't reproduce this (debian sid, luakit 2.3.1-4-ga8b1cd5c).
Setting a `zoom_level` and reloading the page/:opening a new link sets the zoom appropriately with or without a restart.
Are you using the `:settings` chrome, or `:set webview.zoom_level 180`?
Confirm for me that "will not load correctly" means that it loads but `zoom_level` is at 100%.
What system are you on?

Regarding scrolling, have you read through #1007, #970, #826?
They're not really resolved, but it might give some clarity on exactly what quirks you're seeing, and whether it's something novel.

**Comment by myf** [comment]
- @taobert I have been using `:settings` chrome instead of `:set`
- yes "will not load correctly" meaning `zoom_level` is 100%
- I am on archlinux

**edit** I have just tried `:set webview.zoom_level 180` and i got the same repeatable behavior: will render 100% on the current tab but will render 180% on `:tabopen`

**Comment by myf** [comment]
.. i might have found the real issue. I think there might be a very stale `styles.db` in `.local/share/luakit`. deleting it seems to fix most of the zoom problems.. will observe for a bit and close this if it's all fixed.

**Comment by myf** [comment]
sorry for the silence recently. i haven't closed it because i am experiencing the same behavior unpredictably. cleaning the `styles.db` and cookies would reset it but it will eventually come back. i have not figured out what caused it to ignore the zoom level yet.

**Comment by c0dev0id** [comment]
Do you have a stylesheet in `.local/share/luakit/styles/`? Does this define zoom?

**Comment by myf** [comment]
@c0dev0id i used to have some in `.local/share/luakit/styles/` indeed. I have since moved them to a backup folder to debug this issue. but zoom issue still happens sporadically afterwards. they are in a different folder in `.local/share/luakit` so i hope its not being scanned...

**Comment by c0dev0id** [comment]
Will the issue go away when you comment
```lua 
local styles = require "styles"`
```
in `rc.lua`?

If not, then I assume it's completely independent from the styles(.db)

**Comment by myf** [comment]
still observing. what i find interesting is that i have the habit to do `:wq` to preserve the session and sometimes this will cause the zoom level to fail

@c0dev0id removing that require style line does seem to reset it

**Comment by xxxserxxx** [comment]
Commenting out the styles module fixes it for me, too. There is nothing in either `styles.db` or my `styles` directories:

```
$ ls -l ~/.local/share/luakit/styles
total 0
$ sqlite3 ~/.local/share/luakit/styles.db .sch
CREATE TABLE by_file (
        id INTEGER PRIMARY KEY,
        file TEXT,
        enabled INTEGER
    );
$ sqlite3 ~/.local/share/luakit/styles.db 'select * from by_file;'
$
```

This is sporadic, except that when it happens I can't seem to get rid of it for a while. Restarting used to be a quick fix, but the last time it happened it wouldn't reset (which is how I ended up here).

**Comment by PluMGMK** [comment]
Sorry to pull up this old issue, but I see similar behaviour and even after commenting out styles it still seems to be happening. I'm 90% sure this only started happening for me after https://github.com/luakit/luakit/pull/1036 was pulled (although this ticket seems to be older than that, so maybe I should just make a new one…)
