### ISSUE TITLE
google account, no login code sent

### ISSUE THREAD

**Issue by maccagnan** [luakit/luakit#1015]
**Current Behavior:**when I try to login into my google account with two-step verification, I don't get any message with the 6-digit code to my cell phone. Not even if I try resend. If I try on the same account with another browser, it works fine.

**Desired Behavior:** get message to my cell phone when using two-step verification.

**How can we reproduce it (step by step):**

**Environment:**

Linux Distribution & Version:
Output of `luakit --version`:

**Note about webkit issues:**

If you're reporting a rendering issue, please test it with the gnome
browser ephiphany as well. If the issue occurs there too, we're very
likely not able to help. These issues should be reported to webkit:
https://bugs.webkit.org

**Comment by taobert** [comment]
Well, i don't have much interest in giving Google my phone number, so i can't really test this.
I have 2FA set up using "Google Prompts",
that is "Google Play Services" on my phone asks me whether i just tried to log in,
and i click yes to allow the login to procede.
I gather there's an "Authenticator app" if you don't have Google Play Services.

I can confirm that when i "Add phone number" i do receive a code via sms.
I'm not going to type that code in to verify the number, so this doesn't really test the 2FA, 
but it hints that the mechanism should function.

More generally, it's not all that clear how luakit would break this.
The click event might not be sent correctly, but if that gets through, i'd expect that all of the sending would be server-side.
Google might conceivably choose to not send the text if it didn't recognise the UA string.
Is the other browser chromium? Have you tried epiphany?

You don't mention which version of Luakit you're running. Is it current?

**Comment by maccagnan** [comment]
Yes, the latest version on Alpine and another I compiled on Devuan, albeit I don't recall which distro gave me the error. I will try again on both later. I'll try also on Surf which I understand uses Webkit2gtk too. The reason a Google account is important to me is because my students use Google Docs a lot. I had troubles with google on Qutebrowser too, but those solved changing the agent. The error happens on accounts with the two-step verification, which lately is the only for to access Gmail with Sylpheed or Gnubiff.

On Sat, 01 Oct 2022 01:41:50 -0700
taobert ***@***.***> wrote:

> Well, i don't have much interest in giving Google my phone number, so i can't really test this.
> I have 2FA set up using "Google Prompts",
> that is "Google Play Services" on my phone asks me whether i just tried to log in,
> and i click yes to allow the login to procede.
> I gather there's an "Authenticator app" if you don't have Google Play Services.
> 
> I can confirm that when i "Add phone number" i do receive a code via sms.
> I'm not going to type that code in to verify the number, so this doesn't really test the 2FA, 
> but it hints that the mechanism should function.
> 
> More generally, it's not all that clear how luakit would break this.
> The click event might not be sent correctly, but if that gets through, i'd expect that all of the sending would be server-side.
> Google might conceivably choose to not send the text if it didn't recognise the UA string.
> Is the other browser chromium? Have you tried epiphany?
> 
> You don't mention which version of Luakit you're running. Is it current?
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/luakit/luakit/issues/1015#issuecomment-1264293207
> You are receiving this because you authored the thread.
> 
> Message ID: ***@***.***>


-- 
amc252 <amc252@@gmail.com>

**Comment by taobert** [comment]
Sure. I wasn't particularly intending to be dismissive of you using gmail. I do too.
You _can_ set up 2FA without the text messages, if it turns out that that's the only point of failure.
Also, (if you have 2FA enabled) you can set up app passwords to remove the need for the 2FA dance.
I expect they'd work with sylpheed and gnubiff. They _do_ work with mutt, offlineimap and k9 mail.

**Comment by maccagnan** [comment]
I purged/reinstalled Luakit (on Devuan) and now it works fine. Google is very particular in making life hard for anything but Chrome. Even on Qutebrowser at times it's tricky to make it work. Thanks for taking the time to help me.
