### ISSUE TITLE
Luakit does not start with glib2 v2.74.0 on Archlinux

### ISSUE THREAD

**Issue by twnaing** [luakit/luakit#1019]
**Current Behavior:**
Luakit does not open

**Desired Behavior:**
Luakit should open

**How can we reproduce it (step by step):**
Install Luakit 2.3.1 on Archlinux

**Environment:**

Linux Distribution & Version: Archlinux
Output of `luakit --version`: 2.3.1
Relevant info: glib2 v2.74.0

**Note about webkit issues:**

If you're reporting a rendering issue, please test it with the gnome
browser ephiphany as well. If the issue occurs there too, we're very
likely not able to help. These issues should be reported to webkit:
https://bugs.webkit.org

```
[    0.087572] W [glib]: GLib: g_regex_new: assertion '(compile_options & ~G_REGEX_COMPILE_MASK) == 0' failed
[    0.087957] W [glib]: GLib: g_regex_replace_eval: assertion 'regex != NULL' failed
[    0.088175] E [core/common/lualib]: Lua error: attempt to concatenate a nil value
Traceback:
(1) [C]                                     in function traceback
(2) /usr/share/luakit/lib/modes.lua:36      in function new_mode
(3) /usr/share/luakit/lib/modes.lua:139     in main chunk
(4) [C]                                     in function require
(5) /usr/share/luakit/lib/log_chrome.lua:14 in main chunk
(6) [C]                                     in function require
(7) /etc/xdg/luakit/rc.lua:50               in main chunk
[    0.089564] W [core/luah]: loading rc '/etc/xdg/luakit/rc.lua' failed, falling back...
```

Current workaround:
- downgrading glib2 to 2.72.3 works (suggested by @gearhead in [Arch forum](https://bbs.archlinux.org/viewtopic.php?id=280070))

**Comment by henkmet** [comment]
If you don't mind installing it from the AUR (luakit-git) that would be a much better way. The issue has been solved by recent commits and on archlinux downgrading, especially a key package like glibc, is not a supported course of action.

**Comment by twnaing** [comment]
Installed luakit-git and got 

```
luakit 2.3.1-6-ge9c7693f
    built with webkit 2.38.0 (installed version: 2.38.0)
```

and it is working.
