### ISSUE TITLE
Lua error: attempt to concatenate a nil value

### ISSUE THREAD

**Issue by flwwater** [luakit/luakit#1022]
$ luakit
[    0.026764] I [core/luah]: Loading rc: /etc/xdg/luakit/rc.lua
[    0.102755] W [glib]: GLib: g_regex_new: assertion '(compile_options & ~G_REGEX_COMPILE_MASK) == 0' failed
[    0.102801] W [glib]: GLib: g_regex_replace_eval: assertion 'regex != NULL' failed
[    0.102896] E [core/common/lualib]: Lua error: attempt to concatenate a nil value
Traceback:
(1) [C]                                     in function traceback
(2) /usr/share/luakit/lib/modes.lua:36      in function new_mode
(3) /usr/share/luakit/lib/modes.lua:139     in main chunk
(4) [C]                                     in function require
(5) /usr/share/luakit/lib/log_chrome.lua:14 in main chunk
(6) [C]                                     in function require
(7) /etc/xdg/luakit/rc.lua:50               in main chunk
[    0.102927] W [core/luah]: loading rc '/etc/xdg/luakit/rc.lua' failed, falling back...
[    0.025931] W [core/luah]: couldn't load any rc file
[    0.025958] F [core/luakit]: couldn't find rc file

kubuntu22.10
luakit:2.3.1 from apt install

**Comment by taobert** [comment]
This is fixed (here) already.
You could compile from source yourself, wait for kubuntu to update their package, or perhaps install the Debian package.

**Comment by c0dev0id** [comment]
I'm closing this issue. Please reopen, if the issue still exists in the latest version (2.3.3).
