### ISSUE TITLE
How do I save settings in :settings ?

### ISSUE THREAD

**Issue by winteriscariot** [luakit/luakit#1026]
Currently javascript is disabled, and I want to enable it. I do NOT currently have the noscript plugin enabled. If I go to :settings and tick the enable_javascript option, it doesn't "stick." There's no "save" button to save this setting. If I close the browser and restart it, the setting is not saved.

How can I make sure luakit settings persist?

**Comment by Tonus1** [comment]
On the front-page : 
Configuration
Luakit configuration files are written in lua. This means you can program within the config files, which make the configuration options endless.

There are three ways to customize luakit.

1. within luakit

After starting luakit, type :settings. This page shows you webkit engine related settings.

2. userconf.lua

Create a file called $HOME/.config/luakit/userconf.lua. Then add your configuration there. Configuration in this file supersedes configuration set in :settings

3. copy rc.lua

The most powerful customization is to copy rc.lua from /etc/xdg/luakit/rc.lua to $HOME/.config/luakit/rc.lua

When this file is found, /etc/xdg/luakit/rc.lua is ignored.

Be informed that when luakit is updated, you may need to adapt changes from /etc/xdg/luakit/rc.lua to your own copy.

**Comment by c0dev0id** [comment]
Whatever you select in `:settings` should automatically be saved to the file `~/.local/share/luakit/settings`. 

The file is updated right after you make the change in luakit. No "save" necessary.

Check if luakit can create the file and is updating it. It's a text file, so you can view it with `cat ~/.local/share/luakit/settings).

There are more ways to configure luakit as @Tonus1 showed.
