### ISSUE TITLE
Tab list code

### ISSUE THREAD

**Issue by Tonus1** [luakit/luakit#1032]
@taobert wrote this about a year ago :
>If you struggle to remember the indices of every tab you have open,
>(i currently have 48 tabs in my "Luakit" tabgroup, and hide the tablist,) a couple of alternatives would be:
>`tabmenu` in the `luakit-plugins` repository will give you a menu of tabs that you can scroll through and select from.
>Or, you could spawn `dmenu` which will  do the same, and also let you type in a pattern to restrict the tabs shown.
>A reference implementation of the latter might look like:
```lua
modes.add_binds("normal", {
    { "<control-t>", "List tabs in dmenu",
	function (w)
	    local list = ""
	    local dmenu='dmenu -i -l 20'
	    local label

	    for i, view in ipairs(w.tabs.children) do
		label=( (view.title ~= "Web Process Crashed" and view.title)
			or view.uri
			or "" )
		list = list .. i ..  "  " ..  label .. "\n"
	    end
	    list = lousy.util.escape(list)

	    local fh=io.popen("echo '" ..list .. "' |" .. dmenu ,"r")
	    local sel=fh:read("*a")
	local tabchoice = string.match(sel, "^[0-9]+")
	w.tabs:switch(tabchoice)
	end },
})

```

_Originally posted by @taobert in https://github.com/luakit/luakit/issues/889#issuecomment-767894682_
 
For that to work I had to remove
```
list = lousy.util.escape(list)
```
But I am facing an error if I try to escape without chosing a `tabchoice` value. I tryed to add a condition but couldn't achieve that.

Any pointer or help would be great (haven't yet found time to get this lua syntax).

Regards

**Comment by taobert** [comment]
>I am facing an error if I try to escape without chosing a tabchoice value. I tryed to add a condition but couldn't achieve that.

I obviously don't know what _you_ tried, but the code i'm using is:
```lua
    { "<control-t>", "List tabs in dmenu",
	function (w)
	    local cur = w.tabs:current()
	    local list = ""
--	    local dmenu='dmenu -i -l 20'
	    local dmenu='~/Programming/suckless/dmenu-origin/dmenu -i -l 20 -o ' .. cur
	    local label

	    for i, view in ipairs(w.tabs.children) do
		label=( (view.title ~= "Web Process Crashed" and view.title)
			or view.uri
			or "" )
		list = list .. i ..  "  " ..  label .. "\n"
	    end
	    list = lousy.util.escape(list)

	    local fh=io.popen("echo '" ..list .. "' |" .. dmenu ,"r")
	    local sel=fh:read("*a")
	    local tabchoice = string.match(sel, "^[0-9]+")
	    if (tabchoice and (tonumber(tabchoice) ~= cur)) then
--		print("switching to "..tabchoice)
		w.tabs:switch(tabchoice)
	    end
	end },
```



> I had to remove
>```
>list = lousy.util.escape(list)
>```

`io.popen()` runs stuff in a shell.
You _really_ want to escape remotely generated strings before passing them to a shell:
```
io.popen("echo '".."This is an unsafe string '`touch DANGER`'".."'")
```
will create a file called DANGER. It gets worse from there.

**Comment by Tonus1** [comment]
That's really confusing. Even if I copy and paste your code, I get an error that I
```
attempt to index global 'lousy' (a nil value)
```
I found at last a working code with no error when I escape without selecting a tab in the list

```lua
 {"<control->", "List tabs in dmenu",
      function (w)
          local list = ""
          local dmenu='dmenu -i -l 20'
          local label

          for i, view in ipairs(w.tabs.children) do
            label=( (view.title ~= "Web Process Crashed" and view.title)
                  or view.uri
                  or "" )
            list = list .. i ..  "  " ..  label .. "\n"
          end

          local fh=io.popen("echo '" ..list .. "' |" .. dmenu ,"r")
          local sel=fh:read("*a")

          local tabchoice = string.match(sel, "^[0-9]+")
           if (tabchoice) then
           w.tabs:switch(tabchoice)
           end
      end },
```

If you have a clue on what happened, I'm curious.
Anyway thank you for your time and effort, I learnt something from it !

**Comment by taobert** [comment]
Yes, you'll also need:
```lua
local lousy = require("lousy")
```
I have it at the top of the file.

**Comment by Tonus1** [comment]
That obviously did resolve my error.

Thank you !
