### ISSUE TITLE
[Question] how to download a file in a giving path without confirmation

### ISSUE THREAD

**Issue by zakariaGatter** [luakit/luakit#1037]
i create a function for luakit and i want to download a file directly to a `PATH` without confirmation

need help and thank you so much

**Comment by taobert** [comment]
Does "without confirmation" mean "without the 'save file here' dialog"?.
This is poped up by `luakit.save_file()` calling `gtk_file_chooser_dialog_new()`.
You could write your own `luakit.save_file` function which instead used `luakit.spawn()` to call wget/curl/whatever.
Or just make a command/binding that did that when you explicitly tell it to.

**Comment by zakariaGatter** [comment]
its a very good idea using `luakit.spawn()` with `curl` i like it thank you so much

**Comment by taobert** [comment]
Umm, actually, overwriting `luakit.save_file` probably isn't useful (sorry for the bum steer),
and while writing a new command/binding would work, it might not be necessary.

Take a look at the `:download` command.
This calls `downloads.add()` which can take a filename as an argument.
`luakit.save_file` only gets called if a filename isn't supplied.

**Comment by zakariaGatter** [comment]
what im trying to do is create a command on `luakit` to download adblock files from multiple sources 

```lua
 -- list of adblock urls
 local adblock_list = {
     'https://easylist.to/easylist/easylist.txt',
     'https://easylist.to/easylist/easyprivacy.txt',
     'https://secure.fanboy.co.nz/fanboy-cookiemonster.txt',
     'https://easylist.to/easylist/fanboy-social.txt',
     'https://secure.fanboy.co.nz/fanboy-annoyance.txt',
 }
 
 add_cmds({
     {":adblock-update, :abu", "Update adblock List", function(w)
         local downloads = require "downloads"
         local adblock_dir = luakit.data_dir .. "/adblock/"
 --         local downloads.default_dir = adblock_list
         local subscriptions_file = adblock_dir .. "subscriptions"
         for _,url in pairs(adblock_list) do
            local fn = string.gsub(url, "(.*/)(.*)", "%2")
            downloads.add(url, { filename = fn , allow_overwrite = true })
        end
    end},
})
```

when i run this command the list get Downloaded but i need to confirm manualy

**Comment by taobert** [comment]
In my hands, this works if `fn` has a full path:
```lua
local fn = adblock_dir..string.gsub(url, "(.*/)(.*)", "%2")
```
However, the `downloads` module keeps a database of downloads, which has a `UNIQUE` constraint on the finish time.
Because of how fast these download, i see errors about this constraint being violated.
These are not dangerous in and of themselves, but are poor form: we shouldn't train ourselves to ignore errors.

The adblock plugin has the advice that:
> -- * Filter lists need to be updated regularly (~weekly), use cron!

Aside from the joy of tinkering with luakit,
there's not really any benefit to setting up a scheme that requires you to download the filter lists manually,
so as it suggests, use cron.

**Comment by zakariaGatter** [comment]
Waw it work perfect as i want, thank you so much 

I know `cron` is much better is just want to make this function as a training and i think is useful also 

anyhow thank you so much for your help
