### ISSUE TITLE
Dependency problem compiling on Fedora 38

### ISSUE THREAD

**Issue by Naadiyaar** [luakit/luakit#1050]
so i'm trying to make it on Fedora 38 virtual machine but getting some errors about not providing required dependencies here is what i do and outputs:
```bash
[naadi@fedora luakit]$ make
Package webkit2gtk-4.1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `webkit2gtk-4.1.pc'
to the PKG_CONFIG_PATH environment variable
Package 'webkit2gtk-4.1', required by 'virtual:world', not found
Package 'luajit', required by 'virtual:world', not found
config.mk:109: *** Cannot find required package(s\) to build luakit. Please check you have the above packages installed and try again.  Stop.
```
checking for installed packages:
```bash
[naadi@fedora luakit]$ rpm -qa | grep -i webkit2gtk
webkit2gtk4.1-2.40.3-1.fc38.x86_64
webkit2gtk4.0-2.40.3-1.fc38.x86_64
webkit2gtk4.0-devel-2.40.3-1.fc38.x86_64
```
```bash
[naadi@fedora luakit]$ rpm -qa | grep -i luajit
luajit-2.1.0-0.27beta3.fc38.x86_64
luajit2.1-luv-1.44.2.1-3.fc38.x86_64
```

**Comment by taobert** [comment]
None of this addresses why there would be an issue with `luajit` and so might be a red herring, but...

#1025 added support for webkit 4.1, and at that time 4.1 became the default in `config.mk`.
It looks like you have the `-devel-` package for 4.0 but not 4.1.
I would expect that you'll need the 4.1 devel infrastructure.
Alternatively, changing `config.mk` to have:
```
...
PKGS += webkit2gtk-4.0
...
PKGS += javascriptcoregtk-4.0
```
may work for you, as i don't think #1025 broke compatability with the earlier version.

**Comment by Naadiyaar** [comment]
Thanks for response, you're right simply downloading `webkit2gtk4.1-devel` solved issue with that but error with luajit is still there, i tried reinstalling it but didn't help

**Comment by taobert** [comment]
There appears to be a separate `luajit-devel` package which contains luajit as a `.so` (for luakit to link against?) rather than an executable.

**Comment by Naadiyaar** [comment]
Unfortunately I have more issues here which I don't know what to do about, so luakit needs LFS as dependency and i installed it via luarocks both systemwide and userwied using --local flag. however it seems luarocks installs LFS under `/usr/lib64/lua/5.4/lfs.so` and running make after that giving me the error:
```
luajit: build-utils/docgen/gen.lua:1: module 'lfs' not found:
	no field package.preload['lfs']
	no file './lfs.lua'
	no file '/usr/share/luajit-2.1.0-beta3/lfs.lua'
	no file '/usr/local/share/lua/5.1/lfs.lua'
	no file '/usr/local/share/lua/5.1/lfs/init.lua'
	no file '/usr/share/lua/5.1/lfs.lua'
	no file '/usr/share/lua/5.1/lfs/init.lua'
	no file 'build-utils/lfs.lua'
	no file './lfs.so'
	no file '/usr/local/lib/lua/5.1/lfs.so'
	no file '/usr/lib64/lua/5.1/lfs.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'require'
	build-utils/docgen/gen.lua:1: in main chunk
	[C]: in function 'require'
	./build-utils/docgen/makedoc.lua:9: in main chunk
	[C]: at 0x5613703d6db0
make: *** [Makefile:86: doc/apidocs/index.html] Error 1
```
and as you see, lua version/name is different here, so i tried to give it the file `lfs.so` manually either by copying it into `.../.5.1/` or the git directory. but now i'm getting this:
```
luajit: error loading module 'lfs' from file '/usr/lib64/lua/5.1/lfs.so':
	/usr/lib64/lua/5.1/lfs.so: undefined symbol: lua_newuserdatauv
stack traceback:
	[C]: at 0x564a3cde44e0
	[C]: in function 'require'
	build-utils/docgen/gen.lua:1: in main chunk
	[C]: in function 'require'
	./build-utils/docgen/makedoc.lua:9: in main chunk
	[C]: at 0x564a3cd8cdb0
make: *** [Makefile:86: doc/apidocs/index.html] Error 1
```
Which ~~i think is because of backward incompatibility~~ i'm not sure why is this happening. is there any way to fix this?

**Comment by taobert** [comment]
On Tue, Jul 25, 2023 at 12:51:42AM -0700, Naadiyaar wrote:
>  `/usr/lib64/lua/5.4/lfs.so` 

You'll need to install lfs for lua 5.1.
I just use the packages that Debian gives me,
but i see that luarocks has a `--lua-version` argument which may be useful here.


bye
TAO.

**Comment by Naadiyaar** [comment]
yes now it's compiled successfully. 
however, I still have problems executing but it's not related to this topic, thanks for your help
