### ISSUE TITLE
[Question] How to be able to configure or at least be able to adjust the height of the status bar?

### ISSUE THREAD

**Issue by groggone** [luakit/luakit#1057]
I want to make the statusbar have the same height as the tab but i don't know how. Would appreciate the help.

**Comment by taobert** [comment]
I'm not quite sure what you're seeing.
They look pretty similar to me, but i don't usually enable the tab bar, and so i might have not noticed.
Both the tablist (if it's horizontal) and the status bar are `hbox`es,
and (i think) should size themselves to fit what's in them.
So maybe you have `favicons` enabled and the icons are taller than the text?
I don't know enough about the icon sizing to advise on changing that,
but you can change the text size in `theme.lua`:
``` lua
theme.font = "13pt monospace"
```

Alternatively, you can add a margin around what's in an hbox:
```lua
local window = require "window"
window.add_signal("build", function (w)
    w.sbar.layout.margin_top = 10;
    w.sbar.layout.margin_bottom = 10;
end)
```

**Comment by groggone** [comment]
Hello, this is what it looks like. The status bar is much more bigger than the tablist and i don't know why.
![1693100637 Fullscreen](https://github.com/luakit/luakit/assets/97829937/b42702ba-5252-4da2-8f1d-27a983fa82fe)

**Comment by groggone** [comment]
I want the status bar to have the same size as the tablist

**Comment by taobert** [comment]
So, is that how it looked before your original post, or is that due to you adding a 10 px margin top and bottom?

**Comment by c0dev0id** [comment]
No response from author in a while. I'm closing this question.
