### ISSUE TITLE
Make a release with WebKitGTK-4.1/libsoup-3.0 support

### ISSUE THREAD

**Issue by mattst88** [luakit/luakit#1060]
https://github.com/luakit/luakit/issues/1025  and https://github.com/luakit/luakit/pull/1036 requested and implemented WebKitGTK-4.1 and libsoup-3.0 support. The pull request landed in January.

Can we have a release that distros can ship with WebKitGTK-4.1/libsoup-3.0 support?

**Comment by fictitiousexistence** [comment]
This would be great :D

**Comment by c0dev0id** [comment]
Better late than never, right?
https://github.com/luakit/luakit/releases/tag/2.3.4
