### ISSUE TITLE
[Megathread] Fingerprinting/Security/Privacy thread

### ISSUE THREAD

**Issue by ghost** [luakit/luakit#1061]
## Info
I'm creating this mega-thread as a central point to discuss anti-fingerprinting techniques, privacy and security options. I am seeing a lot more people with security, anonimity and privacy in mind pick up on Luakit, so I think a thread like this would be really handy as a place for said users to share their configurations and discuss topics related to the subject.

I'll be posting my findings here too

## Resources
Resources that can be used for testing configurations, finding new anti-fp techniques, settings etc.

- [The Design and Implementation of the Tor Browser](https://2019.www.torproject.org/projects/torbrowser/design/), can be used to uplift certain things
- https://trac.webkit.org/wiki/Fingerprinting, items that can be used for fingerprinting
- https://abrahamjuliot.github.io/creepjs/
- https://www.amiunique.org
- https://coveryourtracks.eff.org/
- https://browserspy.dk/
- https://browserleaks.com/
- https://arkenfox.github.io/TZP/index.html
- https://clienttest.ssllabs.com:8443/ssltest/viewMyClient.html
- https://www.deviceinfo.me/
*feel free to suggest more resources*

**Comment by ghost** [comment]
These are my current "hardening" options:
```lua
local settings = require "settings"
local noscript = require "noscript"
local soup = require "soup"

noscript.enable_scripts = false
settings.webview.enable_xss_auditor = false
settings.webview.enable_javascript = false
settings.webview.enable_java = false
settings.webview.enable_webgl = false
settings.webview.javascript_can_access_clipboard = false
settings.webview.enable_hyperlink_auditing = false
settings.webview.enable_dns_prefetching = false
settings.webview.enable_media_stream = false
settings.webview.enable_offline_web_application_cache = false
settings.webview.javascript_can_open_windows_automatically = false
soup.accept_policy = "never"

-- Going to write a module to strip referrer completely soon
require_web_module("referer_control_wm")

-- NOTE: Luakit sends the default useragent on first request
-- see https://github.com/luakit/luakit/issues/886
settings.webview.user_agent = "Mozilla/5.0 (Windows NT 10.0; rv:102.0) Gecko/20100101 Firefox/102.0"
```

**Comment by ghost** [comment]
A tip for the proxy/vpn users out there, make sure to disable IPv6 to prevent IPv6 leaks from happening by doing:
```properties
sysctl net.ipv6.conf.all.disable_ipv6=1
sysctl net.ipv6.conf.default.disable_ipv6=1 
```

Or by adding those lines (without "sysctl") to your `/etc/sysctl.conf` file.

You can verify by checking https://browserleaks.com/ip

**Comment by ghost** [comment]
I am currently working on a [Redirector](https://github.com/einaregilsson/Redirector)-like plugin, which can be used to redirect sites to privacy-friendly frontends (youtube to invidious, twitter to nitter, imgur to rimgo, etc).

So far I got the first redirect to work, aswell as multiple patterns (example: `http.?://google.com/(.+)?q=(.+)`)

I haven't been able to figure out how to match subdomains tho, so for example `http.?://(.+)google.com` would work on `https://www.google.com` and `https://google.com`. But I'll figure it out eventually

**Comment by ghost** [comment]
Luakit is good for web tracking but fingerprintin not.
On amiunique I am unique and on coveryourtrack I am almost :).
I have the same settings as you posted. I start browser with TZ=UTC luakit.

**Comment by ghost** [comment]
Yeah, fingerprinting is a big problem, which really isn't easy to counter when you use minimal browsers as there's less crowd to blend in.

If only there was a non-firefox, non-chromium, minimal Tor Browser that a lot of people used. If only.

**Comment by ghost** [comment]
Anyways, I finished my redirector extension, and I managed to get it to work with subdomains. It now supports multiple patterns, so you can do `http.?://twitter%.com/(.+)` which would match `http://twitter.com/foo` and `https://twitter.com/foo`, and `http.?://.+%.twitter%.com+/(.+)` which would match `http://www.twitter.com/foo` and `https://www.twitter.com/foo`.

I do wish Luakit had builtin JSON encoding and decoding, as now I'm forced to use an external library, albeit a very lightweight one

**Comment by ghost** [comment]
Do you know [https://www.genmirror.com/](url)? I tried for youtube.

BTW I am new with luakit and not so familiar with lua. I use/using Qutebrowser too.

**Comment by ghost** [comment]
I would suggest using [Invidious](https://github.com/iv-org/invidious) instead of whatever that site is lol.

Yeah no worries, I only picked up Lua like 3 days ago, so far I've been having a blast (except for some moments, like when I had to figure out the hard way that the `pairs()` function returns evertything in a randomized order).

I stopped using QuteBrowser after figuring out [this](https://github.com/qutebrowser/qutebrowser/issues/7777), and also because it uses Chromium under the hood

**Comment by ghost** [comment]
I am using Invidious on Firefox.
I didn't use Qutebrowser long time for the QT5-Webengine issues. Now They start 6 with Qutebrowser 3 but I didn't compile yet and I think I will do not and stay with Luakit which I like more and more.

**Comment by c0dev0id** [comment]
OP is a ghost now, and I think there are things much higher on the todo list for luakit than fpr protection.
