### ISSUE TITLE
module 'scripts.job' not found

### ISSUE THREAD

**Issue by martineausimon** [luakit/luakit#1075]
**Current Behavior:**

Luakit won't start, and I'm getting this error message:

```
[    0.308197] I [core/luah]: Loading rc: /etc/xdg/luakit/rc.lua
[    0.326763] E [core/common/lualib]: Lua error: module 'scripts.job' not found:
                 	no field package.preload['scripts.job']
                 	no file './scripts/job.lua'
                 	no file '/usr/share/luajit-2.1/scripts/job.lua'
                 	no file '/usr/local/share/lua/5.1/scripts/job.lua'
                 	no file '/usr/local/share/lua/5.1/scripts/job/init.lua'
                 	no file '/usr/share/lua/5.1/scripts/job.lua'
                 	no file '/usr/share/lua/5.1/scripts/job/init.lua'
                 	no file '/usr/share/luakit/lib/scripts/job.lua'
                 	no file '/usr/share/luakit/lib/scripts/job/init.lua'
                 	no file '/home/simon/.config/luakit/scripts/job.lua'
                 	no file '/home/simon/.config/luakit/scripts/job/init.lua'
                 	no file '/etc/xdg/luakit/scripts/job.lua'
                 	no file '/etc/xdg/luakit/scripts/job/init.lua'
                 	no file './scripts/job.so'
                 	no file '/usr/local/lib/lua/5.1/scripts/job.so'
                 	no file '/usr/lib/lua/5.1/scripts/job.so'
                 	no file '/usr/local/lib/lua/5.1/loadall.so'
                 	no file './scripts.so'
                 	no file '/usr/local/lib/lua/5.1/scripts.so'
                 	no file '/usr/lib/lua/5.1/scripts.so'
                 	no file '/usr/local/lib/lua/5.1/loadall.so'
                 Traceback:
                 (1) [C]                                          in function require
                 (2) markdown.lua:1                               in main chunk
                 (3) [C]                                          in function require
                 (4) /usr/share/luakit/lib/settings_chrome.lua:13 in main chunk
                 (5) [C]                                          in function require
                 (6) /etc/xdg/luakit/rc.lua:73                    in main chunk
[    0.326900] W [core/luah]: loading rc '/etc/xdg/luakit/rc.lua' failed, falling back...
```

I'm using Arch Linux with the Linux LTS kernel, and the version of Luakit is from the luakit-git on the AUR. The necessary dependencies seem to be installed correctly (luakit, lua51, lua...).

Output of `luakit --version`:
```
luakit 2.3.6-4-g892b58d7
  built with: webkit 2.42.4 (installed version: 2.42.4)
                 GTK 3.24.41 
                GLIB 2.78.4 
                SOUP 3.4.4 
```

**Comment by ghost** [comment]
weird, I can't find anything related to `scripts.job` in the codebase, and my configuration contains no traces of it either.

Also, `luakit-git` seems to be very outdated, according to the [package info](https://aur.archlinux.org/packages/luakit-git). Version `2.2.r75.g68e4ffc7-1` and last updated at 2022-12-25 04:09.

Funky

**Comment by martineausimon** [comment]
Thanks for the quick response ! Strangely, I have the same issue with the version from the official Arch Linux repositories. I just tested an installation from the source, and it works perfectly

**Comment by martineausimon** [comment]
Edit : Luakit only works if it is launched from my terminal within the GitHub clone directory. The error is the same when I run luakit elsewhere

**Comment by ghost** [comment]
maybe try removing the `require` statement from `/etc/xdg/luakit/rc.lua`, maybe it was added by accident?

**Comment by martineausimon** [comment]
I tried searching for a reference to the 'scripts.job' module before opening the issue, but it doesn't appear in `/etc/xdg/luakit/rc.lua`

**Comment by martineausimon** [comment]
It seems to be a PATH problem : start luakit with `LUA_PATH=/usr/local/share/luakit/ luakit` works

**Comment by c0dev0id** [comment]
Do you have LUA_PATH set to something else in your environment?
Do you have DEVELOPMENT_PATHS=1 set in your environment when building luakit?

The arch package builds luakit correctly. I don't know what could cause this path issue.

**Comment by martineausimon** [comment]
I haven't personally configured LUA_PATH, but I'm using [awesomewm](https://github.com/awesomeWM/awesome) and I think that's where the issue stems from. When I add :

```bash
export LUA_PATH="/usr/local/share/luakit:$LUA_PATH"
```

awesomewm no longer starts.

However `echo $LUA_PATH` returns nothing.

**Comment by c0dev0id** [comment]
> However echo $LUA_PATH returns nothing.

What about `env | grep -i lua`?

**Comment by martineausimon** [comment]
`PATH=/home/simon/Documents/github/lua-scripts:/home/simon/.local/bin:/home/simon/Documents/github/bash-scripts/:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl`

Nothing important I think, just a personal folder containing personal lua scripts in my `$PATH`

**Comment by martineausimon** [comment]
I would like to add (but it's probably related?) that Luakit is not really usable on my system, it freezes a lot.

**Comment by c0dev0id** [comment]
I don't know what to do here. `scripts.job` is not one of our files and also not part of the lua/luajit distribution. It's also nowhere mentioned in the code.

**Comment by martineausimon** [comment]
OK, I just found the source of the problem: I had a file `~/markdown.lua` which contained `require("scripts.job")`, a module in my nvim config. I moved this file and the issue is resolved. I wonder why this file was automatically loaded by luakit...

**Comment by taobert** [comment]
There is a `markdown.lua` module in Luakit. (It's used by pages like :bookmarks and :settings.)

If i look at my `package.path`:
```
:lua w:notify(package.path:gsub(";","\n"))
```
 i see `./?.lua` before `/usr/local/share/luakit/lib/?.lua`.
If your `package.path` is similar, (i'm not a hundred percent sure that i'm not setting mine somewhere,)
and you were in your home directory, then `~/markdown.lua` will have been required in preference to the luakit module.
This may be for historical reasons, so that people can override system-installed luakit modules with their own versions,
or may be inadvertant, since `./?.lua` seems to be first in luajit's default package.path.
Either way, it's probably suboptimal.

You can override `package.path` at the top of your `rc.lua`.
In my hands, the following seems to work adequately, but hasn't been tested beyond "Does luakit manage to start?":
```lua
package.path = luakit.install_paths.install_dir..'/lib/?.lua;'..
               luakit.install_paths.install_dir..'/lib/?/init.lua;'..
               luakit.config_dir..'/?.lua;'..
               luakit.config_dir..'/?/init.lua;'..
               '/etc/xdg/luakit/?.lua;'..
               '/etc/xdg/luakit/?/init.lua'
```

**Comment by martineausimon** [comment]
Thank you very much for this information !

**Comment by c0dev0id** [comment]
If changing the path order doesn't break a DEVELOPMENT_PATHS=1 build, then I'm not against flipping the order around.
