### ISSUE TITLE
Impossible to add proxy via config file?

### ISSUE THREAD

**Issue by tabletseeker** [luakit/luakit#1087]
I can set the proxy like this:
```
:proxy proxy-name socks://localhost:8000
```
Or like this:
```
export http_proxy=socks://localhost:8000
```
However there seems to be no way to add a proxy to `~/.config/luakit/rc.lua`

What am I missing?

**Comment by msdemlei** [comment]
On Sat, Sep 07, 2024 at 08:36:34AM -0700, tabletseeker wrote:
> However there seems to be no way to add a proxy to `~/.config/luakit/rc.lua`
>
> What am I missing?

Nothing -- the prosy module self-persists.  Just type :proxy to
switch between proxies.

You *can* do proxy management in your rc.lua using the API you will
find in the lower half of luakit://help/doc/modules/proxy.html -- but
I don't think there is much reason to in non-exotic scenarios.

**Comment by tabletseeker** [comment]
> You *can* do proxy management in your rc.lua using the API you will find in the lower half of luakit://help/doc/modules/proxy.html -- but I don't think there is much reason to in non-exotic scenarios.

Hello, if possible I'd like the proxy setting to be controlled via config, instead of typing out the command.

I've already tried to put the following code in `~/.config/luakit/rc.lua` but I must've done something wrong:
```
local proxy = require "proxy"
proxy.set (anon, http://localhost:8000, true)
proxy.set_active (anon) 
```
I found another file in `/usr/share/luakit/lib/proxy.lua`. 
The set function is defined there, so I thought I might be able to try it there?
```
function _M.set(name, address, save_file)
    name = lousy.util.string.strip(name)
    if not string.match(name, "^([%w%p]+)$") then
        error("Invalid proxy name: " .. name)
    end
    proxies[name] = lousy.util.string.strip(address)
    if save_file ~= false then _M.save() end
end
```

**Comment by msdemlei** [comment]
On Sat, Sep 07, 2024 at 12:05:52PM -0700, tabletseeker wrote:
> local proxy = require "proxy"
> proxy.set (anon, http://localhost:8000, true)
> proxy.set_active (anon)

Umm: is this a literal copy of the code?  If so, this must have
raised syntax errors, no?  (if in doubt, watch the stdout/stderr of
your luakit).

The arguments to set and set_active are strings, so you need quotes.
If it still does not work with quotes... are there other diagnostics?

**Comment by tabletseeker** [comment]
Hey man, thanks for that tip. You are right, I was missing quotes.
One more question, if you don't mind.
I'd also like to change the window position & size of a new window in the config, but couldn't find the same .set commands in the doc. 
Any idea how that's done? 

`window:set_default_size (width, height)` apparently only works in an active window, manually.

**Comment by msdemlei** [comment]
On Mon, Sep 09, 2024 at 11:33:41PM -0700, tabletseeker wrote:
> I'd also like to change the window position & size of a new window
> in the config, but couldn't find the same .set commands in the doc.
> Any idea how that's done?

I think what you are looking for is in
luakit://help/doc/modules/settings.html (settings.set_setting).  I
believe your key would be window.new_window_size and your value
something like "500x400".

I'm not aware that you can control the *position* for the window in
this way.  Under X11, this would primarily be the window manager's
responsibility anyway.  Depending on what you are trying to do,
perhaps using a nicely scriptable window manager (sawfish comes to
mind) will fit that use case better altogether, i.e., for the window
size (which the window manager can also control if it feels like it),
too?

(oh, and would you close your bug when you're happy?)
