### ISSUE TITLE
Native Wayland Support?

### ISSUE THREAD

**Issue by Stormtroppy** [luakit/luakit#1097]
Are there any plans for native wayland support? The app runs on Xwayland but some portals don't support all the features (clipboard, file manager, etc.).

**Comment by balejk** [comment]
luakit already supports Wayland as it is written using GTK+3 which has a Wayland backend. I daily drive it on sway without Xwayland without any of the issues you mention (clipboard, file manager).

In what environment (distribution, installation method, WM) are you using luakit and what is the output of `luakit --version` for your setup?

**Comment by Stormtroppy** [comment]
I'm using hyprland but it's xwayland portal does not support clipboards

This is the output of ` luakit--version `
` luakit 2.3.6
  built with: webkit 2.42.5 (installed version: 2.46.4)
                 GTK 3.24.41 
                GLIB 2.78.4 
                SOUP 3.4.4  `

**Comment by balejk** [comment]
The version output looks fine.

It is also possible that your GTK was built without the Wayland backend,
although I wouldn't expect that nowadays. Could you please check that? I
don't know how to do it directly, however if you are using your
distribution's package, the easiest is probably to look at the package
build recipe.

You can also try to run `GDK_BACKEND=wayland luakit` which should force
GTK to use the Wayland backend (and yes, that's with a D) and see if it
works or reports anything useful.

I was also going to suggest to try to disable Xwayland if that's
possible in Hyprland (theoretically unsetting the DISPLAY environment
variable in the launching shell might suffice) just momentarily to see
if GTK will then use the Wayland backend, however this should be covered
by the above suggestion.

**Comment by Stormtroppy** [comment]
Sorry for the late reply, I had to reinstall luakit because my config broke, and now that I actually test `GDK_BACKEND=wayland luakit`, it works with my clipboard, which doesn't work with the default xwayland. I guess I should just close this issue since there is wayland support

**Comment by Stormtroppy** [comment]
Also, with this, the stuttering I have been experiencing with the Xwayland version is gone

**Comment by balejk** [comment]
I'm glad to hear that, although I'm still a little confused why it
doesn't work for you out of the box by default: even when I enable
Xwayland on my machine, luakit still seems to run natively, only when I
unset the WAYLAND_DISPLAY environment variable does Xwayland get
executed upon me launching luakit.
