### ISSUE TITLE
Page scripts can persist after tab close.

### ISSUE THREAD

**Issue by Plaque-fcc** [luakit/luakit#136]
After visiting m.vk.com, I've noticed (using iftop) that there are several connections to addresses srv41-131.vkontakte.ru what relates directly to vk.com; the tab is closed, they should be gone, no?

If any script can persist residently with no way to drop it, I consider it not only a performance issue, but also a security issue.

**Comment by aidanholm** [comment]
This was probably caused by a WebKit bug; since luakit has been updated to use WebKit 2, this is probably fixed.
