### ISSUE TITLE
Link hints not properly aligned on some websites

### ISSUE THREAD

**Issue by zoqaeski** [luakit/luakit#141]
Every now and then I come across a site for which the link hints aren't properly aligned[1]. Is this a bug in luakit or something to do with the site's styling and/or scripts?

[1] http://wiki.contextgarden.net/ConTeXt_Standalone (Screenshot: http://ompldr.org/vZnRtdQ)

**Comment by aidanholm** [comment]
Cannot reproduce. Luakit has been updated extensively and this issue is probably no longer present.
