### ISSUE TITLE
Locale-dependent decimal separators in config files

### ISSUE THREAD

**Issue by md2** [luakit/luakit#143]
I just upgraded to webkit-gtk-1.8.3-r200 (from 1.6.3-r200),
and luakit is now refusing to start, complaining about malformed numbers
in its config files and plugins:

error loading module 'webview' from file '/etc/xdg/luakit/webview.lua':
        /etc/xdg/luakit/webview.lua:263: malformed number near '0.1'
    [    0,225842] E: luakit: main:189: no windows spawned by rc file, exiting
...
error loading module 'cmdhist' from file '/usr/share/luakit/lib/cmdhist.lua':
        /usr/share/luakit/lib/cmdhist.lua:55: malformed number near '1.5'

If I run it as
  LC_ALL=C luakit
it starts without errors.

luakit-2012.09.13_p1

**Comment by aidanholm** [comment]
luakit has set the LC_NUMERIC locale to C since ed84b9192, so that should fix this.
