### ISSUE TITLE
Some elements does not render correctly

### ISSUE THREAD

**Issue by daGrevis** [luakit/luakit#145]
First I wanted to say HUGE THANKS to developers of this awesome browser. This is excatcly what I was looking for — lightweight browser for programmers/hackers which is highly modable using scripting langauge not some low-level langauge (so Lua, not C). Keep doing great job, mates! :)

And here comes the sad part — browser is incorrectly rendering some elements. It seems that most problems it have w/ images, CSS-a-lot and canvas/SVG elements. Also, some JavaScript effects aren't working properly. I just wanted to point that out, so you won't miss that.  :+1: 

Here's the same page on Luakit and Chromium (both are using WebKit engines, I suppose):

![Preview](http://i49.tinypic.com/2dh9zmb.png)

P.S. This is fucking awesome!!

**Comment by aidanholm** [comment]
Cannot reproduce. Note that luakit has recently been updated to use WebKIt 2, so almost all old rendering issues have been fixed. Feel free to reopen if this issue reoccurs.
