### ISSUE TITLE
follow.lua error on phoronix.com

### ISSUE THREAD

**Issue by diegoviola** [luakit/luakit#157]
Screenshot of the error: http://ompldr.org/vZ2ViOQ

archlinux x86_64

```
[diego@localhost ~]$ luakit --version
luakit 0d5f4ab
[diego@localhost ~]$ 
```

Steps to reproduce: go to phoronix.com, type `f`, then the error happens.

**Comment by aidanholm** [comment]
Cannot reproduce. Note that luakit has recently been updated to use WebKIt 2, so almost all old crashes have been fixed. Feel free to reopen if this issue reoccurs.
