### ISSUE TITLE
Per-view proxy

### ISSUE THREAD

**Issue by gordon-quad** [luakit/luakit#161]
This will be useful to make proxy setting local to view, like instead of using capi.soup.proxy_uri to set proxy, use v.proxy_uri.
Without this feature it is barely impossible to implement foxyproxy-like features to use different proxies based on destination's URL.

**Comment by o-jasper** [comment]
I would like to use this to for instance get stuff via tor, but not when i am identifying myself. I.e. "perfect case", as soon i want to do something identifying me, it doesnt use tor. More likely just have a set of websites not-via-tor.

**Comment by aidanholm** [comment]
This isn't possible to implement in a reasonable fashion, unfortunately. WebKit proxy settings are tied to the WebKitWebContext, and using one per tab has prohibitive memory and performance implications.

This does not prevent implementing domain-specific proxy routing; it's possible to use a local proxy that forwards to another proxy based on the domain.
