### ISSUE TITLE
Sometimes i-modes doesn't start

### ISSUE THREAD

**Issue by daGrevis** [luakit/luakit#162]
So here is my problem: sometimes i-mode (insert mode) doesn't start. Lets say I "follow" to an input element, but Luakit doesn't go in i-mode automatically. Or, for example, page focus on input element on load, but i-mode doesn't get started. It's frustrating because you can accidentaly, by typing text in input element, type command that, lets say, closes tab. I'm looking for way to fix going to i-mode _or_ disable automatic going to i-mode.

**Comment by aidanholm** [comment]
Can't reproduce with latest luakit. Seems to be fixed.
