### ISSUE TITLE
Mailing list unavailable

### ISSUE THREAD

**Issue by mpfusion** [luakit/luakit#165]
I'd like to get in touch with some folk using luakit. However, the mailing list subscribe message bounces with

> luakit-dev-request@lists.luakit.org: Host or domain name not
> found. Name service error for name=lists.luakit.org type=A:
> Host not found

The link to the web UI in the README yields a similar result:

> Cannot resolve hostname (lists.luakit.org)

Has the mailing list moved to a different server?

**Comment by aidanholm** [comment]
@mason-larobina I noticed this too, seems it's dead? If so, no need to bring it back; I think IRC will be enough for now.

**Comment by ghost** [comment]
Can you extract the emails from the list and write an announcement that the list is closed, but IRC is available and luakit is alive! This might bring some old users/contributers back.

**Comment by aidanholm** [comment]
I don't think there's an active public archive, so there's no way to get the old emails, and there's no way to send to the list if the server is down.

**Comment by c0dev0id** [comment]
I don't think there is anything that can be done here. I'm closing this issue.
