### ISSUE TITLE
https ssl trust sometimes doesn't work

### ISSUE THREAD

**Issue by dennisnez** [luakit/luakit#166]
Is anyone else having flaky https trust/notrust verification issues? With some sites, like https://www.google.ca it seems to work fine .. always saying "trust". With other sites, like "https://worldpay.com" it will alternate between trust and notrust, usually (not always!?) ending up with "notrust". With "https://secure.worldpay.com" it always seems to say "notrust" :S.

Testing with my "openssl" client, the certificates do work.

The fact that it does show the green "trust" _while loading_ some sites suggests that it is working, but something overrides it. Any ideas?

**Comment by aidanholm** [comment]
If it's alternating during load, that's because the certificate can only be checked after it's loaded, during the page load, at which point the widget may be updated. I can't reproduce any site-specific issues.
