### ISSUE TITLE
Segmentation fault on Ubuntu 12.10 x86_64

### ISSUE THREAD

**Issue by ghost** [luakit/luakit#168]
I compiled luakit on ubuntu 12.10 from source (all libraries are the -dev versions from the ubuntu repo). Every once in a while, luakit stops working. I ran it with gdb and here is some of the output:

Program received signal SIGSEGV, Segmentation fault. 
0x00007ffff66901e0 in webkit_web_back_forward_list_new_with_web_view () from /usr/lib/libwebkitgtk-1.0.so.0
and before that a couple of errors: 
*\* (luakit:19625): CRITICAL *_: WebKitWebBackForwardList_ webkit_web_back_forward_list_new_with_web_view(WebKitWebView_): assertion `WEBKIT_IS_WEB_VIEW(webView)' failed
 *_ (luakit:19625): CRITICAL *_: gint webkit_web_back_forward_list_get_back_length(WebKitWebBackForwardList_): assertion `WEBKIT_IS_WEB_BACK_FORWARD_LIST(webBackForwardList)' failed

Is this related to the ubuntu versions of the libraries or an error in luakit?

**Comment by aidanholm** [comment]
Cannot reproduce. Note that luakit has recently been updated to use WebKIt 2, so almost all old crashes have been fixed. Feel free to reopen if this issue reoccurs.
