### ISSUE TITLE
Add support for SOCKS proxies

### ISSUE THREAD

**Issue by cf8** [luakit/luakit#169]
Yes, i know there was this kind of request (#69) and it was closed.

But according to this news http://ftp.acc.umu.se/pub/gnome/sources/libsoup/2.39/libsoup-2.39.1.news libsoup can handle SOCKS proxies since version 2.39.1 and current version is 2.40.2.

**Comment by AlmightyDeman** [comment]
Any news about socks5 support? This issue has been opened two years ago. Socks support would be great.
![photo_2015-04-26_03-15-59](https://cloud.githubusercontent.com/assets/2962598/7335464/b91f6834-ebc2-11e4-847c-0e3cb7ed7e3e.jpg)

**Comment by aidanholm** [comment]
SOCKS support is working fine with updated WebKit2-based luakit; please reopen if there are more issues with it!
