### ISSUE TITLE
Awful image quality in image scaling

### ISSUE THREAD

**Issue by leleletgo** [luakit/luakit#173]
Just like how firefox had terrible image scaling, so does luakit
https://bugzilla.mozilla.org/show_bug.cgi?id=486918
https://bug486918.bugzilla.mozilla.org/attachment.cgi?id=428179

This can be fixed by switching to lanczos (which chrome and firefox use) from linear interpolation which is luakit seems to use

**Comment by aidanholm** [comment]
Cannot reproduce. Note that luakit has recently been updated to use WebKIt 2, so this has probably been fixed. Feel free to reopen if this issue reoccurs.
