### ISSUE TITLE
Text being cut off

### ISSUE THREAD

**Issue by toddbranch** [luakit/luakit#175]
On the github issue page, some text is being cut off.
Instead of "Leave a comment", I only see "Le".
Instaed of "Submit new issue", I only see "Su".
When typing the issue, I can only see the first two chars - where "Le" was initially.
I checked the source - the text is present.

**Comment by aidanholm** [comment]
Probably a WebKit 1 issue. Luakit uses WebKit 2 now, so hopefully this is gone for good.
