### ISSUE TITLE
Make luakit use a Chrome-like useragent

### ISSUE THREAD

**Issue by laino** [luakit/luakit#178]
Using the default useragent, some sites (like google) incorrectly detect the browser's capabilities.

An example is Google imagesearch. The text input field does not look 'modern' and fails to override the GTK style (when using a dark GTK style most input boxes are also dark. Can be seen when clicking 'Advanced'). 
Google reverse imagesearch doesn't work at all (The button is missing, and directly opening it by url redirects to Google's hp).

This can be fixed by adding "Chrome/_version_" to the useragent string. 

The current useragent looks like this:
"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.6 (KHTML, like Gecko) luakit/2012.09.13 Safari/537.6"

Fixing the problem by adding Chrome somewhere in the string:
"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.6 (KHTML, like Gecko) Chrome/24.0.1312.57 luakit/2012.09.13 Safari/537.6"

**Comment by c0dev0id** [comment]
I'm closing this issue, because the default user agent is set from webkit. A custom user agent can be set on the `:settings` page or in the configuration file with `settings.webview.user_agent = "Custom User Agent String"`
