### ISSUE TITLE
Fix clicking on editable content

### ISSUE THREAD

**Issue by laino** [luakit/luakit#185]
With the current default webview.lua clicking on on a form field but releasing the mouse outside would throw the user out of insert mode directly.
This can be extremely annoying on websites where the input bar makes the form field go up. It gets impossible to click the field. 

Here's a commit that would fix the issue: 
https://github.com/binlain/luakit/commit/f909f4498d247b2ff4bb49e9d6cfbc8c9d068fb0

**Comment by aidanholm** [comment]
I fixed this a while back
