### ISSUE TITLE
[patch] allow setting luakit as default browser for GNOME

### ISSUE THREAD

**Issue by ghost** [luakit/luakit#186]
Hi, I recently started using luakit as my main browser, thanks for that. One of the things I found missing was a way to be able to set luakit as the default browser in GNOME settings dialogs.

Solved by adding:
`x-scheme-handler/http;x-scheme-handler/https;` to the `Mimetype` line in `/usr/share/applications/luakit.desktop`.

Please consider adding this quick fix, thanks.

**Comment by aidanholm** [comment]
I've added this at 73a093d3
