### ISSUE TITLE
Bookmarks error when trying to add unicode tag 

### ISSUE THREAD

**Issue by hdhog** [luakit/luakit#187]
When you try to add a tag in unicode getting the error. / usr / share / luakit / lib / bookmarks.lua: 91

**Comment by aidanholm** [comment]
Problem is `local remains = string.gsub(tags, "%w[%w-]*", ...)`, line 92. Should split on `,?%s+` instead.

**Comment by c0dev0id** [comment]
I've retested this and it works. The code has meanwhile changed to  `string.gsub(tags, "%S+", ...`

![bmark](https://user-images.githubusercontent.com/44190565/92312775-64ae6280-efc4-11ea-9a45-d9bcd03440dd.png)
