### ISSUE TITLE
Update jquery

### ISSUE THREAD

**Issue by nmeum** [luakit/luakit#198]
You are still using jquery v1.7.2 (the file is `lib/jquery.min.js`) it is only used for the help, history, bookmark and download page so it shouldn't be too hard to upgrade to jquery v1.9.X or even jquery v2.X, no?

**Comment by aidanholm** [comment]
Hi, and thanks for reporting this!

 Currently, there's no urgent need to update jQuery, as there aren't any (known) bugs or performance issues affecting luakit's chrome pages. Additionally, I'm planning to refactor the chrome pages you mentioned and remove jQuery entirely in the process of doing so. This is because it's the only JS file in `lib/`, it's quite large, and it can be removed without any loss of functionality.

I'll close this now; feel free to reopen if you have questions or anything like that.

**Comment by hippi777** [comment]
hi! :)

i couldn't test all of it out, the toggle works, but without animation, but i have no associated text editor, but can be a good start, i've seen there are other 3 files using jq, but currently i had time only for this much, but i think the rest will be this much easier if they are similar...

as it's not 100% the same as the original in function, test it twice :)

lib/introspector_chrome.lua
```javascript
window.onload=function () {
    // toggle source display
    let bindClass = document.getElementsByClassName("bind");
    for (let b = 0; b < bindClass.length; b++) {
        bindClass[b].onclick = function (event) {
            let func_sourceStyle = bindClass[b].getElementsByClassName("func-source")[0].style;
            if (func_sourceStyle.display == "none") {
                func_sourceStyle.display = "block";
            } else {
                func_sourceStyle.display = "none";
            }
        }
    }

    // open a file
    let filenameClass = document.getElementsByClassName("filename");
    for (let f = 0; f < filenameClass.length; l++) {
        filenameClass[f].onclick = function (event) { //a <span> with "clickable" class would be much better instead of using <a> tags
            event.preventDefault(); //not needed with using <span>
            open_editor(event.target.innerText);
            return false; //not necessary at all?
        }
    }

    // open a file with a custom line
    let linedefinedClass = document.getElementsByClassName("linedefined");
    for (let l = 0; l < linedefinedClass.length; l++) {
        linedefinedClass[l].onclick = function (event) {
            event.preventDefault();
            let t = event.target;
            open_editor(t.getAttribute("filename"), t.getAttribute("line")); //should be data-filename - search&replace can help
            return false;
        }
    }
}
```

i even adopted the style (far from my own...), but i had no much idea what kinda naming convention would be good :D

**Comment by hippi777** [comment]
@aidanholm did you check this out? if you like it then i can continue when i'll have time for it, these are simple and i don't have to know anything about the luakit internals to mess with these (and i hate jq (such overhead...) so i like to replace it with plain js in general :D )

**Comment by aidanholm** [comment]
Not yet; will take a look tomorrow

**Comment by aidanholm** [comment]
@szbnwer This looks mostly ok; I have a few comments but it would be easier to manage if you opened a PR

**Comment by hippi777** [comment]
done, i hope i did it right :D this is my 2nd pr, but if there is a better practice, plz let me know :D
