### ISSUE TITLE
Going backwards in history doesn't work on some pages

### ISSUE THREAD

**Issue by nmeum** [luakit/luakit#199]
For instance go to the [reddit frontpage](http://www.reddit.com/) and click on the subreddit of the first item. After the subreddit has been loaded it is impossible to go back to the frontpage unless you press `H` (very quick) multiple times.

Here is the output of luakit -v reddit.com: http://paste42.de/38c9b7eed77595dc81bf88bc6f68a2b7/5389/

Somewhere in there it shows the following error:

```
[    7.885812] E: luakit: luaH_dofunction:104: error while running function
stack traceback:
    [C]: in function 'format'
    /home/nmeum/.config/luakit/rc.lua:28: in function 'info'
    /home/nmeum/.config/luakit/webview.lua:173: in function </home/nmeum/.config/luakit/webview.lua:158>
error: /home/nmeum/.config/luakit/rc.lua:28: bad argument #4 to 'format' (string expected, got nil)
```

However, I don't think that the error is related.

**Comment by aidanholm** [comment]
Cannot reproduce. Note that luakit has recently been updated to use WebKIt 2, so almost all old crashes have been fixed. Feel free to reopen if this issue reoccurs.
