### ISSUE TITLE
Feature ideas

### ISSUE THREAD

**Issue by zoqaeski** [luakit/luakit#201]
With luakit [currently refusing to start](https://github.com/mason-larobina/luakit/issues/200) and no idea what could be causing it, I’ve been exploring some other browsers to see how they compare. Some of them have some really neat features which we could probably implement ourselves. So here’s a couple to get the ball rolling:
- ~~Hard-coding adblock into luakit. Maybe this will avoid some of the issues we’ve been having with adblock lately (e.g. https://github.com/mason-larobina/luakit/issues/125, https://github.com/mason-larobina/luakit/issues/195, https://github.com/mason-larobina/luakit/issues/182)~~
- A settings chrome page—[dwb](http://portix.bitbucket.org/dwb) has [this](http://portix.bitbucket.org/dwb/resources/prefs.jpg) and it’s pretty neat. I don’t know how realistic this is given luakit’s configuration is done in lua.
- https://github.com/mason-larobina/luakit/issues/197 is also relevant here.
- Silently dropping key bindings that aren’t defined. This avoids long strings of nonsense until the user realises they’ve made a typo.
- https://github.com/mason-larobina/luakit/issues/192

I was thinking we could do the work on the luakit-crowd fork and keep it synchronised with this upstream. What do people think?

**Comment by aidanholm** [comment]
Re long strings of nonsense; that's been fixed for a while now: you simply can't type anything that isn't the prefix of a command now.

Re detecting binding collision: good idea.

Re settings chrome page: there's `adblock_chrome` and modes that allow you to edit user scripts and styles without manually editing files, so there's some precedent. Not sure if it's a good idea to unify them all though.

**Comment by aidanholm** [comment]
Binding collision detection will be included in the binding overhaul (#384), which will land in `develop` within the next few days, and be included in the next release.
I think that's all the features requested/mentioned in this issue, so I'll go ahead and close this now.
