### ISSUE TITLE
Selection boxes at the wrong places

### ISSUE THREAD

**Issue by nmeum** [luakit/luakit#203]
Sometimes the selection boxes are not where you would expect them...for instance this is the case on xkcd.com, but this is not the only site where I experienced this problem. Here is a screenshot:

![27-04-2013_21-50-31](https://f.cloud.github.com/assets/2326560/434820/ddd4feb0-af73-11e2-873b-7a581ade1121.png)

**Comment by aidanholm** [comment]
Caused by xkcd `<body>` element having `display: absolute`.

**Comment by c0dev0id** [comment]
Either the issue is fixed meanwhile, of xkcd has fixed their page. I don't see a point in having this issue around any longer... so I close it. But as always - feel free to reopen.
