### ISSUE TITLE
In some Flash videos, red and blue channels are inverted.

### ISSUE THREAD

**Issue by dllu-zz** [luakit/luakit#211]
## Problem description:

In certain Adobe Flash videos, the red and blue channels are inverted. 

Chromium on right, luakit on left:
![2013-06-23-115204_2558x1439_scrot](http://i.imgur.com/i97fMTAl.jpg)

luakit on top, Firefox on bottom:
![2013-06-23-120743_1275x1439_scrot](http://i.imgur.com/3h3KGBYl.png)

Anomalous behaviour only occurs in Flash videos, but not in other Flash applets or media.
## Expected behaviour:

Expected red and blue channels to not be inverted.
## Steps to reproduce:

Open any Youtube video that is only available in Adobe Flash and not in HTML5, e.g. [StarCrafts Season 2 Episode 7 Hellraiser](https://www.youtube.com/watch?v=C1NCfKz1K7I) or [The Future of the Internal Combustion Engine](https://www.youtube.com/watch?v=Bch5B23_pu0). 
## Technical details:

Flash player 11.2.202.291. Screenshot: [helpx.adobe.com/flash-player/kb/find-version-flash-player.html](http://i.imgur.com/bBy0bJE.png)

```
luakit --version
luakit 0d5f4ab
```

Kernel: Linux 3.9.7-1-ARCH

Graphics card: NVIDIA Geforce GTX 560 TI

Graphics driver: `NVRM version: NVIDIA UNIX x86_64 Kernel Module  319.23`

Primary Display: Dell U2711, 2560 x 1440

Secondary Display: Dell S2309W

**Comment by c0dev0id** [comment]
Flash is not supported anymore since NPAPI support is gone (webkit2gtk 2.22).
