### ISSUE TITLE
Luakit freezes on some pages

### ISSUE THREAD

**Issue by mpfusion** [luakit/luakit#213]
### Steps to reproduce
- Open http://intel.com (other pages are affected as well)
### Result

Luakit starts to load the page, then freezes. The user interface becomes entirely grey and cannot be interacted with in any way.
### Version

https://github.com/luakit-crowd/luakit/commit/377d765d19488838b4198e9f5dcb7122cde2d1cc

Default config, no customizations.

**Comment by aidanholm** [comment]
Cannot reproduce. Note that luakit has recently been updated to use WebKIt 2, so almost all old crashes have been fixed. Feel free to reopen if this issue reoccurs.
