### ISSUE TITLE
hint labels and nth-child

### ISSUE THREAD

**Issue by sagotsky** [luakit/luakit#214]
I was having trouble distinguishing hint labels that appeared really close together (thanks, Reddit).  I figured I could zebra stripe them.  But it looks like all hint_labels are even. 

![screenshot](http://imgur.com/ZrEfUGv.png)

When I swap that even to an odd, all the labels go back to dark blue.  

I'm using luakit 0ba2f95 from Ubuntu, which apt tells me is version 2012.09.13-r1-1

**Comment by aidanholm** [comment]
Currently the overlay elements go: hint, label, hint, label, ... within a wrapper div. So all hints are odd, and all labels are even. Try using `.hint_label:nth-child(4n+2)`
