### ISSUE TITLE
Very ugly fonts for a few websites

### ISSUE THREAD

**Issue by tgirod** [luakit/luakit#221]
With a fresh luakit install on archlinux, a few websites (including github) are displayed like this ![something's wrong](https://f.cloud.github.com/assets/130746/1413119/2ac43232-3e16-11e3-962c-e4ee1591fa93.png)

The problem could come from my font configuration, but the same page is displayed properly by firefox.

**Comment by Nixpower** [comment]
Installing freesans did the trick for me, too.
