### ISSUE TITLE
Mailing List

### ISSUE THREAD

**Issue by nathanharper** [luakit/luakit#227]
Hey! I think Luakit is an awesome project, and I was hoping to help out in its development, even if only with the Wiki and stuff. But... it seems like the dev mailing list link in the README is dead. Is it still active?

**Comment by ikcalB** [comment]
Hi devs!

would like to join the mailing list too.

long time vim customizer - LOVING luakit.
I'd like to improve this great project & need some place to ask for advice, how to implement certain features, so a pull request succeeds without editing multiple times. (idk if this issue tracker is an appropriate place for that?)

Furthermore I'd like to stay up-to-date with development c(-:

best regards, Florian

**Comment by McSinyx** [comment]
@ikcalB IMHO all the conversations are on Github issues now, you can just simply follow Luakit on Github (then maybe enable email notification) to catch up. Also I remember @aidanholm telling me that IRC channel is also active.

**Comment by aidanholm** [comment]
Hi Florian! Glad to hear that :)

There is no mailing list at the moment. However, as @McSinyx said, the IRC channel is indeed reasonably active; it's `#luakit` on the OFTC network. It's probably the best place to ask questions related to development, but opening issues here on github is also ok!
