### ISSUE TITLE
Segfault using "follow" on LastFM

### ISSUE THREAD

**Issue by nathanharper** [luakit/luakit#229]
When I try to use the follow (f) command on the www.lastfm.com homepage, luakit crashes consistently.  The output isn't always the same, but it's usually something like

`luakit: malloc.c:3637: _int_malloc: Assertion`(unsigned long)(size) >= (unsigned long)(nb)' failed.`

or

`Job 1, “luakit  www.lastfm.com” terminated by signal SIGSEGV (Address boundary error)`

My uname output is:

`3.11.0-15-generic #23-Ubuntu  x86_64 GNU/Linux`

Only non-standard plugin that I can think of is Pipelight for using SilverLight plugins. It's only happening on my Ubuntu 13.10 box; I have the same Pipelight setup on my box running Archbang and it works fine. Yeah I know, this is horrifically specific :P

**Comment by aidanholm** [comment]
Cannot reproduce. Note that luakit has recently been updated to use WebKIt 2, so almost all old crashes have been fixed. Feel free to reopen if this issue reoccurs.
