### ISSUE TITLE
No html5 audio playback/requesting audio file hangs ("pending")

### ISSUE THREAD

**Issue by maca** [luakit/luakit#230]
I am doing a web app for running from luakit in a raspberry pi, I need to play a sound when certain events ocur. 
Neither by using the audio tag or by instantiating an Audio object and playing it from javascript yields any sound. I've also noticed that the audio file request hangs at "pending..." by looking at the inspector network seccion. In chrome the same request response comes with a 206 status.

**Comment by aidanholm** [comment]
Closing since this is an old issue, and probably WebKit-1-related; feel free to reopen if you still have problems.
