### ISSUE TITLE
Can't attach image in github issues

### ISSUE THREAD

**Issue by zakharvoit** [luakit/luakit#238]
I am trying to attach file to issue, I select file in file dialog, but then nothing happens. And while using some other elements like "Add ssh key" in github preferences nothing happens too.

**Comment by aidanholm** [comment]
![package-x-generic](https://user-images.githubusercontent.com/10691965/27164293-dbf58370-51be-11e7-92a0-4da4fff6ca0c.png) Seems to work fine now.

Probably just one of hundreds of thrilling WebKit 1 bugs.
