### ISSUE TITLE
luakit is crashing

### ISSUE THREAD

**Issue by TANUJ2014** [luakit/luakit#245]
hi ! i am using the stable version of luakit on linux mint 16(petra).Whenever i try to open facebook luakit just crashes, and its only on facebook and is exactly at moment i press login. DO something

**Comment by aidanholm** [comment]
Cannot reproduce. Note that luakit has recently been updated to use WebKIt 2, so almost all old crashes have been fixed. Feel free to reopen if this issue reoccurs.
