### ISSUE TITLE
formfiller.lua - improvements?

### ISSUE THREAD

**Issue by ghost** [luakit/luakit#246]
Hey,
the formfiller works quite well (using za/ze & zl/zL) for most sites, okay sometimes the automatically generated form has to be slightly adjusted, but thats okay...

But auto-login / auto-submit seems only to work if the button has a "tabindex".
i.e. on https://aur.archlinux.org/login/ the login-button is >input type="submit" class="button" value="Login"< 
auto-login doesnt work with submit = -1, n (tried several other indexes).. or true.
So far I can only login via setting submit to false and clicking the button manually or adding "focus = true" to one of the input sections and manually pressing "return".

I'm not skilled in lua or js, but the formfiller of dwb works on this page...probably it uses another approach to determine where the button is...is there any way to improve the formfiller.lua to work with non-tabindexed buttons?

**Comment by aidanholm** [comment]
`formfiller.lua` has been reimplemented, and that site now works. If there are other sites causing problems, feel free to reopen this issue.
