### ISSUE TITLE
TypeError: undefined is not a constructor (evaluating 'new Audio()')

### ISSUE THREAD

**Issue by gamecubate** [luakit/luakit#253]
I'm trying to get the impactJS (http://impactjs.com) engine to work on luakit running on a raspberry pi. My first test passed (text image font display). The second one, for audio, does not:
TypeError: undefined is not a constructor (evaluating 'new Audio()')

Test page URL
http://gamecubate.com/labs/impact-audio-test/

I'll also ask on the rpi forums as I'm not sure that this is a luakit issue.

**Comment by aidanholm** [comment]
Running `new Audio()` in the web developer console works. Closing since this issue is three years old; reopen if you still have issues.
