### ISSUE TITLE
Luakit crashes when following links on Slashdot

### ISSUE THREAD

**Issue by freakanth** [luakit/luakit#254]
Hi,

First of all, thanks for the excellent browser! I'm a big fan, and prefer it most of the time over Chrome or Firefox especially on my little netbook.

I do occasionally have problems with following links on some websites, when Luakit either crashes or freezes. I happened to notice this morning that this was happening consistently on Slashdot when I press the "f" key to follow links. Below is the terminal output, if it helps:

No bp log location saved, using default.
[000:000] Cpu: 6.58.9, x4, 3201Mhz, 7869MB
[000:000] Computer model: Not available
[000:000] Browser XEmbed support present: 1
[000:000] Browser toolkit is Gtk2.
[000:000] Using Gtk2 toolkit
No bp log location saved, using default.
[000:000] Cpu: 6.58.9, x4, 3201Mhz, 7869MB
[000:000] Computer model: Not available
[000:012] Warning(optionsfile.cc:47): Load: Could not open file, err=2
[000:012] No bp log location saved, using default.
[000:013] Cpu: 6.58.9, x4, 3201Mhz, 7869MB
[000:013] Computer model: Not available
[000:013] Browser XEmbed support present: 1
[000:013] Browser toolkit is Gtk2.
[000:013] Using Gtk2 toolkit
[000:012] Warning(optionsfile.cc:47): Load: Could not open file, err=2
[000:012] No bp log location saved, using default.
[000:012] Cpu: 6.58.9, x4, 3201Mhz, 7869MB
[000:012] Computer model: Not available
*\* Message: console message: http://beta.slashdot.org/ @536: /4140/ostg.slashdot/SD_homepage_728x90_A: define slot (div-gpt-ad-728x90_a)

*\* Message: console message: http://beta.slashdot.org/ @536: /4140/ostg.slashdot/SD_homepage_728x90_B: define slot (div-gpt-ad-728x90_b)

*\* Message: console message: http://beta.slashdot.org/ @536: /4140/ostg.slashdot/SD_homepage_HubIcon_200x90_A: define slot (div-gpt-ad-hubicon_200x90_a)

*\* Message: console message: http://beta.slashdot.org/ @536: /4140/ostg.slashdot/SD_homepage_PowerSwitch_980x66_A: define slot (div-gpt-ad-powerswitch_980x66_a)

*\* Message: console message: http://beta.slashdot.org/ @536: /4140/ostg.slashdot/SD_homepage_PollPeel: define slot (div-gpt-ad-pollpeel)

*\* Message: console message: http://beta.slashdot.org/ @536: /4140/ostg.slashdot/SD_VideoWidget_300x250: define slot (div-gpt-ad-videowidget_300x250)

*\* Message: console message: http://beta.slashdot.org/ @536: /4140/ostg.slashdot/SD_homepage_300x250_A: define slot (div-gpt-ad-300x250_a)

*\* Message: console message: http://beta.slashdot.org/ @536: /4140/ostg.slashdot/SD_homepage_300x250_B: define slot (div-gpt-ad-300x250_b)

*\* Message: console message: http://beta.slashdot.org/ @536: /4140/ostg.slashdot/SD_homepage_300x250_C: define slot (div-gpt-ad-300x250_c)

*\* Message: console message: http://beta.slashdot.org/ @536: /4140/ostg.slashdot/SD_homepage_300x250_D: define slot (div-gpt-ad-300x250_d)

Segmentation fault (core dumped)

Please let me know if I can provide any further information on the problem. Thanks!

**Comment by aidanholm** [comment]
The follow mode has been entirely reimplemented, so I'm closing this issue. Please reopen it if you still experience this issue.
