### ISSUE TITLE
FreeBSD and luakit version

### ISSUE THREAD

**Issue by r004** [luakit/luakit#255]
Hello;
The version of luakit in freebsd is 2012.09.13-r1. Is it the most recent version or if I build luakit myself I'll get a better and more recent version of luakit?

**Comment by aidanholm** [comment]
I'm planning an upcoming release: #324

**Comment by xkpd3** [comment]
I'm working on a FreeBSD port. Once a stable download link exists, I will finalize it.
https://github.com/xkpd3/luakit-port

**Comment by aidanholm** [comment]
The release is out! Tag 2017.07.26
