### ISSUE TITLE
follow hints on reddit doesn't do anything

### ISSUE THREAD

**Issue by Ram-Z** [luakit/luakit#258]
Using `f` to follow hints on reddit doesn't open any of the user posted links, all others seem to work. `F`, `;o`, `;t`, `;b`, `;w` and clicking work as expected.

I have reddits "clicking options" set to "open links in new window", if this is not set then `f` will open the link in the current window as expected.

`f` is the only one that uses the `click` evaluator, so I tried changing [lib/follow.lua#L717](https://github.com/mason-larobina/luakit/blob/develop/lib/follow.lua#L717) a bit, setting the last 0 in `initMouseEvent` to 1 (which emulates a middle click instead of left click) will open hints in the current window, even when "open links in new window" is set.

Note that this works in dwb which also emulates clicks when following hints.

Tested with `XDG_CONFIG_HOME=/etc/xdg luakit` and latest HEAD from luakit-crowd.

**Comment by o-jasper** [comment]
Seems to work fine for me now.

**Comment by aidanholm** [comment]
The follow mode has been entirely reimplemented, and works on reddit currently, so I'm closing this issue. Please reopen it if you still experience this issue.
