### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by classic77** [luakit/luakit#259]
Because of the outdated packages in debian I want to build luakit. After installing the dependencies the build process failes with:

./build-utils/gentokens.lua common/tokenize.list common/tokenize.h
lua: ./build-utils/gentokens.lua:78: unexpected symbol near `#'
Makefile:32: recipe for target 'common/tokenize.h' failed
make: **\* [common/tokenize.h] Error 1

**Comment by aidanholm** [comment]
Luakit has changed significantly since 2014, so I'm closing this issue as it is likely no longer relevant; feel free to reopen or open another issue if you still have build problems.
