### ISSUE TITLE
make a nice API reference

### ISSUE THREAD

**Issue by o-jasper** [luakit/luakit#266]
This piece of documentation would be helpful. Perhaps add a command i.e. `:lua-api` and a link to it from `luakit://help/`

Perhaps a script could cook something up, and we can work from there?

**Comment by Bew78LesellB** [comment]
Also interested about a link to the luakit api, but first, where can we found it?

**Comment by o-jasper** [comment]
It has a doxygen, the wiki seems pretty okey, but a good comprehensive list of functions from lua is missing.

**Comment by aidanholm** [comment]
Luakit now has automatically generated documentation at luakit://help/doc/index.html
It still needs some work however.

**Comment by aidanholm** [comment]
There's now also documentation online: https://luakit.github.io/luakit/docs/, so I'll go ahead and close this.
