### ISSUE TITLE
OS X here - install instructions

### ISSUE THREAD

**Issue by xtraa** [luakit/luakit#270]
Hey :)

I'd like to install luakit (says OS X support since 2012), so I just r(ead)tfm and obviously a 'sudo make xyz' does not workie in a darwin unix terminal. How do I make it compute in my environment? :) Thanks in advance

xtraa

**Comment by o-jasper** [comment]
Not familiar with OS X... So does `make` work there? If so, does `./luakit` work? Can do the OS X equivalent of a [userlevel install](https://github.com/mason-larobina/luakit/wiki/Userlevel-install-\(Linux\)) then.

**Comment by o-jasper** [comment]
I do not entirely expect my answer to be useful.. Basically asking if `make` does not work either. Looks like the makefile is fairly simple, so if `gcc` works, can even do it manually.

**Comment by xtraa** [comment]
Thank you for your support, Jasper :) I will try it and see how far I come. At the moment, I think I first have to install the lua framework for OS X.

**Comment by residentsummer** [comment]
@xtraa @o-jasper lua (or even luajit) installation is not a problem (at least with Homebrew). Not so good with webkit and it's Javascript implementation, because brew doesn't have formulas for them... MacPorts, on the other hand, has a port for webkit.

**Comment by mason-larobina** [comment]
I don't have any OSX instructions to offer. If anybody does get it working they should update the wiki / send pull requests.
