### ISSUE TITLE
http://doc.luakit.org/ is not available

### ISSUE THREAD

**Issue by Bew78LesellB** [luakit/luakit#271]
Hello !

I am having fun configuring my Awesome WindowManager (in Lua), and I just discovered luakit... Wooaaa cool !! Another big thing to configure !! :)

on http://www.linuxjournal.com/content/luakit-extensible-micro-browser I've seen a picture of a luakit documentation, data structure, etc...

but the website seems to be out of service...

where can we get the documentation (other than searching in the source code), or when does the doc.luakit.org website will be up ?

Thank's !
bew78

**Comment by Plaque-fcc** [comment]
Hello, bew78!

  I am pretty sure you want to visit luakit.org and look at Wiki pages
here: https://github.com/mason-larobina/luakit/wiki

**Comment by Bew78LesellB** [comment]
No thanks, I already seeb the wiki
On the link I gave before, there is this image:

http://www.linuxjournal.com/files/linuxjournal.com/ufiles/imagecache/large-550px-centered/u1002061/11128f3.png

We can see on the status bar that it's doc.luakit.com ! 

Where is it now?

**Comment by Plaque-fcc** [comment]
Oh, I've never been to there I think. I guess Mason stopped using
luakit.com, intentionally or not, so this image must be seriously
outdated. I think this can't be helped now.

**Comment by o-jasper** [comment]
`Make doc` makes a bunch of doxygen documentation, using it i find that exact page in `doc/html/structwebview__data__t.html`

I *hate* the layout of doxygen, almost like it is trying to maximize the time before you get to see the piece of documentation you want; giant vertical bar ontop, diagram is ontop &rarr; need to scroll past it, giant borders around shit.. At best moderately useful information like where it is defined, and where it is used is shown *as prominently* as the info you want to look at.

And *cant even find* the functions! Looks completely useless to me.

**Comment by mason-larobina** [comment]
As I mentioned in #276 I won't be bringing back doc.luakit.org, the same contents can be seen if you run `make doc` in the source directory.
