### ISSUE TITLE
Modify the behavior of "Follow link" 

### ISSUE THREAD

**Issue by Bew78LesellB** [luakit/luakit#272]
Hello! 
I don't know where to ask for help, if it's not there, please tell me where! 

I want to customize the behavior of the "Follow link", on a webpage, we type f, then the links numbers appear, and we can type the link (with regex).. 

I didn't find the F/f keybind in bind.lua where is it?? 

I want to disable the case sensitiveness of the follow link search, and maybe change the links numbers and style... 

How can I do that, or where can I found information of how to do it? 

Thanks! 
Bew78

**Comment by o-jasper** [comment]
It is in `lib/follow.lua`#L771

Looks like follow might need some other easier customizability too, [like being able to change style(aspects) with `globals.follow.`](http://www.reddit.com/r/luakit/comments/2vwen6/increase_follow_hint_size/)

**Comment by Bew78LesellB** [comment]
Oh yes thanks, I finally found it too, but can I move the files in /usr/share/luakit/lib/* in some dir like ~/.config/luakit/lib  ?

**Comment by Plaque-fcc** [comment]
Yes, it's gonna work in the same way and override globals.

**Comment by mason-larobina** [comment]
As it happens someone has written this patch already, see:

https://github.com/luakit/luakit/pull/275/commits/303d9831848e23f0b92926346425399bcb80d1ea
