### ISSUE TITLE
Luakit crash - Segmentation fault when opening webkit inspector

### ISSUE THREAD

**Issue by kuspoes** [luakit/luakit#273]
Archlinux - Luakit 

Luakit crash (segmentation fault) when trying to using webkit inspector. 

```
** Message: console message: resource:///org/webkitgtk/inspector/UserInterface/Main.js @665: Localized string "Hide console (%s)" was not found.

*** NSPlugin Viewer  *** ERROR: rpc_end_sync called when not in sync!
[1]    17920 segmentation fault (core dumped)  luakit
```

**Comment by Plaque-fcc** [comment]
It looks like a webkit-gtk issue. Seriously.
Needs further investigation before it can be fixed either here or
reported to webkit-gtk project.

**Comment by Plaque-fcc** [comment]
Even with libjavascriptcoregtk-1.0 likely.

**Comment by kuspoes** [comment]
Midori (webkit-gtk)  is also experinced with this bug.

**Comment by Plaque-fcc** [comment]
Yeah. And PyGTK+WebKit apps are affected. That's why I am pretty sure
there's something wrong with webkitgtk/javascriptcoregtk libs. Most
probably with the latter.

**Comment by souzaonofre** [comment]
Hi guys, it's happen, because libwebkit and libgtkwebkit packets not include inspector add-on in your build system, and was not removed the call reference to him in right-click side-menu!!
Why "inspect" add-on is not included? I don't know!
But the libqtwebkit have this add-on included! Why? It's good question!

**Comment by Flashwalker** [comment]
I found this problem in all my webkit based applications (Ubuntu 14.04 i386). Apps crashes during opening webinspector.

I've just reinstall some packages to older versions
(It was installed 2.4.8 version):
``` bash
sudo apt-get download --allow-unauthenticated libwebkitgtk-1.0-0=2.4.0-1ubuntu2 gir1.2-webkit-1.0=2.4.0-1ubuntu2 gir1.2-javascriptcoregtk-1.0=2.4.0-1ubuntu2 libjavascriptcoregtk-1.0-dev=2.4.0-1ubuntu2 libjavascriptcoregtk-1.0-0=2.4.0-1ubuntu2

sudo dpkg -i libwebkitgtk-1.0-0_2.4.0-1ubuntu2_i386.deb gir1.2-webkit-1.0_2.4.0-1ubuntu2_i386.deb libjavascriptcoregtk-1.0-dev_2.4.0-1ubuntu2_i386.deb  gir1.2-javascriptcoregtk-1.0_2.4.0-1ubuntu2_i386.deb libjavascriptcoregtk-1.0-0_2.4.0-1ubuntu2_i386.deb
```

So now i can launch webinspector, but:

* apps still crashing sometime, but rarely (Any way, It works!... with grief in half)
* in terminal still throwing Message

`Message: console message: resource:///org/webkitgtk/inspector/UserInterface/Main.js @665: Localized string "Hide console (%s)" was not found.`

**Comment by aidanholm** [comment]
Cannot reproduce. Note that luakit has recently been updated to use WebKIt 2, so almost all old crashes have been fixed. Feel free to reopen if this issue reoccurs.
