### ISSUE TITLE
Are you alive?

### ISSUE THREAD

**Issue by gBopHuk** [luakit/luakit#274]
Is project developing? I see many issues is not solving. The last commit is date by 3 years ago.

**Comment by mason-larobina** [comment]
Yes, I've been busy with work.

The last commit to `develop` was in January 2015. I will try to make more time for luakit however it's fair to say this project is in maintenance mode (from my POV).

**Comment by o-jasper** [comment]
On the plus side, a lot can be developped with lua, and configuration can switch nearly all of it out.

Havent tried if you can load `.so` files.

**Comment by gBopHuk** [comment]
How are you guys?

**Comment by o-jasper** [comment]
The number of cats has increased. :smile_cat:

Also have taken a different angle, going via local-server and userscripts now. Should be more portable. [Here](https://github.com/o-jasper/page_html). Need to get rid of a dumb hardcoded file path an I should try get all required lua on a firejail instance so i can be surer it works for others..

One of the things i want is sharing bookmarks based on setting "level of publicness". [Build ontop this idea](http://ojasper.nl/blog/software/2015/11/12/libre_bus.html).

**Comment by mason-larobina** [comment]
You guys might be interested in #299
