### ISSUE TITLE
BadDrawable X Window System crash when zooming image & maximizing

### ISSUE THREAD

**Issue by krogank9** [luakit/luakit#281]
steps i follow to reproduce crash
1. have one tab open
2. open new tab of an image big enough to be zoomable
3. switch to tab with image
4. zoom into image
5. maximize -- CRASH

if i maximize then unmaximize before zooming into image, the crash does not happenr
crash only happens if tab is newly opened
if i resize the luakit window (any tab open) before zooming, the crash does not happen

tried it on a different computer (small netbook), could not replicate. possibly because the maximize window isn't a big enough difference between the size of the window before maximizing. glitch only seems to happen when window is maximized to a much larger size than original, and the image is forced to be very small

this crash happens on a raspberry pi 2, openbox window manager

console error message:
The program 'luakit' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadDrawable (invalid Pixmap or Window parameter)'.

Edit:

Also I have found another, similar problem. With large images when I do the above, sometimes instead of crashing on maximize, it will crash when I try to close the tab

**Comment by aidanholm** [comment]
Cannot reproduce. Note that luakit has recently been updated to use WebKIt 2, so almost all old crashes have been fixed. Feel free to reopen if this issue reoccurs.
