### ISSUE TITLE
Crash when getting some of the return values from js

### ISSUE THREAD

**Issue by o-jasper** [luakit/luakit#282]
`:js alert(document.images)` shows it to be a `HTMLCollection`, others like `document.anchors` are this kind object too, and seem to crash aswel. Perhaps something to do with how that kind of object is turned into a lua (meta)table?

```
add_cmds({ lousy.bind.cmd("crash", 
                      function(w)
                         local got = w.view:eval_js("document.images")
                         print("so, after print?")
                         print("table:", got)
                         print(w.view:eval_js("document.images.length"))
                         --for k,v in pairs(got) do print(k,v, v.src) end
                     end)
})
```

It doesnt seem to matter if it is printed or not.

**Comment by aidanholm** [comment]
I can't reproduce this crash with the current version of luakit.
