### ISSUE TITLE
HTML5 Playback?

### ISSUE THREAD

**Issue by zzggbb** [luakit/luakit#284]
Audio playback on http://soundcloud.com and video playback on http://vimeo.com do not work, is this because luakit does not support HTML5 playback? 

Is there any way to get these site to be functional, other than relying on external players like mpv/mplayer/vlc ?

**Comment by robomica** [comment]
I have also been having this issue. When run it a terminal it throws:
>(luakit:6693): GLib-GObject-WARNING **: invalid (NULL) pointer instance
>(luakit:6693): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion >'G_TYPE_CHECK_INSTANCE (instance)' failed

It does this when I hit play on Bandcamp. I've had a similar issue with video.

**Comment by zzggbb** [comment]
I believe that's just a normal GTK error, it shows up all the time regardless of what page is loaded.

On July 9, 2015 5:31:16 AM PDT, robomica <notifications@github.com> wrote:
>I have also been having this issue. When run it a terminal it throws:
>>(luakit:6693): GLib-GObject-WARNING **: invalid (NULL) pointer
>instance
>>(luakit:6693): GLib-GObject-CRITICAL **: g_signal_connect_data:
>assertion >'G_TYPE_CHECK_INSTANCE (instance)' failed
>
>It does this when I hit play on Bandcamp. I've had a similar issue with
>video.
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/mason-larobina/luakit/issues/284#issuecomment-119944838

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by adham90** [comment]
i have the same problem

**Comment by robomica** [comment]
Installing gst-plugins-base, gst-plugins-good, and gst-plugins-libav worked for me. They're listed as optional dependencies for webkitgtk2 on Arch Linux.

**Comment by zzggbb** [comment]
> gst-plugins-libav

gst-libav is the actual package name, for future readers ; )

**Comment by robomica** [comment]
whoops my mistake
