### ISSUE TITLE
Webkit2

### ISSUE THREAD

**Issue by o-jasper** [luakit/luakit#285]
[Looking at qutebrowser](https://github.com/The-Compiler/qutebrowser/blob/master/FAQ.asciidoc), apparently, webkit1 [is deprecated](https://lists.webkit.org/pipermail/webkit-gtk/2014-March/001821.html).

This might cause some some bugs, and we may need to do webkit2 eventually. For instance for me imgur sometimes(relatively rarely, luckily) crashed it.. Either update or my setup changing fixed that somehow though.

**Comment by spcmd** [comment]
Any update on this? Any chance to get a newer engine? Luakit is a very nice browser, it's so sad it's not getting developed anymore. 

qutebrowser is nice, but luakit is much more customizable (thanks to to the lua configs).

**Comment by o-jasper** [comment]
Did try it a bit, not that much luck. I am not sure how bad it is in the first place to be honest.

I kindah moved away and am using firefox with a local server & userscripts talking to it, though i might try make that available via luakit too. (most in the [page_html](https://github.com/o-jasper/page_html) it needs easier packaging.. all in the ring and [sha2](https://github.com/o-jasper/merkletree/tree/develop/lua/merkle))

**Comment by technomancy** [comment]
> I am not sure how bad it is in the first place to be honest.

It's bad.

> this old version of WebKit is affected by over 200 known vulnerabilities

according to https://blogs.gnome.org/mcatanzaro/2017/02/08/an-update-on-webkit-security-updates/

IMO the responsible thing to do would be to add a warning to the readme.

**Comment by aidanholm** [comment]
I've merged my fork into this repository; WebKit 2 is now the only supported version.
