### ISSUE TITLE
Some sites load slowly.

### ISSUE THREAD

**Issue by robomica** [luakit/luakit#286]
Google's image search is the worst. It's so slow I switch to another browser to use it.

**Comment by zzggbb** [comment]
Same problem happens on reddit

**Comment by o-jasper** [comment]
Hmm, I dont seem to have that issue, even with a bare luakit install.(my configs might change it) Latest luakit `master`.. archlinux fairly new versions of stuff.

Apparently webkit 1 is deprecated(#285), though it mostly seems to work fine, and doesn't necessarily mean that it is the engine.

**Comment by LRDPRDX** [comment]
luakit suddenly crushes (closes) on some sites. System: ubuntu 16.04.
