### ISSUE TITLE
Horizontal web inspector

### ISSUE THREAD

**Issue by stevenleeg** [luakit/luakit#294]
Hi there!

I'm just starting out with luakit and have been loving it so far, but one issue I've run into is that I can't seem to find a way to get the web inspector to open in a horizontal pane rather than the default vertical pane.

Is there some button/configuration that I'm missing and if not, is there any way this could be added to the roadmap? 

For users with not a lot of vertical real estate being able to open the web inspector in a horizontal pane (or even in a new window, that way the window manager can handle it rather than luakit) would be a big win.

Thanks in advance!

**Comment by mason-larobina** [comment]
Hi Steve,

This can be changed easily by modifying the `paned` widget constructor in window.lua.

Change `vpaned` to `hpaned` on this line:

https://github.com/goj/.config/blob/master/luakit/window.lua#L28
