### ISSUE TITLE
Execute luakit commands from linux shell script

### ISSUE THREAD

**Issue by mensurdurakovic** [luakit/luakit#295]
Hi!  I wrote unix shell script that is doing this:
1) show local .html file with animation inside luakit browser,
2) sleep 4 seconds,
3) show .mp4 video,
4) show local .html file with animation inside luakit browser,
5) sleep 4 seconds,
5) show .mp4 video with omx player,
6) and so on and so on
Transition from .html file to video is nice, but from video to .html file is not because after finishing with video luakit is showing previously opened .html file and then it opens new tab and shows me second .html file, and I would like that luakit opens next .html file inside current tab and not new one. Any way to do this ?
Also is there any way to execute luakit key bind browser commands (for example "d" to close current tab) from shell script ? 
Please help and thanks in advance

**Comment by o-jasper** [comment]
With `wmctrl -ia $WINDOW_ID` you can pull up the window.. But that is really fragile, and it is tricky to figure out which window ID is which...

Probably better to use the callback that runs after the program in (2nd argument of)`luakit.spawn` to bring it back up.. See there is a `View:focus()`, don't know if that will pull up the tab, or the tab-and-entire-window. (there might be a `Window:focus()` too?)

**Comment by o-jasper** [comment]
add_cmds({
        cmd("blurb", "stuff",
            function(w, query)
               luakit.spawn("wmctrl -ia 0x00600003",
                            function()
                               print("ran", w, w.view, w.focus, w.view.focus, w.raise)
                               w.view:focus() 
               end)
        end)
    })

Doesn't seem to work, afaik, the function should run after `wmctrl -ia 0x00600003` It does [for my mpv stuff](https://github.com/o-jasper/o-jasper-luakit-stuff/tree/master/use_video_program). `mpv` can be configured to go full-screen or any window geometry, and it does raise and close when done. It might be a way to go about this?

Can also try `View:eval_js("window.focus()")`

**Comment by o-jasper** [comment]
Maybe [`gtk_window_activate_focus`](https://developer.gnome.org/gtk3/stable/GtkWindow.html#gtk-window-activate-focus) needs to be used. (the description doesn't seem entirely clear in it) AFAICS, nothing calls that function in C. (probably unreachable with lua as-is)

**Comment by mensurdurakovic** [comment]
Thank you very much for your help, but I solved my problem. So basicly, I had to install "xdotool" to simulate keyboard input, binded "d" key in my "binds.lua" file so when I press "d" on keyboard I close current tab but browser remains open. Simplified shell script looks like this:

#!/bin/sh
setterm -cursor off

luakit myHtmlFile1.html &
sleep 4;
echo "FINISHED WITH 1ST .HTML FILE"
xdotool key "d"

omxplayer myVideo.mp4
clear
echo "FINISHED WITH .MP4 VIDEO"

luakit myHtmlFile2.html &
sleep 4;
echo "FINISHED SCRIPT"

Now transition from video to .html file is very good and it doesn't have interupts like before. Later, I will change script so it will play all files in some directory in infinite loop. Because of that I think best method is to close current tab, so you don't have to worry about memory issues and unnecessary tab stockpiling, specially on low-level memory computers like Raspberry Pi.

**Comment by o-jasper** [comment]
Okey :) Stilll, i think it'd be nice to be able to do this more directly.
