### ISSUE TITLE
Raspberry Pi console mode - can not open Luakit 

### ISSUE THREAD

**Issue by mensurdurakovic** [luakit/luakit#296]
When I try to open Luakit in console mode, I get this message:

    (luakit:623): Gtk-warning **: cannot open display:

Is it even possible to open it in console mode. I wonder how other programs like OMX player can run in console mode, but luakit can't. On startup I call simple python script where I call luakit browser with subprocess command: 

    p = subprocess.Popen(["luakit","google.com"])

**Comment by residentsummer** [comment]
I'm not entirely sure, but looks like omxplayer is capable of running without an X server (there is no mentions of it in docs and no X-related libs are in dependencies list). On the contrary, you need it (better with Desktop Environment) to use luakit. If X is not running (or not installed at all), you need to run/setup it up first.

If server or DE is already started, you just need to specify the virtual display where it's running. It is done through the environment variable called `DISPLAY`. First, try to set it to `:0.0` (the default virtual display that X server will run on; more info [here](http://askubuntu.com/questions/432255/what-is-display-environment-variable/432257)). If this doesn't help, please provide more details on your setup.

**Comment by mensurdurakovic** [comment]
Thank you for answer, I will try it today and message you back how it's gone.

**Comment by mensurdurakovic** [comment]
Thank you for your answer! I checked and X server is already installed on my PI. When I run:

    echo $DISPLAY

I get:

    :0.0

which means it's already set. I am not trying to access my PI remotely over ssh to run programs in console mode. I just want it to run python script on startup which will open luakit and show some websites. I don't know what value of $DISPLAY enviroment variable should be ?

**Comment by mensurdurakovic** [comment]
After a lot of wasted time, I found solution for my problem. Instead of running my python script in console mode and configuring X server, I changed autostart file located in directory:

    /home/pi/.config/lxsession/LXDE-pi
and added line to execute my python script which is working with Luakit browser:

    sudo python /path_to_script/myScript.py
This way, raspberry is starting normally in display mode, and after 1-2 seconds my python script is running Luakit without any problems.
