### ISSUE TITLE
luakit won't run: GTK+ 2.x/3.x error.

### ISSUE THREAD

**Issue by zakariakhamissa** [luakit/luakit#303]
Hello everyone,
I recently installed luakit from source on my machine running Gentoo but it doesn't seem to run.

When I run `luakit` it in the terminal it prints:

`(luakit:9607): Gtk-ERROR **: GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported`
`Trace/breakpoint trap`

I've tried to do several things to try and fix this myself:
I've completely removed gtk3 and installed only gtk2 and, because I was desperate I removed gtk2 and had only gtk3 installed. - but it still throws the same error.

Sorry if this is an inconvenience, any help would be much appreciated,

Zak.

**Comment by JR1994** [comment]
Why didn't you emerge the package from portage? I am running it with no issues.

**Comment by zakariakhamissa** [comment]
> Why didn't you emerge the package from portage?
It was masked for some reason, I thought that it was because the version on portage was not up-to-date so I didn't bother.

You really think I should unmask it and emerge it?

**Comment by zakariakhamissa** [comment]
I unmasked the package in portage and emerged.
Works fine now. 
Thanks!

**Comment by JR1994** [comment]
On 07/03, Zakaria Khamissa wrote:
> > Why didn't you emerge the package from portage?
> It was masked for some reason, I thought that it was because the version on portage was not up-to-date so I didn't bother.
> 
It is masked b/c there is no maintainer and it is be considered for removal from the portage tree. I am trying to see if I can be the maintainer of the ebuild.
