### ISSUE TITLE
Window not open when setting homepage in globals.lua

### ISSUE THREAD

**Issue by Manuel83** [luakit/luakit#306]
I tried to set the homepage for luakit but after setting the gloabls.lua the browser window don't open.

I created the following file for setting the homepage
~/.config/luakit/globals.lua

```
globals = {
    homepage = "www.example.com",
}
```

**Comment by aidanholm** [comment]
Try running `luakit --check` in a terminal window to check for syntax errors.

**Comment by Manuel83** [comment]
The config was ok but the problem was that I just defined the globals section in the file.
I was expecting that the software will merge the config files.

After copying the content of the entire default config.lua it was working fine.
https://github.com/luakit/luakit/blob/develop/config/globals.lua

Not sure if this is a bug or a feature. In general the browser is running super fast. 

One short addtitional question. Is it possible to hide the bottom url address bar in fullscreen mode?

Cheers,
Manuel

**Comment by aidanholm** [comment]
It's possible, but somewhat complicated if you're new to luakit. You'd need to add a window init function either in `config/window.lua` or in `config/rc.lua`, and add a signal handler on `w.win` there for the `property::fullscreen` signal, which will fire whenever the fullscreen state is toggled. Then you can access `w.win.fullscreen` to determine the current window fullscreen state, and set the visibility of the status bar widget (should be `w.sbar.layout`) as appropriate.

**Comment by Manuel83** [comment]
Sounds like 10-20 lines of code. Do you know where I can find an example for a custom signal handler?
For a first test it would be also sufficiant to hide the status bar always. Maybe this means commenting out one line only?

**Comment by aidanholm** [comment]
Haven't tested this; put this in `config/rc.lua`, after `require "window"`, but before the "End user script loading" comment:
```
window.init_funcs.hide_status_bar_when_fullscreen = function (w)
    w.win:add_signal("property::fullscreen", function ()
        w.sbar.layout.visible = not w.win.fullscreen
    end)
end
```

**Comment by Manuel83** [comment]
Thank you very much. Works perfectly!

Would be very helpful if this is supported via a config parameter for kisok mode on a Raspberry Pi.
Shall I open a feature request?

Cheers
Manuel
