### ISSUE TITLE
I can't watch or hear videos in youtube and vimeo

### ISSUE THREAD

**Issue by dsklfjh34843kjshdf** [luakit/luakit#309]
hello, I'm a new user of luakit, and I'm from Argentina, so my english is not very well. 
my problem is: I can't watch or hear videos in youtube and vimeo... my OS is archbang.
I hope your understend my problem with youtube and vimeo videos... thanks... :-)  ;-)

**Comment by mason-larobina** [comment]
Try running with luakit alsa-oss. This sounds like an OS issue not Luakit issue.

**Comment by dsklfjh34843kjshdf** [comment]
thanks, for answer me. I install "luakit alsa-oss" but the problem have no solution.
when I tried to run a video show me this: 
"An error ocurred. Please try again later. (Playback ID: fol2j0lP9AdtcdAI)"
