### ISSUE TITLE
Luakit is not able to login to Nextcloud server.

### ISSUE THREAD

**Issue by sprnza** [luakit/luakit#311]
Hi there!
I've faced with a weird issue. I'm not able to login to my Nexctloud server. It just reload the page without any error neither from Nextcloud nor from Luakit.
I've created a test user. The server is located [here](https://cloud.speran.info)
Username: test
Password: test123456

**Comment by aidanholm** [comment]
That username/password no longer works; are you still experiencing this issue with the latest version of luakit?

**Comment by sprnza** [comment]
Works fine with the latest version of luakit.
