### ISSUE TITLE
artefacts of horizontal scroll-bar

### ISSUE THREAD

**Issue by rotsix** [luakit/luakit#313]
Hi,

About myself : 
Arch 4.9.11
i3 version 4.13 (2016-11-08, branch "4.13")
luakit 2012.09.13-r1-72-gcd8487a

------------------------

I have a problem with the horizontal scoll-bar,
Acts are better than explanations, https://ptpb.pw/SE6U.png here is the problem.

As you can see, when i scoll down, there are some artefacts of the bottom scroll-bar.

Can I disable this bar maybe ? 

Regards

EDIT: got same problem with the right scoll-bar when scrolling right.

**Comment by aidanholm** [comment]
Luakit uses WebKit 2 now, and I can't reproduce this; feel free to reopen if it happens again.
