### ISSUE TITLE
follow.pattern_styles.match_label broken

### ISSUE THREAD

**Issue by sprnza** [luakit/luakit#317]
I try to enable characters for hints as described [here](https://github.com/luakit/luakit/wiki/Alternative-characters-for-following-hints).
I start to get this error and luakit is falling back:
```
luaH_dofunction:147: Lua error: attempt to index global 'follow' (a nil value)
```

My config looks like this:
```
-- Add vimperator-like link hinting & following
require "follow"

-- Use a custom charater set for hint labels
local s = follow.label_styles
follow.label_maker = s.sort(s.reverse(s.charset("asdfqwerzxcv")))

-- Match only hint labels
follow.pattern_maker = follow.pattern_styles.match_label
```

**Comment by aidanholm** [comment]
`require` returns the module, but does not assign it to the global `follow` variable. You need to assign it to a (preferably local) variable: `local follow = require "follow"`.

The way to change the character set has changed; see https://github.com/aidanholm/luakit/issues/312#issuecomment-302354898.

**Comment by sprnza** [comment]
Thanks! Works like a rock!

**Comment by sprnza** [comment]
And how to configure to match only hint labels in this case?

**Comment by aidanholm** [comment]
`follow.pattern_maker = follow.pattern_styles.match_label` still works.

**Comment by sprnza** [comment]
Do you mean to add this to rc.lua?
```
local follow = require "follow"
follow.pattern_maker = follow.pattern_styles.match_label
```
If so luakit stops following hints on type. I mean the hints appear, but nothing happens when I type something in.

**Comment by sprnza** [comment]
In the status bar appears:
`Follow:`
and when I type something hints don't trigger.

**Comment by aidanholm** [comment]
Sorry for the late response! I'm getting the same problem; looks like a bug.

**Comment by aidanholm** [comment]
Fix merged at c030396; feel free to reopen if you have further problems/questions

**Comment by sprnza** [comment]
Yay! Thanks! Could you please bump AUR package version :)

**Comment by aidanholm** [comment]
Which one? There's two: `luakit` and `luakit-git`.

**Comment by sprnza** [comment]
I thought `luakit-git` is a mirror of this repo. Isn't it?

**Comment by aidanholm** [comment]
Oops, there's only one now; my mistake :) I've bumped the version on `luakit-git`.
