### ISSUE TITLE
Add options for system paths in Makefile for FreeBSD

### ISSUE THREAD

**Issue by aidanholm** [luakit/luakit#320]
E.g. option for `/etc/xdg/`, pixmaps dir, applications dir.

**Comment by aidanholm** [comment]
@ds6 I've added `XDGPREFIX`, `PIXMAPDIR`, and `APPDIR` to the Makefile options at 0ea03ce8. You should be able to set `XDGPREFIX=/usr/local/etc/xdg/` and have everything go in the right place. Not sure if you need the other two, but they're there for completeness.

**Comment by ds6** [comment]
Thanks! I believe all that would need to be used for a full installation is `XDGPREFIX=/usr/local/etc/xdg`, because there doesn't seem to be any defaults for that for FreeBSD `gmake`. The rest work fine.
It might be doable to check platforms in the `Makefile` but that's probably excessive.
