### ISSUE TITLE
Add chrome UA domain rule for youtube

### ISSUE THREAD

**Issue by aidanholm** [luakit/luakit#321]

**Comment by aidanholm** [comment]
Will be easy with #440

**Comment by aidanholm** [comment]
And now that #440 is in, it's not needed; youtube now works with the default UA and breaks with a chrome UA ¯\_(ツ)_/¯

**Comment by Plaque-fcc** [comment]
I guess they check if it's what it calls itself with their Google library in JS. Years ago I came to blocking their library with direct Adblock rule…

On August 27, 2017 8:47:49 PM GMT+03:00, Aidan Holm <notifications@github.com> wrote:
>And now that #440 is in, it's not needed; youtube now works with the
>default UA and breaks with a chrome UA ¯\_(ツ)_/¯
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/luakit/luakit/issues/321#issuecomment-325213426

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by aidanholm** [comment]
Which library would that be?

**Comment by Plaque-fcc** [comment]
Need to warm up my old HDD or find out that thing again. Wait a bit.

On August 28, 2017 12:57:41 PM GMT+03:00, Aidan Holm <notifications@github.com> wrote:
>Which library would that be?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/luakit/luakit/issues/321#issuecomment-325312620

-- 
J.K.
