### ISSUE TITLE
Compilation fails.

### ISSUE THREAD

**Issue by luis-lavaire** [luakit/luakit#322]
I'm trying to compile luakit on Arch Linux ARM in the [pine 64](https://www.pine64.org)
but it fails. I'm not a C programmer, so I don't know how to solve this by myself. I'm
not sure if this is an issue or something I'm doing wrong. Here's the info I can provide:

OS: Arch Linux ARM
Kernel: 3.10.65-7-pine64-longsleep
Architecture: aarch64

Output when running 'make'

luakit build options:
CC           = cc
LUA_PKG_NAME = luajit
LUA_BIN_NAME = luajit
CFLAGS       = -std=gnu99 -ggdb -W -Wall -Wextra -Werror=unused-result -pthread -I/usr/include/webkitgtk-4.0 -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/libsoup-2.4 -I/usr/include/libxml2 -I/usr/include/luajit-2.1 -I/usr/include/webkitgtk-4.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I./
CPPFLAGS     =  -DVERSION="2012.09.13-r1-1713-g2de65f50" -DDEVELOPMENT_PATHS -DWITH_WEBKIT2
LDFLAGS      =  -Wl,--export-dynamic -lgthread-2.0 -pthread -lwebkit2gtk-4.0 -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lsoup-2.4 -lgio-2.0 -lgobject-2.0 -lsqlite3 -lluajit-5.1 -ljavascriptcoregtk-4.0 -lglib-2.0
INSTALLDIR   = /usr/local
MANPREFIX    = /usr/local/share/man
DOCDIR       = /usr/local/share/luakit/doc
XDGPREFIX    = /etc/xdg
PIXMAPDIR    = /usr/local/share/pixmaps
APPDIR       = /usr/local/share/applications

build targets:
SRCS     = log.c luakit.c luah.c ipc.c web_context.c common/luaclass.c common/luaserialize.c common/luah.c common/ipc.c common/property.c common/luauniq.c common/luautil.c common/util.c common/luaobject.c common/luajs.c common/clib/regex.c common/clib/luakit.c common/clib/ipc.c common/clib/msg.c common/clib/timer.c clib/request.c clib/sqlite3.c clib/unique.c clib/xdg.c clib/soup.c clib/luakit.c clib/download.c clib/ipc.c clib/web_module.c clib/stylesheet.c clib/widget.c widgets/socket.c widgets/label.c widgets/entry.c widgets/webview.c widgets/common.c widgets/notebook.c widgets/box.c widgets/scrolled.c widgets/paned.c widgets/overlay.c widgets/window.c widgets/spinner.c widgets/drawing_area.c widgets/image.c widgets/eventbox.c common/tokenize.c
HEADS    = buildopts.h luah.h ipc.h globalconf.h web_context.h common/lualib.h common/signal.h common/common.h common/luaserialize.h common/luaclass.h common/ipc.h common/property.h common/luauniq.h common/luautil.h common/log.h common/util.h common/luah.h common/luaobject.h common/luajs.h common/tokenize.h common/clib/luakit.h common/clib/ipc.h common/clib/msg.h common/clib/soup.h common/clib/timer.h common/clib/regex.h widgets/webview.h widgets/common.h clib/unique.h clib/xdg.h clib/luakit.h clib/download.h clib/web_module.h clib/soup.h clib/stylesheet.h clib/widget.h clib/request.h clib/sqlite3.h  common/tokenize.h buildopts.h
OBJS     = log.o luakit.o luah.o ipc.o web_context.o common/luaclass.o common/luaserialize.o common/luah.o common/ipc.o common/property.o common/luauniq.o common/luautil.o common/util.o common/luaobject.o common/luajs.o common/clib/regex.o common/clib/luakit.o common/clib/ipc.o common/clib/msg.o common/clib/timer.o clib/request.o clib/sqlite3.o clib/unique.o clib/xdg.o clib/soup.o clib/luakit.o clib/download.o clib/ipc.o clib/web_module.o clib/stylesheet.o clib/widget.o widgets/socket.o widgets/label.o widgets/entry.o widgets/webview.o widgets/common.o widgets/notebook.o widgets/box.o widgets/scrolled.o widgets/paned.o widgets/overlay.o widgets/window.o widgets/spinner.o widgets/drawing_area.o widgets/image.o widgets/eventbox.o common/tokenize.o
EXT_SRCS = extension/scroll.c extension/script_world.c extension/log.c extension/extension.c extension/ipc.c extension/luajs.c extension/clib/luakit.c extension/clib/ipc.c extension/clib/dom_element.c extension/clib/soup.c extension/clib/dom_document.c extension/clib/page.c common/luaclass.c common/luaserialize.c common/luah.c common/ipc.c common/property.c common/luauniq.c common/luautil.c common/util.c common/luaobject.c common/luajs.c common/clib/regex.c common/clib/luakit.c common/clib/ipc.c common/clib/msg.c common/clib/timer.c common/tokenize.c
EXT_OBJS = extension/scroll.o extension/script_world.o extension/log.o extension/extension.o extension/ipc.o extension/luajs.o extension/clib/luakit.o extension/clib/ipc.o extension/clib/dom_element.o extension/clib/soup.o extension/clib/dom_document.o extension/clib/page.o common/luaclass.o common/luaserialize.o common/luah.o common/ipc.o common/property.o common/luauniq.o common/luautil.o common/util.o common/luaobject.o common/luajs.o common/clib/regex.o common/clib/luakit.o common/clib/ipc.o common/clib/msg.o common/clib/timer.o common/tokenize.o

cc -c luakit.c -o luakit.o
In file included from ./common/luaobject.h:27:0,
                 from common/luah.h:25,
                 from luah.h:25,
                 from luakit.c:23:
./common/luaclass.h:74:68: error: array type has incomplete element type 'struct luaL_reg'
 void luaH_openlib(lua_State *, const gchar *, const struct luaL_reg[],
                                                                    ^
./common/luaclass.h:75:30: error: array type has incomplete element type 'struct luaL_reg'
         const struct luaL_reg[]);
                              ^
./common/luaclass.h:74:60: warning: 'struct luaL_reg' declared inside parameter list will not be visible outside of this definition or declaration
 void luaH_openlib(lua_State *, const gchar *, const struct luaL_reg[],
                                                            ^~~~~~~~
./common/luaclass.h:78:30: error: array type has incomplete element type 'struct luaL_reg'
         const struct luaL_reg[], const struct luaL_reg[]);
                              ^
./common/luaclass.h:78:55: error: array type has incomplete element type 'struct luaL_reg'
         const struct luaL_reg[], const struct luaL_reg[]);
                                                       ^
./common/luaclass.h:78:22: warning: 'struct luaL_reg' declared inside parameter list will not be visible outside of this definition or declaration
         const struct luaL_reg[], const struct luaL_reg[]);
                      ^~~~~~~~
make: *** [Makefile:53: luakit.o] Error 1

**Comment by aidanholm** [comment]
Does any file in `/usr/include/luajit-2.1` contain the text `luaL_reg` or `luaL_Reg`?

**Comment by luis-lavaire** [comment]
@aidanholm, yes, it appears in "/usr/include/luajit-2.1/lauxlib.h". Sould I attach that file?
Thanks for your answer!

**Comment by aidanholm** [comment]
Yes please!

You could also try replacing all instances of `luaL_reg` with `luaL_Reg`. Run `grep -rl luaL_reg | xargs sed -i s/luaL_reg\\b/luaL_Reg/g` from the luakit directory.

**Comment by luis-lavaire** [comment]
Here is it. I added the .txt extension manually to be able to upload it.

[lauxlib.h.txt](https://github.com/luakit/luakit/files/1105985/lauxlib.h.txt)

**Comment by aidanholm** [comment]
Your lauxlib.h is missing a compatibility macro. It seems luakit is using an outdated name; I'll fix this in a few hours.

**Comment by aidanholm** [comment]
This should be fixed at 1a019d99 :)

**Comment by luis-lavaire** [comment]
Well, thanks for your help @aidanholm..!

**Comment by aidanholm** [comment]
You're welcome, thanks for reporting the issue!
