### ISSUE TITLE
Add spell checking API 

### ISSUE THREAD

**Issue by aidanholm** [luakit/luakit#330]
```lua
luakit.enable_spell_checking = true
luakit.spell_checking_languages = { "sv_FI", "pt_BR", ... }
```

**Comment by aidanholm** [comment]
@szbnwer This has been implemented! Just have to download the newest luakit, and add the above to your `rc.lua`. 

Implemented at d9144cff

**Comment by szbnwer** [comment]
thx! i'll try it when i'll have time, this week (* my weeks are from thursday to monday :D ) was shortened with much so i have to work hard now. anyway i like your attitude, i'm very sure about you should be a very good person :)

**Comment by delister** [comment]
hmm...doesn't work for me. luakit version: fc07ed5a (Oct 6, 2018). I added settings to ~/.config/luakit/rc.lua like this:
```
luakit.enable_spell_checking = true
luakit.spell_checking_languages = { "ru_RU", "en_EN" }
```

but typed text not highlighted when errors. May be I need to install something more ?
