### ISSUE TITLE
Error page: show error favicon

### ISSUE THREAD

**Issue by aidanholm** [luakit/luakit#336]
[!] for error pages, [X] for web process crash?

**Comment by aidanholm** [comment]
- ![tab-icon-security-error 2x](https://user-images.githubusercontent.com/10691965/28502055-9dbd2d52-701c-11e7-9801-fe0aa0a598dc.png) for security errors
 - ![tab-icon-crash 2x](https://user-images.githubusercontent.com/10691965/28502044-788f3fac-701c-11e7-94a9-57b5b3e27676.png) for web process crashes
 - ![tab-icon-error 2x](https://user-images.githubusercontent.com/10691965/28502045-7aad6f84-701c-11e7-9a3d-a31e9ca71a57.png) for general errors

**Comment by szbnwer** [comment]
nice :) the x could be a bit bigger for harmony with others but really not important :D

**Comment by aidanholm** [comment]
Current WIP, at 2x
![tab-icons](https://user-images.githubusercontent.com/10691965/28502504-398ff652-7026-11e7-828b-d8737cf45591.png)

**Comment by aidanholm** [comment]
@szbnwer I'm more concerned about the default fallback icon (bottom one in the above screenshot); the others are all barely modified icons from the Arc icon theme, but that one I quickly did myself, and it sticks out a bit; the square needs to be a bit thicker.

**Comment by szbnwer** [comment]
fine, anyway i still didn't change but started to read the sauces (yup :D ) cuz i wanna get a cleaner image about the whole, but slowly i wanna make it a new home, just i'm too deeply inside firefox currently... - so this is my 1st meeting with the icons

**Comment by aidanholm** [comment]
I see what you mean about the X though, could be a bit bigger; will have to wait and see

**Comment by aidanholm** [comment]
Merged at bdf5dd43!
