### ISSUE TITLE
Impossible to select text on aliexpress.com

### ISSUE THREAD

**Issue by sprnza** [luakit/luakit#346]
Hi there!
Just found an annoing issue. It's impossible to select text using mouse pointer on most of pages on aliexpress.com

**Comment by aidanholm** [comment]
Thanks for the report! This looks like a WebKit bug, as epiphany has the same behavior. Attempting to force all text to be selectable with CSS didn't work either.

**Comment by szbnwer** [comment]
guesses for research on it are z-index and js magic, and chromium and firefox are working, so maybe not webkit bug cuz chromium; playing with noscript and user agent possibly can help in the research, in worse case you can select text from web inspector in case of emergency :)

**Comment by taobert** [comment]
I'm not able to reproduce this (even with commit 5b57d85 backed out) with
\#luakit --version
luakit 2.1-27-gad5033f1
  built with webkit 2.26.2 (installed version: 2.26.2)

Is it still causing problems, or can this issue be closed?

**Comment by sprnza** [comment]
Yep, works fine now
