### ISSUE TITLE
[FreeBSD] Only works when started in source directory

### ISSUE THREAD

**Issue by xkpd3** [luakit/luakit#347]
Hello,

I have compiled luakit on FreeBSD. After `gmake install` luakit only works when the luakit command is issued from the luakit source directory.

Example:
```
Github/luakit $ gmake CC=clang
OK
Github/luakit $ sudo gmake install
OK
Github/luakit $ luakit
OK
Github/luakit $ cd ..
Github $ luakit 
NOT OK
```
Not ok in this case means that luakit is opening up, but it is not able to load a page or respond to any command entered.

Screenshot after start from the luakit directory:
![Luakit working](https://shell.srv.hagen.coffee/~sdk/screenshots/2017-07-19_18-47-55.png)

Screenshot after start outside the luakit directory:
![Luakit not working](https://shell.srv.hagen.coffee/~sdk/screenshots/2017-07-19_18-48-45.png)

I assume that either `gmake install` is missing to copy some files or luakit is assuming some paths relative to `$PWD` instead of `$HOME` or `$PREFIX`.

I suspect the `resources` folder being assumed to be in `$PWD`.

Am I the only one that experiences this? :)

Best Regards,
Stefan

**Comment by aidanholm** [comment]
Hello, and thanks for your very detailed report!

The fix is very simple: build luakit with `DEVELOPMENT_PATHS=0`:
```
gmake CC=clang DEVELOPMENT_PATHS=0
```
By default, luakit is setup for a developer; I should probably fix that :)

**Comment by xkpd3** [comment]
Am I on the right track when I say in `lib/tab_favicons.lua` the lines with `fav:filename("resources/icons/...png")` must be changed somehow to prepend the config_data_dir?

**Comment by aidanholm** [comment]
When setting the image to display with `filename()`, with a relative path, the installation path will be automatically appended if `DEVELOPMENT_PATHS` is disabled.

**Comment by aidanholm** [comment]
You can check from luakit if you're running with `DEVELOPMENT_PATHS` set:
```
:lua w:notify(luakit.dev_paths and "Dev build" or "Normal build")
```

**Comment by xkpd3** [comment]
I need to read more careful. It's all documented...
Thanks for the fast response! Finally I have a usable browser again :)

**Comment by aidanholm** [comment]
No problem, glad you got it working :)
