### ISSUE TITLE
How to configure hint styles?

### ISSUE THREAD

**Issue by xkpd3** [luakit/luakit#350]
Hello,

I have a relatively high DPI screen and the hints are so tiny that I can't read them from a normal distance.

I know I can change the css in `lib/follow.lua`, but this is surely not meant that way. I tried to figure out how to work with styles, but did not get very far. I have a css file in `.config/luakit/styles/default.css` but I did not figure out how to load it. `:styles-reload` does something, but `:styles-list` is complaining:

![styles-list](https://shell.srv.hagen.coffee/~sdk/screenshots/2017-07-20_01-09-18.png)

How is this supposed to work?

Is there actually a user documentation planned / in progress? I would be up to contribute while figuring out how all this works.

Best Regards,
Stefan

**Comment by aidanholm** [comment]
That looks like a bug in the styles module. I'll have a look.

Separately, you should be able to do the following:
```lua
follow.stylesheet = follow.stylesheet .. [===[
    #luakit_select_overlay .hint_label { font-size: 40px; }
]===]

**Comment by aidanholm** [comment]
And yep, there are docs at `luakit://help/doc/index.html`, although there's a bunch of stuff that's missing from there but in my local git, waiting for me to finish it up and push it. Contributions are always welcome :)

**Comment by aidanholm** [comment]
I can reproduce your big red error message; happens when you don't have a styles directory, and then run `:styles-list`. Should be fixed now.

If you tried putting stuff in a `default.css` file in there, you probably got an unhelpful "Not loading stylesheet 'default.css'" error message. This is because usually stylesheets apply to specific pages; luakit will refuse to load a stylesheet that applies to everything (which is what you want, of course). To fix this, you can add the following comment, case insensitive, to your CSS file:
```css
/* i really want this to be global */
```
And it should work after that. Another way of doing it is to do this:
```
@-moz-document regexp(".*") {
    /* CSS here */
}
```

**Comment by xkpd3** [comment]
I'm currently not able to load styles at all.

I have two files now:
1. `style1.css` with the following content:
```
/* i really want this to be global */
#luakit_select_overlay .hint_label { font-size: 40px; }
```
2. `style2.css` with the following content:
```
@-moz-document regexp(".*") {
  #luakit_select_overlay .hint_label { font-size: 40px; }
}
```

I copied these files into the following directories:
- `$HOME/.config/luakit/styles/`
- `/etc/xdg/luakit/styles/`
- `/usr/local/share/luakit/styles/`

Luakit is not able to find them. `:styles-list` shows: "No userstyles installed."

**Comment by xkpd3** [comment]
This first suggestion works fine:

in rc.lua:
```
follow.stylesheet = follow.stylesheet .. [===[
    #luakit_select_overlay .hint_label { font-size: 40px; }
]===]
```

I close this issue with this information, as it solves the issue I had. I still wonder what I do wrong with the styles.

**Comment by aidanholm** [comment]
For future reference: solution is that CSS files must be in ~/.local/share/luakit/styles/; this is the _only_ directory searched by the `styles.lua` module.
