### ISSUE TITLE
Luakit on Windows 10 with MS Linux Subsystem + Xming

### ISSUE THREAD

**Issue by xkpd3** [luakit/luakit#351]
Not an issue, just fyi.

Luakit runs nicely on the Windows 10 Linux Subsystem.

The default subsystem is based on Ubuntu "trusty" this needs to be upgraded to "xenial" using `do-release-upgrade`. Once this is done, all dependencies are available and luakit can be compiled just as on a normal Linux installation.

![Luakit on Windows 10](https://seafile.srv.hagen.coffee/f/a45c4e30ea3441209f1d/?dl=1)

Feel free to close this issue and reuse the screenshot as you like.

Best Regards,
Stefan

**Comment by xkpd3** [comment]
...and it kicks ass :-)

![Luakit vs. Chrome - Windows](https://seafile.srv.hagen.coffee/f/a2a55cd42af04c6db7f9/?dl=1)

**Comment by aidanholm** [comment]
Woah, that's amazing! Never would have thought I'd see luakit running on Windows, as WebKitGtk doesn't support it at all. Thanks for letting me know, and for the screenshots: I'll add them to the website at some point.
