### ISSUE TITLE
Hintkey not recognized as unique

### ISSUE THREAD

**Issue by xkpd3** [luakit/luakit#352]
Hello,

I noticed the following hinting behavior.

1. I open a website:
![Hinting Step 1](https://seafile.srv.hagen.coffee/f/3c89aad0d78b4b39a79e/?dl=1)

2. I press "f" to show the hints:
![Hinting Step 2](https://seafile.srv.hagen.coffee/f/564776dea250435f991e/?dl=1)

3. I press "r" to trigger the first google search result:
![Hinting Step 3](https://seafile.srv.hagen.coffee/f/3554ea89c17548c28fe9/?dl=1)

My expectation would have been that after pressing "r", the marked link would open. Instead half the hints disappear. Pressing "r" again does not help. I can only press "tab" multiple times until the link is highlighted and then "enter".

To enable alphabetic hinting, I use this snippet implemented below "-- End user script loading --" in `rc.lua`.

```
-- Use "asdfqwerzxcv" for generating labels
local select = require "select"
select.label_maker = function (s)
    return s.sort(s.reverse(s.charset("qwertzuiopasfghjklyxcvbnm")))
end
```

Best Regards,
Stefan

**Comment by aidanholm** [comment]
This is a commonly encountered issue; see docs in luakit://help/doc/modules/follow.html, but basically you need to add this to `rc.lua`, as by default follow mode matches against link text too (the remaining links all contain the letter r`:
```
-- Match only hint label text
follow.pattern_maker = follow.pattern_styles.match_label
```

**Comment by xkpd3** [comment]
I tired this before, but all I got was this error message.

```
[    3.837343] E: luaH_dofunction:147: Lua error: attempt to index global 'follow' (a nil value)
```

And then luakit was loading with numeric hinting.

**Comment by aidanholm** [comment]
That's because you need to replace `require "follow"` with `local follow = require "follow"`. Modules no longer trash the global namespace.

We should probably do this in the default config file.

**Comment by xkpd3** [comment]
Most excellent! Works like a charm.

Thank you - again!

Best Regards,
Stefan

**Comment by aidanholm** [comment]
You're welcome! :)
