### ISSUE TITLE
Feature: Possibility to override adblock

### ISSUE THREAD

**Issue by xkpd3** [luakit/luakit#359]
Hello,

What if a page is blocked by the adblock plugin, but I still want to visit it? I would like to have a button that allows me to still visit this page. Either by allowing to disable adblock alltogether for this tab, or by whitelisting the requested domain temporarily (preferred).

Just as an idea for the future. Because right now there are domains I just can't visit with luakit without altering the adblock lists manually.

Best Regards
Stefan

**Comment by aidanholm** [comment]
Sure, shouldn't be too difficult to add domain whitelisting. Easiest way is to add an ephemeral filter list that's used for per-session domain whitelists. In the interim you can, of course, always add a whitelist.txt filterlist.

**Comment by aidanholm** [comment]
Added at 60139626; you can also call `adblock.whitelist_domain_access` in your `rc.lua` if you often go to a particular domain.
