### ISSUE TITLE
Use editor.lua in open_editor.lua

### ISSUE THREAD

**Issue by gleachkr** [luakit/luakit#367]
The idea would be to replace the current hardcoded `luakit.spawn` of `xdg-open` a call to `editor.edit`. 

This would require adding a callback parameter to the call to `luakit.spawn` in `editor.lua`, but doing so would close another one of the bullet-pointed limitations of that module mentioned in the docs.

I'd be happy to put in a PR if this sounds like a good idea.

**Comment by aidanholm** [comment]
Sounds great! In fact `luakit.spawn` already has a callback parameter: check `clib/luakit.c:281` for the old doc comment with example.

**Comment by gleachkr** [comment]
closed by #369
