### ISSUE TITLE
Update beginner's guide in wiki

### ISSUE THREAD

**Issue by aidanholm** [luakit/luakit#372]
Traffic stats list it as one most visitors view

**Comment by aidanholm** [comment]
quickstart guide merged into docs at 33a2eec7

**Comment by Ygrex** [comment]
wiki refers to this issue from the home page
https://github.com/luakit/luakit/wiki
with «This wiki is currently out of date! (Issue #372)»
since this issue is closed, can wiki be considered up-to-date now?

**Comment by aidanholm** [comment]
The wiki is still out of date: I just cleaned up and merged some of the pages into the luakit docs. Everything else is still outdatd.
