### ISSUE TITLE
Allow formfiller forms to take a function in the value field.

### ISSUE THREAD

**Issue by gleachkr** [luakit/luakit#376]
The idea would be that you could integrate with an external password manager by seting the value field of an input table in `forms.lua` to something like 
```
function () return io.popen("pass myemail"):read() end
```
It seems like it's possible to do this by just inserting 
```
if type(val) == "function" then val = val() end
```
at line 139 in `formfiller_wm.lua`, though you'd want some documentation. I can put in a PR if you'd like.

**Comment by aidanholm** [comment]
Not a bad idea. What scope would these functions be in? Would it be possible to define a function elsewhere, and then do something like `value = get_secure_password("myemail")`, without defining `get_secure_password` multiple times?.

**Comment by gleachkr** [comment]
Unfortunately, I think the sandboxing around 158 of `formfiller.lua` doesn't interact well with closures. Adding something like
```
cmd = function(_,s) return function () return io.popen(s):read() end end
```
to the forms dsl produces the error that popen has been passed a null value. I guess you can accomplish the same thing without a closure, though, by adding
```
cmd = function(_,s)  return io.popen(s):read() end
```
to the dsl. That might obviate the idea of setting the value field to a function, so long as you want to use a command line password manager.

**Comment by aidanholm** [comment]
The other problem with this approach is that the whole DSL is evaluated when you run the formfiller. So all `cmd` lines would get run, for any page.

**Comment by gleachkr** [comment]
Hm. So is that an argument for the closure idea, to avoid repeatedly `popen`-ing the password manager?

One way to stick with the original function-in-value-field idea, and to have something like `cmd` (a hack---sorry, just thinking out loud) would be to treat `cmd` as a macro, replacing it in form.lua by the relevant closure when  that code is read in from `forms.lua` in `formfiller.lua` around 149.

Or maybe there's a way to get around the sandboxing---I'm not an expert on `setfenv`, so I could easily be overlooking something.

**Comment by aidanholm** [comment]
Oh, I forgot before: when you got `popen` complaining about a nil value, that'd probably be because the returned function gets sent over IPC to the web process and then actually run there. Function serialization doesn't currently serialize the function's upvalues, so that's why that happens. This is the reason for the select.lua label maker API currently being a bit weird.

If that's fixed, then adding custom commands to the DSL table that return closures seems ideal.

**Comment by aidanholm** [comment]
Alright, lua_getupvalue and lua_setupvalue look like the way to go; if you want to take a crack at it, the place is common/luaserialize.c, otherwise I'll get around to it in the next day or two.

**Comment by szbnwer** [comment]
i didn't check out the actual codes (i started go thru the docs today :D ) but something like a table with a window id or url for selecting the right target maybe can be a way to go or factories like fun(target)(call)

i hope i didn't talk about completely unrelated stuffs :D

**Comment by szbnwer** [comment]
uhmm the 1st idea wanted to be something like a detect where am i and if i can make a difference to not call other pages and other instances of the same domain loaded or whatever, then i can look up that table for the way to go... so it can be well organized but maybe a bit tricky to get it for a newbie, but programming is like that anyway :D

**Comment by aidanholm** [comment]
What do you mean by selecting the right target? Currently I think adding an API for customizing the formfiller DSL is the ideal approach, for a few reasons: 1) It'll be very simple to implement 2) It provides an interface for other modules to customize behavior, without restricting how that behavior would work 3) It doesn't add any new behavior itself.

**Comment by szbnwer** [comment]
sorry i've ran out of brain 4 2day, it's already a.m. 6:40 here, so i will dig deeper into the codebase before answer you, but i will sleep now, and 'tomorrow' i will have to drink much and be social, so dunno when i'll response :D have fun as well :)

**Comment by aidanholm** [comment]
No problem, have fun!

**Comment by gleachkr** [comment]
Re: https://github.com/luakit/luakit/issues/376#issuecomment-318521366:

OK, I'll keep thinking about this until #377 lands. Does the `cmd` approach to enriching the dsl seem sensible to you, or when you say API, were you imagining something richer?

**Comment by aidanholm** [comment]
Something like this in `rc.lua`:
```lua
formfiller.dsl.cmd = function () return function () ... end end
```

**Comment by aidanholm** [comment]
I've added upvalue serialization at 4407e76, so your original one should work now:
```lua
cmd = function(_,s) return function () return io.popen(s):read() end end
```

**Comment by gleachkr** [comment]
Great! I'll prepare a PR with something like the API you describe.

**Comment by gleachkr** [comment]
Running into a little trouble after rebuilding on the latest commit. It seems like my development luakit can't find the lousy module:

```
[    0.024861] I [core/luah]: Loading rc: /home/graham/.config/luakit/rc.lua
[    0.054972] E [core/./common/lualib]: Lua error: module 'lousy' not found:
                 9no field package.preload['lousy']
                 9no file './lousy.lua'
                 9no file '/usr/share/luajit-2.0.5/lousy.lua'
                 9no file '/usr/local/share/lua/5.1/lousy.lua'
                 9no file '/usr/local/share/lua/5.1/lousy/init.lua'
                 9no file '/usr/share/lua/5.1/lousy.lua'
                 9no file '/usr/share/lua/5.1/lousy/init.lua'
                 9no file '/home/graham/.config/luakit/lousy.lua'
                 9no file '/home/graham/.config/luakit/lousy/init.lua'
                 9no file '/etc/xdg/luakit/lousy.lua'
                 9no file '/etc/xdg/luakit/lousy/init.lua'
                 9no file '/usr/local/share/luakit/lib/lousy.lua'
                 9no file '/usr/local/share/luakit/lib/lousy/init.lua'
                 9no file './lousy.so'
                 9no file '/usr/local/lib/lua/5.1/lousy.so'
                 9no file '/usr/lib/lua/5.1/lousy.so'
                 9no file '/usr/local/lib/lua/5.1/loadall.so'
                 Traceback:
                 (1) [C]                                   in function require
                 (2) /home/graham/.config/luakit/rc.lua:27 in main chunk
[    0.054995] W [core/luah]: loading rc '/home/graham/.config/luakit/rc.lua' failed, falling back...
[    0.023273] I [core/luah]: Loading rc: /etc/xdg/luakit/rc.lua
[    0.053293] E [core/./common/lualib]: Lua error: module 'lousy' not found:
                 9no field package.preload['lousy']
                 9no file './lousy.lua'
                 9no file '/usr/share/luajit-2.0.5/lousy.lua'
                 9no file '/usr/local/share/lua/5.1/lousy.lua'
                 9no file '/usr/local/share/lua/5.1/lousy/init.lua'
                 9no file '/usr/share/lua/5.1/lousy.lua'
                 9no file '/usr/share/lua/5.1/lousy/init.lua'
                 9no file '/home/graham/.config/luakit/lousy.lua'
                 9no file '/home/graham/.config/luakit/lousy/init.lua'
                 9no file '/etc/xdg/luakit/lousy.lua'
                 9no file '/etc/xdg/luakit/lousy/init.lua'
                 9no file '/usr/local/share/luakit/lib/lousy.lua'
                 9no file '/usr/local/share/luakit/lib/lousy/init.lua'
                 9no file './lousy.so'
                 9no file '/usr/local/lib/lua/5.1/lousy.so'
                 9no file '/usr/lib/lua/5.1/lousy.so'
                 9no file '/usr/local/lib/lua/5.1/loadall.so'
                 Traceback:
                 (1) [C]                       in function require
                 (2) /etc/xdg/luakit/rc.lua:27 in main chunk
[    0.053315] W [core/luah]: loading rc '/etc/xdg/luakit/rc.lua' failed, falling back...
[    0.023916] F [core/luakit]: couldn't find rc file
```

Don't think I did anything differently from when it was working---in both cases, built with a simple `make` and ran luakit from the root of the git repo.

**Comment by aidanholm** [comment]
I recently changed the default for DEVELOPMENT_PATHS; you'll need to set it back to 1

**Comment by gleachkr** [comment]
Got it, thanks.

**Comment by gleachkr** [comment]
Hm. I've rebuilt after https://github.com/luakit/luakit/commit/4407e7662159d54dada74abe129476eb542e951a, but I'm still encountering the error that `popen` has been passed a nil value.

**Comment by aidanholm** [comment]
If you push your changes, I'll pull them and have a look

**Comment by gleachkr** [comment]
Here it is: https://github.com/gleachkr/luakit/tree/closure_example

**Comment by aidanholm** [comment]
Sorry, turns out I borked the upvalue serializing code; it's fixed now, and `cmd` works!

**Comment by gleachkr** [comment]
Awesome! OK, I'll pull that and get back to work. Should have something by tomorrow.

**Comment by aidanholm** [comment]
I was thinking that it's a bit limiting to only be able to use custom commands on the value field. An alternative implementation would be to traverse the parsed formfiller form profile, once one is selected, and call all functions on it, replacing their positions in the table with the value they return.

**Comment by gleachkr** [comment]
Rewriting apply using something like the following seems like it would let you
use functions in all fields (except for "autofill", which I think requires
a separate tweak around 263 in `formfiller.lua`):

```lua
local function apply (form, form_spec)
    local function relax(t)
        local meta = {}
        local relaxed = {}
        function meta:__index(i) 
            if (type(t[i]) == "function") then 
                return t[i]()
            else
                return t[i]
            end
        end
        return setmetatable(relaxed,meta)
    end
    -- Map of attr -> value that form has to match
    local attrs = {}
    for _, v in ipairs({"method", "name", "id", "action", "className"}) do
        attrs[v] = relax(form_spec)[v]
    end
    if not element_attributes_match(form, attrs) then
        return false
    end

    for _, input_spec in ipairs(form_spec.inputs) do
        local matches = match("input", {"name", "id", "className", "type"}, input_spec, {form})
        if #matches > 0 then
            local input_spec = relax(input_spec)
            local val = input_spec.value or input_spec.checked
            if val then fill_input(matches, val) end
            if input_spec.focus then matches[1]:focus() end
            if input_spec.select then matches[1]:select() end
        end
    end
    if relax(form_spec).submit then
        submit_form(form, type(form_spec.submit) == "number" and relax(form_spec).submit or 0)
    end

    return true
end
```

This also evaluates the functions only when they're needed, so we avoid unnecssary `popen`-ing. I think we still need closures for something like `cmd`, but since those now work, would this be an OK approach?

**Comment by aidanholm** [comment]
Looks fine, though I'd rather have it in a separate function that is called on the formspec before calling apply. Instead of using metatables I'd prefer a depth-first traversal and conversion approach; this ensures that each function is evaluated only once:
```lua
local function traverse (t)
   if type(t) == "function" then return traverse(t()) end
   for k, v in pairs(t) do t[k] = traverse(v) end
   return t
end
```
Then in `formfiller_fill`:
```lua
if apply(form, traverse(form_spec)) then ... end
```

**Comment by gleachkr** [comment]
It looks a little easier to modify the logic inside of `apply` so as to check the `attrs` and then abort on match failure (without having called the functions in the `input_spec`) with the metatable approach. I can tweak it a little to avoid having anything be called more than once. Or I could get rid of the metatables and try traverse-convert, but it looks like that would require tweaking `apply` more extensively, to avoid calling functions after a match failure.

Preference?

**Comment by aidanholm** [comment]
I was suggesting editing as below:
```lua
    -- Map of attr -> value that form has to match
    local attrs = {}
    for _, v in ipairs({"method", "name", "id", "action", "className"}) do
        attrs[v] = traverse(form_spec[v])
    end
    if not element_attributes_match(form, attrs) then
        return false
    end
    traverse(form_spec)
```
That is, convert the attr fields first, then check for a match, then convert the whole thing.

**Comment by gleachkr** [comment]
OK, I see the idea. But if e.g. `form _spec["id"]` is a function, won't it end up being called twice here? Once on the first traversal and again on the second? Sorry if I'm missing something.

**Comment by aidanholm** [comment]
Ah right:
```lua
 for _, v in ipairs({"method", "name", "id", "action", "className"}) do
     attrs[v] = traverse(form_spec[v])
+    form_spec[v] = attrs[v]
 end
```

**Comment by gleachkr** [comment]
OK, looks good. I'll start on a PR.

**Comment by aidanholm** [comment]
Implemented with merge of PR https://github.com/luakit/luakit/pull/385!
