### ISSUE TITLE
Domain props zoom affects image only display

### ISSUE THREAD

**Issue by xkpd3** [luakit/luakit#387]
Hi,

I have set the following domain props to generally zoom in by factor 1.4.

```
globals.domain_props = {
  ["all"] = {
    enable_webgl               = true,
    zoom_level                 = 1.4,
  }
}
```

When I now open an image directly from an URL. Like `www.example.com/image.png`, the image itself is also zoomed in by factor 1.4.

Expected result: Websites are zoomed in, but images are fit into the screen. When you click on the image it zooms to 100% image size. If you click again, it goes back to fit into the screen area.

Observed result: Websites are zoomed in. Images are also zoomed in when they should fit into the screen. Clicking on the image goes to 140% of the exact image size.

**Comment by aidanholm** [comment]
I can reproduce this.

This will be tricky to fix properly.
 - `domain_props` only understands domains.
 - `image_css` can set the zoom to 1 on image pages, but won't know how to restore the old value when leaving the image page.
 - `domain_props` and `image_css` will race to set the zoom, on the "committed" load status. So a naive fix would change behavior depending on the order you loaded modules in.

**Comment by xkpd3** [comment]
Is it possible to restrict domain_props to text-type content?
What about something like URL props based on a regular expression?

```
globals.url_props ~= {
  [".*\.png$"] = {
    zoom_level  = 1,
  }
}
```

**Comment by aidanholm** [comment]
I've been thinking for a while about having multiple sources for settings like this; the main source would be for user settings, and then modules would be able to add their own customizations, with higher/lower priority. Then, when resolving a setting to a value, all the sources get merged based on that priority.

I think that this would be a more robust solution. The `image_css` module would provide a high-priority overlay that forces `zoom_level` to be 1 when an image is shown, overriding whatever the user or other plugins have set.

Such a system would not just be limited to domain_props. It'd be necessary to carefully consider the possible use-cases to design it correctly, and it'll take some time. But it could also provide a lot of new flexibility. For example, some users prefer to have all settings in a `settings.cfg` file, and then modify their config with `:set foo = bar` commands. This would be possible with a `settings.lua` module that has its own overlay.

**Comment by aidanholm** [comment]
I added a workaround for this, at a80a68cf; let me know how it goes!

**Comment by xkpd3** [comment]
This works perfectly fine for me. Thank you very much!

You say it's a workaround. So I leave it up to you to either close the issue or keep it open as reminder.

**Comment by aidanholm** [comment]
Glad to hear; I'll close it then. It's a workaround in that the `image_css` module is aware of the `domain_props` behavior and avoids causing the issue, rather than them both using some better API that hides those details and does module priorities or something. But it's ok for now.
