### ISSUE TITLE
website should be a separate repo

### ISSUE THREAD

**Issue by DanielFGray** [luakit/luakit#390]
Since this org exists solely for this project, I think it would be ideal to create a `luakit.github.io` repo so the docs and such are available at https://luakit.github.io rather than having to append the project name again to the url.

Alternatively, since I imagine there is some build task happening that auto-generates docs which might be difficult to de-couple from the code, creating that repo with nothing but a redirect to the correct site would also be helpful.

**Comment by aidanholm** [comment]
Ok, it's moved!
