### ISSUE TITLE
Move readline bindings into separate module

### ISSUE THREAD

**Issue by aidanholm** [luakit/luakit#393]

**Comment by DanielFGray** [comment]
most emacs-y readline bindings use C-u to clear the line and add it to the yank ring, and then use C-y to paste the last thing from the yank ring

**Comment by aidanholm** [comment]
Like this? https://www.gnu.org/software/bash/manual/html_node/Readline-Killing-Commands.html

**Comment by aidanholm** [comment]
This one's done, at 210ce606
