### ISSUE TITLE
website notifications

### ISSUE THREAD

**Issue by DanielFGray** [luakit/luakit#397]
[the docs](https://webkitgtk.org/reference/webkit2gtk/unstable/WebKitNotification.html) make it seem fairly straight forward to add a [request](https://webkitgtk.org/reference/webkit2gtk/2.17.5/WebKitNotificationPermissionRequest.html) for pages to enable notifications

**Comment by aidanholm** [comment]
### Implementation guidelines

- Wrap WebKitWebView's `“permission-request”` signal, and emit a signal of the same name on the `webview` widget.
  - The permission can be represented as a table with a `type` field indicating the request type: `{ type = "notification-request" }`.
  - No need to wrap all possible permission request types; just notifications will do for now.

- Wrap WebKitWebView's `“show-notification”` signal, and emit a signal of the same name on the `webview` widget.
  - It's unclear from the WebKit docs how long WebKitNotification objects live for; you can call `close()` and `clicked()` on them, which suggests that you can store a reference to them. TODO: grep epiphany source.
  - If they have their own lifetime (i.e. not plain-old-data) they need to be wrapped in a clib class.

**Comment by aidanholm** [comment]
@DanielFGray you can now enable notifications for websites with the following:
```lua
webview.add_signal("init", function (view)
    view:add_signal("permission-request", function (v, type)
        if type == "notification" then return true end -- Might want to check v.uri too
    end)
end)
```

**Comment by Tonus1** [comment]
Sorry for the necro :
even if I love luakit, I still do not understand well everything...
where shall I add the code ? would it be pipe automagically to my notification manager (dunst) ?
Thank you for your help !

**Comment by aidanholm** [comment]
Hi @Tonus1, no worries.

That code should go in your `~/.config/luakit/rc.lua` above the ` -- End user script loading -- ` line.

This code just automatically grants permission to send notifications **to all websites**. Webkit should use the standard notification system, so dunst should work fine.
