### ISSUE TITLE
How to change website fonts?

### ISSUE THREAD

**Issue by commagray** [luakit/luakit#406]
Sorry for silly and fully useless issue, but I really don't get it.

I'm new for this browser, and I need to force-select default font aliaces for websites. In all configs hosted on GitHub used deprecated `user_stylesheet_uri` in `domain-props`, but now it's `styles.detect_files` and I don't know how to correct use it.

Can you give an example, please?

P.S.
Maybe adding examples in documentation will be little bit useful for ponyheads like me, neigh?

**Comment by xkpd3** [comment]
Hi,

It is relatively simple. Create folder `.local/share/luakit/styles` in your home directory.

Then create a css file - like `forcefont.css`
```
@-moz-document regexp(".*") {
  html {
     font-family: Arial 12 important!;
  }
}
```

The snipped is untested, but you get the idea.

Best Regards,
Stefan

**Comment by commagray** [comment]
Thanks! <3

**Comment by aidanholm** [comment]
Thanks for the question! I'll add some examples to the docs; they're still a little spartan, I'm afraid.

**Comment by aidanholm** [comment]
I've improved the styles docs and added a section to the migration guide at 4e339c34; I'll go ahead and close this, but feel free to ask any more questions you have!

**Comment by ghost** [comment]
Is there any way I can set the sans serif font, the serif font and the monospaced font using this method ?

**Comment by aidanholm** [comment]
The [domain_props](https://luakit.github.io/luakit/docs/modules/domain_props.html) module has a bunch of `foo_font_family` properties; you can set those in the `domain_props.all` table.

**Comment by ghost** [comment]
Those don't seem to work, it's like this right ?

default_font_family = "xos4 Terminus",

**Comment by aidanholm** [comment]
It should be exactly the same as CSS, I believe.
Re your question on IRC, there's a slight difference; a userstyle will override the font choice for a website, while these properties will define the default property, used for `sans-serif`, `serif`, etc. font families in CSS.
