### ISSUE TITLE
Follow mode: add site-specific quirks

### ISSUE THREAD

**Issue by xkpd3** [luakit/luakit#407]
Here on Github, we have some flyout popup javascript menus. That are not marked with a hint.

Steps to reproduce: Go to your user profile -> Repositories -> Try to change the type or language via hints.

![luakit](https://user-images.githubusercontent.com/663776/28927496-015b711a-786b-11e7-9544-bb997fd4d11f.png)

**Comment by aidanholm** [comment]
Right, and it also happens with the issue label menu. It's because they're not clickable elements, but divs with event handlers attached somewhere. The modern web strikes again.

Should be easy enough to add a site-specific workaround to follow mode.
