### ISSUE TITLE
Command mode: shift-tab unfocuses input bar

### ISSUE THREAD

**Issue by aidanholm** [luakit/luakit#414]

**Comment by aidanholm** [comment]
Fixed at e5f1d320

**Comment by nmeum** [comment]
Could you explain the reason for this change and is there any easy way to revert this from `rc.lua`?

I actually quite like the Tab binding provided by gtk. For instance when logging into my GitHub account I just enter my username press tab and enter my password afterwards, which is quite convient imho.

**Comment by aidanholm** [comment]
This commit should not affect tabbing between form fields; tab currently works as expected in insert mode. Do you mean you use `:open` and enter your username to trigger auto-completion, and then press tab to focus the password field in the webview?

The purpose of this commit was to prevent those bindings from switching the GTK widget focus, which is separate from the form field focus. The GTK widget focus has to be kept in sync with luakit's mode setting state for the UI to work properly.

**Comment by nmeum** [comment]
> This commit should not affect tabbing between form fields; tab currently works as expected in insert mode.

It doesn't seem to work here with luakit c5328c22 on OpenBSD. When I focus the username form field on https://github.com/login luakit goes to insert mode, I enter my username and press tab afterwards (while still in insert mode) but nothing happens and luakit doesn't focus the password form field as expected. However, when I comment out the lines introduced by this change it works as expected.

Not sure what's causing this maybe it is an issue with my local config if you can't reproduce this.

**Comment by aidanholm** [comment]
Ok, that definitely sounds buggy. There may have been some bugs fixed since that release, since there's been a lot of work on `develop` in the meantime, and we're planning a release soon. So I'd suggest trying out a recent `develop` build, and also trying with the default config (e.g. `luakit -c /etc/xdg/luakit/rc.lua`); if neither of those fixes it please let me know.
