### ISSUE TITLE
Tests always fail with DEVELOPMENT_PATHS=0

### ISSUE THREAD

**Issue by SolarAquarion** [luakit/luakit#419]
PASS style/test_widgets / test_widgets_use_macros
PASS style/test_common / test_no_globalconf_in_common
PASS style/test_source_format / test_vim_modeline
PASS style/test_source_format / test_lua_module_uses_M
PASS style/test_source_format / test_header_comment
PASS style/test_source_format / test_no_trailing_whitespace
PASS style/test_source_format / test_include_guard
PASS style/test_source_format / test_no_tabs_in_indentation
PASS style/test_source_format / test_lua_module_functions_are_documented
PASS style/test_source_format / test_lua_header
PASS style/test_documentation / test_module_blurb_not_empty
PASS style/test_luacheck / test_luacheck
PASS async/test_lib_lousy_uri / test_lousy_uri_properties
PASS async/test_lib_lousy_uri / test_lousy_uri_parse
FAIL async/test_completion / 
  ./config/rc.lua:47: module 'log_chrome' not found:
  	no field package.preload['log_chrome']
  	no file './log_chrome.lua'
  	no file '/usr/share/luajit-2.1.0-beta3/log_chrome.lua'
  	no file '/usr/local/share/lua/5.1/log_chrome.lua'
  	no file '/usr/local/share/lua/5.1/log_chrome/init.lua'
  	no file '/usr/share/lua/5.1/log_chrome.lua'
  	no file '/usr/share/lua/5.1/log_chrome/init.lua'
  	no file '/usr/share/luakit/lib/log_chrome.lua'
  	no file '/usr/share/luakit/lib/log_chrome/init.lua'
  	no file '/tmp/luakit_test_RPPR4Y/config/luakit/log_chrome.lua'
  	no file '/tmp/luakit_test_RPPR4Y/config/luakit/log_chrome/init.lua'
  	no file '/etc/xdg/luakit/log_chrome.lua'
  	no file '/etc/xdg/luakit/log_chrome/init.lua'
  	no file './log_chrome.so'
  	no file '/usr/local/lib/lua/5.1/log_chrome.so'
  	no file '/usr/lib/lua/5.1/log_chrome.so'
  	no file '/usr/local/lib/lua/5.1/loadall.so'
WAIT async/test_image_css / test_image_css
  **
  ERROR:log.c:256:ipc_recv_log: assertion failed (n == 3): (4 == 3)
sh: line 1:  3237 Aborted                 (core dumped) env --ignore-environment - HOME=/tmp/luakit_test_DDSC4Y XDG_RUNTIME_DIR=/tmp/luakit_test_DDSC4Y/runtime XDG_DATA_HOME=/tmp/luakit_test_DDSC4Y/data XDG_CONFIG_HOME=/tmp/luakit_test_DDSC4Y/config DISPLAY=:1 XDG_CONFIG_DIRS= XDG_CACHE_HOME=/tmp/luakit_test_DDSC4Y/cache ./luakit -U --log=error -c tests/async/run_test.lua tests/async/test_image_css.lua 2>&1
FAIL async/test_memory_leaks / 
  ./config/rc.lua:47: module 'log_chrome' not found:
  	no field package.preload['log_chrome']
  	no file './log_chrome.lua'
  	no file '/usr/share/luajit-2.1.0-beta3/log_chrome.lua'
  	no file '/usr/local/share/lua/5.1/log_chrome.lua'
  	no file '/usr/local/share/lua/5.1/log_chrome/init.lua'
  	no file '/usr/share/lua/5.1/log_chrome.lua'
  	no file '/usr/share/lua/5.1/log_chrome/init.lua'
  	no file '/usr/share/luakit/lib/log_chrome.lua'
  	no file '/usr/share/luakit/lib/log_chrome/init.lua'
  	no file '/tmp/luakit_test_ZJDN4Y/config/luakit/log_chrome.lua'
  	no file '/tmp/luakit_test_ZJDN4Y/config/luakit/log_chrome/init.lua'
  	no file '/etc/xdg/luakit/log_chrome.lua'
  	no file '/etc/xdg/luakit/log_chrome/init.lua'
  	no file './log_chrome.so'
  	no file '/usr/local/lib/lua/5.1/log_chrome.so'
  	no file '/usr/lib/lua/5.1/log_chrome.so'
  	no file '/usr/local/lib/lua/5.1/loadall.so'
PASS async/test_clib_regex / test_regex_matches
PASS async/test_clib_regex / test_regex_with_no_pattern_fails
PASS async/test_clib_regex / test_module
FAIL async/test_undoclose / 
  ./config/rc.lua:47: module 'log_chrome' not found:
  	no field package.preload['log_chrome']
  	no file './log_chrome.lua'
  	no file '/usr/share/luajit-2.1.0-beta3/log_chrome.lua'
  	no file '/usr/local/share/lua/5.1/log_chrome.lua'
  	no file '/usr/local/share/lua/5.1/log_chrome/init.lua'
  	no file '/usr/share/lua/5.1/log_chrome.lua'
  	no file '/usr/share/lua/5.1/log_chrome/init.lua'
  	no file '/usr/share/luakit/lib/log_chrome.lua'
  	no file '/usr/share/luakit/lib/log_chrome/init.lua'
  	no file '/tmp/luakit_test_7PJT4Y/config/luakit/log_chrome.lua'
  	no file '/tmp/luakit_test_7PJT4Y/config/luakit/log_chrome/init.lua'
  	no file '/etc/xdg/luakit/log_chrome.lua'
  	no file '/etc/xdg/luakit/log_chrome/init.lua'
  	no file './log_chrome.so'
  	no file '/usr/local/lib/lua/5.1/log_chrome.so'
  	no file '/usr/lib/lua/5.1/log_chrome.so'
  	no file '/usr/local/lib/lua/5.1/loadall.so'
PASS async/test_lib_lousy_util / test_lousy_util_lua_escape
PASS async/test_lib_lousy_util / test_lousy_util_table_toarray
PASS async/test_lib_lousy_util / test_lousy_util_table_reverse
PASS async/test_lib_lousy_util / test_lousy_util_table_filter_array
PASS async/test_lib_lousy_util / test_lousy_util_table_join
PASS async/test_lib_lousy_util / test_lousy_util_table_copy_clone
PASS async/test_lib_lousy_util / test_lousy_util_table_isclone
RUN  async/test_lua_files_load_successfully / test_all_lua_files_load_successfulFAIL async/test_lua_files_load_successfully / test_all_lua_files_load_successfully
  tests/async/test_lua_files_load_successfully.lua:15: module 'lousy.widget.zoom' not found:
  	no field package.preload['lousy.widget.zoom']
  	no file './lousy/widget/zoom.lua'
  	no file '/usr/share/luajit-2.1.0-beta3/lousy/widget/zoom.lua'
  	no file '/usr/local/share/lua/5.1/lousy/widget/zoom.lua'
  	no file '/usr/local/share/lua/5.1/lousy/widget/zoom/init.lua'
  	no file '/usr/share/lua/5.1/lousy/widget/zoom.lua'
  	no file '/usr/share/lua/5.1/lousy/widget/zoom/init.lua'
  	no file '/usr/share/luakit/lib/lousy/widget/zoom.lua'
  	no file '/usr/share/luakit/lib/lousy/widget/zoom/init.lua'
  	no file '/tmp/luakit_test_N92B4Y/config/luakit/lousy/widget/zoom.lua'
  	no file '/tmp/luakit_test_N92B4Y/config/luakit/lousy/widget/zoom/init.lua'
  	no file '/etc/xdg/luakit/lousy/widget/zoom.lua'
  	no file '/etc/xdg/luakit/lousy/widget/zoom/init.lua'
  	no file './lousy/widget/zoom.so'
  	no file '/usr/local/lib/lua/5.1/lousy/widget/zoom.so'
  	no file '/usr/lib/lua/5.1/lousy/widget/zoom.so'
  	no file '/usr/local/lib/lua/5.1/loadall.so'
  	no file './lousy.so'
  	no file '/usr/local/lib/lua/5.1/lousy.so'
  	no file '/usr/lib/lua/5.1/lousy.so'
  	no file '/usr/local/lib/lua/5.1/loadall.so'
  Traceback:
  (1) tests/async/test_lua_files_load_successfully.lua:15 in function [anonymous]
PASS async/test_clib_sqlite3 / test_sqlite3_exec
PASS async/test_clib_sqlite3 / test_open_db
PASS async/test_clib_sqlite3 / test_compile_statement
PASS async/test_clib_sqlite3 / test_module
PASS async/test_clib_luakit / test_luakit
PASS async/test_clib_luakit / test_luakit_index
RUN  async/test_clib_luakit / test_website_data
  Error loading module '/usr/lib/mozilla/plugins/libfreshwrapper-flashplayer.so': libevent_pthreads-2.0.so.5: cannot open shared object file: No such file or directory
  Error scanning plugin /usr/lib/mozilla/plugins/libfreshwrapper-flashplayer.so, /usr/lib/webkit2gtk-4.0/WebKitPluginProcess returned 256 exit status
WAIT async/test_clib_luakit / test_website_data
  **
  ERROR:log.c:256:ipc_recv_log: assertion failed (n == 3): (4 == 3)
sh: line 1:  3558 Aborted                 (core dumped) env --ignore-environment - HOME=/tmp/luakit_test_U5GH4Y XDG_RUNTIME_DIR=/tmp/luakit_test_U5GH4Y/runtime XDG_DATA_HOME=/tmp/luakit_test_U5GH4Y/data XDG_CONFIG_HOME=/tmp/luakit_test_U5GH4Y/config DISPLAY=:1 XDG_CONFIG_DIRS= XDG_CACHE_HOME=/tmp/luakit_test_U5GH4Y/cache ./luakit -U --log=error -c tests/async/run_test.lua tests/async/test_clib_luakit.lua 2>&1
FAIL async/test_scroll / 
  ./config/rc.lua:47: module 'log_chrome' not found:
  	no field package.preload['log_chrome']
  	no file './log_chrome.lua'
  	no file '/usr/share/luajit-2.1.0-beta3/log_chrome.lua'
  	no file '/usr/local/share/lua/5.1/log_chrome.lua'
  	no file '/usr/local/share/lua/5.1/log_chrome/init.lua'
  	no file '/usr/share/lua/5.1/log_chrome.lua'
  	no file '/usr/share/lua/5.1/log_chrome/init.lua'
  	no file '/usr/share/luakit/lib/log_chrome.lua'
  	no file '/usr/share/luakit/lib/log_chrome/init.lua'
  	no file '/tmp/luakit_test_PBRI4Y/config/luakit/log_chrome.lua'
  	no file '/tmp/luakit_test_PBRI4Y/config/luakit/log_chrome/init.lua'
  	no file '/etc/xdg/luakit/log_chrome.lua'
  	no file '/etc/xdg/luakit/log_chrome/init.lua'
  	no file './log_chrome.so'
  	no file '/usr/local/lib/lua/5.1/log_chrome.so'
  	no file '/usr/lib/lua/5.1/log_chrome.so'
  	no file '/usr/local/lib/lua/5.1/loadall.so'
WAIT async/test_http_test_server / test_http_server_returns_file_contents
  **
  ERROR:log.c:256:ipc_recv_log: assertion failed (n == 3): (4 == 3)
sh: line 1:  3795 Aborted                 (core dumped) env --ignore-environment - HOME=/tmp/luakit_test_U1FP4Y XDG_RUNTIME_DIR=/tmp/luakit_test_U1FP4Y/runtime XDG_DATA_HOME=/tmp/luakit_test_U1FP4Y/data XDG_CONFIG_HOME=/tmp/luakit_test_U1FP4Y/config DISPLAY=:1 XDG_CONFIG_DIRS= XDG_CACHE_HOME=/tmp/luakit_test_U1FP4Y/cache ./luakit -U --log=error -c tests/async/run_test.lua tests/async/test_http_test_server.lua 2>&1
FAIL async/test_binds_api / test_binds_are_called
  tests/async/test_binds_api.lua:15: attempt to call field 'add_bind' (a nil value)
  Traceback:
  
PASS async/test_clib_soup / test_set_accept_policy
PASS async/test_clib_soup / test_set_cookies_storage
PASS async/test_clib_soup / test_soup
PASS async/test_clib_soup / test_set_proxy_uri
FAIL async/test_config / test__config_rc_loads_successfully
  ./config/rc.lua:47: module 'log_chrome' not found:
  	no field package.preload['log_chrome']
  	no file './log_chrome.lua'
  	no file '/usr/share/luajit-2.1.0-beta3/log_chrome.lua'
  	no file '/usr/local/share/lua/5.1/log_chrome.lua'
  	no file '/usr/local/share/lua/5.1/log_chrome/init.lua'
  	no file '/usr/share/lua/5.1/log_chrome.lua'
  	no file '/usr/share/lua/5.1/log_chrome/init.lua'
  	no file '/usr/share/luakit/lib/log_chrome.lua'
  	no file '/usr/share/luakit/lib/log_chrome/init.lua'
  	no file '/tmp/luakit_test_OPOK4Y/config/luakit/log_chrome.lua'
  	no file '/tmp/luakit_test_OPOK4Y/config/luakit/log_chrome/init.lua'
  	no file '/etc/xdg/luakit/log_chrome.lua'
  	no file '/etc/xdg/luakit/log_chrome/init.lua'
  	no file './log_chrome.so'
  	no file '/usr/local/lib/lua/5.1/log_chrome.so'
  	no file '/usr/lib/lua/5.1/log_chrome.so'
  	no file '/usr/local/lib/lua/5.1/loadall.so'
  Traceback:
  (1) tests/async/test_config.lua:8 in function [anonymous]
WAIT async/test_basic / test_about_blank_loads_successfully
  **
  ERROR:log.c:256:ipc_recv_log: assertion failed (n == 3): (4 == 3)
sh: line 1:  3945 Aborted                 (core dumped) env --ignore-environment - HOME=/tmp/luakit_test_GZCH4Y XDG_RUNTIME_DIR=/tmp/luakit_test_GZCH4Y/runtime XDG_DATA_HOME=/tmp/luakit_test_GZCH4Y/data XDG_CONFIG_HOME=/tmp/luakit_test_GZCH4Y/config DISPLAY=:1 XDG_CONFIG_DIRS= XDG_CACHE_HOME=/tmp/luakit_test_GZCH4Y/cache ./luakit -U --log=error -c tests/async/run_test.lua tests/async/test_basic.lua 2>&1
RUN  async/test_module_binds_have_descriptions / test_module_binds_have_descriptFAIL async/test_module_binds_have_descriptions / test_module_binds_have_descriptions
  /usr/share/luakit/lib/lousy/bind.lua:448: attempt to index local 'b' (a nil value)
  Traceback:
  (1) tests/async/test_module_binds_have_descriptions.lua:36 in function get_mode_bindings_for_module
  (2) tests/async/test_module_binds_have_descriptions.lua:56 in function [anonymous]
PASS async/test_widget / test_widget_of_invalid_type_fails
PASS async/test_widget / test_webview_widget_privacy
PASS async/test_widget / test_bin_widget_set_child
Removing temporary directories
Stopping Xvfb

I think you need to add "log chrome"

**Comment by SolarAquarion** [comment]
I think you need to add the version of it in the build directory

**Comment by aidanholm** [comment]
Did you run tests with DEVELOPMENT_PATHS=1?

**Comment by SolarAquarion** [comment]
no

**Comment by aidanholm** [comment]
That's currently required, although I should fix that so it works with DEVELOPMENT_PATHS=0.

**Comment by lluixhi** [comment]
It's currently required to rebuild the entire package with DEVELOPMENT_PATHS=0 before testing them?
That wasn't the case in 2017.07.26 ...

**Comment by SolarAquarion** [comment]
you can build it and install one time without it and then build with D=0

**Comment by aidanholm** [comment]
Tests have always required DEVELOPMENT_PATHS=1, not 0.
I have a mostly complete fix for this, should be finished soon.

**Comment by aidanholm** [comment]
I've pushed a commit (1d5ae1d5) that fixes tests with DEVELOPMENT_PATHS=0; there may be a few errors (failure to open image files), but those are relatively harmless and shouldn't cause the tests to fail.

**Comment by lluixhi** [comment]
Thanks :)

**Comment by aidanholm** [comment]
Ok, this issue should be completely fixed now. @lluixhi I see you're packaging luakit for gentoo; thanks and let me know if there's any way to make that easier :)
