### ISSUE TITLE
Changing DOCDIR breaks :help

### ISSUE THREAD

**Issue by ghost** [luakit/luakit#421]
I'm changing DOCDIR from "luakit/doc" to "doc/luakit", this breaks the in-application help in the 2017.08.10 release.

In general, on FreeBSD, all application documentation should go to `$PREFIX/share/doc/$PROGRAM/`.

Is this a bug or is DOCDIR not meant to be changed in future?

[EDIT] To be more accurage, only the ApiDocs are affected. The main help page and the Introspector are working.

**Comment by aidanholm** [comment]
That makes sense. The API docs read the installed docs from the file system, with a hardcoded path relative to the installation directory.

Probably the only way to fix this is to add `luakit.docs_paths`.

**Comment by aidanholm** [comment]
Should be fixed at c32dc344

**Comment by ghost** [comment]
Works! Thanks!
