### ISSUE TITLE
How to change about:blank page to custom local HTML file ?

### ISSUE THREAD

**Issue by mensurdurakovic** [luakit/luakit#425]
Since all wiki links are broken, I have no other way than this to ask question in title. 

I have custom local HTML page that basicly shows one picture in full height and width inside body and I want to show that page instead of dull white color. 

I tried to google solution I found nothing useful. Please help and thanks in advance!

**Comment by aidanholm** [comment]
Hi, thanks for asking!

There's built-in support for doing that, sort of: the `newtab_chrome` module will display the HTML file at `~/.local/share/luakit/newtab.html`, and it can be set to open on new tabs; this is what I do. There are some problems using `about:blank`, which is why this uses a different URL. See https://luakit.github.io/luakit/docs/modules/newtab_chrome.html for more info, and let me know if you need more help!

**Comment by mensurdurakovic** [comment]
I am using older version of luakit and I don't want to update it, because all users use that specific version and I have no way to update it for all of them. 

I managed to change background color with this piece of code I wrote inside webview.lua file:

```
webview.init_funcs.set_dark_about_blank = function (view, w)
    view:add_signal("navigation-request", function (_, uri)
        if uri == "about:blank" then
            view:load_string("<html><body bgcolor='#000000'></body></html>", "about:blank")
            return true
        end
    end)
end
```
but it is not enough because I doesn't load my picture, I have tried to change load string to

`"<html><body><img style='position_fixed;top:0;left:0:width:100%;height:100%;' src='file://home/pi/pythonSignage/luakit_startup_page/qs.jpg'></body></html>"`

but it shows this message in console:

`** Message: console message: about:blank @1: Not allowed to load local resource: file://home/pi/pythonSignage/luakit_startup_page/qs.jpg`

I also tried add rights with chmod 777 to picture file, but no success. However when I change img src to some url it shows picture without any problems, but that doesn't fit me. Do you know what is causing this message to appear ?

**Comment by aidanholm** [comment]
Hooking onto that signal should also mostly work. That error message is WebKit preventing you from accessing local files on the `file:///` domain; to fix that you need to either upload your images somewhere, or convert them to data URIs and copy the data URI directly into the string you load with `load_string()`.

Separately; I strongly recommend you update to the latest version. Unless you are only accessing trusted files on a local network, you're extremely vulnerable and will be infected with viruses/ransomware sooner or later. The older version is also unstable and crashes all the time. This repository only supports reasonably recent versions of luakit, and I can only really help with problems with the new luakit, although I'm happy to help you upgrade. If installation problems are preventing you from upgrading, you can also run luakit directly without installing.

**Comment by mensurdurakovic** [comment]
Thank you for response, do you have any example how to convert my picture file into data URI and set it into load_string() function ?

**Comment by aidanholm** [comment]
You could try this one: http://dataurl.net/ It has a page on how to use it, and a converter; I have not tried it myself though.

**Comment by mensurdurakovic** [comment]
Thank you, I will try!
