### ISSUE TITLE
suggestion: use a customized webkit to overcome it's limitations

### ISSUE THREAD

**Issue by hippi777** [luakit/luakit#427]
i've tried to automatize a game (lol, took too much time and addictive X'D) but i couldn't set origin header for my script i wrote into the console (in firefox, because i still didn't move, but i think webkit have the same limits)

so to set headers, secure cookies and overcome whatever other limitations would be very good, and it would turn to be a real haxxor browser, and it would gain more users as well

maybe it could be an option in the makefile, but it depends on the level of customization, once it won't be good to compile without the custom webkit...

i think the point of self compiled webkit is enough to open up Pandora's box, then the rest will happen, but i still have to learn luakit first, so there's no hurry for this from my side, but i think the potency is great and much visible :) so i'm just leaving this here for the future

**Comment by SolarAquarion** [comment]
This browser uses webkit2gtk which is a pretty big project.  I don't think changing the Makefile would be good enough.  It would be absolutely massive undertaking which isn't good enough

**Comment by aidanholm** [comment]
It's an interesting idea, but I don't think it's going to happen, for a few different reasons:

1. Luakit has only a handful of regular contributors; like @SolarAquarion says, there's no way we could hope to patch our own copy of webkit and keep it up-to-date. Plus, we'd need to be responsive with security issues.
1. Luakit uses whatever webkit2gtk libs are on the system. So there's no need for a build step; users can just install a patched version of webkit2gtk. If they want, they can muck about with `config.mk`, of course.
2. Luakit is supposed to provide a consistent API surface to Lua modules, and it's not easy to do that if you have to support all kinds of patches.
3. If there are missing APIs, the ideal solution for this is to submit patches to WebKit. That way the work only has to be done once.

**Comment by hippi777** [comment]
@SolarAquarion:
fine, but in case of interest that could be the entrance point, i don't know if via environment variables oe whatever there could have a way around webkit2gtk and only modify webkit, but in worse case the whole stack can be compiled, maybe a separated makefile that can be triggered via options and targets can isolate that from those who don't need that...

@aidanholm:
yes, i know, there are no much people involved and it wouldn't be an easy task, just as well, as there should be maintenance and hardcore security reviews, just the idea is much valuable...

maybe a curl extension could do the trick, as curl can do anything, that can be a work for one time, without worry for security in general, but then the question is if webkit is abled to do only the rendering and js side without the networking... but i think not, because the full picture is more complicated, so i think everything is wired alltogether, and even if it could make rendering, js and whatever, it wouldn't make a living resoult, like xhr and communicate with a server with the hacked resources, or with curl... but maybe...

i can let go the topic anyway, but maybe you can get the idea any time for a good possibility, but i'm not familiar with webkit and webkit2gtk, so i kinda reached my limits for now in this topic...

and thx 4 all the info and whatever! :)

**Comment by SolarAquarion** [comment]
WebKit2Gtk source code is the only way to modify WebKit. Curl can't do
everything

**Comment by aidanholm** [comment]
@szbnwer As you say, webkit is very interconnected and it's not feasible to replace individual components. You mentioned setting headers; it wouldn't be part of luakit, but you could always run a custom proxy on localhost that modifies requests/responses as you wish.

**Comment by hippi777** [comment]
thx! that sounds good, probably wireshark can do the trick for https sites, it's maybe still not that easy task, but way much easier than my previous idea, aaand wireshark is lua friendly just as well :D
