### ISSUE TITLE
Label, entry heights increase slightly with asian characters

### ISSUE THREAD

**Issue by aidanholm** [luakit/luakit#437]
E.g. tabs, menu items, input bar will have different heights with text "Hi" and text "哈"

**Comment by taobert** [comment]
I can't get this to manifest with current `develop`,
but i may have misunderstood the problem.
 
I've looked at menu items (using `tablist` and `tabgroups` plugins),
tabs (vertical and horizontal), and the command/search input bar.
For tabs, i looked for differences between `http://en.wikipedia.org`
and `http://zh.wikipedia.org`.
For `tabgroup` name, and input bar i used "Hi" and "哈".


Am i mis-testing (wrong test case; eyes not good enough), 
or is this now resolved?
Is this possibly font dependant?

**Comment by aidanholm** [comment]
Thanks for looking into this. I had a local patch to work around, but have removed it and this issue seems to no longer be present, so I'll close this issue. It might be font-dependant though; difficult to tell.
