### ISSUE TITLE
adblock: subscriptions state for disabled lists is mangled

### ISSUE THREAD

**Issue by aidanholm** [luakit/luakit#439]
cc @xkpd3 

### Steps to reproduce
1. Have at least one adblock list enabled; start luakit
2. Open luakit://adblock/ and disable the list
3. Restart luakit
4. Open luakit://adblock/: list state and action are now incorrect

![adblock](https://user-images.githubusercontent.com/10691965/29249463-977485c0-8062-11e7-99da-6aeb8c81dd34.png)

**Comment by maca** [comment]
@aidanholm 

Thanks! that did it, the file was empty before.
