### ISSUE TITLE
Confused regarding keybindings

### ISSUE THREAD

**Issue by ghost** [luakit/luakit#444]
Due to the fact that I started with firefox vim addons before I was using vim/vi all the time I am now dependend on my muscle memory with J,K for switching tabs, d and u for scrolling half page down and up, and I need to change these before anything else.
How do I actually change keybindings ? Where can I find the functions for gt , gT ?

**Comment by aidanholm** [comment]
The easiest way to change keybindings is to use `modes.add_binds`. Here's an example snippet, for J and K:
```lua
modes.add_binds("normal", {
    { "K", "Go to previous tab.", function (w, o) w:prev_tab(o.count or 1) end },
    { "J", "Go to next tab.", function (w, o) w:next_tab(o.count or 1) end },
})
```
Add that to your `rc.lua`, before the "End user script loading" comment. Or, if you have a `userconf.lua` you can put it there. This will automatically clear any previous bindings for J and K, if you have any.

The functions for scrolling by half-page are here: https://github.com/luakit/luakit/blob/69a81d99890f436b15dc0130bc98fc3243ae8063/lib/binds.lua#L219
And the functions for gt, gT are here: https://github.com/luakit/luakit/blob/69a81d99890f436b15dc0130bc98fc3243ae8063/lib/binds.lua#L365

**Comment by aidanholm** [comment]
Re your message on IRC, you don't have to rebind the original function; making a new one will work just as well. I'm moving towards having modules expose bindable actions as part of their public API, but there's a lot of architectural changes planned and it's taking a while for everything to settle into place.

And don't worry about opening an issue, questions are welcome too :)

**Comment by ghost** [comment]
Ohh, that was easy. Thanks. I have a few questions:

+ is there any way I can block gifs from displaying ? For some reason my old cpu goes 40% on some and I don't like the sound of that fan.
+ does         hardware_acceleration_policy = WEBKIT_HARDWARE_ACCELERATION_POLICY_ALWAYS in per domain view properties actually do something ?
+ is there a way I can set the same rule on multiple sites instead of having something like:

            ["A"] = {
                enable_javascript = true,
        },
                ["B"] = {
                enable_javascript = true,
        },
                ["C"] = {
                enable_javascript = true,

+ I don't understand the 'Opening magnet: links with rTorrent', does it call mktorrent ? rtorrent can handle magent links as far as I know.

**Comment by aidanholm** [comment]
- You could block gifs from displaying with a userscript, or you could block anything with a gif MIME type from loading with the [mime-type-decision](https://luakit.github.io/luakit/docs/classes/widget:webview.html#signal-mime-type-decision) webview signal.
- That property is missing, but shouldn't be; I've opened #445
- There's nothing built-in, but you can always script it.
- That looks like a typo. I'll fix that, thanks.

**Comment by ghost** [comment]
Ok thanks, I pretty much have luakit the way I want it now.

**Comment by aidanholm** [comment]
You're welcome! Feel free to ask here or on IRC if you have any more questions :)

**Comment by aidanholm** [comment]
@ahsis BTW I've added the hardware acceleration property now, should work like this:
```lua
view.hardware_acceleration_policy = "always" -- or "on-demand" or "never"
```
