### ISSUE TITLE
Change versioning to major.minor.patch

### ISSUE THREAD

**Issue by aidanholm** [luakit/luakit#458]
### Pro
- Would better distinguish the nature of each release, relative to the one before it. 
   - Has at least some relationship with the changes made to luakit: dates are very arbitrary
   - Provides immediate indicator of API stability
- More familiar format: most software uses major.minor.patch

### Con
- May break version number comparison
  - @xkpd3, @SolarAquarion is this likely to cause packaging problems? I know Arch has the epoch system; not sure if that'd be necessary though.
- Non-zero cost of changing version scheme

**Comment by SolarAquarion** [comment]
I doubt that it will cause major issues.  I mean I do just do git describe
--tag .... Add an epoch=2 and everything will work

**Comment by aidanholm** [comment]
After discussion in `#archlinux` and confirming that a version switch won't cause major problems for packagers, the next release will be version 2.0.0.
