### ISSUE TITLE
globals.lua is deprecated - alternatives?

### ISSUE THREAD

**Issue by halocaridina** [luakit/luakit#468]
Hi Aidan,

Just upgraded to luakit 2017.08.10-94-gc9b4f92a via the AUR and noted the following when starting luakit at the commandline:

```
[    0.088189] W [lua/settings]: globals.lua is deprecated, and will be removed in the next release!
[    0.088231] W [lua/settings]: globals.default_window_size has a non-default value; to migrate, add the following:
[    0.088252] W [lua/settings]:   settings.window.new_window_size = 1920x1080
[    0.088560] E [core/common/lualib]: Lua error: attempt to index local 'meta' (a nil value)
                Traceback:
                (1) /usr/share/luakit/lib/settings.lua:87   in function S_set
                (2) /usr/share/luakit/lib/settings.lua:258  in function migrate_global
                (3) /usr/share/luakit/lib/window.lua:750    in main chunk
                (4) [C]                                     in function require         
                (5) /home/halocaridina/.config/luakit/rc.lua:40 in main chunk
[    0.088616] W [core/luah]: loading rc '/home/halocaridina/.config/luakit/rc.lua' failed, falling back...
[    0.021168] I [core/luah]: Loading rc: /etc/xdg/luakit/rc.lua
```

I noted in the release notes for the 2017-08-10 release that:

> It is no longer possible to override built-in luakit modules with Lua files in one's personal configuration directory.

and that globals.lua is no longer being sourced from rc.lua (the above came from me adding the code for calling it back to the latest version of rc.lua). From reading the docs, its not clear how one should go about migrating from settings in globals.lua to an alternative since attempts to transfer the globals.lua settings to a userconf.lua and calling it with a:

`require "userconf"`

in rc.lua weren't successful. 

**Am I missing something obvious? Otherwise, what is now the most appropriate way of configuring luakit?**

Thanks in advance for the assistance and for developing luakit. Its much appreciated.

In case it helps, here is the content of my globals.lua (apologies for the lack of code tags):

```
-- Global variables for luakit

local globals = {
    homepage            = "about:blank",
    scroll_step         = 40,
    zoom_step           = 0.1,
    max_cmd_history     = 100,
    max_srch_history    = 100,
    default_window_size = "1920x1080",
    vertical_tab_width  = 200,
    term                = "termite",

 -- Disables loading of hostnames from /etc/hosts (for large host files)
 -- load_etc_hosts      = false,
 -- Disables checking if a filepath exists in search_open function
 -- check_filepath      = false,
}

-- List of search engines. Each item must contain a single %s which is
-- replaced by URI encoded search terms. All other occurances of the percent
-- character (%) may need to be escaped by placing another % before or after
-- it to avoid collisions with lua's string.format characters.
-- See: http://www.lua.org/manual/5.1/manual.html#pdf-string.format
globals.search_engines = {
    archwiki       = "https://wiki.archlinux.org/?search=%s",
    aur99   = "https://aur.archlinux.org/packages.php?O=0&K=%s&do_Search=Go",
    duckduckgo     = "https://duckduckgo.com/?q=%s",
    github         = "https://github.com/search?q=%s",
    google         = "https://google.com/search?q=%s",
    imdb           = "http://www.imdb.com/find?s=all&q=%s",
    ncbi           = "https://www.ncbi.nlm.nih.gov/gquery/?term=%s",
    wikipedia      = "https://en.wikipedia.org/wiki/Special:Search?search=%s",
}

-- Set google as fallback search engine
globals.search_engines.default = globals.search_engines.google
-- Use this instead to disable auto-searching
--search_engines.default = "%s"

-- Per-domain webview properties
-- https://webkitgtk.org/reference/webkit2gtk/stable/WebKitWebView.html
-- https://webkitgtk.org/reference/webkit2gtk/stable/WebKitSettings.html
globals.domain_props = {
    ["all"] = {
        enable_webgl                 = true,
        zoom_level                   = 1.5,
        -- enable_smooth_scrolling      = true,
        -- zoom_text_only            = true,
        -- enable_scripts            = false,
        -- enable_plugins            = false,
    }, --[[
--    ["youtube.com"] = {
--        enable_scripts = true,
--        enable_plugins = true,
--    }, ]]
}

-- Cookie acceptance policy
-- Acceptable values: "always", "never", "no_third_party"
soup.accept_policy = "no_third_party"

-- Cookie storage location
-- Remove this line or set to nil to disable cookie persistence
soup.cookies_storage = luakit.data_dir .. "/cookies.db"

return globals

-- vim: et:sw=4:ts=8:sts=4:tw=80
```

**Comment by aidanholm** [comment]
Hey, and thanks for reporting!
The globals config module has been removed, in favour of a new settings API that does validation, among other things. There is a compatibility shim that is supposed to automatically load `globals.lua` on start up and tell you how to migrate (the "add the following" line), but you've hit a bug and this process is breaking. Thanks for pasting your globals file, that should make it much easier to debug

**Comment by halocaridina** [comment]
Perfect, glad to have helped ID that there was a bug breaking the process and that including the globals.lua file proved helpful. I'm happy to do any testing if need, just please let me know.

I've downgraded to luakit 2017.08.10-25-gc2c17415 in the meantime since setting zoom_level = 1.5 is a must-have option.

**Comment by ghost** [comment]
@halocaridina You can now set the zoom_level in `rc.lua` like this:
```
local settings = require "settings"
settings.webview.zoom_level = 150
```
In issue https://github.com/luakit/luakit/issues/440 are a few more examples/details.

**Comment by halocaridina** [comment]
@xkpd3 

Great, thanks for pointing out issue #440. I quickly read it and the changes look promising (and apologies for not doing a search and finding it before posting).

Given that #440 is closed, I assume that use of a settings.ini file is implemented in luakit 2017.08.10-94-gc9b4f92a and I can/should start translating/transferring my $HOME/.config/luakit/globals.lua to a $HOME/.config/luakit/settings.ini for calling via:

`local settings = require "settings" `

from $HOME/.config/luakit/rc.lua?

Cheers and thanks again.

**Comment by ghost** [comment]
No `settings.ini`. I have put all configuration into `rc.lua`
So both lines are in `rc.lua`. No other or additional file is involved.

**Comment by halocaridina** [comment]
OK, thanks for the clarification. I'll go over #440 again this weekend for additional details and layout a plan for organizing my `rc.lua` for minimizing the impact of future upgrades.

**Comment by ghost** [comment]
So - now as I have access to my home laptop, this is my full `rc.lua`. I have disabled some modules, so you may not want to blindly take this over.

Note that it is *not* loading `globals.lua`:
https://gist.github.com/xkpd3/07906cd31482a469c5e26b1957d66549

This is my settings block:
```
-- Settings (the commented ones do not [yet] work)
local settings = require "settings"
settings.window.home_page               = "luakit://newtab"
settings.window.scroll_step             = 40
settings.window.zoom_step               = 0.1
settings.webview.zoom_level  = 125
-- settings.window.max_cmd_history      = 80 
-- settings.window.max_srch_history     = 80
-- settings.window.default_window_size  = "800x600"
-- settings.window.vertical_tab_width   = 200
-- settings.window.load_etc_hosts          = false
-- settings.window.term = "termite"
-- settings.on["vimeo.com"].webview.enable_scripts  = true
settings.on["vimeo.com"].webview.enable_plugins     = true
-- settings.on["youtube.com"].webview.enable_scripts = true
settings.on["youtube.com"].webview.enable_plugins = true
settings.on["all"].webview.enable_webgl = true
settings.window.search_engines.duckduckgo = "https://duckduckgo.com/?q=%s"
settings.window.search_engines.github = "https://github.com/search?q=%s"
settings.window.search_engines.google = "https://google.com/search?q=%s"
settings.window.search_engines.imdb = "http://www.imdb.com/find?s=all&q=%s"
settings.window.search_engines.wikipedia = "https://en.wikipedia.org/wiki/Special:Search?search=%s"
settings.window.search_engines.default = settings.window.search_engines.duckduckgo
```

I tried to take over all configuration. Some of them are not working (yet?) or I chose the wrong object (windows/webview). Maybe @aidanholm can help here.

**Comment by aidanholm** [comment]
@halocaridina 
- There's no `settings.ini` yet; that's #461. #440 was mostly brainstorming and listing use-cases for the new API.
- You shouldn't make a personal `settings.lua`, as it's a core module; just `require` it and then set properties on it, like @xkpd3's example above. Some property names have changed slightly, but the migration shim should tell you what the new names are (when it's fixed!).
- The easiest way to keep your changes easily mergeable with changes to the default config is to keep all of your changes in a single `userprefs.lua` file. It's not a great solution, and I'm trying to think of some way to make this better.

@xkpd3:
 - `max_cmd_history`, `max_srch_history`, and `term` didn't do anything before the new API, so I just removed them. That's why they don't work.
- `default_window_size` is now `new_window_size`.
- `window.vertical_tab_width` is now `vertical_tabs.sidebar_width`.
- `load_etc_hosts` is right; what error do you get when you uncomment that?
- `enable_scripts` is now `enable_javascript`
- You can just do `settings.webview.enable_webgl = true`, unless you want to disable WebGL for specific domains. `settings.foo` is set once when the webview is created, but `settings.on["example.com"].foo` is set on every navigation.

**Comment by aidanholm** [comment]
@halocaridina That error should be fixed now! and @xkpd3 that might have been causing your problem with `load_etc_hosts`, so try that one again.

**Comment by halocaridina** [comment]
@aidanholm and @xkpd3 ,

Thank you both for your quick responses, they are much appreciated.

@aidanholm,

`luakit 2017.08.10-96-gf7cba0c4` appears to solve the globals.lua parsing issue since I was able to successfully start luakit and received the complete message of globals.lua being deprecated in the future and how to migrate options to the settings.lua API.  Thanks again.

@xkpd3,

Your rc.lua example was very helpful in structuring a `userprefs.lua` that I'm calling from `rc.lua` using:

`local userprefs = require "userprefs"`

near the end of the user script section. Appears to work very well and will be easy to merge with future updates to `rc.lua`. Thanks again.

@aidanholm,

The option:

`settings.vertical_tabs.sidebar_width                  = 200`

still appears to have issues since inclusion of it in `userprefs.lua` results in the following error:

`[    0.531666] E [core/common/lualib]: Lua error: attempt to index field 'vertical_tabs' (a nil value)`
`                 Traceback:`
`                 (1) userprefs.lua:9                          in main chunk`
`                 (2) [C]                                      in function require`
`                 (3) /home/halocaridina/.config/luakit/rc.lua:164 in main chunk`
`[    0.531686] W [core/luah]: loading rc '/home/halocaridina/.config/luakit/rc.lua' failed, falling back...`

Hope this helps and thanks again!!

Halocaridina

PS For completeness, here is my current, complete `userprefs.lua`:

-- Settings (the commented ones do not [yet] work)
local settings = require "settings"

settings.window.home_page                             = "about:blank"
settings.window.scroll_step                           = 60
settings.window.zoom_step                             = 0.2
settings.window.new_window_size                       = "1920x1080"
settings.window.load_etc_hosts                        = false
-- settings.vertical_tabs.sidebar_width                  = 200

settings.on["all"].webview.zoom_level                 = 140
settings.on["all"].webview.enable_webgl               = true
settings.on["youtube.com"].webview.enable_javascript  = true
settings.on["youtube.com"].webview.enable_plugins     = true

settings.window.search_engines.archwiki               = "https://wiki.archlinux.org/?search=%s"
settings.window.search_engines.aur                    = "https://aur.archlinux.org/packages.php?O=0&K=%s&do_Search=Go"
settings.window.search_engines.duckduckgo             = "https://duckduckgo.com/?q=%s"
settings.window.search_engines.github                 = "https://github.com/search?q=%s"
settings.window.search_engines.google                 = "https://google.com/search?q=%s"
settings.window.search_engines.imdb                   = "http://www.imdb.com/find?s=all&q=%s"
settings.window.search_engines.ncbi                   = "https://www.ncbi.nlm.nih.gov/gquery/?term=%s"
settings.window.search_engines.wikipedia              = "https://en.wikipedia.org/wiki/Special:Search?search=%s"

settings.window.search_engines.default                = settings.window.search_engines.google

**Comment by aidanholm** [comment]
@halocaridina Are you setting that option before you `require "vertical_tabs"`? You have to set it after you require the module.

**Comment by halocaridina** [comment]
@aidanholm,

Thanks for pointing that out. Lost track that I forgot to add the module load for vertical_tabs to the new `rc.lua`. Works like a charm now.

Looks like the eveything here has been covered so I'll close this issue.

Thanks again and the support is greatly appreciated.

Halocaridina

**Comment by aidanholm** [comment]
You're welcome! Always happy to help :)
