### ISSUE TITLE
Regression: default_zoom reset after webkit crash

### ISSUE THREAD

**Issue by ghost** [luakit/luakit#469]
This issue was previously fixed in https://github.com/luakit/luakit/commit/dafca7b0e5a30fda2c38a42120c39c8445aa24bb for issue https://github.com/luakit/luakit/issues/357 when the zoom domain props were used. With the new settings interface, setting: `settings.webview.zoom_level = 150` works fine, but a Webkit crash resets the zoom to 100.

So I assume Webkit related settings are not reapplied after a crash.

To reproduce:
- set `settings.webview.zoom_level = 150` via the new settings interface.
- make sure that there is no zoom_level domain prop set in the old `globals.lua`
- execute `:lua w.view:crash()` in luakit
- refresh the page

**Comment by aidanholm** [comment]
Thanks for reporting; should be simple to fix

**Comment by aidanholm** [comment]
This is actually a WebKit bug; the zoom should remain at 150%, and the `zoom_level` property stays at that value, but the actual rendered zoom level is reset. I added a patch which just reapplies the setting after a crash.
