### ISSUE TITLE
Login in gog.com doesn't work(JS error?)

### ISSUE THREAD

**Issue by schvabodka-man** [luakit/luakit#471]
Hello there. I've no clue why but when i'm attempting to login in gog.com just nothing happens(js enabled globally). it seems like there is some error in js engine

**Comment by aidanholm** [comment]
Hello; I've played around with it a bit; try setting `soup.accept_policy = "always"` in your `rc.lua`.
That fixes login and signup for me; the downside is that all cookies are accepted (the default is to ignore third-party cookies). There's no way to set this setting on a per-domain basis.

**Comment by c0dev0id** [comment]
I'm closing this issue now as it is old and the solution has been provided.
