### ISSUE TITLE
Make editor.editor_cmd = xdg_open the default

### ISSUE THREAD

**Issue by schvabodka-man** [luakit/luakit#473]
It seems like now it just opens terminal window and runs command in it. It would be really better if it will just run command instead of running it from terminal. For example using any editor that works as gui app get really hard because luakit opens two windows(terminal and editor itself) and it's a bit messy

**Comment by aidanholm** [comment]
You can set `editor.editor_cmd` to run a custom command: use `{file}` and `{line}` to include the file path and line number in your command.

The default does some autodetection to choose the right editor based on environment variables, but assumes a terminal editor; that could be improved. I'll mark this as a feature request.

**Comment by schvabodka-man** [comment]
That's still a dirty hack. Would be a lot better if it would be coded into luakit(with possibility to choose for example between gui and ui). Most emacs users work in x11(plus there is sublime and atom) so it would be great improvement

**Comment by aidanholm** [comment]
Hard-coding command strings for every possible editor and terminal emulator seems more hacky to me; they all have different command formats, and there are dozens of popular editors.

I forgot to mention before, but `editor` can be set to use `xdg-open` on the file to edit. This uses whatever editor you've set up, whether GUI or terminal-based. This doesn't allow starting editing at a specific line, though.

**Comment by schvabodka-man** [comment]
I was meant not a hard coding string for editors but running editor binary directly instead of launching terminal with command

**Comment by aidanholm** [comment]
Oh I see; I agree that opening a terminal window _and_ an editor window sucks. You could try setting the following:
```lua
local editor = require "editor"
editor.editor_cmd = editor.builtin.xdg_open
```
Perhaps this should be the default...

**Comment by schvabodka-man** [comment]
Ok, that worked. now it opens directly emacs without bullshit terminal window. You REALLY should make it default

**Comment by aidanholm** [comment]
Hm, yeah, I think you're right

**Comment by aidanholm** [comment]
This one's fixed
