### ISSUE TITLE
Is there a way to disable window decorations

### ISSUE THREAD

**Issue by ionor** [luakit/luakit#475]
Is there a way to tell luakit not to use the gtk decorators (more specifically - the titlebar). I know there exists patches for GTK itself to remove or make the CSD optional. But i would prefer not to do that.

The obvious reason for my question is that i am using a tiling wm and the decorators are just a waste of space.

**Comment by aidanholm** [comment]
Try adding this to your `rc.lua`:
```lua
window.add_signal("init", function (w) w.win.decorated = false end)
```

**Comment by ionor** [comment]
Works like a charm! Thank you so much :)

**Comment by aidanholm** [comment]
You're welcome :)
