### ISSUE TITLE
zoom_level setting migration issue

### ISSUE THREAD

**Issue by ghost** [luakit/luakit#479]
There is an issue with the zoom_level migration. I started luakit with an old configuration. This is the log output:

![2017-08-29 09_38_28-sdk wdfn34200346a_ _github_luakit](https://user-images.githubusercontent.com/663776/29809854-0af961f4-8c9e-11e7-93bb-f0ed61110d18.png)

In the old domain props settings, `zoom_level` has to be set as decimal value.
The new configuration requires percent. But the compatibility layer just takes the value over.

And indeed, my zoom level is now 1.25%:
![2017-08-29 09_43_36-luakit web browser - https___luakit github io_](https://user-images.githubusercontent.com/663776/29810013-8fe87580-8c9e-11e7-801d-2dfea82bd249.png)

**Comment by aidanholm** [comment]
Thanks for the patch! I'm not sure what you mean when you say "this does _not_ fix the zoom level".

BTW `settings.on[".gif"]` etc. won't work; it only matches domains. Also, the image view should do this automatically now.

**Comment by ghost** [comment]
Yes, I know `settings.on[".gif"]` was back from the time when I experimented with the image zoom levels.

EDIT: reg. "this does not fix the zoom level":
The fix fixes the output in the warning. So it displays `settings.webview.zoom_level = 125` instead of `1.25`. But the zoom setting itself is untouched and remains `1.25`. So the push requests only fixes the log, not the browser behavior.

**Comment by aidanholm** [comment]
I can't reproduce the browser behavior; with `default_zoom_level  = 125` in `globals.lua`, the conversion warning now shows the correct value ` ... = 125` and the browser is indeed at 125% zoom.

Do you mean the webview `zoom_level` property? While the `zoom_level` setting is a percentage (e.g. 125%), the widget property is still a factor (1.25).

**Comment by ghost** [comment]
I was talking about the domain prop zoom level, not the global one.

This one works fine (when not commented) and is translated correctly to `settings.webview.zoom_level = 150`
![image](https://user-images.githubusercontent.com/663776/29825853-e94ca664-8cd5-11e7-8133-2da2adbd77bd.png)

This one is the one I'm talking about here. It translates to `settings.webview.zoom_level` as well, but with value `1.25`
![image](https://user-images.githubusercontent.com/663776/29825897-0ea34422-8cd6-11e7-9d98-d2625eccb6b1.png)

Maybe this is a rare case which does not need to be fixed.

**Comment by aidanholm** [comment]
Ah! Thanks - fixed :)
