### ISSUE TITLE
Default settings can override custom settings (settings.lua)

### ISSUE THREAD

**Issue by hofheinz** [luakit/luakit#484]
First of all thank you for your work on this! This is a really useful project!

About the issue: in `settings.lua`, function `S_get`, there is a problem when the default value for a setting is non-nil, but a custom setting (added with `settings.webview.xy = false` or similar) is false. In that case, the return value of `S_get` (which is `tree[k] or settings_list[k].default`) evaluates to the `*.default` value. (I suppose this is not intended.)

I'm new to lua, and I'm not sure what the easiest way to repair this is. (Judging from a quick search, there appears to be no easy way to find out whether a table contains a certain key. Otherwise, the easiest way would probably be to have something like `if contains(tree,k) then return tree[k] else return settings_list[k].default end`.)

**Comment by hofheinz** [comment]
Sorry for the pull request, you were faster :-)

**Comment by aidanholm** [comment]
Thanks, and you're welcome :)

Thanks for reporting this; it's one of the few annoying subtleties in the Lua language. And your PR is a neater solution, so let's merge that instead

**Comment by hofheinz** [comment]
Great, thank you!
