### ISSUE TITLE
Refreshing adblock-blocked: page adds extra adblock-blocked: prefixes

### ISSUE THREAD

**Issue by aidanholm** [luakit/luakit#487]

**Comment by aidanholm** [comment]
Cannot reproduce

**Comment by jonas-schievink** [comment]
I can reproduce this on current master

**Comment by jonas-schievink** [comment]
Doesn't happen with all URIs, though. Try this one: https://www.google.de/aclk?sa=l&ai=&sig=&ctype=5&q=&ved=&adurl= (easylist should block it)

**Comment by aidanholm** [comment]
Thanks, yep, that one works for me
