### ISSUE TITLE
Open in editor doesn't work well with emacs daemon + emacsclient

### ISSUE THREAD

**Issue by schvabodka-man** [luakit/luakit#491]
For some reason when there is already one emacsclient opened open in editor do nothing(nothing happens). But if there is no working emacs clients it's opening new emacs client and everything works fine

**Comment by aidanholm** [comment]
What is your `editor.editor_cmd`?

**Comment by schvabodka-man** [comment]
Hello there. I fixed this problem by setting this variable to "emacsclient -c". In fact it's my $EDITOR variable of the system but for some reason luakit doesn't picking this variable up. I REALLY THINK that it's releated to shell i'm using(fish shell) which isn't compatible with bash and zsh. So you may notice this problem and maybe fix it

**Comment by aidanholm** [comment]
The editor is spawned with `luakit.spawn()`, a wrapper for `g_spawn_async`, which does not use the `$SHELL`, but uses `$PATH` to find the binary specified as the first argument; so I'm not sure why using fish shell would make a difference. I'll try installing fish and test it out.

The `editor.lua` module will use `$EDITOR` for some of the builtin `editor_cmd` values, but the new default is to use `xdg-open` instead.

With `$EDITOR` set to `emacsclient -c`, do you also get a terminal window opening when you edit a file from luakit?

**Comment by schvabodka-man** [comment]
No, i'm getting nice x11 emacs window. Maybe i fucked up somewhere or it's not a problem with fish shell, but setting editor_cmd manually helped me. I want to also test how it will work with EXWM, but that's for later

**Comment by aidanholm** [comment]
Ah, ok. I'll close this issue then if this problem is fixed; the default `editor_cmd` won't use `$EDITOR`, so this isn't a bug.
