### ISSUE TITLE
Compilation errors on OpenBSD

### ISSUE THREAD

**Issue by hofheinz** [luakit/luakit#495]
Compilation currently fails on OpenBSD because
 - OpenBSD uses a very old gcc version (GCC 4.2.1 on OpenBSD 6.1) that doesn't understand `-Wunused-errors`
 - for the same reason, `#pragma GCC diagnostic`s inside functions are not supported (this causes trouble in `widgets/webview.c`)
 - OpenBSD's grep is different from Linux's, and the expression `grep -q "^Lua 5\\.1\\|^LuaJIT" in config.mk does not work as expected (and hence, no Lua executables are found automatically).

This is easily fixed by making `-Wunused` errors and the `#pragma`s in `widget/webview.c` conditional on `uname_s!=OpenBSD`, and by slightly changing the RE in `config.mk`. (PR follows.) Once this is done, I experience no problems compiling and running under OpenBSD.

**Comment by aidanholm** [comment]
@qbit any thoughts on this? Are you experiencing any problems on OpenBSD?

**Comment by qbit** [comment]
@hofheinz are you on release or snapshots?

I think the `LUA_BIN_NAMES` change should go in.

Not super sure about the rest as i386 and amd64, the only two arches that luakit builds on currently (in snapshots), have switched to `clang` for base:

```
qbit@slip[0]:sys[BIG]λ cc -v
OpenBSD clang version 4.0.0 (tags/RELEASE_400/final) (based on LLVM 4.0.0)
Target: amd64-unknown-openbsd6.2
Thread model: posix
InstalledDir: /usr/bin
```

The  `#pragma`s will be ignored by `clang`, but at the same token, users would have to go out of their way to build with the old gcc.

**Comment by hofheinz** [comment]
@qbit I'm on release (6.1), and I did not use your patches from ports when compiling. Ah, I didn't realize OpenBSD is switching to `clang`, yes, this changes things of course. So how about I change the PR to just the `LUA_BIN_NAMES` thing? (Or would this be something better placed in the ports patches?)

**Comment by aidanholm** [comment]
I am happy to merge the `LUA_BIN_NAMES` (adding `luajit51` and the `-E` flag). I'd prefer not to mangle the code just to support old versions of GCC if an alternative compilation method is reasonably easy to obtain.

**Comment by hofheinz** [comment]
Sure, makes a lot of sense. The commit/PR is modified.

BTW: what would be an appropriate place to suggest a feature? (I have implemented a tiny feature, but I'm not sure if it's reasonably useful to others and desired.) Open an issue? Email? IRC?

**Comment by aidanholm** [comment]
Open an issue, usually, although IRC works as well :)

**Comment by hofheinz** [comment]
Ok, thanks!

**Comment by aidanholm** [comment]
I've added a note to the website, and merged the PR; thanks everyone!
