### ISSUE TITLE
Option to always show tab bar

### ISSUE THREAD

**Issue by hofheinz** [luakit/luakit#497]
Feature (?) proposal: most other browsers always show the tab bar (even if only one tab is open). The only way I could come up with to have this in `rc.lua` is to force a `w.tablist.widget.visible = true` upon each `page-removed` and `page-added` signal. (This seems not very elegant, though.)

Perhaps a more elegant way might be to have a `window.always_display_tabbar` setting. (Drawback: this might require adding a parameter like `always_visible` to the `tablist` widget constructor, and hence might mean slightly changing internal APIs.)

Is this a useful feature to have (as an additional setting)? If yes, I could offer a PR to that effect.

**Comment by aidanholm** [comment]
This seems interesting; I don't mind adding a setting for this, although I think  it would be better named `tablist.always_visible`.

Seems simple enough: register a setting, and query its value in `update_tablist_visibility()`; PR welcome and appreciated!

**Comment by hofheinz** [comment]
Great! What would you say is cleaner: have the `tablist` widget register and query that setting (currently `tablist` doesn't `require "settings"` yet), or have someone else (`window`?) pass that setting as a parameter to the `tablist` constructor?

**Comment by aidanholm** [comment]
I'd say `tablist` should do that

**Comment by hofheinz** [comment]
I could not find any `tablist` or full settings documentation, so I didn't add anything there. Also, perhaps it should be noted that `lousy.widget.tablist` must be explicitly loaded/`require`d to have the setting available. (It's not enough to load `lousy`.)

**Comment by aidanholm** [comment]
There are docs at luakit://help/doc/modules/lousy.widget.tablist.html but no settings docs yet. I imagine most people will be setting settings through luakit://settings/ (when that's merged) so I won't require full documentation yet.
