### ISSUE TITLE
Tabs as windows feature

### ISSUE THREAD

**Issue by schvabodka-man** [luakit/luakit#513]
Hi there. It would be really cool if there would be feature to open one window per one tab. There are lots of usecases for it(mostly switching tabs as regular windows with your wm and also for emacs users using Emacs WM they can treat their tabs in browser as regular Emacs buffers)

**Comment by jonas-schievink** [comment]
Related: #509

**Comment by aidanholm** [comment]
Yep, I think this is a dup of #509
