### ISSUE TITLE
styles plugin doesn't seem to work

### ISSUE THREAD

**Issue by curioussavage** [luakit/luakit#517]
I tried this theme https://github.com/StylishThemes/GitHub-Dark and It is not applied. Its possible that the issue is with their selector but I think thats unlikely since its popular and there are no bug reports in that repo. 

I will try with another stylesheet tomorrow to confirm.

**Comment by aidanholm** [comment]
What steps did you follow when trying to install this stylesheet?

While my version is probably slightly out of date, and has a few custom modifications, I have the same stylesheet (https://github.com/StylishThemes/GitHub-Dark/blob/master/github-dark.css), as a CSS file, installed as `~/.local/share/luakit/styles/github-dark.css`. It works fine.

**Comment by curioussavage** [comment]
I copied the themes css file to that same directory. When I run the `styles-list` command in the browser it shows the theme too.

**Comment by curioussavage** [comment]
I looked at the in browser logs also. Shows the stylesheet was found. No error messages or anything.

**Comment by aidanholm** [comment]
When you are on github.com, does the `styles-list` menu say that the stylesheet is Active or Enabled?

**Comment by curioussavage** [comment]
it says "enabled"

**Comment by aidanholm** [comment]
Looks like there's a bug in the regexp group. In the CSS file, change the first `regexp(...)` to `domain("github.com")` as a workaround.

**Comment by aidanholm** [comment]
Fixed at 438ad81! Thanks for reporting @curioussavage!
