### ISSUE TITLE
Architecture dependent file in /usr/share

### ISSUE THREAD

**Issue by groolot** [luakit/luakit#520]
We install an ELF binary in the `/usr/share` hierarchy, which is reserved for architecture-independent files.

Refer to [Filesystem Hierarchy Standard](http://www.pathname.com/fhs/pub/fhs-2.3.html) ([/usr/share : Architecture-independent data](http://www.pathname.com/fhs/pub/fhs-2.3.html#USRSHAREARCHITECTUREINDEPENDENTDATA)) for details.

**Comment by aidanholm** [comment]
Good catch; `luakit.so` should go in `/usr/lib/luakit`

**Comment by aidanholm** [comment]
Fixed! Sorry for the delay; @groolot does `luakit.so` also need +x?

**Comment by groolot** [comment]
No. `luakit.so` does not have to be `+x`.

We canr emove it from `Makefile`

**Comment by aidanholm** [comment]
It's installed with 644 permissions at the moment, so I'll leave it like that
