### ISSUE TITLE
Graphics corruption.

### ISSUE THREAD

**Issue by lslvr** [luakit/luakit#523]
Hello. I've discorvered a bug in luakit that fires when I open a message dialog on [google hangouts](https://www.talkgadget.google.com). As soon as I open it the graphics in the tab in wich the webpage is loaded gets corrupted as seen on the images. I also noticed this happens with `uzbl-browser`, so I don't know if this issue is from WebKit rather.

I'm running it on Arch Linux x86_64.

- `luakit --version`: d32762e
- webkit2gtk version is 2.16.6-1
- I use intel integrated graphics.

I wil provide any further information needed.

---

![2017-09-20-150351_1440x900_scrot](https://user-images.githubusercontent.com/17011090/30667884-9c233ea2-9e1e-11e7-8d6d-dcbe4e9baf0c.png)
![2017-09-20-150406_1440x900_scrot](https://user-images.githubusercontent.com/17011090/30667886-9c304dae-9e1e-11e7-86e9-d25a0eff55f9.png)
![2017-09-20-150544_1440x900_scrot](https://user-images.githubusercontent.com/17011090/30667885-9c2412aa-9e1e-11e7-951e-5b1d573f0fa8.png)
![2017-09-20-150613_1440x900_scrot](https://user-images.githubusercontent.com/17011090/30667887-9c4c266e-9e1e-11e7-8bb3-2b7f723b0a55.png)

**Comment by jonas-schievink** [comment]
This happened to me on YouTube a few times as well. I think it's a WebKit issue, though.

**Comment by lslvr** [comment]
@jonas-schievink I see. However, youtube runs smoothly. I don't se this anywhere else except for Hangouts.

**Comment by aidanholm** [comment]
Thanks for the report! As @jonas-schievink says, this is a WebKit bug, and not luakit-specific. I did a search of the WebKit bug tracker, but didn't come up with anything obvious.

**Comment by lslvr** [comment]
@aidanholm thanks for your fast responses. This is strange, because in chromium this doesn't happen. I know that chromium uses Blink, but as far as I know Blink is based on Webkit's code.
Maybe I can find some way to solve this. Thank you a lot for bringing luakit to life. A great app. ;D

**Comment by aidanholm** [comment]
Blink's code has diverged significantly from WebKit's, and the Blink team probably have more resources than the people working on the GTK Webkit port. You could try asking on the webkitgtk IRC channel.

You're welcome :) let me know if you have any other problems!
