### ISSUE TITLE
Source contains prebuilt javascript object

### ISSUE THREAD

**Issue by groolot** [luakit/luakit#532]
The source `tarball` contains a prebuilt (minified) `JavaScript` object: `usr/share/luakit/lib/jquery.min.js`.

Lintian please us to use `libjs-jquery`

**Comment by groolot** [comment]
This should be closed by the #455 and #515

**Comment by groolot** [comment]
Until th 2.0 release, if it is not soon enough, I will have to remove, for the debian package, the embeded jquery and depends our package to the libjs-jquery package.

**Comment by aidanholm** [comment]
jQuery has been removed

**Comment by groolot** [comment]
This is a great news! Bravo!
