### ISSUE TITLE
Version numbering to semver

### ISSUE THREAD

**Issue by groolot** [luakit/luakit#540]
When following the old numbering fashion I think this should be done better with semantic versioning.

As @aidanholm open the milestone 3 with a number `2.0.0`, I realize that it has been decided.

When do you think the new versioning will be effective? Because it will have an incidence on Debian numbering too.

**Comment by aidanholm** [comment]
The new versioning will begin with the next release. I'm not sure when exactly that will be; it was planned to be earlier this month, but I've been extremely busy and haven't had much time to work on luakit recently.

**Comment by groolot** [comment]
So I wait a bit for the next release for the Debian packaging.

**Comment by groolot** [comment]
To achieve a better integration into Debian archive, I finally decided to start from version v1.0 inside the develop branch.

The package is waiting for mentor: https://mentors.debian.net/package/luakit2

**Comment by groolot** [comment]
The Debian mentor said to me that it's not a good idea to restart numering, even change the name to luakit2.

Also, we continue numbering with 2017.08.10, etc. the luakit package in Debian.

Finaly, we do not have to include the `debian` diretory inside the `develop` branch. Everything have to be done inside the `debian/sid` branch.

more informations will come next few days I hope.

Having not much time to give to luakit project and the time Debian collaborators explain things make the integration very slow. I hope you're desperated.

**Comment by aidanholm** [comment]
Does debian have no way to handle version number restarts? That's unfortunate...
Split versioning could be doable, but it might be confusing

**Comment by groolot** [comment]
I would have say "I hope uo are NOT desperated !"

Version number restarting is possible, but the conitnuity is preferable. In Debian the new version number would be `1:2.x.y` or something like that. Because they prefer to not change the package name (say `luakit` to `luakit2`), the problem is intact.

They advise me to keep the changelog, the version numbering and the package name from the old version and make changes to maintain the visibility of the package and insure users to use the new one.

Even if things should be different, my involving level in Debian is not deep and strong enough to win the battle. By the way, I think that going their way isn't dammageable for the `luakit` project yet. Maybe next years things will be different and we will re-evaluate at time :)

**Comment by groolot** [comment]
Debian is handling the removal of the old luakit package. See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=893870 and https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=893863

This seems to be a reason that nobody wants to be the mentor of the package, even if it is now based on WebKit2.

I will follow the line to opportunisticaly propose this new luakit version.

Don't be bothered with this, I handle it slowly :)

**Comment by groolot** [comment]
Even if this is a no way for Debian acceptance, for the moment, I've opened a new "pre-release" named upon the release number that will be inserted in Debian in the close future.

Branching for debian is inside the project, but if you think that it's not correct, we can open a forked luakit repopsitory on Debian server.

By the way, I imagine that we can also provide the `.deb` that anyone can install in Debian sid without compiling.

**Comment by groolot** [comment]
What is your plan about releasing 2.0?

**Comment by aidanholm** [comment]
I'd like to get gleachkr's styles PR in first if possible. I believe there were some other minor issues that I'd planned on fixing as well.

**Comment by groolot** [comment]
No problem @aidanholm . I will wait for your merge and your 2.0 tag to begin packaging with epoch numbering. I opened a pre-release for Debian 2:2.0 to see if my workflow was correct, and it would be.

**Comment by groolot** [comment]
I've recently been contacted by Markus Demleitner from Debian to early integrates Luakit in the next Debian release. The current version integrated is the 2017.08.10.

I'm working with him to integrate the most recent version available and use the epoch mechanism. But our other correspondant Mattia Rizzolo respond that the epoch time should be 1: instead of 2: (see https://lists.debian.org/debian-devel/2019/01/msg00174.html).

I'm sorry to have'nt been so much comprehensive about the numbering for Debian. By the way there is a new repository clone specificaly designed for the Debian integration : https://salsa.debian.org/debian/luakit. I will commit there the modifications needed to achive the best luakit integration for the early next Debian release (in falling february).

**Comment by c0dev0id** [comment]
We can close this, right? Thanks for your work!
