### ISSUE TITLE
Latest Release - No Longer Loading in Hi-Dpi mode with zoom change in globals.lua

### ISSUE THREAD

**Issue by IWriteThings** [luakit/luakit#542]
What do I need to change in the rc.lua file to load in Hi-Dpi mode? The zoom method is no longer working on update.

**Comment by aidanholm** [comment]
Try adding `settings.webview.zoom_level = 200` to your `rc.lua`, or changing the value `webview.zoom_level` on the settings page (`luakit://settings/`)

**Comment by IWriteThings** [comment]
Adding `settings.webview.zoom_level = 200` to the `rc.lua` did not work.

However, changing the webview.zoom_level under the settings page functioned perfectly for me. Thanks a bunch! I am going to open a pull request to update the readme with this information for other users.

**Comment by IWriteThings** [comment]
I updated the readme file with a configuration update to help others who may run into this issue.

Thanks a bunch!
Aaron

**Comment by aidanholm** [comment]
Adding `settings.webview.zoom_level = 200` to `rc.lua` should work; was there any error message?

Thanks for the PR! I've added some minor requests
 \- Aidan

**Comment by IWriteThings** [comment]
There was no error message. It simply did not change the size of the text. I added the above text to my rc.lua and then I restarted the browser by closing it and reopening it.

**Comment by aidanholm** [comment]
Ah, I'm guessing you added it at the very end of `rc.lua`? You have to add it before the `End user script loading` comment, as the code after that opens the initial windows/tabs, and the setting is only reapplied after a page reload.
