### ISSUE TITLE
Embeded `markdown.lua` should instead be used from Debian package

### ISSUE THREAD

**Issue by groolot** [luakit/luakit#543]
When packaging for Debian, policy is to embed the less. `lib/markdown.lua` is the same as what [`mardown.lua` Debian package](https://anonscm.debian.org/cgit/pkg-lua/lua-markdown.git/tree/markdown.lua) provide, with the exception of the bf61b7c6ca9e6d5b76d12434be0edcbecc6b7f8d

This is the same kind of issue as the #532 and #534

**Comment by groolot** [comment]
Can we imagine a way to not embed it and depend on it (say in Debian)

**Comment by aidanholm** [comment]
Eh, I guess it'd be possible to use a packaged version but wrap it with a small shim in `lib/markdown.lua`

**Comment by groolot** [comment]
Due to the code modified against the packaged version, we have to use the embedded one for now.
