### ISSUE TITLE
Preserve private state for mouse binding

### ISSUE THREAD

**Issue by spaeps** [luakit/luakit#548]
Actually, by default, clicking with the middle mouse button on a link in a private tab follows the link in a non private tab, imho an unwanted behaviour.
https://github.com/luakit/luakit/blob/f2124f5f05d6052eb7482307eceb58f7d0e47da5/lib/binds.lua#L69
Preserving the private state by default would be better.
```lua
w:new_tab(uri, { switch = false, private = w.view.private })
```

**Comment by aidanholm** [comment]
Good catch, thanks!
