### ISSUE TITLE
eval_js errors on Alpine Linux

### ISSUE THREAD

**Issue by nmeum** [luakit/luakit#550]
On [Alpine Linux](https://alpinelinux.org/) the `eval_js` lua function seems to encounter an exception which can't be converted to a string. The following error message shows up when starting luakit:

```
[    0.336944] E [core/common/lualib]: Lua error: /usr/share/luakit/lib/tab_favicons.lua:update_favicon:37: Unknown JavaScript exception (unable to convert thrown exception object into string)
                 Traceback:
                 (1) [C]                                       in function assert
                 (2) /usr/share/luakit/lib/tab_favicons.lua:38 in function [anonymous]
```

Apart from that luakit starts at normal, however, when performing other activities such as scrolling more error messages show up:

```
[   58.132569] E [core/common/lualib]: Lua error: /usr/share/luakit/lib/lousy/widget/scroll.lua:update:18: Unknown JavaScript exception (unable to convert thrown exception object into string)
                 Traceback:
                 (1) [C]                                              in function assert
                 (2) /usr/share/luakit/lib/lousy/widget/scroll.lua:25 in function [anonymous]
```

These error messages are emitted by the function `luaJS_eval_js` from `common/luajs.c`, however, since I never worked with webkit2gtk before I wasn't able to debug this any further. Any idea how to debug this any further?

---

This bug was encountered with luakit 2017.08.10 and webkit2gtk 2.16.6. luakit was build with `USE_LUAJIT=1 DEVELOPMENT_PATHS=0` and `CFLAGS="-Os -fomit-frame-pointer"`.

**Comment by aidanholm** [comment]
I'm not sure why an exception couldn't be converted to a string. The JS used to update favicons and the scrolling widget is also very simple and shouldn't be throwing any exceptions.

Does this occur when opening `:javascript alert('test')`?

**Comment by nmeum** [comment]
> Does this occur when opening `:javascript alert('test')`?

Yes, it does and the alert box doesn't show up.

**Comment by aidanholm** [comment]
I should add that I can't reproduce this on Arch, but I'll try out an alpine VM when I have time

**Comment by nmeum** [comment]
I am currently assuming that this is a bug in the alpine linux webkit2gtk package and not a bug in luakit itself. So don't prioritize this to high, I will figure this out eventually...

**Comment by tawsi-melek** [comment]
@aidanholm, I have the same exact issue, but unlike @nmeum I'm not on Alpine Linux, but rather on Void Linux.
Both Alpine and Void use Musl as libc instead of Glibc, so that may be somewhat related to the problem, I guess.
I don't think webkit2gtk is to blame, since I can install things like surf and they work.
On my Arch partition, luakit works fine.

**Comment by aidanholm** [comment]
I'll try reproducing on a VM I guess

**Comment by aidanholm** [comment]
Sorry for the wait. I've reproduced this on both alpine and void. It does appear to be musl-related; I couldn't reproduce on a glibc void vm. I'm fairly sure it's caused by JSCore, but debugging it further is going to be tricky.

**Comment by nmeum** [comment]
> Sorry for the wait.

No problem, thanks for taking the time.

**Comment by ds6** [comment]
It appears JavaScript is completely broken when using musl... surf no longer works either.

**Comment by sevmonster** [comment]
It appears WebKit JS is completely broken when building with musl. surf, Midori, luakit, etc. are unable to use it.
https://github.com/voidlinux/void-packages/issues/5360

**Comment by sevmonster** [comment]
@nmeum thanks to TBK's and azarus' efforts on #alpine-linux for porting the Gentoo ebuild patchset over, I was able to get JS working. luakit runs just peachy (posting this using it in fact)
This should also fix any webkit2-based browser, like surf and Midori.

patch: [fix-glibc-js-and-alloc.patch](https://github.com/luakit/luakit/files/2191526/fix-glibc-js-and-alloc.patch.txt)
(FYI: add patch to sources in APKBUILD and run ```abuild checksum && abuild```)

**Comment by nmeum** [comment]
Ok, the patch indeed fixes this problem. I guess this can be closed then.
