### ISSUE TITLE
settings.* always resolves to default values

### ISSUE THREAD

**Issue by arcnmx** [luakit/luakit#554]
Example in rc.lua:

```lua
settings.set_setting("window.max_title_len", 200)
msg.warn(settings.window.max_title_len .. " vs " .. settings.get_setting("window.max_title_len"))
```
prints out `W [lua/rc]: 80 vs 200`

This makes most settings have no effect, whether set through `:set`, `luakit://settings` or `set_setting`. Only using `window.max_title_len = 200` works but doesn't persist and must always be executed on startup in rc.lua

**Comment by aidanholm** [comment]
This is because the `settings.foo.bar` API is for ephemeral settings only, and `set_setting()` sets a persisted setting (saved to disk). Reading a setting via `settings.foo.bar` should probably fall back to any persisted settings.

**Comment by aidanholm** [comment]
Thanks for reporting! Fixed :)
