### ISSUE TITLE
Select hints show more characters than necessary

### ISSUE THREAD

**Issue by arcnmx** [luakit/luakit#555]
Follow hints are often not truncated to the minimum unique hint length, sometimes showing more characters than are necessary to hit. For example, a hint may show `va` but actually trigger upon hitting `v` because no other hints displayed start with `v`.

This seems to only happen with custom charsets, I'm not currently able to reproduce with the default numbers. Currently reproducing this with label_maker of `s.sort(s.reverse(s.charset("asdfqwerzxcvjk")))` and the [github homepage](https://github.com).

**Comment by aidanholm** [comment]
You need to wrap `s.sort(...)` in `s.trim()`; I've changed the documentation example

**Comment by arcnmx** [comment]
Perfect thanks!

**Comment by aidanholm** [comment]
You're welcome :)
