### ISSUE TITLE
Follow hints that use enter_cmd do not work

### ISSUE THREAD

**Issue by arcnmx** [luakit/luakit#556]
Follow modes `;O` `;T` and `;W` all use `w:enter_cmd()` and are meant to put the browser into command mode with the target's URI prefilled. After hitting the keys to select a hint, command mode is never switched to and nothing seems to happen.

**Comment by aidanholm** [comment]
Thanks! Fixed :)

**Comment by arcnmx** [comment]
You are amazingly prompt at this, thanks!
