### ISSUE TITLE
Error on window close

### ISSUE THREAD

**Issue by arcnmx** [luakit/luakit#558]
The `window.close_with_last_tab` setting causes an error to trigger when using the window manager to close any luakit window:

```
E [core/common/lualib]: Lua error: attempt to index field 'tabs' (a nil value)
                 Traceback:
                 (1) /usr/share/luakit/lib/window.lua:471 in function close_win
                 (2) /usr/share/luakit/lib/window.lua:247 in function [anonymous]
```

Seems to not happen when closing the last tab and the window closes itself properly. Also does not happen with that setting `false`.

**Comment by arcnmx** [comment]
This error also seems to get triggered when using `:wq` with multiple luakit windows open.

**Comment by aidanholm** [comment]
Fixed; thanks!
