### ISSUE TITLE
Support for smart address bar (as Firefox, Chromium and etc already have)

### ISSUE THREAD

**Issue by petRUShka** [luakit/luakit#559]
Suppose I have `http://site.com/dashboard` in browser history.

If I type `site` or `dash` and then press `TAB` I get `http://site.com/dashboard`.
But if I type `site dash` and press `TAB` I don't get `http://site.com/dashboard`.

In all modern browsers both options are possible. But unfortunately second one isn't working in Luakit.

P.S. [Firefox help for address bar](https://support.mozilla.org/en-US/kb/awesome-bar-search-firefox-bookmarks-history-tabs) and [Chromium Omnibox](https://www.chromium.org/user-experience/omnibox).

**Comment by aidanholm** [comment]
Thanks for reporting; this has been fixed now. Note that fuzzy matching is now word-based. So `site dash` will work, `si da` will also work, but `sitedash` _won't_ work; there has to be at least one space between URI parts to be matched.
