### ISSUE TITLE
Follow error when element is partially off edge of page

### ISSUE THREAD

**Issue by arcnmx** [luakit/luakit#560]
Occurs when entering keys to follow an element that is mostly cut off by the edge of the window. An easy reproduction is the "Your Repositories" links on the github homepage, but also occurs with other items like the "Issues" tab at the top of this page if you resize the window just right. Resize the window horizontally so it's mostly cut off, then use `f` follow mode to try and click the link.

```
E [core/common/lualib]: Lua error: attempt to index local 'element' (a nil value)
                 Traceback:
                 (1) /usr/share/luakit/lib/follow_wm.lua:28 in function evaluator
                 (2) /usr/share/luakit/lib/follow_wm.lua:69 in function follow_hint
                 (3) /usr/share/luakit/lib/follow_wm.lua:92 in function [anonymous]
E [core/common/lualib]: Lua error: assertion failed!
                 Traceback:
                 (1) [C]                                     in function assert
                 (2) /usr/share/luakit/lib/select_wm.lua:455 in function changed
                 (3) /usr/share/luakit/lib/follow_wm.lua:114 in function [anonymous]

```

This seems to be caused by this calculation returning nil: `doc:element_from_point(r.left + r.width/2, r.top + r.height/2)`

**Comment by aidanholm** [comment]
Good catch; that function is a WebKIt API wrapper and defined to return `nil` if the point tested is not within the viewport. I can't remember why I added the clicking-the-center-element heuristic; possibly it was to fix sites that added click handlers to child elements or some such insanity. Thanks for the PR! I think it will work well enough :)

**Comment by aidanholm** [comment]
Good catch; that function is a WebKIt API wrapper and defined to return `nil` if the point tested is not within the viewport. I can't remember why I added the clicking-the-center-element heuristic; possibly it was to fix sites that added click handlers to child elements or some such insanity. I think your PR will work well enough :)
