### ISSUE TITLE
Error on make with latest develop

### ISSUE THREAD

**Issue by IWriteThings** [luakit/luakit#566]
When I ran make this morning to update luakit, I received the below error.

```
Makefile:64: recipe for target 'extension/clib/dom_element.o' failed
make: *** [extension/clib/dom_element.o] Error 
```

Have the requirements for luakit changed?

Looks like the error is 

```
extension/clib/dom_element.c:411:9: error: unknown type name ‘WebKitDOMClientRect’
         WebKitDOMClientRect* rect = webkit_dom_client_rect_list_item(rects, i);
         ^
```

**Comment by Sammyboy** [comment]
Which version of WebKitGTK do you have installed on your system? With version 2.18.0 it builds fine.

**Comment by aidanholm** [comment]
I had removed support for webkit 2.16, but have temporarily added it back while I ascertain whether it is still receiving security updates; try pulling and building again, and it should work.

**Comment by IWriteThings** [comment]
Works now. Thanks!
