### ISSUE TITLE
Luakit 2017.08.10 adblock subscriptions bad filepath 

### ISSUE THREAD

**Issue by curioussavage** [luakit/luakit#568]
I noticed in the logs that it said the subscriptions file is not there but the file path in the log has an extra /

![luakit-adblock](https://user-images.githubusercontent.com/7064600/31848060-2fedcf90-b5de-11e7-9868-362f7f8458bd.png)

**Comment by curioussavage** [comment]
submitted https://github.com/luakit/luakit/pull/569 to fix this

**Comment by aidanholm** [comment]
Thanks, merged!
