### ISSUE TITLE
New windows trash X selection

### ISSUE THREAD

**Issue by arcnmx** [luakit/luakit#577]
Under default configuration, windows opened with the `:winopen` command will automatically focus the status bar, selecting its whole contents (the newly opened URL). This replaces the current X selection/clipboard with the URL of any window opened.

**Comment by aidanholm** [comment]
Fixed! I'm not actually sure why it was getting focused automatically, and it only seems to happen with the URL label widget for some reason.

**Comment by arcnmx** [comment]
Yeah, I was trying to investigate what was causing it to get selected and couldn't find anything obvious. So quick, that did the trick!

**Comment by aidanholm** [comment]
I suspect it's one of GTK's "helpful" auto-focus features... I simply made the widget non-focusable. If it pops up again, I may make all labels non-focusable by default...

Glad it's working for now though :)
