### ISSUE TITLE
unable to login

### ISSUE THREAD

**Issue by deb75** [luakit/luakit#578]
Hello,

I am unable to login to some website with luakit, as an example coursera.org.

With firefox, when I try to sign in to this website, the current page freezes and darkens while a popup appears and asks me login/password.

With luakit, I just obtain the page freezing and darkening but no popup, so no possiblity to login.

This issue must happen on other websites with the same login page, how can I solve this ?

Thanks in advance for your help.

Regards

**Comment by aidanholm** [comment]
Hi!

Do you have Javascript disabled for coursera? With JS enabled, the site works normally. With JS disabled, I get what you describe: a dark page but no popup.

**Comment by deb75** [comment]
Hi!

Thanks for your fast answeer.

I do not master luakit yet :-) I do not know whether JS is disabled by default or not. I will check that.

Regards

**Comment by amosbird** [comment]
This may be related to some webkit bug. Can you try `epiphany` to see if login works fine there?
