### ISSUE TITLE
Open files with a name containing spaces.

### ISSUE THREAD

**Issue by ramboman** [luakit/luakit#579]
When I open a mhtml file containing a name with spaces in the command line, like this:

```
% luakit 'Git - Branches _ Atlassian Git Tutorial.mhtml'
[    0.041316] I [core/luah]: Loading rc: /data/users/user1/.home/.config/luakit/rc.lua
[    0.051951] I [lua/adblock]: found 0 filter lists
[    0.059716] I [lua/styles]: found 0 user stylesheets
[    0.060718] I [core/web_context]: Web process count: 4
[    0.676654] I [lua/webview]: Requested link: https://duckduckgo.com/?q=Git%20-%20Branches%20_%20Atlassian%20Git%20Tutorial.mhtml (text/html)
[    1.090243] I [lua/webview]: Requested link: https://duckduckgo.com/post2.html (text/html)
```

luakit sends the name into the default search engine, in this case Duckduckgo. 

When I execute this command in luakit:

`:tabopen Git - Branches _ Atlassian Git Tutorial.mhtml`

or 

`:tabopen file:///home/myusername/Git - Branches _ Atlassian Git Tutorial.mhtml`

The same thing also happens.

When I escape the space, but do not specify the file:// in front:

`:tabopen /home/myusername/Git%20-%20Branches%20_%20Atlassian%20Git%20Tutorial.mhtml`

I get the following message:

> Unable to load page
>
> A problem occurred while loading the URL http://home/myusername/Git%20-%20Branches%20_%20Atlassian%20Git%20Tutorial.mhtml
>
> Error resolving “data”: Name or service not known
>
> Proxy in use: system default

Only when I explicitly enter the full url with the file:// and escape the spaces that luakit is able to load the page:

`:tabopen file:///home/myusername/Git%20-%20Branches%20_%20Atlassian%20Git%20Tutorial.mhtml`

Escaping and writing the full path manually defeats the purpose of the fast browser relying on keyboard shortcut.

**Comment by aidanholm** [comment]
@ramboman Thanks for reporting this! It's been bugging me too, but is all fixed now. Sorry for the delay in fixing this one.
