### ISSUE TITLE
How can I move tabbar to the left

### ISSUE THREAD

**Issue by amosbird** [luakit/luakit#585]
This is what it looks like in qutebrowser when tabbar is on the left 

![img-2017-11-07-232805](https://user-images.githubusercontent.com/5085485/32501680-3f811034-c39e-11e7-8e16-c102d3372626.png)

Is it possible in luakit now? thanks!

**Comment by aidanholm** [comment]
Hi! Just add `require "vertical_tabs"` to your config, and restart.

**Comment by amosbird** [comment]
Thanks!
