### ISSUE TITLE
adblock crashes luakit when trying to load some lists

### ISSUE THREAD

**Issue by serg-kozhemyakin** [luakit/luakit#587]
adblock fails to load list that contains records like:
$third-party,domain=rusplt.ru
and crashes luakit at start with trace:
[    0.095490] I [core/luah]: Loading rc: /etc/xdg/luakit/rc.lua
[    0.118885] I [lua/adblock]: found 4 filter lists
[    0.181806] E [core/common/lualib]: Lua error: bad argument #1 to 'ipairs' (table expected, got string)
                 Traceback:
                 (1) [C]                                         in function ipairs
                 (2) /usr/local/share/luakit/lib/adblock.lua:237 in function list_add
                 (3) /usr/local/share/luakit/lib/adblock.lua:281 in function parse_abpfilterlist
                 (4) /usr/local/share/luakit/lib/adblock.lua:419 in function load
                 (5) /usr/local/share/luakit/lib/adblock.lua:503 in main chunk
                 (6) [C]                                         in function require
                 (7) /etc/xdg/luakit/rc.lua:61                   in main chunk
[    0.181849] W [core/luah]: loading rc '/etc/xdg/luakit/rc.lua' failed, falling back...

problem in adblock.lua in sub abp_to_pattern, for such lines condition 
if string.len(s) > 0 then
is false but we don't have else statement for it. trivial 
    else
        s = { "" }
workaround loading of such files but probably is not exactly correct

**Comment by aidanholm** [comment]
This workaround looks correct. Can you confirm that it results in third-party connections to sites (e.g. rusplt.ru) being blocked?

**Comment by serg-kozhemyakin** [comment]
yes, it works. site blocked

**Comment by aidanholm** [comment]
Merged! Sorry it took a while... forgot about this issue :(
