### ISSUE TITLE
Web page dump doesn't work

### ISSUE THREAD

**Issue by mwoz123** [luakit/luakit#592]
When trying to save page to disk error is thrown.

Error (red) log in browser window:
> Error: /usr/local/share/luakit/lib/binds.lua:561: view.source has been removed; use view:get_source() instead
Traceback:
(1) /usr/local/share/luakit/lib/binds.lua:561      in function func
(2) /usr/local/share/luakit/lib/lousy/bind.lua:274 in function [anonymous]
(3) [C]                                            in function xpcall
(4) /usr/local/share/luakit/lib/modes.lua:179      in function activate
(5) /usr/local/share/luakit/lib/modes.lua:103      in function [anonymous]

Nothing in system console log:
> $ luakit google.com
[    0.200963] I [core/luah]: Loading rc: /etc/xdg/luakit/rc.lua
[    0.221117] I [lua/adblock]: found 0 filter lists
[    0.231791] I [lua/styles]: found 0 user stylesheets
[    0.233077] I [core/web_context]: Web process count: 4
[    0.896116] I [lua/webview]: Requested link: https://www.google.pl/?gfe_rd=cr&dcr=0&ei=wcsJWuzoO46BX8_gvpAP&gws_rd=ssl (text/html)
Error scanning plugin /opt/Citrix/ICAClient/npica.so, /usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitPluginProcess returned 256 exit status

File is created with size = 0b.

**Comment by aidanholm** [comment]
Thanks for reporting; fixed it (at b814cb2), should be working now :)

**Comment by mwoz123** [comment]
np. Works now. But could you also make it dump images?

**Comment by aidanholm** [comment]
You probably want to use `:download` for that ... to be honest, I'm not sure why `:dump` exists at all.
