### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by skingtn** [luakit/luakit#607]
Great work!  Possible settings issues below.  Current version, standard modules and no settings file.
1.  Using settings.foo.bar API in a userprefs file, changes to some settings don't seem to take.  A call to get_setting before and just after the change returns original default value (and identifies default as source) in either case.  For other settings, the change does go through.  As example ``settings.webview.auto_load_images = false`` shows true by source default before and true by source default after (i.e. change not effective), but ``settings.webview.load_icons_ignoring_image_load_setting`` is false by source default before but true by source rc after (change effective).  No messages or errors are returned either way, and I can't find any module overrides.  Some win/web settings I can't change from default are auto_load_images, load_etc_hosts, enable_offline_web_applications_cache, print_backgrounds and enable_site_specific_quirks.  Some I can are home_page, close_with_last_tab, scroll_step, allow_file_access_from_file_urls, enable_smooth_scrolling and user_agent.  I change in a local func that logs success or failure and pre/post setting and source (can provide that or it's output separately), but I get same result with one-off calls as above and get-setting warn messages (or just by checking ://settings).  I guess I'm doing something wrong, but I can't make sense of the difference and wondered if you could point me in the right direction, or if this is at all reproducible on your end.  Changing persistently by ://settings or :set is an option for the web/win settings included, but I'd like to keep non-default settings in one place (and either way I'd like to change some of my problem settings at run-time on an ephemeral basis, e.g. a command to toggle image loading).
2. Since :set writes to disk, is there a standard way to make non-persistent settings changes from the luakit console, or is that a script-only option using settings.foo.bar?
3. Is there a log level setting, or would it be useful?  Default seems pretty high and for some reason X dumps the output to my login shell on exit.  I sometimes use the command-line argument, but it can complicate launch if not in an XDG environment and any adjustment requires a restart.
4. Should the settings file be written to data dir or to config dir?  I see config is historically lua only, but settings feels like the new config to me, and on webkit browsers it's pretty great to clear all browsing data by deleting one directory.
Apologies if these have been addressed before, but I couldn't find them.

**Comment by aidanholm** [comment]
Hi, and thanks for all the great questions!

1. Thanks for reporting this; it was a bug, now fixed!
2. You can run `:lua require('settings').foo.bar = baz`; I'm considering making accesses to non-existent global variables in console fall back to loaded modules, so you could just do `:lua settings.foo.bar = baz`.
3. Log level could be a little complicated to expose a settings interface for, as you can specify different log levels for different modules in a hierarchical fashion. I suppose a string property similar to the command-line format would be good, but note that it couldn't take effect immediately: there's lots of logging before the settings module is even loaded.
4. It's a good question. The idea is to support manual lua-level customization for power users, as well as higher-level GUI-based customization for people who don't know lua or don't want to bother. The two customization approaches aren't really supposed to be mixed (although we try to support that), and I see the settings file as more of an opaque data blob than a configuration file. The distinction between the two directories is also less about config vs data and more about lua vs everything else: quickmarks, userscripts, and userstyles could all conceivably be seen as part of a user's browser config, for example, even if they're not lua.

Hope that makes things a bit clearer

**Comment by skingtn** [comment]
1.  Works perfectly, thanks.
2.  That's a good solution and would add some convenience, but require('settings') isn't much to ask.  I just didn't know how to do it.
3.  I think this one is my problem.  Info level is great for :log, just glib logger sending to stderr is some trouble so I need to control stderr better.  But if you were going to make logging more customizable, I'd vote for ability to disable output to stderr, because with :log chrome working so well anything else is redundant for my use (esp. if I could find your internal log file somewhere in case of crash).
4.  I see what you mean.  And with setting.foo.bar back in action, a settings file isn't inevitable so I can delete the data dir anyway.
Thanks again for your efforts--you've got this thing cooking!

**Comment by hippi777** [comment]
hi there :)

for the log if simply print is used print can be overridden with anything. in my app im using my out() function cuz graphical live coding needed an own output but later ive realized i can use that for any kinda purpose, i can put behind that print for terminal or use it as its now for graphical output or ill be able to use it for server output... if logging comes together with anything else, then that could be resolved with a log alias for print that can be overwritten for any purpose...

i hope i could give any helpful ideas :)
