### ISSUE TITLE
Setting keybindings

### ISSUE THREAD

**Issue by arortell** [luakit/luakit#619]
very new to luakit. I came from qutebrowser. I cannot figure out how to set keybindings. I copied the rc.lua file to .conf/luakit tried to set them in that. Created a user userconf.lua file set require “userconf” in rc.lua and set them in that. I copied binds.lua to the .conf/luakit directory and set them in that . Then I read somewhere to set them in modes.lua and I set them in that. None of that worked. I even tried setting them in the above files that were still in /user/share/luakit/lib directory. I love this browser. I tried reading the api doc where it talks about migrating settings because every user dotfile examples I could find where in the old syntax. It talks about what functions to use but not where to put them. Thank. You for all work work on this awesome browser. If some could just post or update the wiki on what and where to put the new keybindings and other settings.

**Comment by aidanholm** [comment]
Hi! Sorry you've been having difficulty. Unfortunately there's still some outdated documentation floating around and the up-to-date documentation isn't always as clear as it could be :(

There's no need to include `binds.lua` or `modes.lua` in your `~/.config/luakit/` directory. In fact, they will be ignored, as there are already core modules with these names that are already loaded! I plan to show a warning when these files are detected, to help prevent confusion in future.

Instead, in your `userconf.lua` file, you simply copy and paste the lua code that will call the correct mode functions. For example, the modes documentation has the following example for adding a binding:
```lua
modes.add_binds("normal", {
    { "<Control-c>", "Copy selected text.", function ()
        luakit.selection.clipboard = luakit.selection.primary
    end},
})
```
To get this to work, your `userconf.lua` file might look like this:
```lua
-- First, we need to get a reference to the modes module, and assign it to a local variable
local modes = require "modes" 

-- Same code as above, copy-pasted from docs
modes.add_binds("normal", {
    { "<Control-c>", "Copy selected text.", function ()
        luakit.selection.clipboard = luakit.selection.primary
    end},
})
```
So the only real change is the `local modes = ..` line. You only need that line once at the top of the file; without it, you'll see an errror like `attempt to index global 'modes' (a nil value)`.

Hopefully that makes things clearer! I'll also update the code samples that are missing `local foo = require "foo"` line. Please let me know if you have further questions :)

**Comment by arortell** [comment]
Thank you so much for your quick response. Worked perfectly. Once again I thank you for your hard on this incredible browser. I love it. I just hate when people get on here demanding options, bitching about small bugs and the way THEY think this should be. Some people just don’t understand exactly how much work goes into something like this. Thank you.

**Comment by aidanholm** [comment]
You're very welcome! I'm glad you're enjoying luakit! Don't worry about asking questions; that's actually a good thing, as it lets me know which bits need more work :)

**Comment by jerojasro** [comment]
I took the example/explanations from @aidanholm and updated the quick start guide. You can see the changes in this pull request: https://github.com/luakit/luakit/pull/645 ; comments/suggestions are welcome.

**Comment by aidanholm** [comment]
I've merged that PR (thanks!) so I'll go ahead and close this; as always, feel free to reopen if you have further questions!
