### ISSUE TITLE
Play Embedded Video in External Player.

### ISSUE THREAD

**Issue by n73red** [luakit/luakit#624]
for old version
```lua
key({}, "v", function (w) 
    local view = w.view
    local uri = view.hovered_uri or view.uri
    if uri then
        luakit.spawn(string.format("urxvt -e cclive --stream best --filename-format '%%t.%%s' "
            .. "--output-dir %q --exec='mplayer \"%%f\"' %q", os.getenv("HOME") .."/downloads", uri))
        -- Alternatively, use mpv.
        -- luakit.spawn(string.format("mpv --geometry=1366x768 %s", uri))
    end 
end),
```
not working,
how did for new version?

_Edited by A.H. to fix code formatting_

**Comment by aidanholm** [comment]
The difference is in how keys are bound now. You can add the following code to `rc.lua`:
```lua
-- This line is only needed once, so you can remove it if you've already required "modes"
local modes = require "modes"

modes.add_binds("normal", {
    { "v", "Play video in page", function (w)
        -- Same function as above
        local view = w.view
        local uri = view.hovered_uri or view.uri
        if uri then
            luakit.spawn(string.format("urxvt -e cclive --stream best --filename-format '%%t.%%s' "
                .. "--output-dir %q --exec='mplayer \"%%f\"' %q", os.getenv("HOME") .."/downloads", uri))
            -- Alternatively, use mpv.
            -- luakit.spawn(string.format("mpv --geometry=1366x768 %s", uri))
        end
    end },
})
```
Hope that helps!

**Comment by n73red** [comment]
anyway dont work, typing hot V in adress - so dont should be

**Comment by aidanholm** [comment]
Hm, is there any error message? Most of what this does is with the external command `urxvt ...`; the only thing the lua does is get the webpage address and pass it to the external command.

**Comment by n73red** [comment]
earlier when you pressed "v" - the command was executed, now "v" is simply written in the address bar, luakit does not understand that this is a hotkey, no command is sent to urxvt, no error messages - the usual situation is the user entered the "v" symbol. .
I can not there have registered? I registered in binds.lua which is located in ~ / .config / luakit

**Comment by aidanholm** [comment]
Ah: the `binds.lua` and `modes.lua` files have been made built-in modules, so files with that name in `~/.config/luakit/` won't do anything.

Instead, you should add the code above to your `~/.config/luakit/rc.lua` file, just before the `-- End user script loading --` comment block.

**Comment by n73red** [comment]
binds.lua and modes.lua     - delete
Instead, you should add the code above to your ~/.config/luakit/rc.lua file, just before the -- End user script loading -- comment block      - did
it still does not work, and the picture has not changed, all the same as the bud that typed the "v" character in the address bar, luakit does not understand your code and there are no error messages

**Comment by n73red** [comment]
Instead, you should add the code above to your ~/.config/luakit/rc.lua file, just before the -- End user script loading -- comment block
```
-- Play Embedded Video in External Player.
 modes.add_binds("normal", {  
       { "v", "Play video in page", function (w)  
        local view = w.view  
         local uri = view.hovered_uri or view.uri
          if uri then  
           luakit.spawn(string.format("mpv --geometry=640x360 %s", uri ))  
        end  
    end },  
  })
```

working!!! #

**Comment by aidanholm** [comment]
Glad it's working :) If you have further stuff you want to migrate, the migration guide (https://luakit.github.io/docs/pages/04-migration-guide.html) might help; but feel free to ask questions as well!

**Comment by vonpupp** [comment]
Hello,

I am trying to use this feature by putting the following snippet on the `~/.config/luakit/userconf.lua`, as described on the [arch-wiki].
```
local settings = require "settings"
local modes = require "modes"

-- Play Embedded Video in External Player.
modes.add_binds("normal", {
  { "v", "Play video in page",
  function (w)
    local view = w.view
    local uri = view.hovered_uri or view.uri
    if uri then
      luakit.spawn(string.format("mpv --geometry=640x360 %s", uri ))
    end
  end },
})
```

However this doesn't seem to work when I press `v`. Any idea please? Thanks!

[arch-wiki]: https://wiki.archlinux.org/index.php/Luakit#Key_bindings

**Comment by vonpupp** [comment]
My mistake, now it is working... If anyone stumbles with this also, I had to copy the original `rc.lua` config as described on the [manual] and add the `require userconf.lua`.

Despite the code works, I found this alternate [solution] which I migrated to the new config API. I liked this alternative since it is visual (triggered with `;d`) and I don't have to manually follow the video. I also liked the fact that it has the ability to download other media types like PDF directly to Zathura. In case it is useful to somebody else herewith the code snippet:

```lua
modes.add_binds("ex-follow", {
  -- Yank element uri to open in an external application
  { "d", "[[Hint all links (as defined by the `follow.selectors.uri` selector) and set the primary selection to the matched elements URI, so that an external app can open it]]",
  function (w)
    w:set_mode("follow", {
      prompt = "video", selector = "uri", evaluator = "uri",
      func = function (uri)
        assert(type(uri) == "string")
        uri = string.gsub(uri, " ", "%%20")
        luakit.selection.primary = uri
        if string.match(uri, "youtube") then
          luakit.spawn(string.format("mpv --ytdl-format 'best[height=720]' '%s'", uri))
          -- This also works
          -- luakit.spawn(string.format("mpv --geometry=640x360 %s", uri ))
          w:notify("trying to play file on mpv " .. uri)
        elseif string.match(uri, "vimeo") then
          luakit.spawn(string.format("mpv %s", uri))
          w:notify("trying to play file on mpv " .. uri)
        elseif string.match(uri, "vine") then
          luakit.spawn(string.format("mpv %s", uri))
          w:notify("trying to play file on mpv " .. uri)
        elseif string.match(uri, "pdf" or "PDF") then
          luakit.spawn(string.format("~/.config/scripts/pdfFromURL %s", uri))
          w:notify("trying to read file via zathura ")
        elseif string.match(uri, "jpg") then
          luakit.spawn(string.format("feh -x %s", uri))
          w:notify("file contains jpg " )
        else
          luakit.spawn(string.format("feh -x %s.jpg", uri))
          w:notify("no jpg extension | unrecognized")
        end
      end
    })
  end },
})
```

Bear in mind that by using the `ytdl-format` option on mpv it requires `youtube-dl`. It can be installed with:
```
pip[3] install --user youtube-dl
```

I can add an entry to the wiki if this is helpful to others.

Best regards,
@vonpupp.

[manual]: https://luakit.github.io/docs/pages/03-quick-start-guide.html
[solution]: https://bbs.archlinux.org/viewtopic.php?id=197393
