### ISSUE TITLE
Wikipedia takes ages to load.

### ISSUE THREAD

**Issue by zappathustra** [luakit/luakit#633]
And that's not the case with Firefox or Chromium. At first I thought it was Wikipedia's servers' fault, but it's not. Luakit just takes forever to load the page, stuck at 10% for a long time.

**Comment by aidanholm** [comment]
Any particular page? My wikipedia is loading fine...

**Comment by zappathustra** [comment]
Any page. See this screencast (Luakit is the leftmost window, then come Chromium and Firefox):

![screencast](https://user-images.githubusercontent.com/1642300/34218140-a86f0c82-e5ad-11e7-8ef3-73ff45baa387.png)

**Comment by aidanholm** [comment]
Could you check to see if you can reproduce that with epiphany?

**Comment by zappathustra** [comment]
Epiphany doesn't load Wikipedia either. Nor do Midori and uzbl. So I guess it's a webkit issue?

**Comment by n73red** [comment]
duckduckgo search was by default in the old version, in the new version another search by default, did you switch search or use the old version of the browser?

**Comment by zappathustra** [comment]
I actually never use DuckDuckGo, I enter addresses by hand. I just used it for the demo. And my luakit was compiled from AUR today, so I guess it's up to date.

No matter how you jump to Wikipedia, it doesn't load.

**Comment by n73red** [comment]
aur - a comprehensible arch, debian sid - I'm going from here from github, it's even more important - wikipedia opens 100%

**Comment by zappathustra** [comment]
I'm not sure I understand what you mean, but the Luakit package on AUR is built from Github. AUR only contains recipes to build packages, not packages themselves, so it's not like Debian Sid.

**Comment by aidanholm** [comment]
Probably a webkit issue, yeah; @zappathustra, what version of webkit are you on?

**Comment by zappathustra** [comment]
My webkit is webkit2gtk 2.18.4-1, updated a few minutes ago because I thought the new version might have fixed the problem, but no.

**Comment by zappathustra** [comment]
Upgraded webkit2gtk to 2.18.5-1, the bug remains (I didn't have much hope).

Do you have any idea where I could start looking to solve it, or what kind of test I could run? It's extremely annoying to open qutebrowser to see Wikipedia pages (which I do quite often).

**Comment by aidanholm** [comment]
Unfortunately I don't; the folks on #webkitgtk+ might have some idea, or you could also check the webkit bugzilla.

**Comment by zappathustra** [comment]
Reported: https://bugs.webkit.org/show_bug.cgi?id=181791

**Comment by zappathustra** [comment]
And now it seems gone. Don't know why. Didn't upgrade anything relevant, it seems. But I don't complain.
