### ISSUE TITLE
Should content of clipboard/primary be splited to words when opened using p* or P*?

### ISSUE THREAD

**Issue by McSinyx** [luakit/luakit#642]
I want to discuss the logic behind these bindings. I'm not sure about other's use of this binding, but I mainly use it when I need to search for terms in articles I read. IMHO, it's very unlikely that one would ever want to search for each selected word, while difficult terms are usually phrases. Let's take an example from [debian.org](https://www.debian.org/license) to make it clearer:

> Work is in progress to make the older material compliant with the above licenses. Until then, please refer to the following terms of the Open Publication License.
>
> This material may be distributed only subject to the terms and conditions set forth in the Open Publication License, Draft v1.0 or later (you can read our local copy, the latest version is usually available at http://www.opencontent.org/openpub/).
>
> “Debian” and the Debian Logo are trademarks of Software in the Public Interest, Inc.

I can't speak for everyone, but `pp` in this case would make a lot more sense if it can be used to search for group of words such as *Open Publication License* or *Public Interest, Inc.*. I can imagine [the current implementation](https://github.com/luakit/luakit/blob/6bb3df7f57f8a8131d522998a42f7d6f25af7fb3/lib/binds.lua#L277) was made (7991929ac66c42516b0b8c14bf7a283567704436) for the following kind of case, but this would be a rare case compare to the above example:

> http://www.jclark.com/xml/copying.txt
> http://www.gnu.org/licenses/gpl.html

Furthermore, it's quite irritating to accidentally press this key combination if one have the habit of selecting while reading - then dozens of tab may be opened.

**Comment by ghost** [comment]
I think these are two different usecases.

1) I select a list of URLs and want to open all of them in luakit. This is implemented
-> Side effect, if the pasted content are not URLs, luakits default behavior is to search for it.

2) I select multiple words (a phrase) and want paste it, I want to search for them as phrase.
-> side effect of 1) applies.

I think both should be possible somehow... maybe checking if first term is a valid URL and then apply 1 otherwise search for it as a phrase (2)?

**Comment by McSinyx** [comment]
Yep, that'd be a lot better idea. Lemme try: I remember that there's already a pattern somewhere in the repo for validate URLs.

**Comment by McSinyx** [comment]
`pt` and `PT` seem to behave the way I ask for (but in new tab), but aren't `pp` and `pt` meant to do the same, accept `pp` in current and `pt` in new tab? If I pull a request, I should uniform both right?

@aidanholm I need your opinion on this before taking futher steps.

**Comment by McSinyx** [comment]
@xkpd3  I think we are trying to make the browser to be too smart. I imagine users would expect `pp` and :open to follow the same logic. The hack we can do here is to split the selection into either:

* System path
* URIs
* Anything between, not splited

e.g. `foo github.com lua string find Pictures/Screenshot` should be splited into `foo`, `github.com`, `lua string find` and `Pictures/Screenshot`.

Implementing this can be easy, but noone can be completely sure if a substring is uri or path. I suggest adding a `:open!` which avoid all these guessing.

Edit: Are we complicating the problem? Is there any *real world* website having URIs separated by whitespaces?

**Comment by aidanholm** [comment]
- There are no URIs separated by spaces; whitespace is escaped canonically.
  - `pp` and `:open` should have different logic:
  - if they had the same logic, `pp` wouldn't be necessary as `o<shift-insert><enter>` is reasonably fast to type.
  - trying to `:open` multiple URIs in the current tab is not well defined---they solve a different problem
    - also a problem for `pp`
  - it's more important for `:tabo` to be consistent with `:o` than with `pp`
- splitting the input into multiple parts is possible, but I'd prefer a simpler solution like @xkpd3's suggestion
   - better to check that all string parts can be parsed as URIs, not just the first

**Comment by McSinyx** [comment]
> There are no URIs separated by spaces

I was asking if is there any webpage that lists URIs separated by white spaces, but then I realise that it can be a user local bookmark file.

I think I'll try to improve the logic, but where do you think I should put the `is_uri` function [(taken from `window.search_open`)](https://github.com/luakit/luakit/blob/43b51b36715c121c41d96aa9db243fd621e5fdb6/lib/window.lua#L602)?

May I add a new binding `ps` to do what `o<S-Ins><Return>` does? It'd be great if `:open` can do `pp` as well (imagine we can `:open github.com reddit.com`), but discussing this here is quite off topic now.

Edit: I accidentally closed the issue

**Comment by aidanholm** [comment]
- Oh, yeah, that makes sense; I misread your question about URIs and whitespace before.
- Perhaps `lousy.uri.is_uri` is a good place.
- I'd rather reduce the number of default bindings if at all possible.

**Comment by McSinyx** [comment]
I tried to move the URI checking out of `window` (https://github.com/McSinyx/luakit/commit/c098b081cdb6354183681a06bd255a58c3a58e6d) and somehow this error pops out:

```[    0.128804] I [core/luah]: Loading rc: /home/cnx/.config/luakit/rc.lua
[    0.278050] E [core/common/lualib]: Lua error: loop or previous error loading module 'lousy'
                 Traceback:
                 (1) [C]                                           in function require
                 (2) /usr/local/share/luakit/lib/settings.lua:10   in main chunk
                 (3) [C]                                           in function require
                 (4) /usr/local/share/luakit/lib/lousy/uri.lua:9   in main chunk
                 (5) [C]                                           in function require
                 (6) /usr/local/share/luakit/lib/lousy/init.lua:14 in main chunk
                 (7) [C]                                           in function require
                 (8) /home/cnx/.config/luakit/rc.lua:15            in main chunk
[    0.299178] W [core/luah]: loading rc '/home/cnx/.config/luakit/rc.lua' failed, falling back...
[    0.140128] I [core/luah]: Loading rc: /etc/xdg/luakit/rc.lua
[    0.276653] E [core/common/lualib]: Lua error: loop or previous error loading module 'lousy'
                 Traceback:
                 (1) [C]                                           in function require
                 (2) /usr/local/share/luakit/lib/settings.lua:10   in main chunk
                 (3) [C]                                           in function require
                 (4) /usr/local/share/luakit/lib/lousy/uri.lua:9   in main chunk
                 (5) [C]                                           in function require
                 (6) /usr/local/share/luakit/lib/lousy/init.lua:14 in main chunk
                 (7) [C]                                           in function require
                 (8) /etc/xdg/luakit/rc.lua:15                     in main chunk
[    0.293620] W [core/luah]: loading rc '/etc/xdg/luakit/rc.lua' failed, falling back...
[    0.126920] F [core/luakit]: couldn't find rc file
```

Do you have any idea about the cause?

Edit: I guess because `settings` require `lousy.uri` and `lousy.uri` requires `settings`, but I'm not sure how to fix.

**Comment by aidanholm** [comment]
That's correct; move the require call into the definition of `is_uri()` to fix it

**Comment by McSinyx** [comment]
I've created PR #646 trying to solve this.
