### ISSUE TITLE
status bar height

### ISSUE THREAD

**Issue by piyavking** [luakit/luakit#648]
Hello,

Tell me, please, how can I adjust statusbar height (vertical size)?

Thanks.

**Comment by aidanholm** [comment]
Hi!

The status bar height is determined based on the font size. To change the font used for the status bar, you can set `theme.sbar_font` in your `theme.lua` file. For example: `theme.sbar_font = "15px monospace"`

Unfortunately two statusbar widgets do not respect `theme.sbar_font`, and you will need to set `theme.sbar_zoom_font` (for the page zoom widget) and `theme.sbar_loaded_font` (for the load progress widget) as well; normally you'd set these to the same value.

**Comment by piyavking** [comment]
it'so sad(((

**Comment by aidanholm** [comment]
Did you manage to adjust the status bar height? If you need more help, feel free to ask! You can also ask questions on #luakit on the OFTC network and we'll be happy to help :)

**Comment by piyavking** [comment]
--Did you manage to adjust the status bar height?--

no, because a similar font height for 'header' (tab bar) and 'footer' (status bar) of luakit window is important for me too)
i think it is not so big feature for request, then ok, it'not so big trouble.

**Comment by aidanholm** [comment]
Oh, I see: you can also set `theme.tab_font = "15px monospace"` (or whatever font + size you like) to adjust the tab font sizes.

If you want to change everything all at once, `theme.font` applies to everything, unless you override it with something more specific, like `theme.tab_font` or `theme.sbar_font`.

**Comment by piyavking** [comment]
I installed luakit from "master" branch, tabs anb status bar heights becomes equally)

Did You planned about making ppa for ubuntu?

**Comment by piyavking** [comment]
problem solved. different heights arose because of the bad GTK theme. checkboxes also appears.
