### ISSUE TITLE
duckduckgo: "open in new window" issue

### ISSUE THREAD

**Issue by sprnza** [luakit/luakit#651]
Hi there!
If I set duckduckgo to open links in new window, luakit stops opening title links using "Follow" command.
See [screenshot](https://i.imgur.com/Ct5xZbU.png). If I Follow "ed" here nothing happens. If I follow "es" a new tab is being opened.
If I disable this feature in duckduckgo settings, title links are being opened just fine but in the current tab.

**Comment by aidanholm** [comment]
Thanks, fixed!

**Comment by sprnza** [comment]
I'm not sure if it's related but a link from ddg's feature that displays snippet from a stackoverflow answer is being opened from second attempt only.
