### ISSUE TITLE
General question about the web inspector

### ISSUE THREAD

**Issue by beatgutzwiller** [luakit/luakit#652]
Hi there

I am one of the guys who switched to luakit because vimperator does not run anymore on firefox.
And I am stunned. This works way better than I would ever have expected. Neverless, the Web Inspector is not really good, so i have to switch between firefox and luakit which isn't exactly lovable.

What I would dream of is not a Web Inspector like it is used in Firefox, but a possibility to open and edit the html in vim (also the css). But before I dig to deep into this, I wonder, is this even possible? Is the data reachable as file, or does the Web Inspector manipulate the Site in Memory?

Best regrads and thank you in advance.

**Comment by aidanholm** [comment]
Hi! Glad to hear you're enjoying luakit!

The web inspector manipulates the page in memory, so unfortunately this isn't really possible.

**Comment by hippi777** [comment]
hi there! :)

if im correct the brackets editor have live coding through something called live debug and it works with chrome, so i think its possible to make very kawl stuffs upon that... however i dunno more about this, but you can get some hints on the git page, git wiki or home page or whatever (dunno, forgot it where ive found it in the middle of last summer)

i think it is more than possible from the side of luakit, but im not familiar with vimperator and the like, i hope they can have plugins for this purpose... in the worst case you can modify/extend/ask to extend brackets, its nice, just *slow* for buffering a whole project via curlftpfs or sshfs, but it can be synchronised on local save if you have the project on your machine, but beware of working on a remote host with others this way... it even have something to working on the same file for 2 copf

btw i think this task may be kinda small or even kinda huge as well, so prepare for the worst :D
