### ISSUE TITLE
luakit crashes on archlinux (not testing)

### ISSUE THREAD

**Issue by zsoltika** [luakit/luakit#66]
I just (re)installed luakit after my system upgrade and it crashes all the time with:

```
zs@nanovac ~ $ luakit
Inconsistency detected by ld.so: dl-open.c: 667: _dl_open: Assertion `_dl_debug_initialize (0, args.nsid)->r_state == RT_CONSISTENT' failed!
```

**Comment by aidanholm** [comment]
Cannot reproduce. Note that luakit has recently been updated to use WebKIt 2, so almost all old crashes have been fixed. Feel free to reopen if this issue reoccurs.
