### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by sandrosBulko** [luakit/luakit#670]
`luakit --version` returns `luakit`

on Linux name-X553MA 4.10.0-38-generic #42~16.04.1-Ubuntu SMP Tue Oct 10 16:32:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

recreation process:
1. open luakit
2. wait for the main page to load
3. hit "o" and enter "youtube.com"
4. wait to load
5. search for "flexicution"
6. play the first video "Logic - Flexicution" by "LogicVEVO"
7. hit "Ctrl+t" and "o" and enter "youtube.com"
8. search for "ssion smith" and enter -> here it receives SIGSEGV signal 

backtrace: https://gist.github.com/sandrosBulko/e37597d270ac9e9bb07414de95de9fea

**Comment by aidanholm** [comment]
It looks like you have an old pre-webkit2 version of luakit; those older versions are very buggy and crash a lot. The newer versions aren't in many repositories, so you may need to build from source to update.
