### ISSUE TITLE
lua51-luacheck issue

### ISSUE THREAD

**Issue by DarkHalo117** [luakit/luakit#674]
Installing luakit from yaourt AUR package manager. This is a fresh arch linux 4.14.15 installation. The issue I'm having is:

Error: Build error: Failed installing src/luacheck/whitespace.lua in /tmp/yaourt-tmp-user/aur-lua51-luacheck/pkg/lua51-luacheck/usr/lib/luarocks/rocks-5.1/luacheck/scm-1/lua/luacheck/whitespace.lua: src/luacheck/whitespace.lua: No such file or directory

I tried installing lua51-luacheck by downloading the aur package by itself and got this:

Error: Build error: Failed installing src/luacheck/whitespace.lua in /home/user/Downloads/lua51-luacheck/pkg/lua51-luacheck/usr/lib/luarocks/rocks-5.1/luacheck/scm-1/lua/luacheck/whitespace.lua: src/luacheck/whitespace.lua: No such file or directory

**Comment by aidanholm** [comment]
Looks like an issue with the luacheck package; just delete the `checkdepends` line in the luakit PKGBUILD to work around that.

**Comment by IWriteThings** [comment]
This fixed the issue for me. Thanks a bunch!

**Comment by c0dev0id** [comment]
@DarkHalo117: Does this fix the issue for you as well?
