### ISSUE TITLE
problem with online video

### ISSUE THREAD

**Issue by piyavking** [luakit/luakit#676]
Hello,

I use luakit last vertion (3ce519fb), last webkit2gtk in software sources (Ubuntu 17.10 Minimal). after updating webkit (I do not remember details) I once remarked then when i try "rewind" or "play/pause" online video like YouTube etc, then video 'freezez' in pause, but audio and 'hover previews' still stay available.

I reinstall luakit 'fully', and start with default config - all the same situation.

Help me with this problem,please

**Comment by aidanholm** [comment]
That sounds like an issue with either webkit2gtk or the gstreamer plugins used to render youtube. You might want to see if there are gstreamer plugins you can install, as that might fix this issue. Also, there have been a lot of changes in the `develop` branch, so building a develop version might fix this as well.

**Comment by piyavking** [comment]
--sounds like an issue with either webkit2gtk or the gstreamer plugins--
yes, I think absolutely equally, but one thing: old, ancient 'luakit' from default ubuntu's software sources haven't this problem. that's mystery for me.

**Comment by piyavking** [comment]
Updated to ubuntu 18.04 and luakit develop a14a77db, the problem remained. It is unfortunate that there is such an significant drawback in the excellent browser. Really at me one such problem with luakit and ubuntu? :(

P.S. There are also no "checkmarks" on the web pages.

**Comment by piyavking** [comment]
I FOUNDED YEAAAAH

'export LIBGL_DRI3_DISABLE=1'

oooo, life is beautiful!!!

**Comment by aidanholm** [comment]
That's great to hear! Glad you tracked it down :)
