### ISSUE TITLE
How to disable the log?

### ISSUE THREAD

**Issue by n73red** [luakit/luakit#678]
Your version of WebKit (2.16.6) is outdated and vulnerable!
See https://webkitgtk.org/security/WSA-2017-0009.html for details.

this version is the newest in the repositories debian stretch

How to disable the log?

**Comment by aidanholm** [comment]
The best way to kill the warning is to upgrade to the version in stretch-backports, which is up-to-date.

You could remove the `require "log_chrome"` line from your `rc.lua` and remove the log status bar widget, which will hide the message. It'll still be logged to `stderr` though. If you really want to just kill the warning, you'll have to edit `lib/window.lua`.

**Comment by n73red** [comment]
> upgrade to the version in stretch-backports
thanks - helped
