### ISSUE TITLE
drive.google.com stopped working

### ISSUE THREAD

**Issue by Ygrex** [luakit/luakit#681]
staring with 0011377ebb67e0bcfdaba1406771842416eb4137 there are several sites got broken with:
```
[11730.787941] E [core/common/lualib]: Lua error: ./lib/lousy/widget/scroll.lua:update:18: TypeError: null is not an object (evaluating 'window.document.documentElement.scrollHeight')
                 Traceback:
                 (1) [C]                            in function assert
                 (2) lib/lousy/widget/scroll.lua:25 in function [anonymous]
```
Specifically trying to open any file in google drive results in failure message «Unable to load file».
Cannot find the relevant pull-request, but reverting back to 48b7195171cf33817fdd9fdd5717a3ed962c5356 makes all the sites working again.

**Comment by aidanholm** [comment]
Sorry for the late response; I didn't have time to reply when I first saw this, and unfortunately github lacks a "mark notification as unseen" feature, so I completely forgot about it :(

The scroll errors should be harmless; that happens when updating the scroll widget. I'll do some digging.

**Comment by c0dev0id** [comment]
@Ygrex: Can you share a file on google drive non-google user can access? Or do you have another example page?

**Comment by Ygrex** [comment]
reproducible on this page:
https://docs.google.com/spreadsheets/d/1jpsuyCNeDiqqQt4cjef1yl26DzdyndHneUGObgjxpq4/edit#gid=1275456760
not sure if the link is stable, just came across it simply googling

**Comment by Ygrex** [comment]
this magically helps even with the current develop branch:
```
git revert f5f0239f19e3000de915067533e7d54e59e13c15
```
applies with no conflicts and works perfect after that

**Comment by Ygrex** [comment]
cannot reproduce with the latest Luakit
