### ISSUE TITLE
session crash recovery

### ISSUE THREAD

**Issue by auser509** [luakit/luakit#683]
I'd love to have a config that basically ensures that all open tabs will be always restored in case of an abnormal restart (e.g. crash). This essentially requires that there's some signal that hooks into tab opening/closing events, and persists/removes the URIs immediately to/from storage (their state doesn't really matter).

Sounds like this should be readily doable, but I'm not too familiar with luakit.

**Comment by aidanholm** [comment]
`lib/session.lua` already handles session autosaving (every 10 seconds after a tab operation). It also provides the `session.always_save` setting (see luakit://settings). Perhaps that helps?

**Comment by auser509** [comment]
Thanks Aidan, yes this does help indeed.

One thing may worth considering is replacing `io.close` with `io.fclose` for the session save function, to ensure that the buffered io is always flushed to disk and avoid potential loss.

An unrelated thing I noticed is that I didn't have access to luakit://settings, as I was running luakit release (c5328c22). Not sure what your release process is (it doesn't seem regular but rather oriented around major webkit transitions), but some distros are against packaging non-release versions of software (looking at voidlinux here which is otherwise rolling/bleeding-edge).

**Comment by aidanholm** [comment]
I can find no mention of the `io.fclose` function anywhere, and explicitly closing the file should flush the file. Also, the only other thread running during the session saving operation is very simple and stable, so crashes during a write that cause data corruption are exceedingly unlikely to happen. It'd be nice to have more sophisticated session saving, however, with e.g. fsync.

The release process is currently pretty irregular. There's a few minor features I'd like to finish at some point before making the next release, but it's almost there.

**Comment by auser509** [comment]
sorry that's my bad, I was actually looking at `io_fclose` at [1], which is not exposed to the language but called internally upon `io_close`, which indeed flushes the buffers. That should take care of cases where for example the browser is killed due to OOM conditions (the userspace buffers will be at least pushed into the kernel). I think fsync would be indeed the next step if you want to ensure that the data are persisted in case of an actual kernel crash/loss of power.

[1] https://www.lua.org/source/5.3/liolib.c.html#io_fclose
