### ISSUE TITLE
Broken markup on Facebook (after dozen of seconds of usage)

### ISSUE THREAD

**Issue by vitaly-zdanevich** [luakit/luakit#687]
![luakit--facebook](https://user-images.githubusercontent.com/3514015/37251584-e83396b6-2523-11e8-843a-99d8204d8d7f.png)

**Comment by McSinyx** [comment]
I also have the same problem but I think it's WebKit's fault on low machine, because this only happen on my 14yo laptop, not at my school modern computers. BTW do you have it on Github too?

**Comment by aidanholm** [comment]
This looks like a webkit rendering bug of some sort. Luakit doesn't do anything graphics-related that might cause this issue.

**Comment by c0dev0id** [comment]
Can you try the following two things?
1) go to the :settings page, `change webview.hardware_acceleration_policy` to `never`
2) `export LIBGL_DRI3_DISABLE=1` before starting luakit (from the same terminal)

**Comment by c0dev0id** [comment]
@vitaly-zdanevich: We can't fix this from the luakit code. How do you want us to deal with this issue?
