### ISSUE TITLE
Adblock not working

### ISSUE THREAD

**Issue by Mishio595** [luakit/luakit#692]
I set up and enabled adblock exactly as instructed and it isn't hiding anything. I even have a cron task to update the list weekly. Yet no matter what site I go to, none of the ads are even affected. I'm not sure if this is me just doing something wrong, but its a major annoyance and one of the things keeping me from using this browser more.

**Comment by aidanholm** [comment]
What does this page show? http://simple-adblock.com/faq/testing-your-adblocker/
It should have "Tested OK" on the left.

What does this page show? luakit://adblock/
It should show at least one enabled list, with that list showing a positive number next to "B: " in the "Rules in use" column.

**Comment by Mishio595** [comment]
![First one](https://user-images.githubusercontent.com/3598536/37973922-d8db3a58-3198-11e8-9472-da80a361f387.png)
![adblock-chrome page](https://user-images.githubusercontent.com/3598536/37973934-e32021ea-3198-11e8-930d-00f2f003c8d7.png)

**Comment by Mishio595** [comment]
the lists being used were pulled directly from https://easylist.to/

**Comment by Mishio595** [comment]
Actually was digging through old issues and this is a duplicated of #573 
Closing

**Comment by aidanholm** [comment]
Glad you managed to resolve the issue; I believe that #573 was fixed after the latest stable release, which may be why you still experienced this problem.

**Comment by Mishio595** [comment]
I use the build from the AUR package luakit-git, but I did have an empty subscriptions file which may have been causing the issue
