### ISSUE TITLE
Unable to configure new tab page

### ISSUE THREAD

**Issue by Mishio595** [luakit/luakit#694]
in my userconf where I configure my home page and search engines, I also call `settings.window.new_tab_page = "file:///path/to/file.html"`. The same file is used for my home page perfectly, but the new tab keeps defaulting to luakit://newtab

**Comment by aidanholm** [comment]
You probably have the `newtab_chrome` module loaded; it overrides that setting with `luakit://newtab/`.
You could remove it, or you could set `newtab_chrome.newtab_file = "file:///.../foo.html"` in lua (it's a module property, not a setting).

Using the `newtab_chrome` module has some other benefits: it prevents the new tab page from being saved in your closed tabs, and has a binding (`E`) to open the newtab page file in your text editor.

**Comment by Mishio595** [comment]
That did it. thank you
