### ISSUE TITLE
Temporarily disable luakit keybindings to allow for website 

### ISSUE THREAD

**Issue by raphaelfournier** [luakit/luakit#699]
Is there a possibility, like in vimium, to disable luakit keybindings so that a user may interact with, for instance, calendar.google.com (which provides its own keybindings to use its interface)? If not, is this use case handle differently in luakit?

**Comment by aidanholm** [comment]
There's passthrough-mode for that, which is activated by Ctrl-Z. There's not currently any built-in support for remapping keys on specific websites though.

**Comment by raphaelfournier** [comment]
Thank you! I didn't find this mode, even if I had googled "luakit passthrough" before asking my question. Is it documented? Is there a built-in possibilty to automatically switch to passthrough mode when landing on a given webpage?

**Comment by aidanholm** [comment]
It's semi documented; it's listed on the `luakit://binds/` page. You could hook onto the "load-status" signal to wait for web pages to linish loading, and then check the URL in your handler and possibly switch to passthrough mode.

**Comment by c0dev0id** [comment]
I think this has been answered.
