### ISSUE TITLE
Open link in new tab make a parent page to be blanked.

### ISSUE THREAD

**Issue by sprnza** [luakit/luakit#700]
Hi there!
Seems like it's site specific. The only place I've manage to reproduce it is [here](https://hh.ru/search/vacancy?area=1&text=engineer).
Steps to reproduce:
1. Either open any vacancie link using mouse or close an opened one clicking on the tab name by middle button of mouse (just double checked. It's no matter how a link is being opened)
1. Parent page is getting a white blank page.

**Comment by aidanholm** [comment]
I can't reproduce this; what version of webkit are you using?

**Comment by sprnza** [comment]
webkit2gtk 2.20.1-1

**Comment by sprnza** [comment]
Yes, just tried with a default rc.lua and everything works just fine. Sorry for bothering.

**Comment by aidanholm** [comment]
No problem!
