### ISSUE TITLE
Can i build from source with lua 5.3.4 ?

### ISSUE THREAD

**Issue by ivanbogomoloff** [luakit/luakit#704]
I try to install from source.
I run make and get this
```bash
/usr/bin/lua51: ./lib/markdown.lua:122: attempt to call a nil value (global 'setfenv')
stack traceback:
	./lib/markdown.lua:122: in main chunk
	[C]: in function 'require'
	build-utils/docgen/gen.lua:3: in main chunk
	[C]: in function 'require'
	./build-utils/docgen/makedoc.lua:9: in main chunk
	[C]: in ?
```
lua51 is symlink to lua 5.3.4.
It is possible to build luakit on lua 5.3.4, maybe with some little hacks in source files? or not?

**Comment by aidanholm** [comment]
Afraid not; lua 5.3 is API-incompatible with 5.1 (so they really shouldn't be symlinked together) and doesn't provide the APIs luakit needs (setfenv in the error message above). You could install lua5.1 alongside lua5.3, or try installing luajit, which is also compatible with luakit.

**Comment by c0dev0id** [comment]
@ivanbogomoloff: I think the response from @aidanholm is pretty clear. I'm closing this issue. If you have further questions, feel free to reopen it.
