### ISSUE TITLE
Can't use Javascript 

### ISSUE THREAD

**Issue by lzt2002** [luakit/luakit#705]
I am using Ubuntu 17.10
When I wanted to open a site which uses Javascript, it failed. I can't open that site.
Then I typed /js and found this

![2018-05-14 13-58-41](https://user-images.githubusercontent.com/37217016/39980579-3f1fd894-577f-11e8-948c-c2198d20aa28.png)

Can anybody help me
Thanks

**Comment by aidanholm** [comment]
What version of luakit are you running?

**Comment by c0dev0id** [comment]
Hi @lzt2002 

typing just `:js` will always raise this error. This function evaluates JavaScript. Try calling `:js alert("It works!")` and see if this throws an error.

How does it fail? Blank page? Error?
Is `webview.enable_javascript` checked in `:settings` (assuming you're using the git version)
Any console / `:log` output?
