### ISSUE TITLE
default zoom level applies only after zoom_set

### ISSUE THREAD

**Issue by maxevtushok** [luakit/luakit#706]
Hello!
I use luakit 2017.08.10-364-gd6f66eb

set webview.zoom_level to 120 in luakit://settings.

when I open new tab - zoom level in this tab is 100.
After pressing "=" ({ "=", actions.zoom.zoom_set },) zoom level sets to 120.

What should I do to get 120 as default level without pressing "=" key?

**Comment by ghost** [comment]
Hi,

`webview.zoom_level` works with the current version of luakit from git. I highly recommend to use it, as it is _much_ newer than the last release.

In your version, you need to set `default_zoom_level` in the file `globals.lua`.

 In the git head version, you can adjust settings like this from within luakit by opening `luakit://settings`. No need anymore to fiddle around with config files :)

**Comment by maxevtushok** [comment]
`luakit 2017.08.10-364-gd6f66eb` is result of `luakit --version` command
currently I'm on develop branch, commit d6f66eb

So I use `luakit://settings`)

**Comment by maxevtushok** [comment]
Recompile and it works.
However it shows old version.
