### ISSUE TITLE
Feature-request: please add WebRTC capabilities

### ISSUE THREAD

**Issue by christf** [luakit/luakit#710]
getaroom.io asks me to use chrome or firefox (which is broken wrt mic usage).
It would be nice being able to use luakit for webrtc use-cases like video calls and desktop sharing.

**Comment by aidanholm** [comment]
Unfortunately that's something that webkit would have to provide; luakit doesn't have any way to implement that functionality.

**Comment by c0dev0id** [comment]
With aidenholms response, I think the ticket can be closed, right?
Also see here: https://www.webrtcinwebkit.org
