### ISSUE TITLE
Is there any way to clear cookies without closing Luakit?

### ISSUE THREAD

**Issue by SIeeplessKnight** [luakit/luakit#711]
I have tried ``sqlite3 -line ~/.local/share/luakit/cookies.db 'delete from moz_cookies;'``
but it seems like cookies are stored in memory somewhere and so this doesn't work as it does with the history module. I'm mainly interested in doing this inside of a Lua module, so if anyone could point me in the right direction I would appreciate it. 

Thank you.

**Comment by aidanholm** [comment]
Apologies for the slow response. There's an API for that, but it's a bit clunky and not documented:
```lua
coroutine.wrap(function()
    luakit.website_data.remove({"cookies"}, "google.com")
end)()
```
The call has to be wrapped in a coroutine because it's asynchronous.

**Comment by SIeeplessKnight** [comment]
I haven't had the time to do any programming lately, but I will try this out later. I appreciate your response, however late it may be.

Thank you.

**Comment by c0dev0id** [comment]
@byteseer: I've just tried it. By binding it to a key. This binds ctrl+s in normal mode and clears the cookies for google:

```
modes.add_binds("normal", {
    { "<Control-c>", "Clear Cookies",
        function (w, state)
            coroutine.wrap(function()
                luakit.website_data.remove({"cookies"}, "google.com")
            end)()
         end
     }
 })
```

This works fine, however I don't know how to clear all cookies as `luakit.website_data.remove` requires a domain as second argument.

Is this sufficient for your module idea?

EDIT: As far as I can see, this is what's possible right now. To delete all cookies we would need to implement and expose the `webkit_website_data_manager_clear()` function in `clib/luakit.c`.

**Comment by aidanholm** [comment]
You could use `luakit.website_data.fetch({"cookies"})` to retrieve all domains that have stored cookies, and then call `luakit.website_data.remove()` for each of those domains; that might be a little slow though. Instead of using `webkit_website_data_manager_clear()`, a better way would be to modify `luakit.website_data.remove()` to accept a list of domains.

**Comment by c0dev0id** [comment]
This is fixed as part of https://github.com/luakit/luakit/commit/4caf97dd1174a45c757d158d88a61d9f86afc65b
