### ISSUE TITLE
Issues after changing settings

### ISSUE THREAD

**Issue by phwelo** [luakit/luakit#715]
```WEBKIT_DISABLE_COMPOSITING_MODE=1 luakit.orig```

After changing settings I guess luakit generates a bash file and renames luakit's binary to `luakit.orig`.
This breaks opening of URLs from other applications as well as all other command line switches.

instead of the script being
```
#!/bin/bash

WEBKIT_DISABLE_COMPOSITING_MODE=1 luakit.orig

```

it should pass through the params
```
#!/bin/bash
WEBKIT_DISABLE_COMPOSITING_MODE=1 luakit.orig "$@"
```

**Comment by c0dev0id** [comment]
Hi @phwelo,

Can you provide more details about what you are doing? And where is this script file? When I look at the luakit source, I can't find anything that creates a bash script.

**Comment by phwelo** [comment]
Not using luakit anymore, but sounds like it may have been something specific to the repo I installed from. Sorry for the goose chase!
