### ISSUE TITLE
Live google search.

### ISSUE THREAD

**Issue by n73red** [luakit/luakit#716]
The live search does not work in Google - you can not select drop-down options. How to cure?

**Comment by amosbird** [comment]
It works fine here. Have you tried the default configuration yet?

**Comment by n73red** [comment]
I always use the default setting and have long noticed that live search in the new version of the browser does not work

**Comment by c0dev0id** [comment]
Hi n73red, which luakit version, webkit version and OS are you using? It's working fine here as well. (Debian Testing / Webkit 2.22 / luakit git-head)
