### ISSUE TITLE
The proxy does not work.

### ISSUE THREAD

**Issue by n73red** [luakit/luakit#717]
I create a proxy entry :proxy proxy_name 00.00.00.00:0000 then I select it in the proxy section and apply it - the pages no longer open. How correctly does the syntax of the record for the proxy look like? Give a working example if you can!

**Comment by aidanholm** [comment]
You need to add `socks://`: so your command would be `:proxy proxy_name socks://00.00.00.00:0000`

**Comment by n73red** [comment]
in this case, you always need socks-proxy?

**Comment by n73red** [comment]
tried different proxy socks & http \ https - nothing works, does not open the page - hangs for 10% for a long time and nothing happens .... the old version of the browser works with the proxy without problems

**Comment by aidanholm** [comment]
Unfortunately I'm not too clear on what proxy types are actually supported, apart from SOCKS 4, 4a, and 5 proxies. I haven't found much gnome documentation.

Also unfortunately, there's basically no way to introspect proxies and diagnose connectivity issues from luakit; if you have some networking knowledge you could try using wireshark to diagnose your problem.

If you need to connect to a proxy of an unsupported type, you might have to run a local SOCKS proxy that forwards to your remote proxy. Ugly... but hopefully not too complicated and unlikely to have a significant speed impact.

**Comment by n73red** [comment]
Do you work through a proxy? do the pages open?

**Comment by aidanholm** [comment]
I occasionally proxy through a remote host by connecting with `ssh -D 8080 remote`, which starts a local socks proxy; then I have a proxy rule with `socks://localhost:8080` as the rule. It works flawlessly for me

**Comment by n73red** [comment]
understandably, luakit alone can no longer be in the proxy ...
