### ISSUE TITLE
Not Supported Angular 6 Project

### ISSUE THREAD

**Issue by harshmpatel** [luakit/luakit#720]
Now I am working on debian os.
I will create one program using angular 6 but it will be not supported in luakit browser so what i should do run for that.
Also Inspect Element is not working.

**Comment by c0dev0id** [comment]
Hi HarshPetelpit,
is it working in any other webkit based browser (epiphany for example)?

EDIT: I was looking through some agular projects and tested some angular 6 examples / demos. They worked fine for me. Can you be a bit more specific about what is not working and which software versions (luakit/webkit) your are using? I've tested on debian testing with luakit git head and webkit 2.22.

**Comment by c0dev0id** [comment]
Author seems to have lost interest.
