### ISSUE TITLE
Keyboard-based scrolling does not work on sentry docs site

### ISSUE THREAD

**Issue by dlobue** [luakit/luakit#721]
The url of the website is: https://docs.sentry.io/
I am unable to scroll using j/k, arrow keys, page up/down, ctrl-d, ctrl-f, G, home/end, etc. The only way I am able to scroll is using scroll-wheel functionality on my mouse.

**Comment by aidanholm** [comment]
This is a relatively common site-specific issue; it happens when sites don't scroll the main body element. Unfortunately there's not much luakit can do about this. The site behaves the same in chrome, for example.

**Comment by dlobue** [comment]
@aidanholm chromium with cvim is still able to work on the site however by allowing you to switch scrolling focus to a different div/frame/whatever by clicking it. Would that be possible to implement?
