### ISSUE TITLE
luakit get stuck and start using all the CPU when closing the last tab

### ISSUE THREAD

**Issue by iamleot** [luakit/luakit#725]
When closing the last tab and when `window.close_with_last_tab` setting is `false` (default) luakit is no longer responsive (despite some events appears when invoked via `--log=DEBUG`) and start using all the CPU.

**Comment by c0dev0id** [comment]
Does this still occur for you people?

I tried to reproduce it with the current luakit and the CPU dropped to zero after closing the last tab.

Video: https://codevoid.de/h/luakit_cpu.mp4

**Comment by iamleot** [comment]
At least for me, yes, I can still reproduce it with current Git HEAD.
