### ISSUE TITLE
how to disable or change shortcuts 

### ISSUE THREAD

**Issue by rikhtehgaran** [luakit/luakit#735]
i want to use inspect element to add font-size on an html but it always Follows when i type f in css styles and it drives me crazy. i don't need any shortcut how can i disable all or change it .
it's very buggy it conflicts to type something with shortcut

**Comment by c0dev0id** [comment]
Hi,
yes, this is a known issue. You can switch to pass through mode with `ctrl+z`. This disables the the luakit bindings until you press ESC. I hope this helps for now.
