### ISSUE TITLE
A page with javascript causes permanent high CPU load

### ISSUE THREAD

**Issue by c0dev0id** [luakit/luakit#736]
## I'm submitting a…
Bug Report

## Current Behavior
Opening a page with Javascript causes permanent high CPU load. (~60%+ on my machine)

## Expected Behavior
After the page has rendered, I expect the CPU load to drop.
I tested with vimb and surf. Both behave as expected.

## Reproduction Instructions
Open github.com in luakit and wait until it is loaded. The CPU utilization will not go down.

Starting luakit with --log=debug will show a loop of eval_js being triggered. This output will repeat until the page is closed. It will also stop when I switch to another tab (without JS):
```
[   21.268112] D [core/common/luaobject]: emit "expose" on 0x41bb7128 from <GTK> (0 args, 0 nret)
[   21.268737] D [core/common/ipc]: Process 'UI': send eval_js message
[   21.284657] D [core/common/ipc]: Process 'Web[16030]': recv eval_js message
[   21.284990] D [core/common/ipc]: Process 'Web[16030]': send eval_js message
[   21.285047] D [core/common/ipc]: Process 'UI': recv eval_js message
[   21.285365] D [core/common/luaobject]: emit "expose" on 0x41bb7128 from <GTK> (0 args, 0 nret)
[   21.285612] D [core/common/ipc]: Process 'UI': send eval_js message
[   21.302965] D [core/common/ipc]: Process 'Web[16030]': recv eval_js message
[   21.303076] D [core/common/ipc]: Process 'Web[16030]': send eval_js message
[   21.303143] D [core/common/ipc]: Process 'UI': recv eval_js message
```

## Environment

Linux Distribution & Version: Debian Stretch
Output of `luakit --version`:
```
luakit 2017.08.10-381-gfc07ed5a
  built with webkit 2.22.3 (installed version: 2.22.3)
```

Probably related to #725 and #726

**Comment by aidanholm** [comment]
This looks like `lib/lousy/widget/scroll.lua` is constantly recalculating the current scroll position, using JS, which it does whenever the page is exposed (re-rendered). I'm not sure why it'd be constantly re-rendering, or that recalculating the scroll position would cause that...

**Comment by c0dev0id** [comment]
Yes and no. The scroll widget is triggered within the loop. If you deactivate the scroll widget, the loop is still there and will loop with the "expose" event triggered in luaobject.

On some pages, the loop eventually stops. On github it goes forever. On stackoverflow it stops. Interesting is openbsd.org where it stops, then starts again then stops again.

Something is triggering the re-rendering.

Without the scroll widget it looks like this:
```
[  497.839853] D [core/common/luaobject]: emit "expose" on
0x116f7cc0 from <GTK> (0 args, 0 nret)
[  497.872660] D [core/common/luaobject]: emit "expose" on
0x116f7cc0 from <GTK> (0 args, 0 nret)
[  497.889633] D [core/common/luaobject]: emit "expose" on
0x116f7cc0 from <GTK> (0 args, 0 nret)
```

**Comment by c0dev0id** [comment]
I've de-implemented the draw event (expose_cb) entirely. Better now... didn't break anything I notice. Tests run.

EDIT: Tested on linux - doesn't help at all.

**Comment by 7415963987456321** [comment]
Any progress on this?

**Comment by aidanholm** [comment]
@c0dev0id In that case it's likely a webkit bug. Not sure that there's much to do in that case. :/
@7415963987456321 unfortunately not

**Comment by c0dev0id** [comment]
Actually, there is an update. I've disabled all hardware acceleration in `:settings` Hardware Acceleration => none, Accelerated Canvas => disabled. The permanent 20% CPU I had just sitting on github dropped to 4%.

I also can watch youtube with 15% CPU, which was a 60% CPU job before. And it even feels snappy!

Before, the luakit process itself was at 4% constantly. Now it's sitting at 0%.

I'm closing the issue, because this has solved it for me.

**Comment by hippi777** [comment]
hi there! :)

i had this issue randomly twice in the last 2 days, but on firefox, so what if its related to youtube but not any engines? :D

btw i dunno how to trigger it, just happened after watching much videos and surfing in the meantime, so im not even sure if yt was guilty, cuz i dont have a profiler for deciding wich page did it...

**Comment by c0dev0id** [comment]
For me it was on every js page. Not just youtube. Also github and others.
One indicator was that also the X(org) process had permanent high (above 10%) CPU utilization.

Firefox is always low here :)

**Comment by hippi777** [comment]
fine then :)
