### ISSUE TITLE
How is it possible to disable the popup menu which shows up on left button long-press?

### ISSUE THREAD

**Issue by Ben5501** [luakit/luakit#738]
Hello!

I try to find a way to completely disable the **popup menu** which shows up on long-press (on a Touch-Device) or right-click with a mouse.
Which i.e. shows entries like "back", "forward", "reload",... 

Is there a setting for that? 

I think it should work by catching the signal "populate-popup".
But how can we access that in rc.lua? 

Luakit: luakit 2017.08.10-370-gcdb32ac

**Comment by McSinyx** [comment]
I believe that is explicitly handled by WebKit. I also belive that Luakit is not designed to be touch-friendly either (I mean browsers like this are created as an effort to get somewhere close to mouse/touch browsing experience using keyboard only, mainly when we do multiple jobs with keyboard and reaching for a mouse isn't favorable -- if you are comfortable with touch, Firefox for instance would be better).

**Comment by aidanholm** [comment]
The `context_menu_cb` function in `webview.c` would need to be modified to check the popup menu entry table after the `populate-popup` signal finishes, and return `TRUE` if the entry table is empty. Disabling the popup menu from lua would then be simple; you'd need to add a signal handler for `populate-popup` and then remove all existing entries from the entry table it receives as an argument.

**Comment by Ben5501** [comment]
Thank you for your help.
Why has the `context_menu_cb` function to be modified? Is it not enough to clear the entries from the table in the signal handler? 
Could you give me further advice how to setup the signal handler in rc.lua? How is it possible to listen for the "populate-popup" signal?

**Comment by aidanholm** [comment]
I was wrong earlier; GTK apparently does detect when you give it an empty list of menu items, and doesn't show a menu in this case. So something like this should be sufficient:
```lua
webview.add_signal("init", function (v)
    v:add_signal("populate-popup", function (_, menu)
        for k in pairs(menu) do menu[k] = nil end
    end)
end)
```
This can be placed in your `rc.lua` file, and will disable the popup menu completely.

**Comment by Ben5501** [comment]
Yes, that works like charme. Thank you.

Will make i.e. Drag and Drop possible on a Touch-Device.
