### ISSUE TITLE
How is possible to disable tab history and reuse the same tab?

### ISSUE THREAD

**Issue by Ben5501** [luakit/luakit#739]
Is it possible to configure Luakit to *not* save the tab history and open it on startup?
We just want to open one URL which is given on Luakit startup like "luakit http://localhost" 

Luakit version: luakit 2017.08.10-370-gcdb32ac

**Comment by c0dev0id** [comment]
Hi,

have you tried `man luakit`? :-)

`luakit -U http://localhost` will do what you want.

But there are more options. If you don't want the tabhistory ever, you can comment
`local tabhistory = require "tabhistory"` in `rc.lua`.

If you want luakit to work without session management, you can comment the session handling at the end of rc.lua and replace it with a simple `window.new(uris)`. (this is what I do).

**Comment by Ben5501** [comment]
> have you tried man luakit? :-)

No, I have not checked the manual. Actually I did not know about it. Shame.
So thank you. I think one of the options will do the trick.

**Comment by c0dev0id** [comment]
I'm closing the issue. Please reopen it if you still have further questions to this topic.
