### ISSUE TITLE
compiling error in debian (WSL)

### ISSUE THREAD

**Issue by user0210** [luakit/luakit#748]
Hello, Im trying to compile from the debian/sid branch and get this error, when running "make":

philipp@PHIL-WIN-TAB:~/github/luakit$ make
luakit build options:
CC           = cc
LUA_PKG_NAME = luajit
LUA_BIN_NAME = luajit
CFLAGS       = -std=gnu99 -ggdb -W -Wall -Wextra -Werror=unused-result -pthread -I/usr/include/webkitgtk-4.0 -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/libdrm -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libsoup-2.4 -I/usr/include/libxml2 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/luajit-2.1 -I/usr/include/webkitgtk-4.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I./
CPPFLAGS     =  -DVERSION="debian/2.1"
LDFLAGS      =  -Wl,--export-dynamic -lgthread-2.0 -pthread -lwebkit2gtk-4.0 -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lsoup-2.4 -lgio-2.0 -lsqlite3 -lluajit-5.1 -ljavascriptcoregtk-4.0 -lgobject-2.0 -lglib-2.0
MANPREFIX    = /usr/local/share/man
DOCDIR       = /usr/local/share/luakit/doc
XDGPREFIX    = /etc/xdg
PIXMAPDIR    = /usr/local/share/pixmaps
ICONDIR      = /usr/local/share/icons/hicolor/scalable/apps
APPDIR       = /usr/local/share/applications

build targets:
SRCS     = web_context.c log.c luakit.c luah.c ipc.c common/lualib.c common/resource.c common/luah.c common/luaserialize.c common/luaclass.c common/ipc.c common/property.c common/luauniq.c common/luautil.c common/util.c common/luayield.c common/luaobject.c common/luajs.c common/clib/regex.c common/clib/luakit.c common/clib/ipc.c common/clib/utf8.c common/clib/timer.c clib/request.c clib/sqlite3.c clib/unique.c clib/xdg.c clib/luakit.c clib/download.c clib/ipc.c clib/msg.c clib/web_module.c clib/soup.c clib/stylesheet.c clib/widget.c widgets/socket.c widgets/stack.c widgets/label.c widgets/webview.c widgets/common.c widgets/notebook.c widgets/box.c widgets/scrolled.c widgets/paned.c widgets/overlay.c widgets/eventbox.c widgets/window.c widgets/spinner.c widgets/drawing_area.c widgets/image.c widgets/entry.c common/tokenize.c
HEADS    = log.h luah.h ipc.h globalconf.h web_context.h common/lualib.h common/resource.h common/signal.h common/property.h common/common.h common/luaserialize.h common/luaclass.h common/ipc.h common/luauniq.h common/luautil.h common/log.h common/util.h common/luah.h common/luayield.h common/luaobject.h common/luajs.h common/clib/luakit.h common/clib/ipc.h common/clib/msg.h common/clib/soup.h common/clib/utf8.h common/clib/timer.h common/clib/regex.h widgets/webview.h widgets/common.h clib/unique.h clib/widget.h clib/xdg.h clib/luakit.h clib/download.h clib/msg.h clib/web_module.h clib/soup.h clib/stylesheet.h clib/request.h clib/sqlite3.h  common/tokenize.h buildopts.h
OBJS     = web_context.o log.o luakit.o luah.o ipc.o common/lualib.o common/resource.o common/luah.o common/luaserialize.o common/luaclass.o common/ipc.o common/property.o common/luauniq.o common/luautil.o common/util.o common/luayield.o common/luaobject.o common/luajs.o common/clib/regex.o common/clib/luakit.o common/clib/ipc.o common/clib/utf8.o common/clib/timer.o clib/request.o clib/sqlite3.o clib/unique.o clib/xdg.o clib/luakit.o clib/download.o clib/ipc.o clib/msg.o clib/web_module.o clib/soup.o clib/stylesheet.o clib/widget.o widgets/socket.o widgets/stack.o widgets/label.o widgets/webview.o widgets/common.o widgets/notebook.o widgets/box.o widgets/scrolled.o widgets/paned.o widgets/overlay.o widgets/eventbox.o widgets/window.o widgets/spinner.o widgets/drawing_area.o widgets/image.o widgets/entry.o common/tokenize.o
EXT_SRCS = extension/scroll.c extension/script_world.c extension/log.c extension/extension.c extension/ipc.c extension/luajs.c extension/clib/soup.c extension/clib/luakit.c extension/clib/ipc.c extension/clib/msg.c extension/clib/dom_element.c extension/clib/dom_document.c extension/clib/page.c common/lualib.c common/resource.c common/luah.c common/luaserialize.c common/luaclass.c common/ipc.c common/property.c common/luauniq.c common/luautil.c common/util.c common/luayield.c common/luaobject.c common/luajs.c common/clib/regex.c common/clib/luakit.c common/clib/ipc.c common/clib/utf8.c common/clib/timer.c common/tokenize.c
EXT_OBJS = extension/scroll.o extension/script_world.o extension/log.o extension/extension.o extension/ipc.o extension/luajs.o extension/clib/soup.o extension/clib/luakit.o extension/clib/ipc.o extension/clib/msg.o extension/clib/dom_element.o extension/clib/dom_document.o extension/clib/page.o common/lualib.o common/resource.o common/luah.o common/luaserialize.o common/luaclass.o common/ipc.o common/property.o common/luauniq.o common/luautil.o common/util.o common/luayield.o common/luaobject.o common/luajs.o common/clib/regex.o common/clib/luakit.o common/clib/ipc.o common/clib/utf8.o common/clib/timer.o common/tokenize.o

luajit ./build-utils/gentokens.lua common/tokenize.list common/tokenize.h
sed -e 's#LUAKIT_INSTALL_PATH .*#LUAKIT_INSTALL_PATH "/usr/local/share/luakit"#' \
        -e 's#LUAKIT_CONFIG_PATH .*#LUAKIT_CONFIG_PATH "/etc/xdg"#' \
        -e 's#LUAKIT_DOC_PATH .*#LUAKIT_DOC_PATH "/usr/local/share/luakit/doc"#' \
        -e 's#LUAKIT_MAN_PATH .*#LUAKIT_MAN_PATH "/usr/local/share/man"#' \
        -e 's#LUAKIT_PIXMAP_PATH .*#LUAKIT_PIXMAP_PATH "/usr/local/share/pixmaps"#' \
        -e 's#LUAKIT_APP_PATH .*#LUAKIT_APP_PATH "/usr/local/share/applications"#' \
        -e 's#LUAKIT_LIB_PATH .*#LUAKIT_LIB_PATH "/usr/local/lib/luakit"#' \
        buildopts.h.in > buildopts.h
cc -c web_context.c -o web_context.o
cc -c log.c -o log.o
cc -c luakit.c -o luakit.o
cc -c luah.c -o luah.o
cc -c ipc.c -o ipc.o
cc -c common/lualib.c -o common/lualib.o
cc -c common/resource.c -o common/resource.o
cc -c common/luah.c -o common/luah.o
cc -c common/luaserialize.c -o common/luaserialize.o
cc -c common/luaclass.c -o common/luaclass.o
cc -c common/ipc.c -o common/ipc.o
cc -c common/property.c -o common/property.o
cc -c common/luauniq.c -o common/luauniq.o
cc -c common/luautil.c -o common/luautil.o
cc -c common/util.c -o common/util.o
cc -c common/luayield.c -o common/luayield.o
cc -c common/luaobject.c -o common/luaobject.o
cc -c common/luajs.c -o common/luajs.o
cc -c common/clib/regex.c -o common/clib/regex.o
cc -c common/clib/luakit.c -o common/clib/luakit.o
cc -c common/clib/ipc.c -o common/clib/ipc.o
cc -c common/clib/utf8.c -o common/clib/utf8.o
cc -c common/clib/timer.c -o common/clib/timer.o
cc -c clib/request.c -o clib/request.o
cc -c clib/sqlite3.c -o clib/sqlite3.o
cc -c clib/unique.c -o clib/unique.o
cc -c clib/xdg.c -o clib/xdg.o
cc -c clib/luakit.c -o clib/luakit.o
cc -c clib/download.c -o clib/download.o
cc -c clib/ipc.c -o clib/ipc.o
cc -c clib/msg.c -o clib/msg.o
cc -c clib/web_module.c -o clib/web_module.o
cc -c clib/soup.c -o clib/soup.o
cc -c clib/stylesheet.c -o clib/stylesheet.o
cc -c clib/widget.c -o clib/widget.o
cc -c widgets/socket.c -o widgets/socket.o
cc -c widgets/stack.c -o widgets/stack.o
cc -c widgets/label.c -o widgets/label.o
cc -c widgets/webview.c -o widgets/webview.o
cc -c widgets/common.c -o widgets/common.o
widgets/common.c: In function ‘luaH_widget_send_key’:
widgets/common.c:382:5: warning: ‘gdk_keymap_get_default’ is deprecated: Use 'gdk_keymap_get_for_display' instead [-Wdeprecated-declarations]
     if (!gdk_keymap_get_entries_for_keyval(gdk_keymap_get_default(),
     ^~
In file included from /usr/include/gtk-3.0/gdk/gdk.h:48,
                 from /usr/include/gtk-3.0/gtk/gtk.h:30,
                 from widgets/common.c:21:
/usr/include/gtk-3.0/gdk/gdkkeys.h:84:12: note: declared here
 GdkKeymap* gdk_keymap_get_default     (void);
            ^~~~~~~~~~~~~~~~~~~~~~
cc -c widgets/notebook.c -o widgets/notebook.o
cc -c widgets/box.c -o widgets/box.o
cc -c widgets/scrolled.c -o widgets/scrolled.o
cc -c widgets/paned.c -o widgets/paned.o
cc -c widgets/overlay.c -o widgets/overlay.o
cc -c widgets/eventbox.c -o widgets/eventbox.o
cc -c widgets/window.c -o widgets/window.o
cc -c widgets/spinner.c -o widgets/spinner.o
cc -c widgets/drawing_area.c -o widgets/drawing_area.o
cc -c widgets/image.c -o widgets/image.o
cc -c widgets/entry.c -o widgets/entry.o
luajit ./build-utils/gentokens.lua common/tokenize.list common/tokenize.c
cc -c common/tokenize.c -o common/tokenize.o
cc -o luakit web_context.o log.o luakit.o luah.o ipc.o common/lualib.o common/resource.o common/luah.o common/luaserialize.o common/luaclass.o common/ipc.o common/property.o common/luauniq.o common/luautil.o common/util.o common/luayield.o common/luaobject.o common/luajs.o common/clib/regex.o common/clib/luakit.o common/clib/ipc.o common/clib/utf8.o common/clib/timer.o clib/request.o clib/sqlite3.o clib/unique.o clib/xdg.o clib/luakit.o clib/download.o clib/ipc.o clib/msg.o clib/web_module.o clib/soup.o clib/stylesheet.o clib/widget.o widgets/socket.o widgets/stack.o widgets/label.o widgets/webview.o widgets/common.o widgets/notebook.o widgets/box.o widgets/scrolled.o widgets/paned.o widgets/overlay.o widgets/eventbox.o widgets/window.o widgets/spinner.o widgets/drawing_area.o widgets/image.o widgets/entry.o common/tokenize.o
sed: -e expression #1, char 25: unknown option to `s'
make: *** [Makefile:78: luakit.1] Error 1

## Environment
WSL with Wlinux (Debian)

**Comment by aidanholm** [comment]
The error above is: ```sed: -e expression #1, char 25: unknown option to `s'```. This issue is caused by the version in `CPPFLAGS = -DVERSION="debian/2.1"` containing a slash, which presumably comes from the branch name. This breaks the sed expression on line 78 of the `Makefile`, since it uses slashes as the delimiter.

@groolot any ideas?

**Comment by hippi777** [comment]
hi there! :)

you can use any char as a delimiter, i think even invisible ones like \1 or whatever. use | @ or # for a common choice (like s|x|y|). bash wont b against it as its in a doublequoted string, so they are meaningless there, and none of them will appear in versioning i believe... just stay in ascii127 range for making it sane, and avoid $ \ " and ' for a better world :D

btw u can still put an echo before that sed to know what was in $VERSION

it can come from:
- env
- make arguments
- in case of .git dir presents, then from `git describe --tags --always`
- if $Format is not an empty string then from whatever `$Format:%h$` is resolved to
- or finally this nice string (that cant trigger the current sed) "ERROR: Commit hash detection failure. Dear packager, please figure outwhat has gone wrong and or get in touch with us." (yep. "outwhat" would like to get an extra space for its happiness)

**Comment by hippi777** [comment]
btw im kinda expert in bash stuffs, so yell for me in case of need, those are even in the shallow parts of the sauce, so i can learn in the meantime (one day i wanna read all the sauce of lk, but thats still not 2morrow :D )
