### ISSUE TITLE
Can't get video playback

### ISSUE THREAD

**Issue by maca** [luakit/luakit#75]
I can't get video playback when I try in vimeo or youtube. In youtube I can get audio playback for some of the videos but in vimeo I get an error message.

I am on arch linux, do I have to install any codecs or anything?

**Comment by vitaly-zdanevich** [comment]
Already installed on my Ubuntu but still no YouTube :(

**Comment by hippi777** [comment]
hi there @vitaly-zdanevich :) i think this is the well-known user agent issue, search the issues for that and youtube. actually google makes some magic based on the user agent, so u need to change that to something common if this is the case... if that wont solve ur problem, then u can try to install from source, and if neither will help then only the others around can help, and even these were Aidan Holm's wisdoms that ive learned from him on the go actually :D

good luck! :)

**Comment by aidanholm** [comment]
As @szbnwer mentioned, it could be a user agent issue; the other common causes are needing to install some packages (sorry, can't remember which ones off the top of my head) and needing to adjust HW acceleration settings, specifically `settings.webview.hardware_acceleration_policy`.

What kind of error are you getting? Blank page, or youtube error message?
