### ISSUE TITLE
MHTML support

### ISSUE THREAD

**Issue by bodqhrohro** [luakit/luakit#758]
## I'm submitting a…
Feature Request

## Current Behavior
.mht files are downloaded only.

## Expected Behavior
View the contents in Luakit.

## Reproduction Instructions
[Sample files.](https://www.fileformat.info/format/mime-html/sample/index.htm)

## Environment

Linux Distribution & Version: Debian 10
Output of `luakit --version`: luakit 2.0.0
  built with webkit 2.22.5 (installed version: 2.22.5)

**Comment by aidanholm** [comment]
Unfortunately this depends on webkit adding support for mhtml files; it's not something that luakit can do by itself.
