### ISSUE TITLE
Feature request: user_stylesheet_uri to take a collection

### ISSUE THREAD

**Issue by martinjlowm** [luakit/luakit#76]
Currently `user-stylesheet-uri` only accepts one file.

In situations where adblock is used, it is not possible to also have a custom.css.
Say you both want adblock and a global font-size (or some other styling).

I could see it possible by reading a table of files, combine them to a final file and then pass that file to `user-stylesheet-uri`

Question is if this would be a feature worth having in the core or if it should be done externally. Any thoughts?

**Comment by aidanholm** [comment]
There's a `styles.lua` user styles module now.
