### ISSUE TITLE
Build Fails on GDK_WINDOW_XID

### ISSUE THREAD

**Issue by myf** [luakit/luakit#762]
## I'm submitting a…

Bug Report
## Current Behavior

When I run `make` on luakit it was looking for GDK_WINDOW_XID but could not find it

```
widgets/window.c:104:28: warning: implicit declaration of function ‘GDK_WINDOW_XID’; did you mean ‘GDK_WINDOW’? [-Wimplicit-function-declaration]
         lua_pushinteger(L, GDK_WINDOW_XID(
                            ^~~~~~~~~~~~~~
                            GDK_WINDOW
```
## Expected Behavior

it should build sucessfully

## Reproduction Instructions

make
## Environment

Linux Distribution & Version:
linux 4.20.12, Archlinux
Output of `luakit --version`:
current head on git `209bdeb776858656391ad139ab41d31907caf4b4`

**Comment by niksfirefly** [comment]
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS

```
luakit/widgets/window.c:104: undefined reference to `GDK_WINDOW_XID'
luakit/widgets/window.c:113: undefined reference to `GDK_WINDOW_XID'
collect2: error: ld returned 1 exit status
Makefile:69: recipe for target 'luakit' failed
make: *** [luakit] Error 1
```

**Comment by aidanholm** [comment]
What Gtk version are you building against? Mine is 3.24.5 and works fine. It's worth noting that I use [gtk-mushrooms](https://aur.archlinux.org/packages/gtk3-mushrooms/), but I wouldn't expect that to be `GTK_WINDOW_XID` to have been patched by that...

**Comment by niksfirefly** [comment]
packages 
libgtk-3-0, 3.22.30-1ubuntu2
libwebkit2gtk-4.0-37
any other requirements for debs?
