### ISSUE TITLE
An option to show both tab numbers and favicons

### ISSUE THREAD

**Issue by bodqhrohro** [luakit/luakit#765]
## I'm submitting a…
Feature Request

## Current Behavior
The `tab_favicons` module supports only replacing tab numbers with favicons, which makes keyboard navigation difficult.

## Expected Behavior
An option to display both favicons and tab numbers.

## Environment

Linux Distribution & Version: Debian 10
Output of `luakit --version`: luakit 2.0.0
  built with webkit 2.22.5 (installed version: 2.22.6)

**Comment by Jamesxu182** [comment]
Try

``` lua
lousy.widget.tab.label_format = '<span font="Monspace">{index}: </span>{title}'
```

in __userconf.lua__

**Comment by bodqhrohro** [comment]
Nice solution, thanks.
