### ISSUE TITLE
Javascript strict mode 

### ISSUE THREAD

**Issue by FredericGuilbault** [luakit/luakit#766]
When using luakit on raspberry for locally hosted nodejs app. 

## I'm submitting a Feature Request or help support

Hi, How to turn off the javascript strict mode. Sadly This break 3/3 of the nodejs app I use.
Error message complain about the use of const in the app code.

I saw there was a way to enable/dissable javascript but nothing about strict mode.

**Comment by c0dev0id** [comment]
Hi Frederic,

Strict-mode is something that has to be enabled/disabled within the javascript code.
Try this: [JS Strict Mode - Tryit Editor](https://www.w3schools.com/js/tryit.asp?filename=tryjs_strict_variable
)

Open the link in luakit. When hitting run, luakit will report an error on the console in the inspector. If you remove the "use strict" from the code, luakit will not show this error.

There is no way to force webkit to ignore the strict mode when it has been set by the developer.

However, there might be differences in the strict-mode handling. What you can do is the following:
- Check if it works in the gnome browser "epiphany" (which can be seen as a reference implementation)
  - if it works there, come back here - we can most likely make it work in luakit too
  - if it does not work there, it is an issue with either the app code or the webkit javascript implementation => report to webkit and/or the app developer.

If you add an example link/reproduction steps, I can look at the specific case.

**Comment by FredericGuilbault** [comment]
Got it, Thx. 

What confused me is the fact that apps are working under chromium.
