### ISSUE TITLE
World readable cookie.db

### ISSUE THREAD

**Issue by mason-larobina** [luakit/luakit#77]
Find an appropriate way to change the permissions on the `$XDG_{CACHE,CONFIG,DATA}_DIR/luakit` dirs to prevent other users peeking at a users cookies.db and other sensitive data (I.e. form data).

**Comment by c0dev0id** [comment]
Fixed with commits https://github.com/luakit/luakit/commit/092268122af4d512c10d367f0e9da35d2cb8ebb3 and https://github.com/luakit/luakit/commit/33930243cb3d54a45ab47e1ce5bf5747b025e6a0.
