### ISSUE TITLE
Configure custom follow hint CSS

### ISSUE THREAD

**Issue by nwallace** [luakit/luakit#770]
## Feature Request: Users can configure custom hint labels and overlay CSS styles for follow mode

Currently, follow hint labels and overlays are not configurable like other parts of the browser (menus, tabs, etc). Users should be able to customize hint label/overlay colors and font in the `theme.lua`.

Please correct me if this is possible and I just missed it.

## Work in progress

I started [a branch to implement this feature](https://github.com/luakit/luakit/compare/develop...nwallace:feature/follow-mode-theming). It adds some new fields in `theme.lua`, then interpolates those values directly into the CSS. This isn't a particularly safe approach.

Also, I couldn't figure out how to get my development build to use my user's custom theme overrides (from `~/.config/luakit/themes.lua`), so I haven't actually tested that users can override these values. I'm assuming that's handled by `lousy.theme`, but I haven't verified it.

Is this ready for a pull request, or should I change some aspects of the implementation?

**Comment by nwallace** [comment]
I realized my current approach might mess up existing installations when they upgrade. If a user already has a `theme.lua` file, it won't include these new styles, and the way I've implemented it, there's no fallback. In fact, it would generate invalid CSS, which might cause other problems... How should I handle this?

I can think of a couple of options:
1. I could add to [`default_theme` in `lib/lousy/theme.lua`](https://github.com/luakit/luakit/blob/develop/lib/lousy/theme.lua#L35), but that doesn't seem to be a common thing to do
2. I could fall back to hard-coded values right in `lib/follow.lua` if any of the theme fields are missing.

I'm thinking option 2 would be more in-line with the rest of the codebase... it looks like that's what's happening in `lib/lousy/widget/menu.lua`. Any preference?

**Comment by nwallace** [comment]
I went ahead and implemented a quick fix using fallbacks in `lib/follow.lua`. The fallback values are duplicates of the values in `config/theme.lua`, but I couldn't figure out a great way to DRY that up. Suggestions on that or the approach in general are welcome!

**Comment by hippi777** [comment]
hi there! :)

what about just putting the whole into a freestanding file that can be modified at will. (u can have a hint comment in it that suggests to make a backup before anything else.) so a working stuff that can be modified is just as great as a fallback but without messing with anything else, so if any1 wanna play with it, they will see the point when they mess up everything, but will know everything thats actually needed there...

bests! :)

**Comment by aidanholm** [comment]
PR looks pretty good! The usual way for people to customize the hint styles is just to directly set the `follow.stylesheet` variable, but I think that having some theme variables is good too.

DRYing this properly would probably mean revamping the theme system so that lua modules could register a set of namespaced theme keys along with their default values. Then the `config/theme.lua` file would be empty by default.
