### ISSUE TITLE
setting up homepage in userconf.lua

### ISSUE THREAD

**Issue by calocedrus** [luakit/luakit#772]
New luakit user here, just compiled the develop branch on Debian stretch (to be precise, Raspbian stretch).
I can launch luakit all right but if I want to setup my homepage by using a `~/.config/luakit/userconf.lua` I get an error : 
`[core/common/lualib] Lua error: attempt to index global 'settings' (a nil value)`

My userconf.lua simply contains:

`settings.window.home_page = "https://duckduckgo.com"`

If I comment out the above line luakit starts fine.
So what is the proper way to set one's home page? And how can userconf.lua be taken into consideration?
The issue of setting up the homepage is also mentioned in #719.

**Comment by aidanholm** [comment]
Hi! The cause of this is very simple: you need to import the settings module first.

You can do this by adding a `local settings = require "settings"` line above that:
```lua
local settings = require "settings"
settings.window.home_page = "https://duckduckgo.com"
```

Hope this helps!

**Comment by calocedrus** [comment]
It certainly does help! Thanks!

**Comment by aidanholm** [comment]
Great :) You're welcome!
