### ISSUE TITLE
many web pages appear blank

### ISSUE THREAD

**Issue by calocedrus** [luakit/luakit#773]
On a fresh luakit install (develop branch, Raspbian stretch), the page at https://github.com.luakit/luakit appears blank, as does that at duckduckgo and many others. But when I hover over the blank pages with the mouse pointer I do see some hyperlinks appearing at the bottom of the luakit window indicating the page may have been loaded fine but the content isn't shown. 
However the pages at luakit.github.io appear normally, google.com as well.
Why does the above pages appear blank? Is it a theme setting issue?

How may I solve this?

Note:
- `:lua w:notify(luakit.version.." / "..luakit.webkit_version)` returns 2.1-9-g08d7c763 / 2.18.6
- issue #636 seems to be related but I am not able to understand the logics behind solving the issue for me
- I had the luakit installed with the package manager of debian but uninstalled it as well as the old components located in /etc/xdg/luakit

**Comment by aidanholm** [comment]
These kinds of issues are pretty tough to debug. You could first try disabling the `webview.hardware_acceleration_policy` setting in luakit://settings/ as that often helps.

**Comment by sgerwk** [comment]
Same here, on a x86. Solution works, but is hard to implement since luakit://settings/ is one of the pages that appear blank. In the end, .local/share/luakit/settings was:

```
{{
["domain"]={2},
},
{
[""]={3},
},
{
["webview.hardware_acceleration_policy"]="never",
},
}
```

**Comment by sgerwk** [comment]
Forgot to say: I could make a part of the page visible by selecting a region and dragging it. Maybe this helps.

**Comment by aidanholm** [comment]
Ah, I should have mentioned this earlier (sorry!), but you can also do this:
```
:lua settings.webview.hardware_acceleration_policy = "never"
```
That can be run from command mode, or put in your rc file.

**Comment by calocedrus** [comment]
Aidan, I've added 

`settings.webview.hardware_acceleration_policy = "never" `

at the end of my `/etc/xdg/luakit/rc.local` and it seems all is well now!

Thanks!

**Comment by sgerwk** [comment]
In the end, this may be a gtkwebkit bug:

https://bugs.webkit.org/show_bug.cgi?id=197141

**Comment by aidanholm** [comment]
@sgerwk Thanks for the info!

**Comment by noboruma** [comment]
Still happening on Debian bullseye on `luakit` package version `1:2.2.1-1`
@calocedrus' solution works like a charm!

**Comment by taobert** [comment]
On rpi, you could also try increasing `gpu_mem` (per #903).
