### ISSUE TITLE
No way to reload userscripts without restarting the browser

### ISSUE THREAD

**Issue by bodqhrohro** [luakit/luakit#776]
## I'm submitting a…
Feature Request

## Current Behavior

While userstyles can be manually reloaded with the `:styles-reload` command, there is no such a command for userscripts. It makes testing them under LuaKit very inconvenient, as scripts are loaded only once at the browser start, and the same version is executed, even if the file was changed and disabled/enabled in `:userscripts` menu.

## Expected Behavior

A command to reload userscripts, similar to `:styles-reload`.

## Reproduction Instructions

Enable `userscripts` module, put some script in the `scripts` directory, start LuaKit, then change the script and reload a tab in LuaKit: the old version of script is executed again.

## Environment

Linux Distribution & Version: Debian 10.
Output of `luakit --version`: luakit 2.0.0
  built with webkit 2.22.6 (installed version: 2.22.7)

**Comment by taobert** [comment]
How sophisticated an implementation do you want Aidan?
This seems to only need a two line patch:
```
diff --git a/lib/userscripts.lua b/lib/userscripts.lua
index 71279ffe..e4431c8d 100644
--- a/lib/userscripts.lua
+++ b/lib/userscripts.lua
@@ -350,6 +350,10 @@ add_cmds({

     { "`, :uscripts", "List installed userscripts.",
         function (w) w:set_mode("uscriptlist") end },
+
+    { ":userscripts-reload, :uscripts-reload", "Reload installed userscripts.",
+        function (w) load_all() end },
 })

 local scripts_menu_rows = setmetatable({}, { __mode = "k" })
```
If a script is changed, then calling `:userscripts-reload` and reloading the page gives the new behaviour.

One caveat is that if the script is renamed/deleted, 
the old one is not removed from the list of available scripts,
but it can just be disabled in the `:userscripts` list if it's causing problems.

**Comment by aidanholm** [comment]
Hi @taobert, sorry for the slow response.

I'm not really familiar with the userscripts module, but that patch looks nice and simple to me. Handling renames/deletes would be preferred though -- I think just clearing all loaded userscripts before calling `load_all()` should do the trick.
