### ISSUE TITLE
Question / Feature: Disable caching entirely

### ISSUE THREAD

**Issue by thomas-reinhold** [luakit/luakit#777]
Hi everyone, 

I would like to know if there is a possibility to entirely disable browser caching in Luakit? I.e. in terms of a config variable or a code modification. Thank you very much for an answer!

  Best regards, 
       Thomas

**Comment by aidanholm** [comment]
Hi! There are two related settings provided by webkit; `webview.enable_page_cache` and `webview.enable_offline_web_application_cache`. The first one is the one which you're probably interested in. You can change those at luakit://settings/ or you could add a `settings.webview.enable_page_cache = false` line to your rc file. Hope this helps!

**Comment by thomas-reinhold** [comment]
That is exactly what I was looking for. Thank you very much, we'll check it out!
