### ISSUE TITLE
Youtube crash

### ISSUE THREAD

**Issue by delister** [luakit/luakit#781]
Hi, i read all issues related with this problem, but didn't find solution.
When i goes  to youtube home page or page with concretical video my system not respond. Don't work numlock and caps switch, but audio plays. Over some time (2 - 3 min) web page craches and system starts to work.

I rebuilded luakit with -O0 and -g3 flags and got error message:
`
luakit -v
`
`
...
"WebKitWebProcess: ../libdrm-2.4.97/nouveau/pushbuf.c:723: nouveau_pushbuf_data: Assertion kref failed."
...
`

I rebuilded webkit-gtk and mesa without support vaapi and vdpau and in this case video works, but very slowly: frame by frame...0.5 - 1 fps may be :)

System: gentoo
luakit: c5328c22
webkit-gtk: 2.24.1

**Comment by aidanholm** [comment]
Hi!

Unfortunately, this doesn't seem like a problem I can help with; it looks like a problem either with webkit or with nouveau :/ You could try changing the `webview.hardware_acceleration_policy
` setting in `luakit://settings/`. If that doesn't help, it's not ideal, but you could try using a script like https://github.com/luakit/luakit/wiki/Play-embedded-video-in-external-player to launch youtube videos in mpv, vlc, or similar. This is what I personally do (albeit with a slightly different script) as the youtube interface is quite slow for me as well.

**Comment by delister** [comment]
Ok, thx. I like solution with play video in external player. But some sites autoplay video and my system freeze. 
I found more one temporary solution, wich works for me is software rendering:
`LIBGL_ALWAYS_SOFTWARE=1 luakit`
It is what same what and `webview.hardware_acceleration_policy` in `luakit://settings/` ?

Video plays smoothly and it exclude problem with freeze. May be stronger loads CPU.

How you think ? If firefox use hardware render to play videos, then problem in webkit-gtk ?

**Comment by c0dev0id** [comment]
Are you using the intel graphics driver (i915)? Try setting `LIBGL_DRI3_DISABLE=1`. This solved quite a few problems with videos on my system.

**Comment by delister** [comment]
No, i use nouveau driver. I have tried it, but no effect. I think what it nouveau problem, because i found similar situation (https://forums.gentoo.org/viewtopic-t-1087046.html). There man installed proprietarry nvidia driver and video started play. But him now another problem.
