### ISSUE TITLE
I can't setup custom characters for hints

### ISSUE THREAD

**Issue by delister** [luakit/luakit#782]
I try setup custom characters for hint. In my rc.lua I added code from example:
```
 -- Add vimperator-like link hinting & following
local follow = require "follow"
-- Use a custom charater set for hint labels
local s = follow.label_styles
follow.label_maker = s.sort(s.reverse(s.charset("asdfqwerzxcv"))) 
```

But when I run luakit, I get error:

`[core/common/lualib]: Lua error: attempt to index local s (a nil value)`

I checked documentation: https://luakit.github.io/docs/modules/follow.html and didn't see property `label_styles`. And here I found another example:
```
local select = require "select"

select.label_maker = function ()
    local chars = charset("asdfqwerzxcv")
    return trim(sort(reverse(chars)))
end
```

But I got error:
` [core/common/lualib]: Lua error: attempt to call global charset (a nil value)`

How I can to setup it ?

luakit version: c5328c22

**Comment by c0dev0id** [comment]
Hi,

it looks like you're using a pretty old release. Maybe consider updating to version 2.1.

This works for me and I think it also worked in the August 2017 release...:

```
-- Use "qwertzuiopasfghjklyxcvbnm" for generating labels
local select = require "select"
select.label_maker = function (s)
    return s.trim(s.sort(s.reverse(s.charset("qwertzuiopasfghjklyxcvbnm"))))
end
follow.pattern_maker = follow.pattern_styles.match_label
```

**Comment by delister** [comment]
Thx, update to 2.1 helped me.
