### ISSUE TITLE
Multi account containers

### ISSUE THREAD

**Issue by delister** [luakit/luakit#783]
is it possible to make some analog this firefox plugin ?https://addons.mozilla.org/ru/firefox/addon/multi-account-containers/

It creates difirent types of tabs, e.g.: "Personal", "Banking", "Shoping", "Work". And the types have difirent spaces for storage cookie, history, some other things. So site opened in "Personal" tab can't "see" cookie from site wich were open in tab "Work".

How it can make ?

**Comment by c0dev0id** [comment]
This would need a url based separation of cache, cookies etc. I think this might be possible by launching additional and unrelated webkit instances. This would be a major undertaking...

It is certainly not the same, but you could start multiple luakit instances with different configurations.
```
alias luakit-facebook="luakit -Uc $HOME/.config/luakit/rc-personal.lua"
alias luakit-banking="luakit -Uc $HOME/.config/luakit/rc-banking.lua"
```

Within the configuration file, you would need to set independent cookie paths. Like...
```
soup.cookies_storage = luakit.data_dir .. "/cookies-personal.db"
soup.cookies_storage = luakit.data_dir .. "/cookies-banking.db"
```

That way you could have different luakit settings and launch them individually and they could not see each others cookies. I haven't tried it, but something like this may work.

**Comment by c0dev0id** [comment]
I'm closing this, because I think the feature request is too much of a stretch to implement. Also - no response from the ticket author in a while.

**Comment by samuelallan72** [comment]
@c0dev0id @delister I was trying to figure out something similar today and discovered this issue.  It looks like the `--profile` / `-p` arg may be useful here:

```
$ luakit -U -p banking
$ luakit -U -p personal
```

This isn't documented anywhere apart from the `luakit --help` menu.
