### ISSUE TITLE
Websites out of date

### ISSUE THREAD

**Issue by eikenb** [luakit/luakit#785]
Alternative browsers are getting some attention due to the Firefox add-on issue. You  might want to update your website. The couple issues I noticed...

1. You list http://luakit.org as the website in the github description, that domain seems to have expired.
2. https://luakit.github.io/, the website linked to from HN, has 2017-08-10 prominently displayed as the latest release. When in fact you have a much newer release (2.1) listed on github.

**Comment by aidanholm** [comment]
Thanks! Updated both of these.
