### ISSUE TITLE
Is there a way to set cache_dir?

### ISSUE THREAD

**Issue by alex3kov** [luakit/luakit#789]
## I'm submitting a...
Question / Feature Request

## Current Behavior
Luakit stores cache in defaut `~/.cache/luakit/` location with, as far as I can see, no way to change it. I found `luakit.cache_dir` property but it's read only. 

## Expected Behavior
Users are able to either set cache location (I'm trying to place it in /tmp/) or instruct Luakit to cache in memory. For example, here's how Firefox does it: [link](https://wiki.archlinux.org/index.php/Firefox/Tweaks#Turn_off_the_disk_cache)

## Reproduction Instructions
Try to change Luakit's cache location.

## Environment

Linux Distribution & Version: Parabola x86_64 (rolling)
Output of `luakit --version`:
luakit fc07ed5a
  built with webkit 2.24.1 (installed version: 2.24.1)

**Comment by aidanholm** [comment]
Unfortunately it's currently difficult to change that to a read-write variable, as it needs to be set before webkit starts. You could run luakit with `XDG_CACHE_HOME=/tmp` though, which should work. Hope this helps!

**Comment by alex3kov** [comment]
Thanks, I already did it another way: made a symlink ~/.cache/luakit ->
/tmp/luakit.cache and put `mkdir /tmp/luakit.cache` in startup script. It
just feels cleaner to me for some reason. Both ways work, hopefully this 
issue will help someone with the same goal (cache in /tmp/ to reduce SSD
writes).

**Comment by aidanholm** [comment]
Great! I'll close this issue then. Note that your browser cache being cleared every time you restart will affect browsing speed. You could wrap luakit in a script that moves the cache to /tmp when luakit starts and then back when it exits, if this matters to you.
