### ISSUE TITLE
rendering issue

### ISSUE THREAD

**Issue by jk121960** [luakit/luakit#79]
Hi, Love luakit the rendering actually got a lot better with the recent libkit upgrade. One thing though, most I ignore like the huge oversized controls etc, but certain things are not showing up at all. Example if you go to amazon.com the home page on the left side top there is a floating menu. This does not show at all. Granted the only webkit vi microbrowser it shows in is Jumanji but they did it somehow. I want to stick with luakit because of the configurability, but I dont want to not see stuff all togeather. I would appreciate you taking a look at this. 

thanks 

--jerry

**Comment by groolot** [comment]
In the 2017.06 update, this seems to not be reproducible.
