### ISSUE TITLE
Disable pinch/zoom 

### ISSUE THREAD

**Issue by tishma** [luakit/luakit#791]
I am looking for an option (either via a cmd line param - like in chromium, or `rc.lua` - that I'm comfortable modifying) - to disable two finger up/down or pinch zooming on a touchscreen connected to a linux box.

Is it possible and I just can't find it or should I just quit?

Thanks

**Comment by aidanholm** [comment]
Sorry for the very late reply; I've done some searching and I don't believe there's currently a way to disable this.

**Comment by c0dev0id** [comment]
I'm closing the issue due to inactivity. Feel free to reopen if there are additional questions.
