### ISSUE TITLE
gstreamer libraries installed but still cannot play videos

### ISSUE THREAD

**Issue by or-dan123** [luakit/luakit#793]
I have installed the following on webkit on arch:
gstreamer
gst-libav
gst-plugins-base
gst-plugins-good
gst-plugins-bad
gst-plugins-ugly

When I open a youtube video for example in luakit, I firstly see a circle loading on top of a white blank screen and after a few seconds I am prompted with youtube's snowscreen which informs me that "an error occured"

Firstly I thought it was a problem with webkit2gtk so I have reinstalled it and made sure it is installed with gstreamer libraries, then I recompiled luakit with the latest version, and unfortunately the problem still exist.  

Then just for debugging I installed gnome Web which also uses webkit2gtk, and when I play a video on gnome Web it works perfectly well with no issues at all. So I suspect that the issue is with luakit and not with webkit or gstreamer.

How do I fix it?
Thanks for the help!

**Comment by aidanholm** [comment]
Sorry for the very slow reply. Youtube is a site that luakit often has problems with. You could try changing the `webview.hardware_acceleration_policy` setting to 'never' on luakit://settings/. Another thing to try is changing your user agent to a chrome-like user agent; this has been known to help in the past. Hope this helps!

**Comment by or-dan123** [comment]
setting webview.hardware_acceleration_policy to never works like a charm thank you very much!

**Comment by aidanholm** [comment]
Great :)
