### ISSUE TITLE
Vertical tabs don't scroll automatically to fit the current tab

### ISSUE THREAD

**Issue by bodqhrohro** [luakit/luakit#794]
## I'm submitting a…
Bug Report

## Current Behavior
When I, for example, open a new tab with `t`, it's added below the viewport, so I need to manually scroll the vertical tabs panel to see it.

## Expected Behavior
The vertical tabs panel is automatically scrolled to fit the current tab.

## Reproduction Instructions
Open more tabs than fits to a screen, so a scrollbar appears.

## Environment

Linux Distribution & Version: Debian 10
Output of `luakit --version`: luakit 2.0.0
  built with webkit 2.22.6 (installed version: 2.24.2)

**Comment by bodqhrohro** [comment]
Clarification: it's actually **scrolled**, but the current tab does not fit completely. Like this:
![2019-07-03-195101_1366x768_scrot](https://user-images.githubusercontent.com/2134486/60610230-08eab700-9dcc-11e9-97ff-0c6a1fea124a.png)

**Comment by aidanholm** [comment]
Your screenshot shows a 6px margin around the tablist, which seems to not be accounted for when scrolling (tab height is 19px, and 19px - 2*6px = 5px, which is the visible height of the blue tab). Was this added intentionally, or is it a side effect of your system theme? Even after adjusting the margin with`:lua w.tablist.widget.margin = 6`, I still couldn't reproduce this.

**Comment by bodqhrohro** [comment]
>or is it a side effect of your system theme?

This: https://github.com/jgpws/jgd-cobalt-blue/blob/master/source-code/gtk-3.20/gtk-widgets.css#L1414
