### ISSUE TITLE
Add support for U2F/FIDO2

### ISSUE THREAD

**Issue by terlar** [luakit/luakit#795]
## I'm submitting a…
Feature Request

## Current Behavior
When trying to use U2F/FIDO2 via a YubiKey for example you are presented with a message like this from the site:
> Security key or built-in authenticator is not supported on this browser.

## Expected Behavior
When trying to use U2F/FIDO2 it should be recognized by the browser and allow the user to execute 2FA via pressing the button on the 2FA device. Perferably you wouldn't have to switch into insert mode before pressing the button and it should act as if in pass through mode during the authentication.

## Reproduction Instructions
A developer needs to have a YubiKey or another U2F provider. Then go to a site such as:
https://demo.yubico.com/u2f/

## Environment

Linux Distribution & Version:
- host os: `Linux 5.1.18, NixOS, 19.09.git.eadc8510514 (Loris)`
Output of `luakit --version`:
```
luakit fc07ed5a
  built with webkit 2.24.2 (installed version: 2.24.2)
```

**Comment by aidanholm** [comment]
This will probably have to be added at the WebKit level; it's not something that luakit can (or should) implement.

**Comment by terlar** [comment]
I see, perhaps it might even be partly supported, someone mentioned it being available as an experimental feature in webkit:
https://webkit.org/status/#feature-web-authentication

Is there a way to access "experimental features" in webkit?

**Comment by aidanholm** [comment]
You might have to build webkit2gtk yourself for that. For future reference, the umbrella bug for U2F/FIDO support is https://bugs.webkit.org/show_bug.cgi?id=181943.
