### ISSUE TITLE
How to Nav Backwards and Forwards?

### ISSUE THREAD

**Issue by johnyradio** [luakit/luakit#801]
## Current Behavior
Can't nav forward to backward to already-visited pages

## Expected Behavior
ALT-left arrow should nav to previous page visited

## Environment
arch linux
Output of `luakit --version`:
luakit 2.1
  built with webkit 2.24.3 (installed version: 2.24.3)

**Comment by alex3kov** [comment]
Luakit has vim-inspired keybindings, by default it's `H` for backwards and `L` for forward.

**Comment by aidanholm** [comment]
If you'd rather use alt-left and alt-right, you can easily replace the current bindings:
```lua
local modes = require "modes"
modes.remap_binds("normal", {
    { "<Alt-Left>", "H" },
    { "<Alt-Right>", "L" },
})
```

**Comment by johnyradio** [comment]
Great info!
- Thx

**Comment by aidanholm** [comment]
You're welcome!
