### ISSUE TITLE
Web inspector don't highlight elements

### ISSUE THREAD

**Issue by delister** [luakit/luakit#802]
Hello, when I hover mouse on element in web inspector, then don't highlight this element on web page. How I can fix it ? And more when I move mouse cursor in web inspector, then on web page work js handlers trigger by hover event.

luakit version: fc07ed5a

**Comment by aidanholm** [comment]
Sorry for the slow response! Unfortunately this is likely to be a webkit issue, and not something that we can fix in luakit. I also can't reproduce this issue. Could you try to reproduce this issue in epiphany? (Epiphany also uses webkit, so this will help verify the source of the issue)

**Comment by delister** [comment]
In epiphany also exist bug with when I move mouse on web inpector panel it trigger hover event on web page ( opens menu and etc.).

But don't exist other bug what don't highlight html elemetns selected in web inspector.

And more, if I wait sometime with opened webinspector, then start crached other tabs (in luakit) in epiphany i don't follow this, but maybe I didn’t wait long enough...

**Comment by c0dev0id** [comment]
Does this issue still exist? It seems to work here. When I open `:inspect` and move over elements in the HTML code in the inspector, the corresponding elements in the webview are highlighted.

**Comment by aidanholm** [comment]
Seems fixed. Feel free to reopen if it reoccurs :)
