### ISSUE TITLE
Strange font substitutions.

### ISSUE THREAD

**Issue by zappathustra** [luakit/luakit#805]
Strange issue lately. Some characters are substituted (somehow as if they were missing in the font). For instance:

![screenshot](https://user-images.githubusercontent.com/1642300/64958446-75d00200-d88f-11e9-927a-27b121f408f9.png)

This happens completely at random. It may happen on one page and then not anymore if you close and relaunch Luakit on the same page. It happens or not, or affects different letters, depending on the zoom level.

Couldn't make it happen with Epiphany, but I havent tried very hard...

Running on Arch with webkit2gtk 2.24, given bug #804.

**Comment by alex3kov** [comment]
Happens to me too.

**Comment by gersonamoriz** [comment]
This is also happening to me ..

**Comment by aidanholm** [comment]
Yep, I'm seeing this too; also on arch with webkit2gtk 2.24

**Comment by gersonamoriz** [comment]
Does anyone seeing this bug, normally access Websites that contain  different languages ?

**Comment by gersonamoriz** [comment]
if so, do you have several locales generated or only for one Language ?

**Comment by zappathustra** [comment]
> Does anyone seeing this bug, normally access Websites that contain different languages ?
> if so, do you have several locales generated or only for one Language ?

I access websites in French and English, and my locale is only generated for French.

**Comment by gersonamoriz** [comment]
> > Does anyone seeing this bug, normally access Websites that contain different languages ?
> > if so, do you have several locales generated or only for one Language ?
> 
> I access websites in French and English, and my locale is only generated for French.
Thanks, I hope thi others answer too, I do too in several languages, my Locale is us_UTF ..

**Comment by alex3kov** [comment]
> Does anyone seeing this bug, normally access Websites that contain different languages ?
> if so, do you have several locales generated or only for one Language ?

I'm seeing this on English-only websites. I do have several locales generated (for English and Russian).

**Comment by zappathustra** [comment]
> > I access websites in French and English, and my locale is only generated for French.
>
> Thanks, I hope thi others answer too, I do too in several languages, my Locale is us_UTF ..

Oops, my bad: I also have en_US.utf8. I checked with `locale` instead of `locale -a`, and didn't realize it didn't sound right.

**Comment by gersonamoriz** [comment]
I personally have tested having all the locales relevant to the languages I use generated, but I am still seeing this bug, I have also tested with the original locale from my OS, and I am still seeing the bug.
I have also noticed than if zoom out or in a couple of times, then everything is ok, does this apply to any of you ?

**Comment by gersonamoriz** [comment]
If anyone wants to try this, here it is: (I am still testing after an Hour of Browsing)

Generate all Languages you use/visit locales but both UTF and ISO,
now clear cookies and if possible cache, and reopen browser.

**Comment by gersonamoriz** [comment]
> If anyone wants to try this, here it is: (I am still testing after an Hour of Browsing)
> 
> Generate all Languages you use/visit locales but both UTF and ISO,
> now clear cookies and if possible cache, and reopen browser.

Although, this makes no much sense, unless something to do with logging to console, or sandboxing issue, this seems to have gon away for the moment, please let me know if anybody has done this with no success.

**Comment by isovector** [comment]
@gersonamoriz how do you do these things? I've been running into this issue for a few weeks now and would love a fix.

**Comment by gersonamoriz** [comment]
> @gersonamoriz how do you do these things? I've been running into this issue for a few weeks now and would love a fix.
I am not sure to know what you mean by that, these things ? generating locales ?

**Comment by zappathustra** [comment]
I haven't seen the problem in a while. Still running webkit2gtk 2.24 though. Anybody else?

**Comment by c0dev0id** [comment]
Same here. I haven't seen this issue in quite a while. Is this still happening to anyone?

**Comment by aidanholm** [comment]
I haven't seen this in a long time either, so closing as not reproducible -- feel free to reopen if this still affects you though.
