### ISSUE TITLE
Update security warning on home page

### ISSUE THREAD

**Issue by technomancy** [luakit/luakit#806]
## I'm submitting a documentation bug report

Under "Important WebKit Security Notice" on https://luakit.github.io/ it says that "Debian and OpenSUSE ship outdated and vulnerable versions in their stable channel." However, the latest Debian stable (buster) includes security updates for Webkit now: https://blogs.igalia.com/berto/2019/08/26/the-status-of-webkitgtk-in-debian/ So Debian can be included in the list of distros which ship an acceptable version.

**Comment by aidanholm** [comment]
Great, thanks for notifying me; I've updated the warning message.
