### ISSUE TITLE
Did not load config with deifferent profile

### ISSUE THREAD

**Issue by delister** [luakit/luakit#809]
## I'm submitting a…
Question

## Current Behavior
When I run luakit without --profile argument, luakit load rc.lua from /home/user/.config/luakit/rc.lua. But if I run luakit with --profile argument, then rc.lua don't load from home dir.

## Expected Behavior
I don't know, may be exist special path for configs per profile ?

## Environment

Linux Distribution Gentoo 4.19.72
Output of `luakit --version`:
```
luakit fc07ed5a
  built with webkit 2.24.4 (installed version: 2.24.4)
```

**Comment by delister** [comment]
For each profile config dir is `~/.config/luakit/[PROFILE NAME]`

**Comment by chomwitt** [comment]
where does luakit keeps profile data ? I just created a new profile named 'clang' opened two pages quit and reponed . luakit reopened my pages but 
/home/chomwitt/.config/luakit/clang/ is empty (no hidden files either).

**Comment by chomwitt** [comment]
Ok. i found it! 
/home/chomwitt/.local/share/luakit/clang/
