### ISSUE TITLE
How to abort load page before request send ?

### ISSUE THREAD

**Issue by delister** [luakit/luakit#811]
I want to programmatically cancel load page for specific url with custom logic. And I want to make it before request will send. How I can make it ? Tnx.

**Comment by aidanholm** [comment]
You'd need to write a web module and add a signal handler for the `send-request` signal. Return `false` from your signal handler to block the page load, and return nothing to allow it. See `lib/adblock_wm.lua` for an example at the bottom of the file.

**Comment by delister** [comment]
Thanks!
