### ISSUE TITLE
New instance when run luakit from terminal

### ISSUE THREAD

**Issue by delister** [luakit/luakit#812]
I run main luakit from awesome wm or over rofi. It create new instance. 
```bash
 ->  ps xf
 PID TTY      STAT   TIME COMMAND
15964 ?        Ssl    0:06 luakit
15974 ?        SLl    0:09  \_ /usr/libexec/webkit2gtk-4.0/WebKitWebProcess 4 23
15975 ?        SLl    0:00  \_ /usr/libexec/webkit2gtk-4.0/WebKitNetworkProcess 5 23
15986 ?        SLl    0:01  \_ /usr/libexec/webkit2gtk-4.0/WebKitWebProcess 7 26
16039 ?        SLl    0:01  \_ /usr/libexec/webkit2gtk-4.0/WebKitWebProcess 12 36
16093 ?        SLl    0:02  \_ /usr/libexec/webkit2gtk-4.0/WebKitWebProcess 15 39
```
Next, I run newsboat for read feed and when I want to open website in external browser (luakit), luakit open in new window with all tabs from main instance plus open new tab witj url from newsboat.

```bash
 ->  ps xf
 PID TTY      STAT   TIME COMMAND
15964 ?        Ssl    0:06 luakit
15974 ?        SLl    0:09  \_ /usr/libexec/webkit2gtk-4.0/WebKitWebProcess 4 23
15975 ?        SLl    0:00  \_ /usr/libexec/webkit2gtk-4.0/WebKitNetworkProcess 5 23
15986 ?        SLl    0:01  \_ /usr/libexec/webkit2gtk-4.0/WebKitWebProcess 7 26
16039 ?        SLl    0:01  \_ /usr/libexec/webkit2gtk-4.0/WebKitWebProcess 12 36
16093 ?        SLl    0:02  \_ /usr/libexec/webkit2gtk-4.0/WebKitWebProcess 15 39

13179 ?        Ss     0:00 urxvt
13180 pts/0    Ss     0:00  \_ bash
16940 pts/0    Sl+    0:00      \_ newsboat
16978 pts/0    Sl+    0:01          \_ /usr/bin/luakit
16995 pts/0    SLl+   0:00              \_ /usr/libexec/webkit2gtk-4.0/WebKitWebProcess 4 24
16996 pts/0    SLl+   0:00              \_ /usr/libexec/webkit2gtk-4.0/WebKitNetworkProcess 5 24
17006 pts/0    SLl+   0:00              \_ /usr/libexec/webkit2gtk-4.0/WebKitWebProcess 7 27
17011 pts/0    SLl+   0:01              \_ /usr/libexec/webkit2gtk-4.0/WebKitWebProcess 9 27
17012 pts/0    SLl+   0:00              \_ /usr/libexec/webkit2gtk-4.0/WebKitWebProcess 11 27
```

How I can run luakit from terminal what it didn't create new window (instance) ?

**Comment by c0dev0id** [comment]
Do you mean `luakit -U`?

**Comment by delister** [comment]
No, simple `luakit https://domain.com`. Also after run luakit from awesome wm or rofi, and then run `luakit http://some.site` from terminal (urxvt ex.) It open new window luakit.

**Comment by c0dev0id** [comment]
I meant you could try `luakit -U`.

If you need more:
I'm using luakit in spectrwm and I've deimplemented the whole session and tab behavior. This is all done a the bottom of [rc.lua](http://codevoid.de/1/git/dotfiles/file/.config/luakit/rc.lua.gph).

In my installation I've replace the whole session handling with a single line: `window.new(uris)`. This is pretty much perfect for a tiling WM.

**Comment by c0dev0id** [comment]
I'm closing the issue due to months without author response. Feel free to reopen it in case there are further questions.
