### ISSUE TITLE
Map keys to other keys?

### ISSUE THREAD

**Issue by or-dan123** [luakit/luakit#817]
Hello I am using both English and Hebrew keyboards. When I press for example the key ל which corresponds to k on English keyboards, I would expect it to execute the command binded to k, which it doesn't(because its to are not the same keys).

So my question is, can I bind in some way a key to a different key instead of binding two keys to the same command?
For example I can just bind ל to k, instead of binding ל and k to scroll up?

I am using debian 10
luakit 2.1-23-g18187d8e
  built with webkit 2.26.1 (installed version: 2.26.1)

**Comment by taobert** [comment]
Sorry, for the late reply, 
I believe what you're after is modes.remap_binds() (see luakit://help/doc/modules/modes.html).
I haven't tried it with Hebrew.

**Comment by or-dan123** [comment]
It does the job!
Thank you very much

**Comment by taobert** [comment]
That's great. 
Maybe close the issue so that people can focus on the others..:)
