### ISSUE TITLE
Blocking cookies in Luakit

### ISSUE THREAD

**Issue by MarcoBeishuizen** [luakit/luakit#825]
Is it possible to block (at least) 3rd party cookies in Luakit?

**Comment by aidanholm** [comment]
Third-party cookies are blocked by default; see `luakit://help/doc/modules/soup.html#property-accept_policy`. Finer-grained cookie-blocking is not really possible at the moment due to limited APIs from webkit.

**Comment by MarcoBeishuizen** [comment]
Ah, great didn't know that. Thanks.
Did find some old lua scripts for cookieblocking but they don't work on the current Luakit version. Standard blocking of third party cookies is great for now though.

**Comment by c0dev0id** [comment]
I think the question from the author has been answered. I'm closing the issue.

@MarcoBeishuizen: feel free to reopen it in case my assumption is wrong.
