### ISSUE TITLE
luakit doesn't keyboard-scroll on some pages

### ISSUE THREAD

**Issue by msdemlei** [luakit/luakit#826]
I'm submitting a Bug Report

## Current Behavior

On several pages – for me, https://ui.adsabs.harvard.edu/ would be the most important one –, luakit doesn't scroll a page when the space bar is pressed.  Of course, j/k-scrolling doesn't work either.

Interestingly, once I enable passthrough mode, spacebar-scrolling does work, so it seems it's not a webkit problem.  However, as a could-it-be-related item, buster chromium, even with the input field unfocused, needs a click somewhere on the web page before it starts spacebar-scrolling.

## Expected Behavior

Luakit scrolls a page when I press space (with or without passthrough) whenever no text input is focused.

## Reproduction Instructions

Go to https://ui.adsabs.harvard.edu/ (or, if you're in an German ICE train, the train info portal, which exhibits the same behaviour), unfocus any input the web page may have focused by default, hit space.

## Environment

Linux Distribution & Version: Debian buster

Output of `luakit --version`: luakit 2.1-29-ga023d261, built with webkit 2.26.3 (installed version: 2.26.3)

The buster luakit (luakit 2.0.0 built with webkit 2.22.6 (installed version: 2.26.3) also shows this behaviour.

I'm happy to try and debug this, but a hint as to where I ought to look first would be most welcome.

**Comment by taobert** [comment]
Well, it's not really a solution, but here's a bit more detail...
 
What's happening (i believe) is that `https://ui.adsabs.harvard.edu/styles/css/styles.css` sets `body`,`html` and `.app-container` to  `height: 100%;` which makes all these elements the size of the window. It then stipulates `overflow-y: scroll;` for `.app-container`, which i guess allows it to be scrolled by the mouse wheel, but not the keyboard. I can confirm that in pass-through, space and arrow keys scroll (but obviously not luakit specific binds).

I'm able to work around the key-based scrolling problems by removing the explicit height from `.app-container`:

```
@-moz-document domain('ui.adsabs.harvard.edu'){
   #app-container { height: auto !important; }
}
```

edit: setting `height: auto` for `html` or `body` also works, and may be more portable.

**Comment by msdemlei** [comment]
On Fri, Mar 27, 2020 at 03:28:55AM -0700, taobert wrote:
> Well, it's not really a solution, but here's a bit more detail...
>  
> What's happening (i believe) is that
> `https://ui.adsabs.harvard.edu/styles/css/styles.css` sets
> `body`,`html` and `.app-container` to  `height: 100%;` which makes
> all these elements the size of the window. It then stipulates
> `overflow-y: scroll;` for `.app-container`, which i guess allows it
> to be scrolled by the mouse wheel, but not the keyboard. I can

Oh wow.  Based on this, I hoped that perhaps using some other height
to base the scrolling on might fix the problem (that isn't all that
rare, so I suspect this is a pattern set by one of those javascript
"frameworks").

Alas, all of clientHeight, scrollHeight and offsetHeight on
document.body as well as the getBoundingClientRect just are the
window size.

Sigh.  Why can't people leave the browsers alone?

Anyway: Does anyone have an idea how one could figure out the true
height for such documents without breaking anything else and without
having to dig too deeply into the DOM?

**Comment by taobert** [comment]
I may be misunderstanding your further questions, so forgive me if i'm going off on a tangent and being unduly patronising. In this case, i don't see that you need to figure out the true height yourself, you just have to override the site style, and tell the browser to figure it out (`height: auto`). You can put the style snippet i gave you:
```
@-moz-document domain('ui.adsabs.harvard.edu'){
   html { height: auto !important; }
}
```
 in a file in your user-styles directory (mine is `~/.config/luakit/styles/`). You might then have to do a `:styles-reload` in luakit, and make sure it's enabled in `:styles-list`.

**Comment by msdemlei** [comment]
On Sat, Mar 28, 2020 at 04:50:46PM -0700, taobert wrote:
> yourself, you just have to override the site style, and tell the
> browser to figure it out (`height: auto`). You can put the style
> snippet i gave you:
> ```
> @-moz-document domain('ui.adsabs.harvard.edu'){
>    html { height: auto !important; }
> }
> ```
>  in a file in your user-styles directory (mine is
>  `~/.config/luakit/styles/`). You might then have to do a
>  `:styles-reload` in luakit, and make sure it's enabled in
>  `:styles-list`. 

Thanks for the workaround, but since this kind of thing isn't
terribly rare (as said in the original report, serveral pages on the
Deutsche Bahn train portals show the same misbehaviour), it would
rather clearly be preferable if luakit didn't need style overrides.

Now, the rendering engine apparently knows the true size of the
page, or else it couldn't keyboard scroll in passthrough mode.  If
we knew where it spits out that information, we could fix
extensions/scroll.c (which would be desirable anyway since
webkit_dom_element_get_scroll_width and friends give deprecation
warnings these days).

That's what I was asking: Does anyone have sufficient DOM fu to guess
where that actual size might be exposed?  Perhaps even in a way that
it properly works on "normal" pages, too?

**Comment by taobert** [comment]
> ...this kind of thing isn't
> terribly rare ... it would
> rather clearly be preferable if luakit didn't need style overrides.

I agree absolutly, but a real solution is (curently) beyend my ken.

**Comment by hippi777** [comment]
hi there! :)

in firefox, it scrolls down on hitting space, so i think it has a general solution, maybe u could ask them at least for a pointer to their sauce. otherwise, in the worst case, i believe that a scroll event could be propagated to the right place as a more general solution, and then u dont need to understand every css of every affected page, but find the right place only and register it... but this is still a hack... :D 

bests! :)

**Comment by msdemlei** [comment]
> in firefox, it scrolls down on hitting space, so i think it has a
> general solution, maybe u could ask them at least for a pointer to their

Well, it actually scrolls in luakit, too, when you pass through the
space keyboard event, as that eventually bubbles through to the
pseudo-scrolling element.  But there's no way this could be useful for
luakit, in particular because we'd like to scroll with hjkl, too.

I've poked around for other reasonable workarounds, and I am now
satisfied there are none, and we can only do userstyles until hopefully
the particular "css toolkits" that do this kind of thing vanish again.

Hence, I'm closing this report.  Thanks to all who provided hints.
