### ISSUE TITLE
Compiling with GCC 10

### ISSUE THREAD

**Issue by gleachkr** [luakit/luakit#846]
## I'm submitting a…

Bug report

## Current Behavior

Currently compiling under gcc 10 produces a number of linker errors, which I think are related to a patch that turns on the `-fnocommon` flag by default. Adding `-fcommon` to the CFLAGS in config.mk allows normal compilation.

## Expected Behavior

Compiling without error

## Reproduction Instructions

Try to compile the current development branch on a system with gcc 10

## Environment

Encountered on a fresh arch linux install.

**Comment by msdemlei** [comment]
Well, -fcommon is a bit of a hack, and so I'd suggest we rather merge PR #837 (which I've just fixed... ahem).

**Comment by gleachkr** [comment]
closed by 4efe52b8179d4ab7f782e319b38101e197dc2ade?

**Comment by aidanholm** [comment]
Yup, thanks!
