### ISSUE TITLE
Tag new release?

### ISSUE THREAD

**Issue by craftyguy** [luakit/luakit#847]
The current release in distros now has a few issues with the latest webkit2gtk (high CPU usage, etc) that are resolved already in the master branch. Is it time to consider tagging a new release?

I suppose there are still some open MRs that probably need to be merged before that happens (e.g. #837)..

**Comment by craftyguy** [comment]
@aidanholm thoughts?

**Comment by aidanholm** [comment]
Sorry for the slow response; `develop` is still affected by https://github.com/luakit/luakit/issues/804, and I'm inclined to not release until that's fixed. Unfortunately I have little time to contribute to luakit at the moment, but will try to look into the WIP fix soon.

**Comment by aidanholm** [comment]
Er, this may have been fixed actually! I'll do some more experiments...

**Comment by aidanholm** [comment]
Okay, yes, it's fixed :tada: I've also fixed the issue with blank new tabs, so I think we're probably ready for a release. I'll try to get one out sometime in the next few days.

**Comment by msdemlei** [comment]
In case some encouragement helps: I've been using the fixed version for a while now, and I've not encountered any problems.

Since current HEAD so much better than what's behind the most recent tag at this point, I'd say a tag is absolutely justified (I'd even say a release is fine, too, but something like 2.2-pre1 would make my gbp import-org --uscan happy, too).

**Comment by msdemlei** [comment]
Hm... this has gotten some extra urgency in that the package has been scheduled for autoremoval in testing because of bug #846 by 2020-08-06.

Now, if all else fails I can build from a git checkout, but it's extra work and hackery which I'd rather dodge.

**Comment by craftyguy** [comment]
@aidanholm how's it going? are there any remaining tasks that some of us could help out with to get a release tagged?

**Comment by aidanholm** [comment]
Just a matter of finding some free time, but I have tagged and released Luakit 2.2!
