### ISSUE TITLE
Unable to login on reddit (cannot load … due to access control checks)

### ISSUE THREAD

**Issue by Eragonfr** [luakit/luakit#848]
## Current Behavior
I'm not able to login on reddit because of `access control check`
(I've also these weird errors on github, but it's not blocking me on the login page)

## Expected Behavior
Be able to login

## Reproduction Instructions
Goto https://reddit.com/login and try to login

## Environment
I'm using the luakit-git package from Archlinux User Repository (AUR)
Linux Distribution & Version: Artix Linux OpenRC (Archlinux without systemd) Linux 5.6.14
Output of `luakit --version`: Luakit 2.1.36-ga188409e build with webkit 2.28.2 (installed version: 2.28.2)

But this error also appear when i use the release ( the luakit package in the community repository from archlinux)

**Comment by Eragonfr** [comment]
That seems to be related to the AdBlock, when I fully disable it(and also reload the login page multiples times) i can login

**Comment by aidanholm** [comment]
Strange; I can log in just fine with adblock fully enabled. Could you please retry with the latest `develop` commit and let me know if that works?

**Comment by Eragonfr** [comment]
It work now, I don't understand… I think it's fixed

**Comment by aidanholm** [comment]
I'm glad to hear it! I'll close this now, but feel free to reopen if this issue reappears :-)
