### ISSUE TITLE
[Windows] Luakit does not start

### ISSUE THREAD

**Issue by deopdeop** [luakit/luakit#849]
I am trying to run luakit on wsl1 (ubuntu) which seems to only support version 1.4 through the latest git release

When I run luakit I get this error on most sites I visit

root@DESKTOP-C4HVM66 ~/luakit# luakit
[    0.577765] I [core/luah]: Loading rc: /root/.config/luakit/rc.lua
[    0.754001] W [core/log]: not sure how to handle this one: '198'
[    0.765563] W [core/log]: not sure how to handle this one: '212'
[    0.774354] W [core/log]: not sure how to handle this one: '230'
[    0.794791] W [core/log]: not sure how to handle this one: '349'
[    1.150162] I [lua/adblock]: found 0 filter lists
[    1.305408] I [lua/styles]: found 0 user stylesheets
[    1.320248] I [core/web_context]: Web process count: 4
[    1.371985] W [core/log]: not sure how to handle this one: '(unknown)'
[    1.493767] W [lua/(unkn]: (unknown)
[    4.118035] I [lua/webview]: Requested link: https://luakit.github.io/ (text/html)
Failed to get the memory usage
[   11.432598] I [lua/webview]: Requested link: https://www.youtube.com/ (text/html)

(WebKitWebProcess:22224): Gdk-ERROR **: 19:22:26.465: The program 'WebKitWebProcess' received an X Window System error.
This probably reflects a bug in the program.
The error was 'GLXBadFBConfig'.
  (Details: serial 178 error_code 163 request_code 149 (GLX) minor_code 21)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

**Comment by craftyguy** [comment]
windows crap for linux is not Ubuntu, and the GLXBadFBConfig suggests that gtk (or X) are failing to get a gl context for display. Running luakit as root is probably a bad idea too.

**Comment by aidanholm** [comment]
You may be missing an X server for WSL.

**Comment by c0dev0id** [comment]
@deopdeop: As mentioned already, you need an X server for windows. I had this running with https://sourceforge.net/projects/xming/ for a while.

Please try another program, like xeyes first to confirm that X is working properly. If this works, then try luakit.

I'm closing the issue for now. Feel free to reopen it if you have further issues.
