### ISSUE TITLE
Is there a way to use DjView NPAPI plugin with Luakit Web Browser?

### ISSUE THREAD

**Issue by jsbien** [luakit/luakit#852]
Cf. e.g. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=962181

**Comment by bodqhrohro** [comment]
Are other plugins working for you? The support for GTK+2 NPAPI plugins was surely removed in WebKitGTK+ 2.26, and they could possibly break others as well.

**Comment by jsbien** [comment]
I'm no longer interested in Luakit Web Browser, as there is usable, although not perfect, DjVu extension for Firefox (https://djvu.js.org/)

**Comment by c0dev0id** [comment]
As the issue is already answered (NPAPI support got removed) and the Author is not interested in luakit anymore, I'm closing this issue.
