### ISSUE TITLE
Blank new tabs.

### ISSUE THREAD

**Issue by zappathustra** [luakit/luakit#854]
When links open automatically in a new tab (e.g. in Google news), a blank tab is created (and reloading is useless) as if `:tabopen` were used without an argument. Explicit `:tabopen website.com` works properly, though.

I'm using webkit 2.28 under Arch. I tried reverting to 2.26 to see if the problem came from there, but compilation aborted with an error.

**Comment by MarcoBeishuizen** [comment]
Isn't this the same as #834?
Patch e333849 should be reverted I think.

**Comment by zappathustra** [comment]
> Isn't this the same as #834?

Probably. I never use the menu with "Open in a new tab", but Ctrl+click or F instead, and they aren't affected, so I thought it was something different.
