### ISSUE TITLE
Missing navigator.mediaDevices

### ISSUE THREAD

**Issue by jakecoble** [luakit/luakit#855]
Despite having `webview.enable_media_stream` set to `true`, `navigator.mediaDevices` is undefined.

luakit 2.1-47-gb5245c58
  built with webkit 2.28.2 (installed version: 2.28.2)

**Comment by jakecoble** [comment]
Looks like this is consistent across webkit2gtk browsers, despite this appearing to be supported by webkit2gtk.

**Comment by jakecoble** [comment]
It appears that none of the webkit2gtk releases support WebRTC at the moment, despite a WebRTC implementation being present in the webkit2gtk codebase.

`webview.enable_media_stream` is not functional and won't be until webkit2gtk releases a version with WebRTC support.

**Comment by c0dev0id** [comment]
@jakecoble This is handled by webkit and not by luakit. Once WebRTC support is present, it should "just work". 

Epiphany is the webkit reference implementation. If it doesn't work there, there is little chance that another webkit browser (which are basically webkit wrappers) can do it.

I'm closing the issue, as there is nothing we can do about it right now.
