### ISSUE TITLE
Gentoo ebuild needs update and maintainer

### ISSUE THREAD

**Issue by vitaly-zdanevich** [luakit/luakit#856]
https://packages.gentoo.org/packages/www-client/luakit

I see the text `This package needs a new maintainer!`. And available is only testing version for amd64, would be nice to have x86 also.

![image](https://user-images.githubusercontent.com/3514015/88483465-d11f5600-cf70-11ea-82c2-07f17bf6049a.png)

**Comment by craftyguy** [comment]
Why don't you maintain the package on gentoo? :smile:

**Comment by vitaly-zdanevich** [comment]
I can try, if you approve me.

**Comment by craftyguy** [comment]
I can't approve you, but this is a Gentoos packaging thing, so try asking on gentoo's IRC channel (#gentoo on freenode)?

**Comment by vitaly-zdanevich** [comment]
Yes, I mean approve from your side too. Ok, I will try.

**Comment by craftyguy** [comment]
I don't represent luakit, but I don't see why their approval is necessary for you to package it.

**Comment by aidanholm** [comment]
@vitaly-zdanevich please feel free to package/maintain! In general there's no central decision making / process for repo-specific packages.

**Comment by uggedal** [comment]
I took the upstream live ebuild, added explicit lua version for make install, and it works without issues for 2.2: https://github.com/uggedal/overlay/blob/master/www-client/luakit/luakit-2.2.ebuild

**Comment by oz123** [comment]
The gentoo ebuild is updated. I'm willing to adopt the package. PR Sent.

**Comment by c0dev0id** [comment]
@oz123 Cool, 2.2.1 even. The .1 only contains a little fix I needed for the OpenBSD package. But this is fine. I'm closing this ticket then. Thanks a lot!
