### ISSUE TITLE
cannot load anything

### ISSUE THREAD

**Issue by brightersun99** [luakit/luakit#858]
## I'm submitting a…
Bug report

## Current Behavior
fails to load any URLs
urls, such as google, or other websites or even :binds do not load 
![staff_test_2020-09-10_10-56-39](https://user-images.githubusercontent.com/70897846/92751650-2dd6a480-f356-11ea-8c08-e784ae6d1d12.png)
[log_luakit.txt](https://github.com/luakit/luakit/files/5202701/log_luakit.txt)

## Expected Behavior
loads specified URLs

## Reproduction Instructions
on openbsd 6.7 release amd64, install luakit 
doas pkg_add luakit
attempt to open URLs on luakit

## Environment

Linux Distribution & Version: openbsd 6.7 release amd64
Output of `luakit --version`: luakit fc07ed5a
  built with webkit 2.28.2 (installed version: 2.28.4)

will attempt to build latest after this post

**Comment by c0dev0id** [comment]
I think you also wrote me per email. If so, there is no need to answer to my response. All questions I had are anwered here.

The issue you're having is fixed in the Luakit that comes with OpenBSD 6.8 (it's in -current) already.
You can use this port (https://codevoid.de/9/p/luakit-2.2.tgz) or fetch it from OpenBSD-current. It should work on OpenBSD 6.7 as well.

**Comment by brightersun99** [comment]
Sorry, my email provider told me that email failed to send. 
I will attempt to upgrade my system to CURRENT

**Comment by c0dev0id** [comment]
Actually, OpenBSD 6.8 beta is tagged already, so it's pretty much around the corner. If you wait a little, you don't need to go to current. But if you want to go to -current, this is how:
```
# sysupgrade -s
<reboot>
# pkg_add -u
# cd /usr && cvs -qd anoncvs@anoncvs.ca.openbsd.org:/cvs checkout -P ports
```

After that you have a current base system with current ports and packages.

Updating current works with the same commands, except that last one. You update the ports with:
```
# cd /usr/ports && cvs -q up -Pd
```
