### ISSUE TITLE
Error calling bind()

### ISSUE THREAD

**Issue by Tonus1** [luakit/luakit#865]
## I'm submitting a…
Bug Report

## Current Behavior
When running as normal user, got this error
[core/ipc]: Error calling bind(): Permission denied
## Expected Behavior
Luakit launch without error as with root account

## Reproduction Instructions
Build package with either compiler, with or without luajit

## Environment

Linux Distribution & Version: slackware current 
Output of `luakit --version`: 3859dasen9

**Comment by c0dev0id** [comment]
Can your user write to the `/tmp` directory?

When Luakit is started, it creates a `/tmp/luakit-ipc-<randomchars>` socket. If it can't do this, the mentioned error occurs.

**Comment by c0dev0id** [comment]
No reaction for 3+ months => closing.

**Comment by Tonus1** [comment]
Sorry, didn't saw your answer. I do not remember how I delt with that but might have downgraded... I will look at that

**Comment by Tonus1** [comment]
You spotted the culprit, thanks. I might have something wrong in my build script. I will study that.
