### ISSUE TITLE
luakit crashes when opening more than ~45 tabs

### ISSUE THREAD

**Issue by craftyguy** [luakit/luakit#867]
## I'm submitting a…
bug report

## Current Behavior
luakit crashes when ~45 tabs are open. This is printed to the console when luakit is run with `--verbose`:

```
[   20.032758] F [glib]: (unknown): Unable to fork a new child process: Failed to fork (Resource temporarily unavailable)
```

## Expected Behavior
luakit should handle more open tabs

## Reproduction Instructions
open luakit, and start opening links in new tabs until you get >45

## Environment
Linux Distribution & Version: Arch Linux
Output of `luakit --version`: 

```
luakit 2.2.1-2-g53ed76fb
  built with webkit 2.30.1 (installed version: 2.30.1)
```

**Comment by c0dev0id** [comment]
Hello,

I've successfully opened 60 tabs here on NetBSD. The error you're getting indicates that you might hit an OS limit.

Which OS/Version are you  using?
Please execute `ulimit -a` with the same user you're running luakit with and post the output here.

Luakit forks a webkit process for each tab. If the process limit is low enough, the OS does not allow a new fork.

I've tested it by executing `luakit -v <60 URLs here>`. Can you reproduce it this way?

**Comment by c0dev0id** [comment]
When I keep opening tabs, I reach the limit here with 93.

```
(WebKitWebProcess:4258): GLib-ERROR **: 06:49:45.673: creating thread 'pool-spawner': Error creating thread: Resource temporarily unavailable

(WebKitWebProcess:1847): GLib-ERROR **: 06:49:45.940: creating thread 'send_thread': Error creating thread: Resource temporarily unavailable

(WebKitWebProcess:1581): GLib-ERROR **: 06:49:46.350: Creating pipes for GWakeup: Too many open files in system
```

ulimit -a
```
time(cpu-seconds)    unlimited
file(blocks)         unlimited
coredump(blocks)     unlimited
data(kbytes)         262144
stack(kbytes)        4096
lockedmem(kbytes)    1247698
memory(kbytes)       3743096
nofiles(descriptors) 1024
processes            1024
threads              1024
vmemory(kbytes)      unlimited
sbsize(bytes)        unlimited
```

In this case, the limit are the file descriptors. Appearently one webkit instance must consume about 110 file descriptors, so with 93 instances, the limit is reached. (the luakit main process also needs some)

EDIT: On my OpenBSD box, I was able to open 120 tabs. It took forever, but it worked (I did not try more).

**Comment by hippi777** [comment]
hi there! :) 

sorry for messing with the thread (however maybe it can be useful here) but is this mandatory? i still didnt switch to luakit after a very long while (((dont ask, my life is an ever growing mess, and i continuously have bigger issues... #devLife))) but i always have extreme amounts of tabs in firefox while i actually load max a few dozens of them simultaneously in a session (before restarting it :D ) so the question is whether it is possible to limit the worker threads? i plan to make profiles for different topics, but that will only reduce the amount of the total number of opened tabs (while bookmarks are for things i may never return to, but im willing to consider to use them, especially if i have a way to put them into a tree structure)

many thx for any help! :)

**Comment by craftyguy** [comment]
> Hello,
> 
> I've successfully opened 60 tabs here on NetBSD. The error you're getting indicates that you might hit an OS limit.
> 
> Which OS/Version are you using?

Arch Linux (kernel 5.8)

> Please execute `ulimit -a` with the same user you're running luakit with and post the output here.

```
❯ ulimit -a
-t: cpu time (seconds)              unlimited
-f: file size (blocks)              unlimited
-d: data seg size (kbytes)          unlimited
-s: stack size (kbytes)             8192
-c: core file size (blocks)         unlimited
-m: resident set size (kbytes)      unlimited
-u: processes                       4000
-n: file descriptors                1024
-l: locked-in-memory size (kbytes)  64
-v: address space (kbytes)          unlimited
-x: file locks                      unlimited
-i: pending signals                 127648
-q: bytes in POSIX msg queues       819200
-e: max nice                        0
-r: max rt priority                 0
-N 15:                              unlimited
```

Yeah you have to keep the tabs open, not just open/close a tab X times. I'm a little confused though because 45 * 110 > 1024 (the value above for max fd...) Unless the number of fd open on Linux per tab is less?

**Comment by c0dev0id** [comment]
@hippi777 
> so the question is whether it is possible to limit the worker threads?

It was possible. See https://github.com/luakit/luakit/blob/develop/config/rc.lua#L29 But WebKit took this away and the setting is ignored by current WebKit versions. There seems to be a single process mode, which doesn't work with luakit. But this would also mean that a webview crash would crash all your tabs.

@craftyguy 
Not sure if file descriptors are what's limiting you. But you could push them with `ulimit -n 2048` and see if it helps.

File descriptors are used by a lot of things ("everything is a file" in linux). So the number of FDs per process can be different for each OS and also depends which luakit plugins you use and if you have webkit plugins loaded and probably even how heavy on JS the websites are... and maybe even to how many different servers the websites hold connections open.

On linux, you can see the process file descriptors in `/proc/<PID>/fd`. With a little scripting, you should be able to count what's used by luakit + webkit processes.

Try this while luakit is running: `pgrep luakit\|WebKit | sed 's,.*,/proc/&/fd/,' | xargs find | wc -l`

EDIT: Keep in mind that the limits are "user limits", not process limits. So it also depends on what you're running besides luakit.

**Comment by hippi777** [comment]
ahh, thats sad, however thx for the info! :)

**Comment by craftyguy** [comment]
> ulimit -n 2048

Yeah, that helps.

> Appearently one webkit instance must consume about 110 file descriptors

That seems nuts, so that's purely a webkit thing and not a luakit-specific thing? Sadly, other browser engines (firefox, webengine) don't seem to spam file descriptors as much, since I've been able to have way more tabs open on the same system.

**Comment by c0dev0id** [comment]
I did some measurements for you.

Luakit Process only:
1 tab: 41
5 tab: 57

Luakit Webkit Processes only:
1 tab: 80 (codevoid.de)
1 tab: 105 (github.com/luakit/luakit/issues)
5 tabs: 265 (codevoid.de github.com msn.com luakit.github.io)

Chrome:
5 tabs: 503 (codevoid.de github.com msn.com luakit.github.io)

Firefox:
5 tabs: 494 (codevoid.de github.com msn.com luakit.github.io)

Vimb (main process+webkit processes):
5 tabs: 617 (codevoid.de github.com msn.com luakit.github.io)

Qutebrowser (qtwebengine):
5 tabs: 183 (codevoid.de github.com msn.com luakit.github.io)

**Comment by craftyguy** [comment]
Wow, thank you for the quantitative analysis. I'll close this issue, since something is clearly wonky with my system (I *know* I've been able to run many tabs at once on other browsers, but I have been using luakit exclusively for some time now)

**Comment by c0dev0id** [comment]
I need to correct myself. The picture changes with more tabs.

40 tabs (40x github.com)

Firefox: 647
Luakit: 2051
Chrome: 1959
Qutebrowser: 1321
Epiphany: 3214 (gnome browser and reference webkitgtk implementation)

I noticed that Chrome needs more FDs but they go down after a page has finished loading. Firefox seems to reuse processes at around 650 FDs. They simply stop increasing.

So yes, webkit is pretty FD-hungry with this "one-process-per-tab" design.

Unrelated observation on the side: Qutebrowser was the fastest to open and load this many tabs.

PS: Measurements were done on OpenBSD. It might be different on other OS. You can use `fstat -p <pid>` to examine the file descriptors of a process. I did it with `pgrep luakit\|WebKit | xargs -L1 fstat -p  | grep -v USER | wc -l`

**Comment by c0dev0id** [comment]
@craftyguy *ping* (just for the notification so you get the update ^^^)

**Comment by c0dev0id** [comment]
@craftyguy: I had to research this single process mode... surprisingly it works! (I didn't think so, because we have another issue here that says otherwise).

```
$ export WEBKIT_USE_SINGLE_WEB_PROCESS=1
$ luakit
```

This enables webkit single process mode. I opened 40 github tabs with ~160 file descriptors. And it was crazy fast, compared to the multi process mode.

Just be aware that one webview crash will crash all tabs.

**Comment by craftyguy** [comment]
@c0dev0id wow, nice! I'll give that a try. Yeah seems like a bit of a regress back to the way things were with a single process, but it might lead to overall better stability on some (my) systems where I have lots of tabs open.

**Comment by aidanholm** [comment]
Re 'crazy fast', one of the biggest annoyances for me after the multi-process switch was the delay when opening new tabs, since a new process must be forked and initialized. I've been thinking of changing luakit's C code to keep a pre-created but hidden webkitwebview ready to return immediately when a new webview is requested... one of these days maybe.. :)

**Comment by c0dev0id** [comment]
> Re 'crazy fast

It's not only the fork time. It's also how heavy it is on resources. As discussed in this issue, having 40 tabs open pretty much consumes all file descriptors for the logged in user in some installations. And then there is memory and what those processes are doing in background.

I've set this single process mode active on my system since I found it and I'm quiet happy with it. Reloading some tabs every once in a while is bugging me less than having luakit being laggy and heavy on the system. Especially because luakit is a small browser that's often used on small/old systems.

I think we could document this toggle or even support it with a "-s" (single process mode) command line switch.

Really fancy would be some crash tracking and prevention logic that shows a page for "known to crash webview" URLs.

```
   This URL lead to a webview crash before.
      [ try again ] [ open in firefox ]
```

**Comment by hippi777** [comment]
crashing isnt that much of a big deal if the opened pages are saved before loading anything, and this single process mode with profiles for whatever like work, researches, general surfing etc seems to be a good way to go for me :D

**Comment by craftyguy** [comment]
> I think we could document this toggle or even support it with a "-s" (single process mode) command line switch.

I've been running with single process mode ever since you discovered/mentioned it here, and luakit is like a whole new browser now (faster, and I don't hit the fd limit stuff anymore with many, many tabs opened). It would be great to have this as cmdline switch, or possibly as a setting in the app (something like `:set webview.use_single_process true` ?)
