### ISSUE TITLE
Support For External Plugins

### ISSUE THREAD

**Issue by shmalebx9** [luakit/luakit#872]
As far as I can tell luakit does not provide a way to use external pulgins. Specifically I want to enable widevine since I have it installed on my system.

**Comment by c0dev0id** [comment]
You can use webkit plugins like wysbadblock (https://github.com/jun7/wyebadblock), as well as luakit lua extensions.

You can not use Firefox/Chrome plugins. I don't see widevine supporting webkit anytime soon (or ever).

**Comment by shmalebx9** [comment]
> You can use webkit plugins like wysbadblock (https://github.com/jun7/wyebadblock), as well as luakit lua extensions.
> 
> You can not use Firefox/Chrome plugins. I don't see widevine supporting webkit anytime soon (or ever).

Well that's sad. I guess it comes with simplicity.
