### ISSUE TITLE
Way to show tabs on full screen

### ISSUE THREAD

**Issue by cannyboy** [luakit/luakit#875]
Couldn't find a setting or binding for this.. Is there a way to show tabs once I've switched to full screen? Or even a setting to automatically show tabs on full-screen?

**Comment by taobert** [comment]
The tablist (and status bar) are hidden in response to the `property::fullscreen` signal.
You can override this behaviour in your `userconf.lua` by removing the signal handler,
and (optionally) replacing it with a new one that only hides the status bar:
```
local window = require "window"
window.add_signal("init", function (w)
        w.win:remove_signals("property::fullscreen")
        w.win:add_signal("property::fullscreen", function (win)
            w:update_sbar_visibility()
        end)
end)
```
The tablist will then be displayed (or not) based on the `tablist.visibility` setting.

If you're wanting to toggle it on and off frequently, you could then make a key binding to modify `tablist.visibility`,
or look at  Alexander Clare's `tabmenu` plugin (in the `luakit-plugins` repository) as an alternative.
Edit (20210325): `tabmenu` is now part of the main repository.

**Comment by aidanholm** [comment]
Closing as resolved.
