### ISSUE TITLE
Clipboard support in Wayland

### ISSUE THREAD

**Issue by kflak** [luakit/luakit#876]
Hi, and thanks for a wonderful browser! I am dipping my toes into luakit from qutebrowser right now and so far it looks very promising. 

## I'm submitting a Bug Report

When yanking the uri it is not copied to the clipboard on wayland/sway. I am using `wl-{copy,paste} for my clipboard needs on sway.
## Current Behavior

No clipboard support
## Expected Behavior

Clipboard should work.
## Reproduction Instructions

Run yy on any page. Try to paste the resulting text elsewhere.
## Environment

Linux Distribution & Version: Arch Linux 5.4.78-rt44-1-rt-lts, swaywm 1.5.1
Output of `luakit --version`:
```
luakit 2.2.1
  built with webkit 2.28.4 (installed version: 2.30.3)
```

**Comment by craftyguy** [comment]
Hmm, I'm running sway (also on Arch Linux), and yanking the page url works for me, I can paste it in other apps.

For example:
```
❯ wl-paste
https://github.com/luakit/luakit/issues/876
```

Is luakit running as a native wayland app on your system, or are you maybe running it under Xwayland?

**Comment by kflak** [comment]
I'm running it natively, so that shouldn't be the problem. In fact, it seems every copy operation is broken... Is there something I can do to help debug this? Any logs/verbosity level settings I could dig up? Something about the various lua-lib dependcies and their versions that might be fouling things up?

EDIT: I tried now also with the `luakit-git` package, just to make sure I have the very latest version, but the problem persists.

**Comment by aidanholm** [comment]
Hi @kflak; have you tried both `y` (copy to primary selection) and `Y` / `shift-y` (copy to clipboard) ?

**Comment by ldelossa** [comment]
@aidanholm came here with same issue, your solution solved it for me. Didn't realize it Y to copy to clipboard.

**Comment by kflak** [comment]
> Hi @kflak; have you tried both `y` (copy to primary selection) and `Y` / `shift-y` (copy to clipboard) ?

Hi, somehow this one slipped by unnoticed! yes, shift-Y works.
