### ISSUE TITLE
Special Unicode characters are incorrectly picked up

### ISSUE THREAD

**Issue by folliehiyuki** [luakit/luakit#878]
## Current Behavior

I have a local html file, which imports `FiraCode Nerd font` for displaying some Unicode characters. Luakit displays text just fine (using the correct font), but picks the first font it has found to display the special unicode characters (or so I believe). 

Here it displays with NotoEmoji and a CJK font (which use the same unicode code) instead of the imported font.

![1](https://user-images.githubusercontent.com/67634026/101241286-a8b91c80-3705-11eb-8c34-6afcb303df73.png)

![2](https://user-images.githubusercontent.com/67634026/101241299-cf775300-3705-11eb-9e67-355b8fa52abb.png)

## Expected Behavior

This is how they look like in other browsers (using the imported font)

![3](https://user-images.githubusercontent.com/67634026/101241310-e9b13100-3705-11eb-9bd2-92189d8b9a62.png)

![4](https://user-images.githubusercontent.com/67634026/101241311-ee75e500-3705-11eb-8be6-1db64f023f0f.png)

## Reproduction Instructions

- Specify a font for the html file
- Install fonts that have overlapped unicode codes.

## Environment

Linux Distribution & Version: Void Linux musl
Output of `luakit --version`: luakit 2.2.1
built with webkit 2.30.0 (installed version: 2.30.2)

**Comment by c0dev0id** [comment]
Can you check with other webkit based browsers?) (epiphany, vimb, surf ...)
I think each engine has an own idea about how to handle fallback fonts.

Are you saying this does only happen in a local file, but when you look at the same file served via HTTP you get the expected result?

Please share the file you used for testing. I have the fonts here. I just want to make sure that I use the same technique to reference the font in the file.

**Comment by folliehiyuki** [comment]
[Here](https://gitlab.com/FollieHiyuki/Startpage) is the page I use. I use `@font-face` to import the font.
[Link](https://folliehiyuki.gitlab.io/Startpage/) to the page hosted on Gitlab (to test via HTTP)

It appears to behave the same whether I open it via HTTP or local file.

Just installed epiphany as you suggested. It displays the font incorrectly like luakit, so I assume you are correct (that this is because of the webkit engine)

**Comment by c0dev0id** [comment]
Yep, that's webkit. I'm closing this issue. Feel free to ask for it on https://bugs.webkit.org.
