### ISSUE TITLE
luakit://binds/ cannot find binding defined it in user config

### ISSUE THREAD

**Issue by dm9pZCAq** [luakit/luakit#885]
## I'm submitting a…
Bug Report

## Current Behavior
`luakit://binds/` cannot find binding defined it in user config

Traceback:
```
/usr/share/luakit/lib/binds_chrome.lua:238: unable to load resource: /usr/share/luakit/./userconf.lua
Traceback:
(1) [C]                                        in function load
(2) /usr/share/luakit/lib/binds_chrome.lua:238 in function function_source_range
(3) /usr/share/luakit/lib/binds_chrome.lua:270 in function help_get_modes
(4) /usr/share/luakit/lib/binds_chrome.lua:289 in function [anonymous]
(5) [C]                                        in function xpcall
(6) /usr/share/luakit/lib/chrome.lua:261       in function [anonymous]
```
## Expected Behavior
properly show bindings

## Reproduction Instructions
in ` ~/.config/luakit/userconf.lua`:
```lua
local modes = require'modes'
modes.add_binds('normal', {
	{ '<Control-c>', 'Copy selected text.', function()
		luakit.selection.clipboard = luakit.selection.primary
	end },
})
```

## Environment
Linux Distribution: `Gentoo`
package: `www-client/luakit-2.2.1-r100::gentoo`
Output of `luakit --version`: `luakit 5f25506f built with webkit 2.30.3 (installed version: 2.30.3)`
lua version: `LuaJIT 2.0.5`

**Comment by c0dev0id** [comment]
Do you really not have a space between `require` and `'modes'`?

Works for me:

![binds_002](https://user-images.githubusercontent.com/44190565/105617749-f5a1a100-5de0-11eb-9269-1fd7454527a9.png)

**Comment by dm9pZCAq** [comment]
oh yeah, problem was in space between `require` and module
