### ISSUE TITLE
Allow horizontal scroll of Flex Box

### ISSUE THREAD

**Issue by coderkun** [luakit/luakit#894]
**Current Behavior:**

On the HTML page shown below the Flex Box is rendered correctly but it is not possible to horizontally scroll in order to see the most-right content. Other webkit-based browsers show a horizontal scrollbar and allow horizontal scrolling.

**Desired Behavior:**

I would like to be able to horizontally scroll to the most-right content.

**How can we reproduce it (step by step):**

Open the following HTML page with Luakit:

    <!DOCTYPE html>
    <html>

    <head>
        <meta charset="utf-8" />
        <title>Flex Box</title>
        <style>
            main { display:block; position:relative; overflow-x:scroll; }
            .box { display:flex; align-items:stretch; height:100%; }
            .item { display:flex; padding:10px; margin:15px; border:1px solid black; }
            .content { display:flex; flex-direction:column; position:relative; width:296px; margin:6px; }
            .vertical { display:flex; flex-grow:1; flex-direction:column; }
        </style>
    </head>

    <body>
        <main>
            <div class="box">
                <div class="item">
                    <div class="content">
                        <div class="vertical">
                            1
                        </div>
                    </div>
                </div>
                <div class="item">
                    <div class="content">
                        <div class="vertical">
                            2
                        </div>
                    </div>
                </div>
                <div class="item">
                    <div class="content">
                        <div class="vertical">
                            3
                        </div>
                    </div>
                </div>
                <div class="item">
                    <div class="content">
                        <div class="vertical">
                            4
                        </div>
                    </div>
                </div>
                <div class="item">
                    <div class="content">
                        <div class="vertical">
                            5
                        </div>
                    </div>
                </div>
                <div class="item">
                    <div class="content">
                        <div class="vertical">
                            6
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </body>

    </html>

**Environment:**

Linux Distribution & Version: Arch Linux, package [luakit](lhttps://archlinux.org/packages/community/x86_64/luakit/), version 2.1.1-1

Output of `luakit --version`:

    luakit 2.2.1
      built with webkit 2.28.4 (installed version: 2.30.4)

**Note about webkit issues:**

Tested with Epiphany 3.38.2 and webkit2gtk 2.30.4 where horizontal scrolling works as expected.

**Comment by c0dev0id** [comment]
Hi,
Luakit hides scrollbars per default. Comment the the following entry in `rc.lua`:
```
local hide_scrollbars = require "hide_scrollbars"
```

Then restart luakit and the scrollbar will be shown.

**Comment by coderkun** [comment]
Thanks, @c0dev0id, that shows the horizontal scrollbar (is there a way to enable this via `userconf.lua` without modifying `rc.lua`?) and I can use the mouse to scroll. But I cannot scroll via any key binding (e. g. h/l or <Left>/<Right>). Is that because the scrolling element is not the page? Is there any way to select the element to scroll?

Btw. a real world example is the defult Mastodon interface. Nextcloud Deck uses a horizontal Flow Box like this, too.

**Comment by c0dev0id** [comment]
No, there is no way I know to "unload" a script after it has been loaded. Do you need to modify `rc.lua` for this.

I think, ideally it should be the other way around. I'm thinking about delievering a ready to copy userconf.lua, which contains all the "require" lines in commented form. So we would have `rc.lua` which contains the the boilerplate and userconf.lua which is meant to be copied to the user directory and would only be loaded from there.

Even better would be a nicer plugin concept. Ideally something like `:plugins` which shows a list of plugins and modules that can be enabled/disabled there. If this would be generic enough, no "require" lines would be needed anymore and userconf could really be customization on top of those.

There are a few things I'd like to work on before that. But eventually I'll get to it.

Regarding Webkit and focus... I also can't scroll with arrow keys on you flex example (also not with epiphany). Luakit does nothing special in that regard. If you can `<tab>` to an element that you can normally scroll with the arrow keys, luakits `hjkl` should work too.

I wondered a bit about mastodon... but I unchecked the "advanced interface" option in the settings on my instance. This solves this problem for me :) (luakit is mostly too slow on JS heavy pages here anyway.

**Comment by coderkun** [comment]
Thanks for your explanations. You are right that scrolling by arrow keys works when “tabbed” to certain elements. Together with the visual scroll bars, that is good enough for my use case.

Thanks again for your help.
