### ISSUE TITLE
Question: per domain cookies policy

### ISSUE THREAD

**Issue by spk** [luakit/luakit#898]
**Current Behavior:**

Cookies policy can be defined with `soup.accept_policy` Acceptable values: "always", "never", "no_third_party"

**Desired Behavior:**

Is it possible to define this policy per domain like `settings.on["127.0.0.1"].webview.enable_html5_local_storage` ?

**How can we reproduce it (step by step):**

None

**Environment:**

Linux Distribution & Version:
Output of `luakit --version`:

2.0.0

**Note about webkit issues:**

If you're reporting a rendering issue, please test it with the gnome
browser ephiphany as well. If the issue occurs there too, we're very
likely not able to help. These issues should be reported to webkit:
https://bugs.webkit.org

**Comment by taobert** [comment]
Well, nobody with _actual_ knowledge has chimed in, so i will.
I would have expected that it _was_ possible.
Have you tried and found that it didn't work?

**Comment by c0dev0id** [comment]
The cookie policy is not a webview or window setting. It's set up by the soup library (https://luakit.github.io/docs/modules/soup.html#property-cookies_storage) and then used to initialize the Webkit Context. The Webkit Context is then used for all Windows and WebViews (Tabs).

That means the cookie database is global and can not be set on a per-domain basis.

These are the settings webkit exposes:
https://webkitgtk.org/reference/webkit2gtk/unstable/WebKitSettings.html

Once the cookie database shows up there, we might be able to expose it in `:settings` (if soup allows it)

So this is a feature request towards webkit, not luakit.

**Comment by spk** [comment]
Thanks for the detailed answer everything is clear :green_heart:
