### ISSUE TITLE
youtube on luakit

### ISSUE THREAD

**Issue by zakariaGatter** [luakit/luakit#900]
I Cant watch youtube on luakit it give me (this browser not supported) msg 

I tried to change the user-agent to firefox and chrome but the same resoult 

did anyone have a solution 

Linux Distribution & Version: void linux
Output of `luakit --version`: luakit 2.2.1

**Comment by c0dev0id** [comment]
Do you have gstreamer1 + plugins installed?

**Comment by Tonus1** [comment]
Wtorks fine herewith Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0 Safari/605.1.15
Could you test with another browser ? On viewpure ? http://www.viewpure.com/

**Comment by zakariaGatter** [comment]
> Do you have gstreamer1 + plugins installed?

yes i have gstreamer1 installed but i see not plugings for it 

```
[*] gstreamer1-1.18.3_1          Core GStreamer libraries and elements (1.x)
[-] gstreamer1-devel-1.18.3_1    Core GStreamer libraries and elements (1.x) - development files
[*] gstreamer1-pipewire-0.3.22_1 Server and user space API to deal with multimedia pipelines - gstreamer plugin
```

this is all the gstreamer1 packages i have in my system

**Comment by zakariaGatter** [comment]
> Wtorks fine herewith Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0 Safari/605.1.15
> Could you test with another browser ? On viewpure ? http://www.viewpure.com/

i tried the user agent u give me 

> :webview.user_agent "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0 Safari/605.1.15"

but still the same with youtube and viewpure

**Comment by travankor** [comment]
it's a problem with void's webkit2gtk https://github.com/void-linux/void-packages/issues/25852

**Comment by zakariaGatter** [comment]
Ohhh ok thank you for your help and you time

**Comment by c0dev0id** [comment]
Closed; Not our bug.

**Comment by DevElCuy** [comment]
Quick fix (to save you the pain of scrolling 200 messages):

Make sure to install:

gstreamer-plugins-bad
gstreamer-plugins-ugly

Make sure to UNINSTALL:

gstreamer1.0-libav

NOTE: Package names are from Ubuntu, they might vary across versions and distros
