### ISSUE TITLE
[FEATURE REQUEST] hint all input fields

### ISSUE THREAD

**Issue by julianuu** [luakit/luakit#918]
In `qutebrowser`, I can hit `;t`and it hints all the input fields. I couldn't find it here. In `qutebrowser` I use it a lot.

**Comment by julianuu** [comment]
The closest thing I could find is `(n)i`, where `(n)`is some number. It appears this will send me to the nth input field. But I can only do trial and error to find the right number.

**Comment by taobert** [comment]
What benefit would this have over `f` which hints input fields and other clickable elements?

**Comment by julianuu** [comment]
For example when I am oopening an issue on github, I have to select the text field when switching between preview and editing, or when I want to edit the title. And github has so many links, that it takes some time to type the right numbers after hitting f. And when just pressing i it might send me to one of the search boxes.

**Comment by taobert** [comment]
Well, when i press `f` on the github new issue page, using the default character set, i get two character hints.
It's not clear to me that pressing `f` `61` is significantly more arduous than `;t` `2`.
I can see that it would be somewhat so, as `;t` will be muscle memory,
and you will only have to cognitively process one new character (and will have a pretty good idea what that will be ahead of time).

If you're finding yourself presented with hints containing _many_ characters,
then you might consider changing the character set from the default.  I use:
```
-- Use home row (and a bit) characters for generating labels
local select = require "select"
select.label_maker = function (s)
    return s.sort(s.reverse(s.charset("fjdksla;ghutnvir")))
end
-- Match only hint label text
follow.pattern_maker = follow.pattern_styles.match_label
```
The more characters you add the less likely there will be multiple-character hints,
but the more likely they'll be away from the home row.
(If you add punctuation characters (i have a ';'), you should skim #757,
and consider adding a direction to your style.)

Anyway, Luakit's hinting infrastructure is pretty user-extensible, 
and you can implement the behaviour you're after by adding appropriate selectors and bindings in your `userconf.lua`:

```
local follow = require "follow"
follow.selectors.text = "textarea, input:not([type=hidden])"
modes.add_binds("ex-follow", {
    { "t", [[Hint all text elements and focus the matched element.]],
        function (w)
            w:set_mode("follow", {
                prompt = "focus", selector = "text", evaluator = "focus",
                func = function (s) w:emit_form_root_active_signal(s) end,
            })
        end },
})
```
You might want to tweak the selector (`input:not([type=hidden])` is taken from the `clickable`/`focus` selectors,
and not quite what you're after), and using `;t` steps on the default binding (open uri in new tab).
Also, i'm not sure i've understood what you're after, as you mention switching from github's `preview` to `write`, and qutebrowser's `;t` doesn't hint these buttons.

IMO, `follow.lua` is already suffering from feature creep, and adding more niche bindings here is misguided.
I feel rather that it should serve as a set of examples for people to implement whatever behaviour they want.

**Comment by julianuu** [comment]
Thanks a lot for your time and suggestions! Yes I totally understand the feature creep-argument. Of course I can only speak for myself. I will look into implementing that feature myself. I didn't know it would be so easily extendible.

Yes, the reason why it feels easier for me is that I don't have find the correct 2 digit combination from all those that show up with my eyes, and then type those two digits, but I know I will have to type only 1,2 or 3.

I guess I expressed myself a bit unclear. With the switching between `preview` and `write` I was only trying to give an example for when it might happen that I would have to focus a text input field many times. I didn't mean I wanted an easy way to click on the `preview` or `write` button itself.

**Comment by taobert** [comment]
Cool.
I've just added a missing parenthesis to my suggested selector (although it worked even without it).
I think the code should serve your needs as is, but if you need any further help tweaking it, just yell.
If you _do_ find some variations that work better for you, please add a comment with them for future searchers.

With specific reference to github write/preview, clicking Write seems to make the text area the focussed element,
but you need to type `i` to enter insert and start typing.
This will be something that github's crew thought to do, and not generally the case, so you'd still run into analogous problems everywhere else.

**Comment by julianuu** [comment]
Thanks that works pretty well! Sometimes it hints a few elements also that don't seem to be text fields. Like on github/new issue it hints the the attach button, and on google the search buttons. These are so few elements that its still single digit hints, so its no problem in these examples.

Right, for my mentioned github example its not really needed actually.

**Comment by taobert** [comment]
On Sat, Apr 24, 2021 at 12:25:54PM -0700, julianuu wrote:
> Sometimes it hints a few elements also that don't seem to be text fields.
Yes, it'll match any `input` field that's not hidden.
These will include checkboxes and radio buttons etc.
You could check explicitly for `type=text` or `type=password` if it were important to you.

**Comment by julianuu** [comment]
Ah nice, yes it seems with `follow.selectors.text = "textarea, input:not([type=hidden])[type=text]"`it does the same as `qutebrowser`s `;t`.

**Comment by julianuu** [comment]
For completeness, I went with the following `userconf.lua`. With only `[type=text]` it does not hint password fields.
```
local modes = require "modes"
local follow = require "follow"
follow.selectors.text = "textarea, input:not([type=hidden])[type=text], input:not([type=hidden])[type=password]"
modes.add_binds("ex-follow", {
    { "f",
        function (w)
            w:set_mode("follow", {
                prompt = "focus", selector = "text", evaluator = "focus",
                func = function (s) w:emit_form_root_active_signal(s) end,
            })
        end },
})
```

**Comment by taobert** [comment]
Erm, well an `<input/>` tag has _a_ type which could be (among other things) `type="text"` _or_ `type="password"` _or_ `type="hidden"`. If an input's type is "text" or "password", it's necessarily not "hidden", so the `:not([type=hidden])` parts of the selector are redundant (and potentially confusing).

Edit (20210514): Also for completeness, there's also a `go_input` module which skips the hinting step and focuses the n-th input on the page (default binding `[<n>]gi`).
