### ISSUE TITLE
Should it be possible to rewrite the referrer string?

### ISSUE THREAD

**Issue by jmthackett** [luakit/luakit#923]
Hi!

I'm really new to luakit but know a little about lua. What I'm trying to work out is whether or not it is going to be possible to rewrite the referrer string (and preferably, other headers) to some value of my choosing, from a module.

Am I trying to do something impossible?

**Comment by taobert** [comment]
The (in-app) api docs (luakit://help/doc/classes/page.html) have an example of doing this by intercepting the `send-request` signal.
I've not played with it, and it's possible that the docs are not up to date, so let us know if you can't get it working, and i'll think harder.

**Comment by jmthackett** [comment]
I can confirm that works fine - a little late, admittedly. I have done this:

```
local _M = {}

luakit.add_signal("page-created", function(page)
    page:add_signal("send-request", function(p, _, headers)
        headers.Referer = "https://www.google.com/"
        msg.verbose("Setting referer '%s'", headers.Referer)
    end)
end)

return _M
```

It is based on the `referer_control_wm` webmodule and works like a charm. Thank you!

**Comment by c0dev0id** [comment]
Good you found a solution! Thanks for showing it.
