### ISSUE TITLE
Custom action with hint-link

### ISSUE THREAD

**Issue by fedoranvar** [luakit/luakit#929]
Like in 'follow hint', how can i get hint link and pass it to my custom functon ?
e.g. play it in mpv, of copy it, etc.

Thank you!

**Comment by taobert** [comment]
`;y` will hint uris and yank the selected one into the primary X buffer.
If you want a specific binding to open a given link in mpv,
you should read `follow.lua` for examples on how the default bindings work,
and #918 for some detail on how to add stuff in your `userconf.lua`.

**Comment by fedoranvar** [comment]
thank you will look into it!
