### ISSUE TITLE
Bookmarks limited to 100

### ISSUE THREAD

**Issue by ghost** [luakit/luakit#932]
**Current Behavior:**
If the `bookmarks.db` has more than 100 bookmarks, `:bookmarks` does not show them all.

**Desired Behavior:**
A sane value or unlimited bookmarks should be shown when a user opens `:bookmarks`

**How can we reproduce it (step by step):**
1. Open `luakit`
2. Add over 100 bookmarks (or add them using `sqlite3` then open `luakit`)
3. Type `:bookmarks` and only 100 will show up

Adding `1000` to the following line allowed the amount of bookmarks I have to show. I set it to `65536` for now, but having a limit may not be necessary:

https://github.com/luakit/luakit/blob/ad2ce7e2fb80049a960989d3c9a840c837879ae4/lib/bookmarks_chrome.lua#L286

**Environment:**

Linux Distribution & Version: Manjaro (up-to-date)
Output of `luakit --version`: 2.3

**Comment by taobert** [comment]
Yes. Thankyou.
I'll have a think about it.

My suspicion is that having hundreds of entries on a page is probably not ideal most of the time,
but not being able to get at the last N bookmarks (and having no indicator that they even exist) is a problem.
Perhaps paging them, and adding a "Bookmarks per page" setting would be appropriate.
Do _you_ have opinions about how it should work? (I don't use the bookmarks.)

FWIW, the search function seems to correctly restrict things, and should help somewhat.
Also, for anyone else playng with it, you don't need to restart luakit after adding bookmarks with sqlite3.

Edit: `:history` pages, with next/prev buttons. `bookmarks_chrome.lua` looks to have most of the infrastructure of `history_chrome.lua`, so figuring out why it's not behaving the same, and correcting that is probably easyish.

**Comment by ghost** [comment]
>My suspicion is that having hundreds of entries on a page is probably not ideal most of the time,
but not being able to get at the last N bookmarks (and having no indicator that they even exist) is a problem.
Perhaps paging them, and adding a "Bookmarks per page" setting would be appropriate.
Do you have opinions about how it should work? (I don't use the bookmarks.)

I would agree that having a continuous run of all bookmarks wouldn't be ideal in cases where there are large numbers of bookmarks, and having folders using the `tags` element in the db, or some kind of page navigation would be preferable. It might make more sense for the script to query the db when the page is opened, which might defeat the need for a limit.

**Comment by taobert** [comment]
It appears that during a reworking of `bookmarks_chrome.lua` (dd32b979b) a call to `updateNavButtons` (previously `update_nav_buttons`) was misplaced, causing them to not get drawn.
This will be fixed by #933.
Thanks again for the bug report.
