### ISSUE TITLE
Test failure test_undo_close_works

### ISSUE THREAD

**Issue by oz123** [luakit/luakit#943]
**Current Behavior:**

```
PASS async/test_lua_files_load_successfully / test_all_lua_files_load_successfully
CONT async/test_undoclose / test_undo_close_works
  nil
CONT async/test_undoclose / test_undo_close_works
  nil
FAIL async/test_undoclose / test_undo_close_works
  tests/async/test_undoclose.lua:49: assertion failed!
  Traceback:
  (1) /usr/share/lua/5.1/luassert/assert.lua:171 in function assert
```

I believe this is because the window title is not set.

Linux Distribution & Version: gentoo
Output of `luakit --version`:
$ luakit --version
luakit 6f69789af
  built with webkit 2.30.6 (installed version: 2.32.1)

**Comment by oz123** [comment]
This bug is quite old: https://bugs.gentoo.org/742599

**Comment by c0dev0id** [comment]
It happens here too (on OpenBSD), but it doesn't happen on the connected Travis CI Ubuntu machine.

**Comment by oz123** [comment]
Thanks for the response. I was wondering if it related to Lua vs LuaJIT (I didn't mention that)...

**Comment by taobert** [comment]
I see this too (debian sid):
```
FAIL async/test_undoclose / test_undo_close_works
  tests/async/test_undoclose.lua:47: assertion failed!
  Traceback:
  (1) /usr/share/lua/5.1/luassert/assert.lua:171 in function assert
  (2) tests/async/test_undoclose.lua:47          in function [anonymous]
FAIL async/test_undoclose / test_undo_close_restores_tab_history
  tests/async/test_undoclose.lua:59: Expected objects to be equal.
  Passed in:
  (number) 2
  Expected:
  (number) 3
  Traceback:
  (1) /usr/share/lua/5.1/luassert/assert.lua:52 in function is_equal
  (2) tests/async/test_undoclose.lua:59         in function [anonymous]
```
however undoing closed tabs works correctly for me in the browser, so this is specifically an issue with the test.

Briefly, the test opens a new tab (`tests/html/undoclose_page.html`), closes it, undoes the close and checks that what's been reopened is correct.

The assert at `tests/async/test_undoclose.lua:47` is testing that the page title is what it should be: `assert(w.view.title == "undoclose_page")`. Instead, the title is nil.
The assert directly above (line 46) tests that `w.view.uri` is the same before and after and doesn't baulk.
Copying the line 47 assert to just after the page is (ostensibly) opened the first time, also causes the assert to trigger, so this is not a problem with undoing the close, it's a problem with the title being set.
Further, adding an additional `get_source` (copied from `tests/async/test_http_test_server.lua`):
```
coroutine.wrap(function ()
    test.continue(w.view:get_source())
    end)()
local source = test.wait()
```
after the load/undo close, prevents the alert from triggering.
So, it seems that the undo tab infrastructure is correctly recreating a webview with the correct uri, but for whatever reason, the title is not getting from the html into the view (in either the initial load or the undo close), but an explicit `get_source` sets the title correctly.

Also, commenting out the line 47 assert, prevents the subsequent failure of `test_undo_close_restores_tab_history` (which i see but isn't mentioned by the OP).

**Comment by oz123** [comment]
Awesome 👍 great job analysing this.
@c0dev0id @taobert do you want me to create a PR with a patch based on  this information?

**Comment by taobert** [comment]
Well, i think that my quick look gave some clues about where _not_ to investigate, but didn't really arrive at a (correct) solution.
Neither commenting out the problematic assert, nor adding the explicit `get_source` appeal to me, because this issue implies that the test harness doesn't work quite as it is assumed to (and presumably used to). (Maybe - as you suggest - due to lua/luajit differences, maybe due to webkit evolution, maybe something else.) It'd be preferable to use this to learn something rather than just silence the error.

In `tests/async/test_http_test_server.lua` the `get_source` lines i used are prefaced with the comment:
```
-- Wrap view.source get in another coroutine, since auto-suspending the
-- test coroutine confuses the test runner
```
I don't grok the test harness (or coroutines) well enough to know how pertinent this is, but it sounds like it's working around something.

**Comment by c0dev0id** [comment]
I noticed in a few places that changes become active after an additional request. For example enabling/disabling javascript with the noscript plugin has strange effects. You can test it here: https://javatester.org/javascript.html

1. open the page
2. toggle javascript (`,ts` with noscript loaded)
3. refresh
4. refresh

On the first refresh, you see markup in the javascript-test-box. On the second refresh it renders correctly.

We noticed a similiar behavior when setting the User Agent, where a User Agent change gets active only after the second refresh (request to be precise).

The test might be hinting at someting we haven't figured out yet. So I'm with @taobert here. Either we find a bug or we learn something about the test framework.

**Comment by c0dev0id** [comment]
The title is not instantly restored from the history, but updated from whatever page is loaded. This happens async and we need to wait for the `property::title` signal until we can read `w.view.title`.

I printed the title on various places and at some point "undoclose_page" started to appear after(!) the assertion error, which hinted at a timing problem.

**Comment by c0dev0id** [comment]
The fix referenced before didn't fix the undoclose bug. But this one does: https://github.com/luakit/luakit/commit/92a2a5a1e76018a2d4c4344abebd3034c198e8f9 (finally!)
