### ISSUE TITLE
Support development tools

### ISSUE THREAD

**Issue by ghost** [luakit/luakit#947]
Hi! luakit! :)
I switched my mainly use browser from chromium to luakit, when I use luakit to debug some website, I not found the JavaScript console or JavaScript profiler, I also watched documentation,  I not found any information about developer tools,  I need some guidance. :)

**Comment by taobert** [comment]
There's a console in webkit's web inspector, accessible either from `Inspect element` in the right-click menu, or with `:inspect`.
I don't know about profiling.

**Comment by ghost** [comment]
@taobert Ok, I called it successful.
Maybe luakit documentation can add about using luakit for website development?
p.s.: Just a idea. :)

**Comment by c0dev0id** [comment]
You mean, something like this? `luakit://help/doc/modules/webinspector.html`
It is also accessable with F12, just like in chrome and firefox.

**Comment by ghost** [comment]
@c0dev0id Sorry, I didn't read the documentation carefully, Maybe I used to using vim a lot, problem solving followed vim way, lol
