### ISSUE TITLE
Luakit hangs up on several sites/pages.

### ISSUE THREAD

**Issue by Plaque-fcc** [luakit/luakit#95]
When browsing things like http://welinux.ru/post/6175/ I get page load progress 89% and when I stop loading or close tab it results in stopping updating of window content at all.
I may switch/close tabs, execute commands (at least, `:wq` works as it's supposed to), shutdown luakit. But I can't use it any meaningful before restart.

Maybe I can add here sites that cause the same GUI redraw failure.

**Comment by aidanholm** [comment]
Cannot reproduce. Note that luakit has recently been updated to use WebKIt 2, and many old site-specific bugs have been fixed. Feel free to reopen if this issue reoccurs.
