### ISSUE TITLE
Open a website after a minute the web process crashed

### ISSUE THREAD

**Issue by ghost** [luakit/luakit#954]
**Current Behavior:**
Open the luakit, and load my set home page, after 1 minute, crashed

**Desired Behavior:**
Open the luakit, load home page, no crashed, just like normal usage

**How can we reproduce it (step by step):**
Set a website as home pages
Open luakit

**Environment:**

Linux Distribution & Version: Arch Linux
Output of `luakit --version`: luakit 2.3

**Comment by taobert** [comment]
Current `develop` doesn't crash for me with the default home page (https://luakit.github.io/) or if i set the home page to http://google.com.
Which home page are you loading?

**Comment by ghost** [comment]
@taobert https://www.bing.com

**Comment by taobert** [comment]
Current develop doesn't crash for me with bing either. Are you using the default rc.lua?

**Comment by ghost** [comment]
@taobert Yes, just writing the userconf.lua

**Comment by ghost** [comment]
@taobert My userconf.lua is [here](https://github.com/c4dr01d/flakes/blob/master/dotfiles/luakit/userconf.lua)

**Comment by taobert** [comment]
Well it seems to stay up for me.
Does it work with other sites set as the home page?
Does it only crash with a home page set?
And do other webkit-gtk based browsers work for you?

**Comment by ghost** [comment]
@taobert No, I tried other pages, have same issue

**Comment by ghost** [comment]
@taobert Other browsers with my home page is normal, only in luakit, crashed

**Comment by c0dev0id** [comment]
@c4dr01d : What is "other browsers"? Have you tried other webkit based browsers like epiphany?

When you start luakit in a terminal. Is there any output in this terminal when luakit crashes?

**Comment by ghost** [comment]
@c0dev0id I tried epiphany, same with the luakit
start luakit in terminal, I got the this result:
![屏幕截图 2021-08-26 101747](https://user-images.githubusercontent.com/50952350/130889540-c1380097-51a6-44d4-a880-e3dba882cd45.png)
epiphany open same website with same result:
![屏幕截图 2021-08-26 101838](https://user-images.githubusercontent.com/50952350/130889603-4fcce09c-3117-4d3c-a359-7333e6b15cbd.png)

**Comment by c0dev0id** [comment]
Ok, in this case, this is an issue with the webkitgtk framework. You can reach webkitgtk developer on this bug tracker: https://bugs.webkit.org
