### ISSUE TITLE
Does luakit support CSS Grid?

### ISSUE THREAD

**Issue by wsw70** [luakit/luakit#957]
I have an app that looks good during development (on Chrome) and also good on Luakit ("production" = home dashboard) **except for CSS Grid elements**.

They are really weird in terms of placement and before going further with the investigation I just wanted to make sure whether Luakit does support CSS Grid.

**Comment by c0dev0id** [comment]
CSS Grid Layouts should work on all browsers for quite a while. Including Luakit and other Webkit based browsers.

You can check the feature status here: https://webkit.org/status

**Comment by wsw70** [comment]
> CSS Grid Layouts should work on all browsers for quite a while. Including Luakit and other Webkit based browsers.
> 
> You can check the feature status here: https://webkit.org/status

Thanks. There must be something weird then. I switched to a flexbox layout and it is displayed fine (in dev on Chrome and I get  exactly the same layout on Luakit in prod)

**Comment by c0dev0id** [comment]
Is this answered then? I'm closing the issue.

**Comment by wsw70** [comment]
> Is this answered then? I'm closing the issue.

I believe it is answered since Luakit relies on Webkit anyway. In any case

- a flex app works on Windows/Chrome and Raspbian/Luakit
- a grid app works on Windows/Chrome but not on Raspbian/Luakit

but this is then a problem elsewhere than in Luakit
