### ISSUE TITLE
luakit freezes when handling Zoom scheme

### ISSUE THREAD

**Issue by ldelossa** [luakit/luakit#959]
**Current Behavior:**
When implementing a zoom scheme handler:

```
webview.add_signal("init", function (view)
    view:add_signal("navigation-request", function (v, uri)
        if string.match(string.lower(uri), "^mailto:") then
            local mailto = "https://mail.google.com/mail/?extsrc=mailto&url=%s"
            local w = window.ancestor(v)
            w:new_tab(string.format(mailto, uri))
            return false
        end
        if string.match(string.lower(uri), "^zoommtg:") then
            local cmd = string.format('%s %q', "zoom", uri)
            io.popen(cmd)
            return false
        end
    end)
end)
```

luakit successfully opens zoom but then hangs shortly after. 
I do not believe I require a close of the handle returned by `io.popen` but maybe I am wrong?

**Desired Behavior:**
luakit opens zoom and continues to operate normally

**How can we reproduce it (step by step):**
I believe you can use that scheme handling function above and open a zoom link. Zoom should open successfully but luakit should freeze.

**Environment:**

Linux Distribution & Version: Fedora 35 Gnome Wayland
Output of `luakit --version`:

```
  luakit --version
luakit 2.3-16-g54fcecaa
  built with webkit 2.32.3 (installed version: 2.32.3)
```

**Note about webkit issues:**

If you're reporting a rendering issue, please test it with the gnome
browser ephiphany as well. If the issue occurs there too, we're very
likely not able to help. These issues should be reported to webkit:
https://bugs.webkit.org

**Comment by taobert** [comment]
I have something similar, but use `luakit.spawn` rather than `io.popen`.
I haven't used zoom for a while, and so can't promise that what i have works, but give that a go.

**Comment by ldelossa** [comment]
@taobert thanks, switching from `io.popen` to `luakit.spawn` worked!
