### ISSUE TITLE
luakit adblock feature isnt working,

### ISSUE THREAD

**Issue by FrostKnight** [luakit/luakit#971]
I wondered if ublock filters work and if not, how you can get them working...

I am on your newest non-master version. I compiled from source, using 2.32.1 and I keep getting hit with google related ads even with ublock origin filters and easylist.'s normal filter, and its privacy one too.

In essence, can you tell me how to make ads go away?  

Also, is there a way to disable third party cookies with this?

**Comment by MuhammedZakir** [comment]
Can you give an example link? I have enabled adblock and haven't seen an ad for a long time.

You probably have done it, but have you enabled adblock -- luakit://adblock/ ?

**Comment by FrostKnight** [comment]
Hmm, I don't have too much time right now, but yeah, it is enabled and I had downloaded some lists and put them into the adblock directory.  I downloaded a few from the ublock origin github area.

Its possible some annoying error cut them back a bit, I will try to see if I made an error, later today, then I will get back to you if it is still happening.

Either way, I do appreciate this browser having minimal dependencies.

**Comment by MuhammedZakir** [comment]
This is what I use:

```
https://easylist.to/easylist/easylist.txt
https://easylist.to/easylist/easyprivacy.txt
#https://secure.fanboy.co.nz/fanboy-cookiemonster.txt
#https://easylist.to/easylist/fanboy-social.txt
https://secure.fanboy.co.nz/fanboy-annoyance.txt
https://easylist-downloads.adblockplus.org/antiadblockfilters.txt
#https://easylist-downloads.adblockplus.org/easylist_noelemhide.txt
https://someonewhocares.org/hosts/
https://winhelp2002.mvps.org/hosts.zip
https://pgl.yoyo.org/adservers/serverlist.php?hostformat=adblockplus&showintro=1&startdate%5Bday%5D=&mimetype=plaintext
```

Links starting with `#` are saved for future and I'm not using them atm. Also, some lists are or have cosmetic filters which LuaKit doesn't support.

**Comment by FrostKnight** [comment]
hmmm....  well, here is what happens for me...

"luakit https://www.vitacost.com/gelo" 

The above is the website,

[    0.047403] I [core/luah]: Loading rc: /home/user/.config/luakit/rc.lua
[    0.090987] I [lua/adblock]: found 5 filter lists
[    1.220181] I [lua/styles]: found 0 user stylesheets
[    3.433836] I [lua/webview]: Requested link: https://search.disroot.org/ (text/html)
[   19.287035] I [lua/webview]: Requested link: https://search.disroot.org/search (text/html)
[   22.318372] I [lua/webview]: Requested link: https://www.vitacost.com/ (text/html)
[   67.464742] I [lua/webview]: Requested link: https://www.vitacost.com/gelo (text/html)
[   70.734041] I [lua/webview]: Requested link: https://088809342f63fa41f92dd6c3e0d4e26d.safeframe.googlesyndication.com/safeframe/1-0-38/html/container.html (text/html)
[   70.977137] I [lua/webview]: Requested link: https://tpc.googlesyndication.com/sodar/sodar2/224/runner.html (text/html)
[   71.158680] I [lua/webview]: Requested link: https://www.google.com/recaptcha/api2/aframe (text/html)


as for cosmetic filters, you saying I shouldn't bother with ublock type filters?

**Comment by FrostKnight** [comment]
Actually, I wondered one other thing, how do you update the lists and also I should mention these ones are being used:



File | Rules in use | Update URL | State | Actions
-- | -- | -- | -- | --
ubo_lanblock.txt | B: 0 | W: 0 | I: 0 |   | Enabled | Disable
ubo_unbreak.txt | B: 13 | W: 127 | I: 18 |   | Enabled | Disable
easylist.txt | B: 40233 | W: 306 | I: 10 |   | Enabled | Disable
easyprivacy.txt | B: 42616 | W: 638 | I: 265 |   | Enabled | Disable
malwarefilter.txt | B: 156846 | W: 0 | I: 0 |   | Enabled | Disable
ubo_annoyances.txt | B: 32 | W: 0 | I: 0 |   | Enabled | Disable


They are in fact enabled though...

I tried to copy and paste what it looks like, but meh... couldnt completely...

I am kind of new to this web browser, it took a while to even figure out how to change the search engines that are default and add adblock lists at .local/share/luakit/adblock 

and have them work, I guess I have depended on firefox based browsers way too long... ;)

Hmm, well what do you know...

It seems that I tried using a fanboy list aka, the ultimate merged one and wala it worked...

Fascinating... 

Ublock origin lists must not work in this web browser, I hope you guys can fix that at some point, but now I know why it wasn't working... aka, the adblocking... ;)

Will you guys ever though be supporting disabling cosmetic filters? Or is it utterly impossible no matter how long it takes?

Either way, please sticky a warning about ublock origin filterlists in case people don't realize they won't work.

**Comment by FrostKnight** [comment]
Small notice, I can block ads now, so I think for now this can be closed, although it very much puzzles me that you cannot disable cosmic filters and/or use ublock origin scripts and have them work, but meh... oh well ;)

Thanks for the advice

**Comment by zlice** [comment]
Sorry to dead-thread, but what did you do to get adblock to work? Only works when it wants to for me. Youtube is usually a no or works partially, ad block test sites allow pop-ups and redirects too.

**Comment by c0dev0id** [comment]
Luakits adblock does *not* do cosmetic filtering. Which means it does not replace/rewrite any code. It blocks access to certain resources via request level pattern matching.

Therefore adding lists that are mainly for cosmetic blocking do not help. They only slow down luakits startup time because it has to load the lists (and then discard most of it).

You can start luakit with the following parameter to see which filters are hit:
```
luakit --log=lua/adblock_wm=debug
```

**Comment by zlice** [comment]
`--log=lua/adblock_wm=debug` is treated as a uri for me and uses my default search engine.

It sounds like it isn't going to do what I want then =/ dang

**Comment by c0dev0id** [comment]
That's not what it should do. Do you have some sort of wrapper script or alias set? Does `luakit --version` work?

**Comment by zlice** [comment]
`--version` works

**Comment by MuhammedZakir** [comment]
You may have used 3 hyphens instead of 2 for `--log`? Try
```sh
luakit --log=lua/adblock_wm=debug
```

If it still doesn't work, what is the output of `which luakit`?

**Comment by zlice** [comment]
```
luakit --log-lua/adblock_wm=debug
[    0.049200] I [core/luah]: Loading rc: /etc/xdg/luakit/rc.lua
[    0.081469] I [lua/adblock]: found 3 filter lists
[    0.297324] I [lua/styles]: found 1 user stylesheet
[    1.196218] I [lua/webview]: Requested link: https://www.google.com/search?source=hp&ei=PAM3X8mTIcyltQbsjLzoDQ&q=--log-lua%2Fadblock_wm%3Ddebug (text/html)
```

**Comment by zlice** [comment]
had `-` instead of `=`, my bad
