### ISSUE TITLE
Safety considerations for luakit.spawn

### ISSUE THREAD

**Issue by samuelallan72** [luakit/luakit#973]
`luakit.spawn` is documented as "parsed with a simple shell-like parser".   Are there considerations I need to think about to avoid shell injection?  For example from the 02-faq.md:

    if string.match(string.lower(uri), "^mailto:") then
        luakit.spawn(string.format("%s %q", "urxvt -title mutt -e mutt", uri))
        return false
    end

Is there a reason this kind of string formatting is used?  Do I need to avoid certain use cases?

Would there be any interest in a spawn function that took a list of arguments and didn't use any kind of shell or shell-like parsing?

**Comment by taobert** [comment]
So, i need to preface this by saying that i am not someone that you should take security advice from.

It looks to me like `luakit.spawn`'s argument is tokenised with `g_shell_parse_argv` and
passed to `g_spawn_async`, which appears to be largely analogous to the `exec* (3)` suite.
My supposition is that the description you quote is based on [glib's documentation](https://docs.gtk.org/glib/func.shell_parse_argv.html), which states that `g_shell_parse_argv`
>Parses a command line into an argument vector, in much the same way the shell would, but without many of the expansions the shell would perform (variable expansion, globs, operators, filename expansion, etc. are not supported). The results are defined to be the same as those you would get from a UNIX98 /bin/sh, as long as the input contains none of the unsupported shell expansions. If the input does contain such expansions, they are passed through literally.

I think that the talk of shells implies rather more functionality than there actually is, and i doubt that there's scope for an interloper to inject semicolons/pipes/redirects &c. (disclaimer: i am not someone you should take security advice from).
Indeed, my quick testing shows that running:
- `:lua luakit.spawn("echo test>/tmp/test")` prints "test>/tmp/test" to the console (and _doesn't_ create the file), 
- `:lua luakit.spawn("echo test | cat")` prints "test | cat", 
-  `:lua luakit.spawn("echo test; echo test2")` prints "test; echo test2".

...so these characters appear inocuous.
However,  `:lua luakit.spawn("echo test # echoing test")` prints only "test", so it seems that the "shell" honours comments.
Further, `:lua luakit.spawn("echo 'test\nline2'")` prints over two lines,
whereas `:lua luakit.spawn("echo test\nline2")` prints on one line with the "\n" replaced with a space. 
So quotes make the parser treat 'test\nline2' as one argument, and without them, the string is broken at the whitespace ("\n") into two arguments "test" and "line2".

So, using `string.format(...%q...)` is probably desirable in case the argument contains hashes/spaces/backslashes/&c. which may impact tokenisation, but if you don't mind things not working if you encounter unexpected, but possibly legitimate formats (`local(this is a comment)@example.com` is a well formed email address), then just concatenating strings (`luakit.spawn("urxvt -title mutt -e mutt " .. uri)`) is probably safe enough. But you wouldn't take security advice from me, right?

Luakit _does_ set `G_SPAWN_SEARCH_PATH`, so if you don't specify a full path to the executable, then you're trusting your PATH.

Also, having written the above, i found a nice long comment in [the glib source](https://github.com/GNOME/glib/blob/main/glib/gshell.c#L354), which defines/explains/discusses the tokenisation in more detail.

**Comment by samuelallan72** [comment]
@taobert thanks for this, this is really helpful!  I'll take a read through the docs, and maybe open a pull request to clarify this in the docs. :+1:
