### ISSUE TITLE
Need basic explanation of how to use on start up (with option to disable once you're sure you won't need it)

### ISSUE THREAD

**Issue by awsdert** [luakit/luakit#977]
**Current Behaviour:**
Just installed because I was looking to try out another browser I could potentially move to, found myself unable to go back a page or even give focus to the bar I'm supposed to type into to change the address.

**Desired Behaviour:**
1st time users like myself need a popup at start up that tells us the basics of using the browser, how navigate, what keys to press, how to set our own keys and add widgets and panels, that last part can just be a link to an in depth wiki, also since I'd like to launch with a specified shared library attached (for example ```luakit -l process_api_wrapper```) it would be appreciated if there's info for that linked also.

**How can we reproduce it (step by step):**
Just find a random stranger and ask them to try out luakit

**Environment:**
Manjaro cinnamon x64 (not that it matters in this particular case)

Linux Distribution & Version:
Output of `luakit --version`:
```
luakit 2.3
  built with webkit 2.30.6 (installed version: 2.34.2)
```

**Comment by taobert** [comment]
Hmm, so did you perhaps start luakit with a url to navigate to, and so not see the default home page?
With the default configuration, and _without_ a specified url, i would have expected it to open `https://luakit.github.io/`.
At the top of this page there's a link labelled `Documentation`.
If you follow that link, you'll see (in the `Pages` section at the top) a link called `Quick-start Guide`.

Now, there may be a case to be made that the Quick-start Guide could be expanded, that it should be the default home page,
and/or that there should be some additional hint in case a new user stipulates a url and misses the home page,
but luakit is unlikely to ever be the best choice of browser-framework for "a random stranger"
or anyone else who's distressed by the prospect of clicking a link that says Documentation.

Regarding launching with a shared library, what is it that you're hoping to achieve here?
The bulk of luakit is written in lua, and adding code to a user's `userconf.lua` allows them to extend or override much of luakit's default code.
If, by contrast, you're wanting to insinuate some sort of shim between the luakit executable and system libraries, then i think you should use LD_PRELOAD. It wouldn't make sense to add code to luakit to handle something which was both this nichey, and could already be done from the shell.

**Comment by awsdert** [comment]
I booted it as just plain ```luakit``` so I presume I was on that page, however I scrolled down to the screen shots while looking through the main page and clicked on a screenshot expecting it to do the usual of overlapping the screen shot above the page content, instead it took me directly to the screen shot and I was unable to get back, even with a mouse key that was purpose built for going back a page (I have a 5 button mouse), I tried pressing escape to see if that would focus the bar as clicking on it did nothing and that didn't work either, I eventually gave up and used firefox to open this issue

**Comment by awsdert** [comment]
Having been looking through the docs for a little while now there's 2 sections I believe absolutely should be in the popup at the start, here's the 1st:
```
How do I find the path to the configuration directory?

To find the path to the current configuration directory, run the following command:

:lua w:notify(luakit.config_dir)
```
Here's the 2nd section:
```
Switching to command mode

Many common operations in luakit, such as typing and opening a URL, involve the use of commands. This is done by switching to command mode, typing the command, and pressing <Enter>.

To switch to command mode, press : (i.e. <Shift-;>), and the command bar will appear at the bottom of the window. In the remainder of this document, commands will be written prefixed by a :; so :open means to first press :, and then type open.

Go to a URL in the current tab

Type :open followed by a space and the URL to navigate to, and press <Enter>. For example, to open the luakit website, type :open luakit.github.io and then press press <Enter>.
```

**Comment by taobert** [comment]
Well, the second of your must-haves is from the Quick-start Guide.
Regarding the first, the Quick-start Guide currently points users towards the default config directory (`~/.config/luakit/`).
Given your stated audience, `luakit.config_dir` probably hasn't been changed from the default,
and instructing them to use the default directory (as the Quick-start Guide does) is likely more useful
than telling them how to print it's current value (as the Files and Directories page does).
Telling users "the basics of using the browser" is exactly what the Quick-start Guide is for, and i think it largely achieves this.
I'm pretty unconvinced that adding additional code to luakit in order to remove a users need to look for/at documentation is the best thing for either luakit or the user. I _can_ see some benefit to setting the default home page to be the Quick-start Guide.

Regarding your inability to go back after navigating to a screenshot,
there is a `back` option in the right-click context menu, consistent with firefox and chromium.
A mouse vendor is free to claim that a button on their mouse is "purpose built" for whatever task they like,
but unless said vendor undertakes to add that support to every software package their customer uses (spoiler: they don't),
then the customer's mileage is likely to vary.
Adding default bindings for mouse buttons 4 and 5 wouldn't be a bad idea,
but [it appears](https://stackoverflow.com/questions/60895686/how-to-get-mouse-buttons-4-5-browser-back-browser-forward-working-in-firef) that this was only done in firefox in September, so your surprise at their absence seems somewhat misplaced.
If, instead of giving up and using firefox to open this issue, you'd used firefox to google "luakit back",
i think you would have found that the Quick-start Guide and Arch's excellent wiki would have been at the top of your list (although our respective filter bubbles may come into play here). Arch's wiki has the keybinding(s) itself, and the Quick-start Guide refers users to `luakit://binds` to see what's available.

What is it you're wanting to achieve by loading a shared library?

**Comment by awsdert** [comment]
> Well, the second of your must-haves is from the Quick-start Guide. Regarding the first, the Quick-start Guide currently points users towards the default config directory (`~/.config/luakit/`). Given your stated audience, `luakit.config_dir` probably hasn't been changed from the default, and instructing them to use the default directory (as the Quick-start Guide does) is likely more useful than telling them how to print it's current value (as the Files and Directories page does). Telling users "the basics of using the browser" is exactly what the Quick-start Guide is for, and i think it largely achieves this. I'm pretty unconvinced that adding additional code to luakit in order to remove a users need to look for/at documentation is the best thing for either luakit or the user. I _can_ see some benefit to setting the default home page to be the Quick-start Guide.

Even if you set it to the quick start guide it's all to easy to for a new user to still be lost and navigate away by accident, at that point they won't know how to go back unless they happen to have reached that point in the docs before they accidentally get themselves stuck else where like I did (which is proof enough that just because a person is techy, doesn't mean they won't get stuck when using software that goes against the norm).

> 
> Regarding your inability to go back after navigating to a screenshot, there is a `back` option in the right-click context menu, consistent with firefox and chromium. A mouse vendor is free to claim that a button on their mouse is "purpose built" for whatever task they like, but unless said vendor undertakes to add that support to every software package their customer uses (spoiler: they don't), then the customer's mileage is likely to vary. Adding default bindings for mouse buttons 4 and 5 wouldn't be a bad idea, but [it appears](https://stackoverflow.com/questions/60895686/how-to-get-mouse-buttons-4-5-browser-back-browser-forward-working-in-firef) that this was only done in firefox in September, so your surprise at their absence seems somewhat misplaced.

Prior to using them I had been using the backspace key, only thought to use the buttons recently but though it was bog standard behaviour since buttons 4 & 5 being for navigation has been on mice for years now (which also negates your point about vendors "claiming" it is purpose built for navigation, it's not a claim if it's the standard expectation), anyways the lack of mouse navigation buttons support I could forgive (part of the reason I went looking for how to customise luakit) though if you want more people to switch luakit and not just techy people (who are generally more forgiving of bad interfaces) interested in trying it out then you're gonna need to compromise and make the popup for the bare bone basics, you can link to the docs in the popup, fine, but make sure at minimum the ':' and the right click for back is mentioned in the popup, without knowing those a user's experience will be easily tainted by not being able to do something as simple as navigating (which defeats the purpose of a browser).

> If, instead of giving up and using firefox to open this issue, you'd used firefox to google "luakit back", i think you would have found that the Quick-start Guide and Arch's excellent wiki would have been at the top of your list (although our respective filter bubbles may come into play here). Arch's wiki has the keybinding(s) itself, and the Quick-start Guide refers users to `luakit://binds` to see what's available.

That's besides the point, the point is not every user will think to do that (like I didn't), to draw users in you need to cater for people who fail to think of something like that.

> What is it you're wanting to achieve by loading a shared library?

I wanted to make use of lua's HTML widgets to give an interface to a new cheat app, gameconqueror is ancient and severely lacking, pince is better but lacks multi-threading and is slower because it uses python, given it's purpose python is ill-suited to the task, I can do it in C and have even made my own custom pseudo mutex handlers, being able to outsource the interface is helpful, I would prefer to use IUP but for whatever reason it doesn't seem to like manjaro.

**Comment by c0dev0id** [comment]
Sorry to be harsh here. But a user that can't figure out the homepage, can't figure out `man luakit` and can't figure out `:help` is very likely better off with a UI driven browser like firefox/chrome/epiphany. Luakit is a niche browser for people looking for a hackable browser with vim bindings. Luakit is not here to hold your hand.

**Comment by awsdert** [comment]
> Sorry to be harsh here. But a user that can't figure out the homepage, can't figure out `man luakit` and can't figure out `:help` is very likely better off with a UI driven browser like firefox/chrome/epiphany. Luakit is a niche browser for people looking for a hackable browser with vim bindings. Luakit is not here to hold your hand.

elitist much? I'm not asking it to hold my or anyone's hand, just have a simple popup at start with bare bone basics noted, the quick start contains a bit more than just bare bones, I even mentioned an option to disable it once one is comfortable they won't need it anymore, I'm not asking that certain keys & buttons be supported or anything complex, just a simple pop-up, would take at most an hour to create, that's not a lot to ask, the attaching library thing was just an extra that I'm not too concerned about, I can get by without attaching to luakit, it's just a convenience I would like to have if luakit's developer/s get round to it, shooting down any request just because you don't wanna spend just a moment to disable it the next time you boot luakit is the attitude of an asshole and has no place in a development environment

**Comment by c0dev0id** [comment]
> just because you don't wanna spend just a moment to disable it the next time you boot luakit is the attitude of an asshole and has no place in a development environment.

Fun attitude towards people that develop the thing you want to use. I'm happy to review your diff, because users demanding features from developers for projects they create and maintain in their spare time is exactly what foss development needs /s.

**Comment by awsdert** [comment]
> > just because you don't wanna spend just a moment to disable it the next time you boot luakit is the attitude of an asshole and has no place in a development environment.
> 
> Fun attitude towards people that develop the thing you want to use. I'm happy to review your diff, because users demanding features from developers for projects they create and maintain in their spare time is exactly what foss development needs /s.

You completely ignored my point and treated as a demand, my point was your reason for striking it off was not acceptable in any circumstance, had you said something like you don't have the time or (if it was something difficult) it was either too difficult or impossible then it would've been acceptable, just striking it off because you can't be arsed is asshole behaviour, saying you'll consider it when you're next in the mood to work on luakit would've been fine, you could've also directed me to the file/s & documentation I would need to implement it myself and submit a patch for luakit thereafter, in development there always needs to be a GOOD reason for ignoring user experience, anything else is just asshole behaviour
