### ISSUE TITLE
Does darkmode exist?

### ISSUE THREAD

**Issue by ldelossa** [luakit/luakit#982]
**Current Behavior:**
There is no dark mode

**Desired Behavior:**
Enable dark mode

**How can we reproduce it (step by step):**
Google for "luakit" dark mode, you'll be linked to an older site where darkmode exists. 

**Environment:**

Linux Distribution & Version:
Output of `luakit --version`:

```

🖭  luakit --version
luakit 2.3-16-g54fcecaa
  built with webkit 2.32.3 (installed version: 2.34.4)
 
```

**Comment by c0dev0id** [comment]
Go to to `:settings` and enable `application.prefer_dark_mode`. Then restart luakit.

Dark mode enabled 🎉

**Comment by ldelossa** [comment]
I seem to not have this setting, I build from HEAD of development, maybe in doing something wrong?

**Comment by c0dev0id** [comment]
You don't see this? If you build from git, this should be there for a year already (Implemented with https://github.com/luakit/luakit/commit/ea082a5b496b1ca2db80c676e0976d9d082c9295)
![scr-2022-02-16_13-33-eege8Eo8](https://user-images.githubusercontent.com/44190565/154265800-c490ae59-b282-4f13-a799-7e002ed36ea3.png)

**Comment by ldelossa** [comment]
Ah, my bad. I had a all hacked up worktree checked out which I was *actually* building, I must have boinked something up to the point where i broke some settings. I checked out the right HEAD and now its there. Thanks for humoring me :)
