### ISSUE TITLE
Default bindings are rebound in multiple files

### ISSUE THREAD

**Issue by andOrlando** [luakit/luakit#984]
**Current Behavior:**
calling `require "binds"` will rebind the default keybindings

**Desired Behavior:**
there should probably be two seperate files, one for binding the keybinds and the other for the actual module. That way users can completely get rid of the default keybindings if they want without having to call mode.remove_bind on everything and it won't try to redefine these keybinds every single time it's called, which is a good 10 times.

It would be nice to be able to comment out `local binds = require "binds"` in rc.lua and be able to completely define my own keybinds, but it doesn't do that.

**How can we reproduce it (step by step):**
load tabhistory.lua, styles.lua, undoclose.lua, quickmarks.lua, binds_chrome.lua, userscripts.lua, proxy.lua, tabmenu.lua, or formfiller.lua and it will recreate the keybinds.

**Environment:**

Linux Distribution & Version: 
NixOS 21.11.336147.4275a321bea (Porcupine)
Output of `luakit --version`:
luakit 6f69789a
  built with webkit 2.34.6 (installed version: 2.34.6)

**Note about webkit issues:**

If you're reporting a rendering issue, please test it with the gnome
browser ephiphany as well. If the issue occurs there too, we're very
likely not able to help. These issues should be reported to webkit:
https://bugs.webkit.org

**Comment by taobert** [comment]
Hrmmm.
While this is perhaps not a wholly unreasonable request,
it's unlikely to become high enough priority for someone else that _they_ will work on it.
As you mention, binds can be removed if a user doesn't want them.
Per #771 they can be removed in a less onerous manner than repeatedly calling `mode.remove_bind`,
and further, you can get a list of modes to iterate through with `modes.get_modes`.
So the issue would seem to be that you want someone else to change the code base to remove your need to add a few lines of configuration.

I may have misunderstood, but your suggestion that there should be "two seperate files,
one for binding the keybinds and the other for the actual module" sounds like you prepose breaking `binds.lua` into two files.
In fact though, `binds.lua` _is_ the file which has the keybinds (`modes.lua` has the functional side).
`binds.lua` is included in the files you mention as they contain new modes (menus) and want to inherit the default bindings for menus (often extending them with module-specific menu bindings).
So using this strategy, _every_ module would require splitting into two files.
I'd agitate against this course of action just from a number-of-files perspective, 
but it would also entail every user changing their configuration to explicitly require the default binds _for every module_, 
and is unlikely to be well-regarded.
If you're interested in playing with this and submitting a PR,
a more sensible option (IMO) would be to have a module test a global flag (`settings.application.no_default_bindings`?) before requiring `binds.lua` or setting binds itself.
While this implementation would be less bad, i still don't see it as valuable.
Both setting the binds, and then removing them happen at startup, so i don't see there being a benefit to performance.
I personally feel that luakit provides the functionality to remove any and all binds that a user doesn't want,
and that that should be the end of the story.

**Comment by andOrlando** [comment]
Right you are--I didn't see that issue. You're right that it's a bit much to separate it into two files if the same would have to be done and while I hold that it seems redundant to be setting it that many times, I can see how it's not a high priority.

Thanks for the response.
