### ISSUE TITLE
[ Question ] The state of teleconference applications

### ISSUE THREAD

**Issue by ldelossa** [luakit/luakit#985]
**Current Behavior:**

I use sway with Wayland. I'm unable to use webcam or share my screen in the browser.

**Desired Behavior:**

The ability to do both those aforementioned things.

**How can we reproduce it (step by step):**

I tend to use the test pages here:

https://www.webrtc-experiment.com/Pluginfree-Screen-Sharing/#22103408570350027 (screen share)
https://www.onlinemictest.com/webcam-test/ (web cam)

Both are unsuccessful. 

**Environment:**

I use Fedora with Sway and `xdg-desktop-portal-wlr`

Linux Distribution & Version:
Output of `luakit --version`:

I build from HEAD. 

**Note about webkit issues:**

If you're reporting a rendering issue, please test it with the gnome
browser ephiphany as well. If the issue occurs there too, we're very
likely not able to help. These issues should be reported to webkit:
https://bugs.webkit.org

**Comment by c0dev0id** [comment]
Hi, webkitgtk is not there yet. I can look into it once epiphany supports it.
On webkitgtk.com they write on the main page that they work on WebAudio and WebRTC.

**Comment by ldelossa** [comment]
Got it, I see it now. Thanks.
