### ISSUE TITLE
luakit often takes more than a minute to load

### ISSUE THREAD

**Issue by ahillio** [luakit/luakit#986]
**Current Behavior:**
Time for luakit to startup makes it unusable. Often greater than one minute. Never less than 10 seconds.

Currently I tried to opening a link from my terminal and (I presume xdg-open was called which invoked Luakit) 7 minutes ago Luakit sill hasn't loaded the webpage. 

**Desired Behavior:**
Less than 5 seconds to load (preferably faster).

**How can we reproduce it (step by step):**
I don't know. I assume this is not happening for other people.

**Environment:**

Linux Distribution & Version: Ubuntu 20.04 LTS
Output of `luakit --version`:
luakit 2.0.0
  built with webkit 2.26.2 (installed version: 2.34.6)

**Comment by Tonus1** [comment]
Do you have a saved session ? It usually takes a significant time to load tabs saved.

**Comment by ahillio** [comment]
No. New session. No saved tabs.

**Comment by Tonus1** [comment]
How did you install ? What is your OS ? You have a -l switch that would change the log level. That could give you/maintainers some useful informations...

**Comment by ahillio** [comment]
Thanks for these prompts. Ubuntu like the post says. Installed via `apt`.

`-l` is a struggle... I see it's synonymous to `--log`, right? I'm not sure how it works or where it's putting the log data. If i do:
`❯ luakit --log=luakit_log1 --uri=https://github.com` I get:
`[    0.000593] W [core/luakit]: ignoring unrecognized --log option 'luakit_log1'`. 
I looked in `/var/log` (and current dir) and didn't see anything with with `lua` in the name. And all the extra data output in the terminal was just that complaint about unrecognized option. How does it work to get more logging info?

Mainly I've tried opening luakit from my "programs" menu via the Super/Window key (and then typing 'lua') and from my Vim wiki markdown files which utilize `xdg-open` for selecting default program to open links.  It seems to be consistently slow regardless of which method is used to open it.

When running `luakit` from terminal/shell, I get:
```
[    0.070200] I [core/luah]: Loading rc: /etc/xdg/luakit/rc.lua
[    0.563054] I [lua/adblock]: found 0 filter lists
[    0.576106] I [lua/styles]: found 0 user stylesheets
[    0.577432] I [core/web_context]: Web process count: 4

** (luakit:2901616): WARNING **: 22:23:39.582: webkit_web_context_set_web_process_count_limit is deprecated and does nothing. Limiting the number of web processes is no longer possible for security reasons
```
That doesn't sound particularly problematic to me ("warning" sounds less severe than "error") but maybe the number of processes should not be limited this way? Maybe this causing the delay?

Maybe that's a bug that's been fixed? Should I be running a more recent version? Debian packages aren't all that up-to-date. It looks like `2.3` is current version.

**Comment by c0dev0id** [comment]
The warning can be ignored. It's just telling you that the `webkit_web_context_set_web_process_count_limit` has no effect. You can limit the web processes by setting `WEBKIT_USE_SINGLE_WEB_PROCESS=1` in your environment before starting luakit.

You can use `--log=debug` to see a lot of debug output and you can use `--log=core/widgets=debug` to filter the output to core/widget stuff. You can also call `luakit -v` for verbose output (a bit less than debug).

There was quite a bit of fixing between 2.0 and 2.3. I'd recommend to update to 2.3.
