### ISSUE TITLE
[ Question ] tablist scroll binding

### ISSUE THREAD

**Issue by numberokta** [luakit/luakit#991]
hi, i am looking for tablist scroll binding **(\<Control-Left\>** and **\<Control-right\>**) source codes and could not find it anywhere in source files. i am building **mouse** scroll tablist module and i am going to implement that source code in my module.

### [another question, but irrelevant]
is **WEBKIT_USE_SINGLE_WEB_PROCESS=1** deprecated ?

### [version]
luakit 2.3
webkit 2.34.6

**Comment by taobert** [comment]
I'm sorry, i'm not sure what you're asking.
Do you want key codes to differentially reference left and right ctrl keys? (You may need to use `xmodmap` to reassign one of them.)
Do you want key codes for ctrl-(left|right) arrow? (I think `<Control-Left>`/`<Control-Right>` should work.)
Do you want to know where bindings for the tablist are set? (I think they're not. I think most tab-related bindings are set on the window. But tablist _does_ set some mouse click event handlers.)
I'm not aware of a way to scroll the tablist to an arbitrary point (but it could be built), and it gets reset via `scroll_current_tab_into_view()` after certain actions, so you'd need to disable/settingise that behaviour.



I believe that WEBKIT_USE_SINGLE_WEB_PROCESS=1 was added to webkit as a workaround for a single release to give developers a little bit of time to rejig their code after the shared process model got jettisoned for security reasons (spectre/meltdown?). I'm pretty sure that for my personal use, i'd be prepared to accept the lower level of security in exchange for the much lower overhead, but it is what it is.. Long ago, i spent some time trying to make something similar using the `related_view` option, but never got anything stable, and then got distracted. I still suspect that this is the right way to do it (albeit with the aforementioned loss of security), but that my grasp of webkit magic is inadequate.

**Comment by numberokta** [comment]
I'm looking for a way to scroll tablist with mouse wheel.
I found, there is scroll signal for eventbox widget (i think defined on **line 85** in **widgets/eventbox.c** and on **line 88** in **widgets/common.c**), but i don't know how it works.
i test this:
```
local _M = {}
local tab = require("lousy.widget.tab")
tab.add_signal("build", function(tl, view)
 tl.widget:add_signal("scroll", function()
    -- do something
  end)
end)
return _M
```
but it does't work
there is another way:
```
local _M = {}
local tab = require("lousy.widget.tab")
local enter = false
tab.add_signal("build", function(tl, view)
 tl.widget:add_signal("mouse-enter", function()
   enter = true
  end)
  tl.widget:add_signal("mouse-leave", function()
   enter = false
  end)
end)
function todo()
  if enter then
    -- do something
  end
end
-- [binding todo function with mouse wheel event]
return _M
```
but unfortunately, i don't know how to bind mouse wheel event with a function.
