### ISSUE TITLE
Website still tells luakit is at v2.2 from sept. 2020

### ISSUE THREAD

**Issue by Tonus1** [luakit/luakit#993]
**Current Behavior:**
Luakit seems not updated.

**Desired Behavior:**
The website advertises the last release. Better : time for a new release ?

**How can we reproduce it (step by step):**
Just goto your favorite search engine, type luakit and go for the link.

**Environment:**
Just got there with... luakit :)

Linux Distribution & Version:
Output of `luakit --version`:
luakit 2.3
  built with webkit 2.36.1 (installed version: 2.36.1)
Slackware 15.0

**Comment by msdemlei** [comment]
Talking about which, I'd be grateful for a release rolling up the little changes that went in over the last few years (just today I've missed the improved proxy support in the Debian-packaged luakit).  Is there anything particular where I could be of use to make that happen?

**Comment by c0dev0id** [comment]
I don't have access to the website, but we could move towards a release. I'm also starting to miss changes in the packaged version.

I'll look into it in the next two weeks.

**Comment by c0dev0id** [comment]
A bit later than expected, but we have a release now :)

I'm also closing this issue. Maybe @aidanholm wants to regenerate the website at some point (or explain me how to do it and add me to the repo). But as long this doesn't happen, there's not much anybody else can do about it :(
