### ISSUE TITLE
Add GNU Hurd to list of supported platforms

### ISSUE THREAD

**Issue by KSPAtlas** [luakit/luakit#994]
**Current Behavior:**
Windows (WSL), Linux, BSD

**Desired Behavior:**
Windows (WSL), Linux, BSD, Hurd

**How can we reproduce it (step by step):**
Luakit is now available in the Debian GNU/Hurd repositories, and it works well except for larger pages (due to underlying Hurd bugs)

**Comment by taobert** [comment]
This is great news, and thanks for reporting it.
There is [a separate repo](https://github.com/luakit/luakit.github.io) for the web page,
and i suspect that this issue should be raised there.
I'm not sure whether @c0dev0id who currently deals with the bulk of the pull requests here is able to merge to that repo,
so it may take some time to get updated.

**Comment by c0dev0id** [comment]
Hi, unfortunately I have no access to this repo. That's also why the webpage is outdated. @aidanholm has access.
