### ISSUE TITLE
[Question] How to save a session, but without data related to "closed" tabs?

### ISSUE THREAD

**Issue by MuhammedZakir** [luakit/luakit#995]
I looked into `session.save` function, but I couldn't understand as the code seems to only handle "open" tabs, however, the session file contains "closed" tabs.

**Comment by taobert** [comment]
The code in `lib/session.lua` does indeed only save open tabs, but it also emits a `save` event.
This save event triggers a signal handler set in `lib/undoclose.lua` which saves the closed tabs.

If you don't want to use the `undoclose` functionality at all, you could just not load this module.

If you do want to be able to reopen closed tabs, but don't want them saved, then
- Maybe you can fiddle with the signal handlers (I feel like signal handlers can be removed, but can't recall off the top of my head how).
- Maybe you can fiddle with the saved list of closed tabs:
This list of closed tabs is local to `lib/undoclose.lua`, and so (i think) can't be changed directly from outside the module.
However, i see that there's a `undoclose.max_saved_tabs` setting.
When a tab is closed, the list of closed tabs is truncated to this number.
So, you could build some code that set this to zero, closed a tab, and then reset it to the number you want.
This would be fairly straightforward to do on luakit close, but it looks like maybe sessions are saved periodically.
If you were to use this approach every time the session saved, it would obviously impact undoclose's function.

**Comment by MuhammedZakir** [comment]
I commented out these lines [1] and it's now working as I wanted. Thank you!

[1] https://github.com/luakit/luakit/blob/6cac83342bfe87ea57f05b67976f8def814b3934/lib/undoclose.lua#L146-L148
