### ISSUE TITLE
Tab bars (top) and info bar (bottom) are not seen when in fullscreen mode (F11)

### ISSUE THREAD

**Issue by MuhammedZakir** [luakit/luakit#998]
**Current Behavior:**

Tab bars (top) and info bar (bottom) are not seen when in fullscreen mode (`F11`).

Edit: Command-line bar(?) is shown correctly when pressing `Shift-;`.

**Desired Behavior:**

They should be seen even when the app is in fullscreen.

**How can we reproduce it (step by step):**

1. Open the app.
2. Enter fullscreen; usually `F11` or `Alt-F11`.

**Environment:**

Linux Distribution & Version: Manjaro XFCE (X11)
Output of `luakit --version`:
```
luakit 2.3
  built with webkit 2.34.6 (installed version: 2.36.3)
```

**Comment by taobert** [comment]
This is the intended behaviour. You can override it yourself.
The ui hiding is triggered by the `"property::fullscreen"` signal, set in `lib/window.lua`:
```lua
        w.win:add_signal("property::fullscreen", function (win)
            w:update_sbar_visibility()
            w.tablist.visible = not win.fullscreen
        end)
```
You can remove the signal handler with `w.win:remove_signals("property::fullscreen")`.
Note that this will remove _all_ handlers for this signal.
Currently there _is_ only one handler tied to this signal,
but this might cause problems with future releases, or if you want to to finess your setup.


As an aside, I have (had) the somewhat less sophisticated:
```lua
window.add_signal("init", function (w)
    w.update_sbar_visibility_old = w.update_sbar_visibility
    w.update_sbar_visibility = function (w)
	w:update_sbar_visibility_old()
	w.bar_layout.visible = true
    end,
end)
```
for the status bar, as i prefer to have the tab bar hidden, but i might now shift to just removing the signal handler...

**Comment by MuhammedZakir** [comment]
Thanks a lot! :-D

Thinking about it more, I found that I only want these to be shown in some situations. So I went with this key binding:
```lua
    {
        "<control-g>",
        "Toggle tab-bar and status-bar visibility.",
        function(w)
            local visibility = w.bar_layout.visible or w.tablist.visible
            -- status-bar
            w.bar_layout.visible = not visibility
            -- tab-bar
            w.tablist.visible = not visibility
        end
    },
```

**Comment by taobert** [comment]
I seem to recall this approach having issues (see #919 and #492).
`w.bar_layout.visible` gets reset from time to time when `update_sbar_visibility` gets called,
so if you rely on a key binding like this, you may need to keep hitting the key.

**Comment by MuhammedZakir** [comment]
You're right. Added these and changed `ctrl-g` to call `set_bar_visibility(w, true)`:
```lua
local cur_visibility = true
function set_bar_visibility (w, toggle, visibility)
    if toggle == true then
        cur_visibility = not cur_visibility
    end
    if type(visibility) == 'boolean' then
        cur_visibility = visibility
    end
    -- status-bar
    if (w.bar_layout.visible_child == w.sbar.ebox) then
        w.bar_layout.visible = cur_visibility
    end
    -- tab-bar
    w.tablist.visible = cur_visibility
    --w:update_sbar_visibility()
end
window.add_signal("init", function (w)
    w.update_sbar_visibility_old = w.update_sbar_visibility
    w.update_sbar_visibility = function (w)
        --if (w.bar_layout.visible_child == w.sbar.ebox) then
        --    cur_visibility = w.bar_layout.visible
        --end
        w:update_sbar_visibility_old()
        set_bar_visibility(w)
    end

    w.win:add_signal("property::fullscreen", function (win)
        -- Hide bars if fullscreen.
        set_bar_visibility(w, false, not win.fullscreen)
    end)
end)
```
